### ISSUE TITLE
Creating buttons in custom actions

### ISSUE THREAD

**Issue by DhruvMevada** [RasaHQ/rasa_core#1010]
**Rasa Core version**:0.11.3

**Python version**: 

**Operating system** (windows, osx, ...):

**Issue**:
 As we are mentioning buttons in templates in domain.yml file, Can I create buttons in custom actions?

**Comment by akelad** [comment]
Yes you can, there's the `dispatcher.utter_button_message` function that does this. Please ask this type of questions in our [forum](https://forum.rasa.com)
