### ISSUE TITLE
Interactive learning can export current conversations as stories and continue

### ISSUE THREAD

**Issue by GaoQ1** [RasaHQ/rasa_core#1014]
**Rasa Core version**:
rasa-core 0.11
**Python version**: 
python 3.6
**Operating system** (windows, osx, ...):
windows 10
**Issue**:
As the tittle, can rasa-core interactive learning export current conversations as stories and continue. Now everytime it quite and I have to retrain the dialogue. Tks!

**Comment by GaoQ1** [comment]
@tmbo

**Comment by akelad** [comment]
what do you mean? when you press export it exists the conversation, yes

**Comment by GaoQ1** [comment]
yes. I thought it wastes time to run again.

**Comment by tmbo** [comment]
The `/restart` will only work with the latest master though - I think in the currently released version the exported stories aren't really useful if you use restarts.

**Comment by GaoQ1** [comment]
`/restart` restart a new converstation, but it covers the previous dialogue. It cannot export the story and go on train and append new story to the current story. 
And my rasa-nlu:  0.13.3, rasa-core: 0.11.3.

**Comment by akelad** [comment]
What do you mean? If you upgrade to 0.11.4, it should work fine

**Comment by GaoQ1** [comment]
emmm, I upgrade to 0.11.4. And how to export story? It doesn't like the previous version.

**Comment by GaoQ1** [comment]
oh, I know, Ctrl + c.  Tks.

**Comment by sjtilney** [comment]
> `/restart` restart a new converstation, but it covers the previous dialogue. It cannot export the story and go on train and append new story to the current story.
> And my rasa-nlu: 0.13.3, rasa-core: 0.11.3.

Did you ever find a solution to this? ie, create multiple stories in a single interactive training session
