### ISSUE TITLE
domain and tracker differences in rasa_core_sdk

### ISSUE THREAD

**Issue by arachny** [RasaHQ/rasa_core#1028]
**Rasa Core version**: 0.11.4

**Python version**: 2.7.14

**Operating system** (windows, osx, ...): Ubuntu 18.04

**Issue**:
Since I updated all my code to the latest version and I now try to utilise the `rasa_core_sdk`, some of my code does not run as the new `dispatcher`and `tracker `objects do not match the same objects in the sdk library. So I try to run the following action:

```
class ActionInactivityAbc(Action):
    def name(self):
        return "action_abc"

    def run(self, dispatcher, tracker, domain):
        dispatcher.utter_message("Test")
        return [StoryExported("log-stories/stories_" + str(dispatcher.sender_id) + ".md"),Restarted()]
```

am getting errors like:
`AttributeError: 'CollectingDispatcher' object has no attribute 'sender_id'`

Same will happen if I try anything like:

```
dispatcher.output_channel
tracker.current_state()['latest_message']
```

etc.

Any ideas how I could access those attributes for the `dispatcher`and `tracker `objects from the new `rasa_core_sdk`?

**Comment by akelad** [comment]
`tracker.latest_message.get('text')` should work! 
@tmbo any ideas about the sender_id?

**Comment by tmbo** [comment]
`tracker.current_state()['latest_message']` should work as well. `tracker.sender_id` should work to get that id.

**Comment by arachny** [comment]
I tried to create a simple chatbot with only one action just to test that... but I cannot get it to work.
When I check the `dispatcher` object type It get: `<class 'rasa_core_sdk.executor.CollectingDispatcher'>`
So obviously this does not have any properties like `sender_id`

I am attaching the project I worked with (you might need to install the wikipedia package).
[wikibot.zip](https://github.com/RasaHQ/rasa_core/files/2411383/wikibot.zip)

If you train and run it... try to say "hi" and then "What is AI?"

**Comment by tmbo** [comment]
The tracker has the sender_id, not the dispatcher.

**Comment by arachny** [comment]
I see!... sorry about that... did not realised those moved to the other object.

I fixed that and I am not getting a strange error!
when I try to run:
`tracker.current_state()["latest_message"]`
I get the error:
```
File "/usr/local/lib/python2.7/dist-packages/rasa_core_sdk/__init__.py", line 61, in current_state                              latest_event_time = self.events[-1].timestamp
AttributeError: 'dict' object has no attribute 'timestamp'
```
Also, is there an alternative for the old `dispatcher.output_channel`?

**Comment by tmbo** [comment]
You don't have access to the output channel, as that is running on a separate server.

**Comment by arachny** [comment]
@tmbo  the update sorted this problem, but I run into one more... not sure if is a bug.

If I try to use my own implementation of a PolicyEnsemble I get the following error now (this used to work btw):
```
File "/usr/local/lib/python2.7/dist-packages/rasa_core/processor.py", line 155, in predict_next_action probabilities, policy = self._get_next_action_probabilities(tracker)
ValueError: too many values to unpack
```
I use this like:
```
    fallback = FallbackPolicy(
        fallback_action_name="utter_default", core_threshold=0.2, nlu_threshold=0.2
    )
    policies = [MemoizationPolicy(max_history=4), MyPolicy(), fallback]
    ensemble = MyPolicyEnsemble(policies)
    agent = Agent(domain_file, policies=ensemble)
```

and even if I use the policy from the rasa code:
```
class MyPolicyEnsemble(PolicyEnsemble):
    def probabilities_using_best_policy(self, tracker, domain):
        # type: (DialogueStateTracker, Domain) -> List[float]
        result = None
        max_confidence = -1
        best_policy_name = None
        for i, p in enumerate(self.policies):
            probabilities = p.predict_action_probabilities(tracker, domain)
            confidence = np.max(probabilities)
            if confidence > max_confidence:
                max_confidence = confidence
                result = probabilities
                best_policy_name = "policy_{}_{}".format(i, type(p).__name__)
        # normalize probablilities
        if np.sum(result) != 0:
            result = result / np.linalg.norm(result)
        logger.debug("Predicted next action using {}" "".format(best_policy_name))
        return result
```

I still get the error.

**Comment by tmbo** [comment]
The signature for `probabilities_using_best_policy` is 
`# type: (DialogueStateTracker, Domain) -> Tuple[List[float], Text]` - this means you need to return a tuple (probabilities and policy name)

**Comment by arachny** [comment]
Great, that worked. Thank you
