### ISSUE TITLE
Login for multiple Action in single custom Action file

### ISSUE THREAD

**Issue by abhishakskilrock** [RasaHQ/rasa_core#1029]
Hi, I want to do multiple sign in through rasa like for action A payload is X and for action B payload is Y how can I add more than one sign in single custom action file. One more thing I want to know that if I take username and password in slots how to push them in payload?

**Comment by akelad** [comment]
Please ask these kind of questions in our [forum](https://forum.rasa.com)

**Comment by abhishakskilrock** [comment]
> Please ask these kind of questions in our [forum](https://forum.rasa.com)

I asked this question there too. ref:https://forum.rasa.com/t/sign-in-authentication-with-rasa/205/17?u=abhishakskilrock
