### ISSUE TITLE
Should the verbose flag default to False?

### ISSUE THREAD

**Issue by coreytrampe** [RasaHQ/rasa_core#103]
https://github.com/RasaHQ/rasa_core/blob/863503ba40a7ee75bdcf60459f51fc861617c909/rasa_core/run.py#L43

I guess my Python is super rusty, but I don't see a way to disable verbose logging.

**Comment by tmbo** [comment]
`--verbose 0` should do the trick. Not sure about making it not log details by default.

**Comment by coreytrampe** [comment]
It does not.

With `--verbose 0`, it returns `run.py: error: unrecognized arguments: 0`.
With `--verbose=0`, it returns `run.py: error: argument -v/--verbose: ignored explicit argument '0'`.

That level of logging makes the CLI hostile as an user interface. If the user interface were separate somehow... like in a web browser maybe... then it would be fine. But for a new user following the Building a Simple Bot tutorial, it's just a lot of noise.

**Comment by tmbo** [comment]
That's right, that flag wasn't very helpful. replaced it :+1:
