### ISSUE TITLE
Parse HTTP API - next_action field value is set to action_listen

### ISSUE THREAD

**Issue by vishal-palankar** [RasaHQ/rasa_core#1034]
**Rasa Core version**: 0.8.5

**Python version**: python3.5

**Operating system** (windows, osx, ...): Linux CentOs

**Issue**: "next_action" field value is set to "action_listen" in Parse Call 

I have made http api call to parse endpoint and at certain point, it returns action_listen as value. any subsequent calls made will keep the next_action value set to action_listen.

Kindly help

**Comment by souvikg10** [comment]
I think you don't have stories that corresponds to the intent that was understood by your chatbot.

**Comment by akelad** [comment]
i'd also suggest updating your Core version to a newer one, 0.8.x is a very old version

**Comment by akelad** [comment]
i'd also suggest updating your Core version to a newer one, 0.8.x is a very old version

**Comment by Shreeti-Saha** [comment]
I am using 0.8.5 version and I am getting action_listen in the parse call. If I upgrade to the newer version will it resolve the issue?

**Comment by akelad** [comment]
well there's probably a mistake in your stories that's causing it, but i'd suggest upgrading anyways yeah

**Comment by akelad** [comment]
@vishal-palankar has your issue been resolved?

**Comment by joseariel** [comment]
Hello, I'm having a similar issue. I have verified that the stories I am training follow the sequence of the tracker when testing, however I still can't seem to get rasa_core to respond with anything but action_listen. 

Is there any other place I could check maybe within the source to debug this issue and at least understand why is rasa_core stuck with action_listen?
