### ISSUE TITLE
Skype Connectivity with RASA Core

### ISSUE THREAD

**Issue by vinayver198** [RasaHQ/rasa_core#1038]
**Rasa Core version**:

**Python version**: 

**Operating system** (windows, osx, ...):

**Issue**:

**Content of domain file** (if used & relevant):
```yaml

Hi,
Is there any connector available for connecting RASA core with Skype Enterprise

**Comment by akelad** [comment]
Yes, you can use the [Microsoft Bot Framework connector](https://rasa.com/docs/core/connectors/#microsoft-bot-framework-setup)

**Comment by vinayver198** [comment]
Thanks
