### ISSUE TITLE
Can We Store Slack converstion on database?

### ISSUE THREAD

**Issue by tushar1328** [RasaHQ/rasa_core#1051]
## Can We Store Slack converstion on database?

**Rasa Core version**: 11.2

**Python version**:  3.5

**Operating system** : UBUNTU 16.04 LTS

**Question**:
Is there any way we can store the conversation data on to the database so that we can have more knowledge of the conversation and can improve.

**Comment by akelad** [comment]
yes, you can use a different tracker store, e.g. the `MongoTrackerStore` or the `RedisTrackerStore`
https://github.com/RasaHQ/rasa_core/blob/master/rasa_core/tracker_store.py
