### ISSUE TITLE
Rasa major update?

### ISSUE THREAD

**Issue by e8180kimo** [RasaHQ/rasa_core#1062]
**Issue**:
Do the developers of Rasa team has any new version of the releasing date?
I was using 0.10 but then updated to 0.11 and have to do some migration.
Will this version (0.11) be the most stable and supportive? Should I stick to this version? 
Or any other major release?

```

**Comment by akelad** [comment]
As we're following semantic versioning, any increase in 0.x is a major release (e.g. from 0.10 to 0.11). This will be the case until we reach 1.0
In general though, the latest version is the one we recommend you use (paying attention to the migration guide of course)

**Comment by e8180kimo** [comment]
If you released 0.12, will you stop support 0.11?

**Comment by akelad** [comment]
We'd always recommend you upgrade to the latest version yeah.

**Comment by e8180kimo** [comment]
Yah, but my question is will you stop to support the older version?

**Comment by akelad** [comment]
we probably won't be porting any bugging fixes back there in the long term, no. Probably if there's major things after 0.12 is released we might fix them in 0.11, but as soon as 0.13 gets released we won't be maintaining 0.11 much
