### ISSUE TITLE
 Couldn't connect to the server

### ISSUE THREAD

**Issue by zhuohaochen** [RasaHQ/rasa_core#1070]
I create new CustomAction and succeeded registering it. And I also create a endpoints.yml file: action_endpoint:
  url: "http://localhost:5055/webhook"
core_endpoint:
  url: "http://localhost:5055"

and use --endpoints in the command. But when my program calls the custom action it shows "Failed to run custom action...Couldn't connect to the server at 'http://localhost:5055/webhook'" 
What's wrong with it?

**Comment by tmbo** [comment]
what is the command you use to run the action server?

**Comment by zhuohaochen** [comment]
I used "python -m rasa_core_sdk.endpoint --actions action"
where the custom action classes are defined in action.py and it successfully registered
then I used the following commands:
python -m rasa_core.train -d domain.yml -s stories.md -o models/dialogue  --endpoints endpoints.yml
python -m rasa_nlu.train -c nlu_config.yml --data /nlu.md -o models --fixed_model_name nlu --project current --verbose
python -m rasa_core.run -d models/dialogue -u models/current/nlu --endpoints workspace/endpoints.yml

Did I make any mistakes?

**Comment by zhuohaochen** [comment]
Here is the error:
Failed to run custom action 'action_location_match'. Couldn't connect to the server at 'http://localhost:5055/webhook'. Is the server running? Error: HTTPConnectionPool(host='localhost', port=5055): Max retries exceeded with url: /webhook (Caused by NewConnectionError('<urllib3.connection.HTTPConnection object at 0x7fb0fc3f1710>: Failed to establish a new connection: [Errno 111] Connection refused',))

**Comment by tmbo** [comment]
what does your browser say if you open http://localhost:5055/health ?

**Comment by zhuohaochen** [comment]
This site can’t be reached
localhost refused to connect

**Comment by tmbo** [comment]
Are you sure `python -m rasa_core_sdk.endpoint --actions action` is still running? it needs to run in the background - you can not stop it to execute the other commands (use a second shell for that).

If it is actually running, another issue might be firewall / enterprise proxy settings that prevent you from connecting

**Comment by akelad** [comment]
This means something is already running on that port, you need to either change the port, or find the process and kill it. In general, if you have an issue please create a new one
