### ISSUE TITLE
How is it used tracker.travel_back_in_time() ?

### ISSUE THREAD

**Issue by basque21** [RasaHQ/rasa_core#1072]
How can I use the function tracker.travel_back_in_time(arg) to restore the tracker with previous events? is the argument an integer and means how many steps go backwards or what is it? I'm trying with integers, floats, positive, negative...and I'm getting a tracker with None-s in all slots, and everything empty...

Thanks

**Comment by akelad** [comment]
Thanks for raising this issue, @Ghostvv  will get back to you about it soon.

**Comment by Ghostvv** [comment]
Could you please explain in more details, what do you mean by `restore the tracker with previous events`.

function tracker.travel_back_in_time(arg) takes timestamp, `float`, as an argument
```
    def travel_back_in_time(self, target_time):
        # type: (float) -> DialogueStateTracker
        """Creates a new tracker with a state at a specific timestamp.

        A new tracker will be created and all events previous to the
        passed time stamp will be replayed. Events that occur exactly
        at the target time will be included."""
```

if you want to go certain number of `ActionExecution` back, you need to count them backwards in `tracker.events`
