### ISSUE TITLE
Illegal instruction (core dumped) on quickstart tutorial

### ISSUE THREAD

**Issue by mamamot** [RasaHQ/rasa_core#1076]
**Rasa Core version**:
0.11.6
**Python version**: 
3.5.2
**Operating system** (windows, osx, ...):
Ubuntu 16.04
**Issue**:
I have an issue with the quickstart tutorial. After copy-pasting the domain and stories files, I run
`
python3 -m rasa_core.train -d domain.yml -s stories.md -o models/dialogue
`

And then I see "Illegal instruction (core dumped)" error. When running under gdb, I see the following output:
`
Thread 1 "python3" received signal SIGILL, Illegal instruction.
0x00007fffda301250 in std::pair<std::__detail::_Node_iterator<std::pair<tensorflow::StringPiece const, std::function<bool (tensorflow::Variant*)> >, false, true>, bool> std::_Hashtable<tensorflow::StringPiece, std::pair<tensorflow::StringPiece const, std::function<bool (tensorflow::Variant*)> >, std::allocator<std::pair<tensorflow::StringPiece const, std::function<bool (tensorflow::Variant*)> > >,
`

I have tensorflow 1.10.1 obtained via pip.

**Comment by mamamot** [comment]
I seem to have identified the issue, so if you have the same problem, the cause might be the old CPU. My CPU does not support AVX instructions which are required by Tensorflow, so I guess TF needs to be compiled from scratch.

**Comment by tmbo** [comment]
I am afraid there is not a lot we can do about this. But would be great if you could post the commands or a link to a help page that shows how to install tf from source

**Comment by mamamot** [comment]
Sure, the old processors that lack AVX have not been supported since Tensorflow 1.6. Building from binaries is tedious, but doable: [https://www.tensorflow.org/install/source](https://www.tensorflow.org/install/source)
