### ISSUE TITLE
how to fetch BOT response from mongodb instead of adding templates in domain file.

### ISSUE THREAD

**Issue by ashukrishna100** [RasaHQ/rasa_core#1078]
**Rasa Core version**:0.11

**Python version**: 3.6.5

**Operating system** (windows, osx, ...):windows

**Issue**:

**Content of domain file** (if used & relevant):
```yaml

```

**Comment by akelad** [comment]
This is something you have to implement yourself, for more information read here: https://rasa.com/docs/core/responses/#managing-bot-utterances-using-an-external-cms
