### ISSUE TITLE
Returning intents list and utterance_key from HTTP REST API

### ISSUE THREAD

**Issue by joseariel** [RasaHQ/rasa_core#1087]
**Rasa Core version**:

0.11.6

**Python version**: 

3.4.2

**Operating system** (windows, osx, ...):

Ubuntu

**Issue**:

We're trying to use the HTTP REST API in the same way it used to work with the 0.7.9 version of rasa_core in which the utterance key, recognized intent key and the list of top intents for the message was included along with the 'text' response in json.

We're using the following but it only returns the "text" response and not the keys of the intents and utterances:

python -m rasa_core.run \
    --enable_api
    -d models/dialogue \
    -u models/nlu/current \
    -o out.log

We need some guidance on how to achieve this within the same HTTP request.

Thanks so much

**Content of domain file** (if used & relevant):
```yaml

```

**Comment by amn41** [comment]
Which endpoint were you previously using? The `POST /conversations/{sender_id}/messages` [endpoint](https://www.rasa.com/docs/core/master/server/#operation/addMessage) returns this information

**Comment by joseariel** [comment]
Hi Alan, 

In rasa_core version 0.7.9, we were using POST /conversations/{sender_id}/parse and passing the text message from the end-user. 

This returned the utterance and intents recognized with its keys and confidence levels. Here's a sample:

{
    "next_action": "utter_greet",
    "tracker": {
        "latest_message": {
            "entities": [],
            "intent": {
                "confidence": 0.96065930211551682,
                "name": "greet"
            },
            "intent_ranking": [
                {
                    "confidence": 0.96065930211551682,
                    "name": "greet"
                },
                {
                    "confidence": 0.13740526134884382,
                    "name": "thankyou"
                },
                {
                    "confidence": 0.09525491259547693,
                    "name": "stop"
                }
            ],
            "text": "Hi"
        },
        "paused": false,
        "sender_id": "1517085592",
        "slots": {
            "product_type": null
        }
    }
}

**Comment by joseariel** [comment]
To make sure I understood your comment, Alan. Are you saying that the POST /conversations/{sender_id}/parse endpoint was renamed to POST /conversations/{sender_id}/messages ?

And will this predict the next action/response based on the text message provided?
