### ISSUE TITLE
Slot configuration

### ISSUE THREAD

**Issue by Richelle2016** [RasaHQ/rasa_core#110]
**Rasa Core version** (e.g. `0.7.3`):

**Operating system** (windows, osx, ...): Windows

**Issue**: Hello, i am testing rasa_core and i generated my own domain with stories. I want to know if there is any configuration to do in the code about slots because i have the intent accept for example and in base of the slots registrated the answer suppose to be different. But rasa_core mismatch the actions.
Thanks.

**Content of domain file** (if used & relevant):
```yaml

```

**Comment by tmbo** [comment]
You need to put your slots into the domain file. The slots need to either be filled by a custom action you wrote our by an entity that has the same name. 

Make sure to include story example where the slot is set in the training, e.g.:
```md
## hello story
* _mood_greet
  - greet_user
  - slot{"user_name": "Rasa"}    <!-- e.g fetched from an external service in the greet_user action -->
  - utter_how_can_help
  - ...
```

**Comment by Richelle2016** [comment]
Thanks @tmbo.
This is for example what i'am talking about; I have for example this story:
##story1
*_mood_greet
    - utter_how_can_help
* _new_connection
    - utter_ask_if_new_client
* _accept[new_client=yes]
    - utter_ask_multiples_connections
* _accept[multiples_connections=yes]
     - utter_show_result
And when i enter the intent accept whit the slot multiples_connections=yes, the action is utter_ask_multiples_connections.
That is why i was asking if there is some configurations to do in the python code while setting the domain and the stories in order to add the probability to have the good action.
Thanks.

**Comment by tmbo** [comment]
There is a difference between slots and entities. Entities are present in user messages, e.g. `accept[multiples_connections=yes]`. If there is no slot with the same name (in this case `multiples_connections`) there won't be a slot set to this value. Does that make sense?
