### ISSUE TITLE
Allow multiple stories being generated during interactive learning

### ISSUE THREAD

**Issue by smn-snkl** [RasaHQ/rasa_core#1106]
**Rasa Core version**:
0.11.6
**Python version**: 
Python 2.7.15
**Operating system** (windows, osx, ...):
osx
**Issue**:
Starting up the interactive learning session takes quite a while. So it would be nice to add multiple stories in one session. Right now you can use /restart to start over, but you lose your progress by doing so. Maybe there could be a /new to start a new conversation / story.

**Comment by akelad** [comment]
in the master version of core, if you do `/restart` it will start over, but it will still export all your conversations once you tell it to export :) could you try installing the master version?

**Comment by smn-snkl** [comment]
@akelad : I just upgrade to 0.12 (master branch), but I still see the same behavior. After doing /restart it asks you to confirm that the intent is restart, the action is restart and then it clears the history. If you then have another conversation and then /stop and export, the stories.md only contains the last conversation.

**Comment by smn-snkl** [comment]
Ok, I just found the solution. Instead of restarting with /restart which clears the history, you should /stop and then select "Start fresh". Then you keep all the stories.

Thanks, that's great!

**Comment by akelad** [comment]
@tmbo is that correct behaviour with `/restart`?

**Comment by tmbo** [comment]
I guess we should properly handle `/restart` and do the same as we do with the `Start fresh` menu item

**Comment by akelad** [comment]
cool, will create a new issue
