### ISSUE TITLE
"Wrong fb secret!" 

### ISSUE THREAD

**Issue by sirainatou** [RasaHQ/rasa_core#1107]
**Rasa Core version**:
0.12.0a4
**Python version**: 
3.6.3
**Operating system** (windows, osx, ...):
windows
**Issue**:
I still get "failure, invalid token" when I run "python -m rasa_core.run -d models/dialogue -u models/current/nlu --port 5002 --credentials credentials.yml" 
I am sure that I entered the correct verify token.

**Content of domain file** (if used & relevant):
```yaml

```

**Comment by amsolu** [comment]
Sirainatau,
I did have the same issue and downgrading core to 0.11.5 works for me.
Why don't you give a try wait for 5 minutes and start to communicate via facebook again.

Then back to your regular version, but I suspect a transition from 0.11.5 to 0.11.6 breaks something 

Thanks

**Comment by matthies1** [comment]
> @sirainatou can you try installing latest master and let me know if the problem is still there?

I have installed the latest master version and getting the same error.

Operating system: ubuntu 16.04 LTS
Python version: Python 3.6.6 :: Anaconda, Inc.
