### ISSUE TITLE
restaurant demo example don't work

### ISSUE THREAD

**Issue by wesleytao** [RasaHQ/rasa_core#1109]
**Rasa Core version**: latest version 0.11.8

**Python version**: 3.6

**Operating system** (windows, osx, ...):Centos Aws

**Issue**: restaurant example don't work

**Content of domain file** (if used & relevant):
```yaml

```

![image](https://user-images.githubusercontent.com/25362155/46309492-81e18780-c58a-11e8-94b9-6611bd70830a.png)

**Comment by akelad** [comment]
Please post the command you used that caused this error

**Comment by jonDel** [comment]
I ran into the same error. I train both nlu and core successfully, but when using the agent to load the pretrained core model, I got the following error message:
```
File "/home/*/miniconda3/envs/rasa_chatbot_0.11/lib/python3.6/site-packages/tensorflow-1.11.0-py3.6-linux-x86_64.egg/tensorflow/python/keras/engine/saving.py", line 251, in load_model
    training_config['weighted_metrics'])
KeyError: 'weighted_metrics'
```

**Comment by wesleytao** [comment]
@jonDel I don't remember how I solve this problem. But I do know it is something related to tensorflow version.

**Comment by wesleytao** [comment]
@jonDel  hey I met this problem again. 
Now I found the problem. 
When you do `pip3 install -r requirements` it will have this problem
Try to do `pip install -r requirements` to see if it works.
It works for me.

**Comment by akelad** [comment]
Ok so the problem is probably that you trained your model with tensorflow==0.10 but then loaded the model with tensorflow==0.11, we're gonna merge a fix asap

**Comment by jonDel** [comment]
@akelad , my custom model was using pure keras instead of the recently added keras module from tensorflow. It seems that the whole issue is related to a namespace confusion. I changed my custom model to use tensorfow.keras and all went well.
