### ISSUE TITLE
Remote bot not working via curl or http

### ISSUE THREAD

**Issue by yogeshhk** [RasaHQ/rasa_core#111]
**Rasa Core version** (e.g. `0.7.3`): 0.7.6

**Operating system** (windows, osx, ...): Windows 7

**Issue**:
I followed concert-remote bot tutorial from Rasa documentation, on the example code from github
After training nlu and dialogue, I tried running rasa_core.server like localhost:5005/conversations/default/parse -d '{"query":"hello there"}
but I got this error json.decoder.JSONDecodeError: Expecting value: line 1 column 1 (char 0) 
When I just type http://localhost:5005/... it said "hello from Rasa Core"...
but then, when I tried localhost:5005/conversations/default/parse -d '{"query":"hello there"}' gave error

**Content of domain file** (if used & relevant):
```yaml

```

**Comment by tmbo** [comment]
@yogeshhk which python version is that?

**Comment by yogeshhk** [comment]
3.5

**Comment by yogeshhk** [comment]
Has this problem been reproduced at your end?

One comment on Gitter  said 'it is versioning problem of library spacy, sklearn_crfsuite and scikit-learn" ..is this of any help? I have following versions:
spacy: 2.0.3
sklearn-crfsuite: 0.3.6
scikit-learn: 0.19.1

I am using more-or-less latest of python libraries.

Any idea, why I am seeing the errors while running rasa_core.server?

**Comment by tmbo** [comment]
It is not tested with 3.5, can you retry with 3.6?

**Comment by yogeshhk** [comment]
I am not using 3.6 as I did not have good experience with my other work, due to its incompatibility with some other libraries.

Can anything be done within 3.5 land?

Can the error be reproduced first on your side and then debugged to see what the real cause?

**Comment by tmbo** [comment]
Can you please post the complete curl request you did as well as the command you used to start the server?

**Comment by Ashwin-Shenoy-NITK** [comment]
I have tried with python 3.6.3 but its giving the same error as mentioned

**Comment by tmbo** [comment]
I've added a logging output to the latest master version when hitting the `/parse` endpoint and the json deserialisation fails. Do you mind trying that out and pasting the error message logged before the stacktrace is logged?

**Comment by SibaprasadM** [comment]
Hi Tom,

Below is the log:
2018-03-03 23:50:37+0530 [-] 2018-03-03 23:50:37 ERROR main - Failed to decode json during parse request. Error: Expecting value: line 1 column 1 (char 0). Request content: 'b"'{query:hi}'"'

**Comment by tmbo** [comment]
I think it is due to the outer `'` if you take a close look at the logged content, there are to many `"`'s and `'`'s
