### ISSUE TITLE
I have a problem with RASA deployed in Facebook Messenger

### ISSUE THREAD

**Issue by LuisQ95** [RasaHQ/rasa_core#1118]
I need help with this problem:

Error in app: Exception on /webhooks/facebook/webhook [POST]

AttributeError: 'Messenger' object has no attribute 'name'

My version of RASA-core is 0.11.8 and RASA-nlu is 0.13.5.

**Comment by akelad** [comment]
Please fill out the issue template when creating an issue

**Rasa Core version**:

**Python version**: 

**Operating system** (windows, osx, ...):

**Issue**:



**Content of domain file** (if used & relevant):
```yaml

```

Can you post the full error trace please?

**Comment by amsolu** [comment]
LuisQ95 I had the same issue, it was fixed when I downgraded rasa_core to 0.11.5
Please try it pip install rasa_core==0.11.5

**Comment by LuisQ95** [comment]
akelad 
Rasa Core version : 0.11.8
Python version: 3.6.6
OS: Windowns 7

Content of domain:
slots:
  location:
    type: text


intents:
 - saludo
 - adios
 - informacion
 - csweb
 - csbimoneda
 - csmantenimiento
 - csoperacionesventanilla
 - csoperacionescajero
 - csestablecimiento
 - csfondos
 - csseguro
 - csabrir
 - csdepositos
 - csfranquicia
 - csestados

entities:
 - location

templates:
  utter_greet:
    - 'Hola! Como te puedo ayudar?'
  utter_goodbye:
    - 'Hablamos mas tarde.'
    - 'Adios :('
  utter_ask_location:
    - 'En que locacion?'
  utter_ask_web:
    - 'Ya diste el primer paso, ahora solo debes acercarte a nuestras oficinas para obtener la Tarjeta de Debito que te permitira acceder a todos nuestros canales de atencion Banca por Internet, Banca Movil, Banca por Telefono, entre otros. Con tu Tarjeta de Debito podras realizar operaciones, como pagar tus servicios, realizar transferencias y mucho mas.'
  utter_ask_bimoneda:
    - 'Es una cuenta en la que puedes realizar operaciones en Soles y en Dolares al tipo de cambio del dia. No mantiene los saldos separados por tipo de moneda. Tu saldo se guarda en la moneda que eliges al abrir la cuenta.'
  utter_ask_mantenimiento:
    - 'Nada, siempre y cuando tu Cuenta Sueldo reciba abonos de Pago de Haberes de manera consecutiva.'
  utter_ask_ventanilla:
    - 'Puedes realizar depositos ilimitados, 2 operaciones sin costo (retiros de dinero y transferencias entre cuentas) en la misma localidad donde se contrato tu cuenta.'
  utter_ask_cajero:
    - 'En cajeros del BBVA Continental puedes retirar ilimitadamente sin costo a nivel nacional.'
  utter_ask_establecimiento:
    - 'Si, puedes utilizarla en la amplia red de establecimientos afiliados a Visa.'
  utter_ask_fondos:
    - 'Si, cuando lo necesites.'
  utter_ask_seguro:
    - 'Si, los saldos estan cubiertos por Fondo de Seguro Deposito hasta por 99372 (periodo Setiembre 2018 Noviembre 2018 N B-2243-2018, sujeto a modificacion trimestral por la SBS).'
  utter_ask_abrir:
    - 'No necesitas de un deposito minimo para abrir tu Cuenta Sueldo.'
  utter_ask_depositos:
    - 'Si, siempre.'
  utter_ask_franquicia:
    - 'Es el monto a partir del cual el Banco paga intereses: '
  utter_ask_estados:
    - 'No, sin embargo se pueden emitirse si asi lo solicitas.'


actions:
 - utter_greet
 - utter_goodbye
 - utter_ask_location
 - action_weather
 - utter_ask_web
 - utter_ask_bimoneda
 - utter_ask_mantenimiento
 - utter_ask_ventanilla
 - utter_ask_cajero
 - utter_ask_establecimiento
 - utter_ask_fondos
 - utter_ask_seguro
 - utter_ask_abrir
 - utter_ask_depositos
 - utter_ask_franquicia
 - utter_ask_estados

**Comment by amsolu** [comment]
Luis,
Try downgrading rasa_core to 0.11.5
pip install rasa_core==0.11.5
and check if this is working for you as well, 
My2cents

**Comment by amsolu** [comment]
Sorry, I did it twice :(

**Comment by LuisQ95** [comment]
amsolu, Thank you very much. My bot now is working fine. :D :+1:

**Comment by amsolu** [comment]
Hola, me alegra haber ayudado, ahora me queda claro que algo cambiaron y no esta documentado :)
Como podemos mantener contacto en privado?
No se si este sistema permite eso

Abrazo

**Comment by akelad** [comment]
Hm, no we wouldn't recommend downgrading in general. @LuisQ95 can you please post the full error you got? this is something we need to fix

**Comment by LuisQ95** [comment]
Hi akelad, look this is my error in
Rasa Core version : 0.11.8
Python version: 3.6.6
OS: Windowns 7 (Service pack 1)

(base) C:\Users\UserTBS1\Desktop\bot_u_es>python run_app.py
C:\Users\UserTBS1\Anaconda3\lib\site-packages\rasa_nlu\extractors\entity_synonym
s.py:85: UserWarning: Failed to load synonyms file from './models/nlu/default/we
athernlu\entity_synonyms.json'
  "".format(entity_synonyms_file))
C:\Users\UserTBS1\Anaconda3\lib\site-packages\pykwalify\core.py:99: UnsafeLoader
Warning:
The default 'Loader' for 'load(stream)' without further arguments can be unsafe.

Use 'load(stream, Loader=ruamel.yaml.Loader)' explicitly if that is OK.
Alternatively include the following in your code:

  import warnings
  warnings.simplefilter('ignore', ruamel.yaml.error.UnsafeLoaderWarning)

In most other cases you should consider using 'safe_load(stream)'
  data = yaml.load(stream)
2018-10-05 08:43:07.944161: I T:\src\github\tensorflow\tensorflow\core\platform\
cpu_feature_guard.cc:141] Your CPU supports instructions that this TensorFlow bi
nary was not compiled to use: AVX2
[2018-10-05 08:44:20,063] ERROR in app: Exception on /webhooks/facebook/webhook
[POST]
Traceback (most recent call last):
  File "C:\Users\UserTBS1\Anaconda3\lib\site-packages\flask\app.py", line 2292,
in wsgi_app
    response = self.full_dispatch_request()
  File "C:\Users\UserTBS1\Anaconda3\lib\site-packages\flask\app.py", line 1815,
in full_dispatch_request
    rv = self.handle_user_exception(e)
  File "C:\Users\UserTBS1\Anaconda3\lib\site-packages\flask\app.py", line 1718,
in handle_user_exception
    reraise(exc_type, exc_value, tb)
  File "C:\Users\UserTBS1\Anaconda3\lib\site-packages\flask\_compat.py", line 35
, in reraise
    raise value
  File "C:\Users\UserTBS1\Anaconda3\lib\site-packages\flask\app.py", line 1813,
in full_dispatch_request
    rv = self.dispatch_request()
  File "C:\Users\UserTBS1\Anaconda3\lib\site-packages\flask\app.py", line 1799,
in dispatch_request
    return self.view_functions[rule.endpoint](**req.view_args)
  File "C:\Users\UserTBS1\Anaconda3\lib\site-packages\rasa_core\channels\faceboo
k.py", line 273, in webhook
    messenger.handle(request.get_json(force=True))
  File "C:\Users\UserTBS1\Anaconda3\lib\site-packages\fbmessenger\__init__.py",
line 259, in handle
    return self.message(message)
  File "C:\Users\UserTBS1\Anaconda3\lib\site-packages\rasa_core\channels\faceboo
k.py", line 62, in message
    self._handle_user_message(text, self.get_user_id())
  File "C:\Users\UserTBS1\Anaconda3\lib\site-packages\rasa_core\channels\faceboo
k.py", line 77, in _handle_user_message
    input_channel=self.name())
### AttributeError: 'Messenger' object has no attribute 'name'
127.0.0.1 - - [2018-10-05 08:44:20] "POST /webhooks/facebook/webhook HTTP/1.1" 5
00 412 0.015001

**Comment by LuisQ95** [comment]
Hola amsolu, quizas se pueda mediante linkedin. mi cuenta esta con mi nombre Luis Quispe. 

Saludos

**Comment by akelad** [comment]
Hi please upgrade to 0.11.11, i just fixed the error with this PR #1138
