### ISSUE TITLE
Failed to validate domain.yml - intents are true/false?

### ISSUE THREAD

**Issue by alex742** [RasaHQ/rasa_core#1126]
**Rasa Core version**: 0.11.8

**Python version**: 3.6.6

**Operating system** (windows, osx, ...): Windows 

**Issue**:
When running the command: 
python -m rasa_core.train -d domains/domain.yml -s stories/story.md -o models/model_test/dialogue --epochs 200
an error appears stating that my domain.yml file couldn't be validated and that there is a schema error.

I've attached the error message, my domain file, data file, and stories file. I had to change the file type to upload them, I have them as yml for domain and md for the others.

![image](https://user-images.githubusercontent.com/14424567/46474048-cca50e80-c7d9-11e8-8923-9e4181640ad8.png)

[domain.txt](https://github.com/RasaHQ/rasa_core/files/2446313/domain.txt)
[story.txt](https://github.com/RasaHQ/rasa_core/files/2446314/story.txt)
[data.txt](https://github.com/RasaHQ/rasa_core/files/2446315/data.txt)

**Comment by alex742** [comment]
I will add that this doesn't seem to stop the intents from triggering

**Comment by akelad** [comment]
Thanks for raising this issue, @MetcalfeTom  will get back to you about it soon.

**Comment by MetcalfeTom** [comment]
Hi!  Thanks for uploading the data, I think I have found the problem.

Could you try renaming the intents `yes` and `no` to `mood_affirm` and `mood_deny` in all three of your data files?  You can keep the training examples in `data.md`, just rename the intent label.

**Comment by alex742** [comment]
Thanks that fixed it! So just to clarify, are "yes" and "no" key words or something? So it gets confused when I use them?

**Comment by MetcalfeTom** [comment]
Great to hear!

Exactly that - the problem is that YAML automatically maps a bunch of strings (like `on, off, yes, no`) to boolean values

**Comment by mk4224** [comment]
Issue:
When running the command: python train_online.py

i am getting following error. Please help me to fix this: 
In most other cases you should consider using 'safe_load(stream)'
  data = yaml.load(stream)
ERROR:pykwalify.core:validation.invalid
ERROR:pykwalify.core: --- All found errors ---
ERROR:pykwalify.core:[u"Value '-location' is not a list. Value path: '/entities'"]
Traceback (most recent call last):
  File "train_online.py", line 39, in <module>
    run_weather_online(nlu_interpreter)
  File "train_online.py", line 25, in run_weather_online
    action_endpoint=action_endpoint)
  File "/usr/local/lib/python2.7/dist-packages/rasa_core/agent.py", line 198, in __init__
    self.domain = self._create_domain(domain)
  File "/usr/local/lib/python2.7/dist-packages/rasa_core/agent.py", line 636, in _create_domain
    return Domain.load(domain)
  File "/usr/local/lib/python2.7/dist-packages/rasa_core/domain.py", line 89, in load
    return cls.from_yaml(read_file(filename))
  File "/usr/local/lib/python2.7/dist-packages/rasa_core/domain.py", line 93, in from_yaml
    cls.validate_domain_yaml(yaml)
  File "/usr/local/lib/python2.7/dist-packages/rasa_core/domain.py", line 129, in validate_domain_yaml
    raise ValueError("Failed to validate your domain yaml. "
ValueError: Failed to validate your domain yaml. Make sure the file is correct, to do sotake a look at the errors logged during validation previous to this exception.

**Comment by mk4224** [comment]
my domain.yml file is :

slots:
  location:
    type: text


intents:
 - greet
 - goodbye
 - inform_ct


entities:
 -location

templates:
  utter_greet:
    - 'Hello! How can I help?'
  utter_goodbye:
    - 'Talk to you later.'
    - 'Bye bye :('
  utter_ask_keyword:
    - 'Please give keywords'


actions:
 - utter_greet
 - utter_goodbye
 - utter_ask_keyword
 - action.ActionWeather
 - utter_ct
