### ISSUE TITLE
Tracker issues

### ISSUE THREAD

**Issue by amsolu** [RasaHQ/rasa_core#1130]
**Rasa Core version**:0.11.5

**Python version**: 3.6

**Operating system** (windows, osx, ...): Linux Ubuntu

**Issue**: Using the tracker to save conversations.
I was trying to get the conversations from the different channels I did connect to my Rasa Stack
Using http://localhost:5002/conversations I did get the list of active conversations however I am not able to get the information from Telegram conversations, I found out Telegram is the single one represented as a number instead of a text, see below:

(bot36) ale@ubuntu:~/Projects/weather_bot$ curl http://localhost:5002/conversations | python -mjson.tool
  % Total    % Received % Xferd  Average Speed   Time    Time     Time  Current
                                 Dload  Upload   Total   Spent    Left  Speed
100    72  100    72    0     0  10285      0 --:--:-- --:--:-- --:--:-- 10285
[
    "+130XXXX1311",        <-  Twilio
    626931294,               <- Telegram
    "2270705826305018" <- facebook
]

Any time I am running twilio and facebook tracker with its sender_id works but when trying the same with Telegram, I am getting this:

(bot36) ale@ubuntu:~/Projects/weather_bot$ curl http://localhost:5002/conversations/626931294/tracker | python -mjson.tool
  % Total    % Received % Xferd  Average Speed   Time    Time     Time  Current
                                 Dload  Upload   Total   Spent    Left  Speed
100   270  100   270    0     0   2142      0 --:--:-- --:--:-- --:--:--  2142
{
    "events": [
        {
            "event": "action",
            "name": "action_listen",
            "timestamp": 1538625454.9052396
        }
    ],
    "followup_action": null,
    "latest_event_time": 1538625454.9052396,
    "latest_message": {
        "entities": [],
        "intent": {},
        "text": null
    },
    "paused": false,
    "sender_id": "626931294",
    "slots": {
        "location": null
    }
}
Rasa is adding the quotes and I am assuming this is the reason I am getting all empty.
If I am running conversations again, a new sender_id appear which looks like the same Telegram id including quotes.

I don't know where the issue is, but I have no more ideas :(
(bot36) ale@ubuntu:~/Projects/weather_bot$ curl http://localhost:5002/conversations | python -mjson.tool
  % Total    % Received % Xferd  Average Speed   Time    Time     Time  Current
                                 Dload  Upload   Total   Spent    Left  Speed
100    72  100    72    0     0  10285      0 --:--:-- --:--:-- --:--:-- 10285
[
    "+13058071311",
    626931294,
    "2270705826305018",
    "626931294"
]
Thanks

**Comment by amsolu** [comment]
Updating, this is the info from Telegram where it shows the sender_id as a number instead of textPOST /webhooks/telegram/webhook

    Summary
    Headers
    Raw
    Binary

336 bytes application/json

{
    "update_id": 250524961,
    "message": {
        "message_id": 638,
        "from": {
            "id": 626931294,
            "is_bot": false,
            "first_name": "Alejandro",
            "last_name": "Migliora",
            "username": "AleMigliora",
            "language_code": "en-US"
        },
        "chat": {
            "id": 626931294,
            "first_name": "Alejandro",
            "last_name": "Migliora",
            "username": "AleMigliora",
            "type": "private"
        },
        "date": 1538625227,
        "text": "Hello"
    }
}

**Comment by akelad** [comment]
I'm not sure what the issue is exactly? it would be good if you could format your curl responses with ``` to make it more legible. 
And could you post the output you're expecting to get and the one you're getting from Telegram?

**Comment by amsolu** [comment]
Akelad, I am not understanding your answer.
The issue is clear, I can not get the tracker information from Telegram channel.

According to the documentation 
https://rasa.com/docs/core/server/#
under HTTP API -> 
https://rasa.com/docs/core/server/#id6 ENDPOINTS

if you execute : 
GET /conversations/(str: sender_id)/tracker¶
Retrieves the current tracker state for the conversation with sender_id. This includes the set slots as well as the latest message and all previous events.

This works as expected in most of the channels and you can get the whole conversation with that sender_id (in my case facebook, twilio, default) however when you follow the exact same procedure with telegram

% Total % Received % Xferd Average Speed Time Time Time Current
Dload Upload Total Spent Left Speed
100 270 100 270 0 0 2142 0 --:--:-- --:--:-- --:--:-- 2142
{
"events": [
{
"event": "action",
"name": "action_listen",
"timestamp": 1538625454.9052396
}
],
"followup_action": null,
"latest_event_time": 1538625454.9052396,
"latest_message": {
"entities": [],
"intent": {},
"text": null
},
"paused": false,
"sender_id": "626931294",
"slots": {
"location": null
}
}

Everything is empty, NONE of the conversations is there, despite we had the same conversations we had in the other channels.

Digging a little bit, my thought is the format of the sender_id (Type) is different in Telegram see the output when you request the active conversations:

per the DOCUMENTATION
GET /conversations¶
List the sender ids of all the running conversations.

My output is:
% Total % Received % Xferd Average Speed Time Time Time Current
Dload Upload Total Spent Left Speed
100 72 100 72 0 0 10285 0 --:--:-- --:--:-- --:--:-- 10285
[
"+130XXXX1311", <- Twilio
626931294, <- Telegram
"2270705826305018" <- facebook
]

If you have a look to the sender_id active list, the ones in quote works (Type text
Telegram sender_id is getting as a number and I GUESS/BELIEVE this is the issue for the lack of information when trying to GET the conversation tracker.

Hope this time it is a little more clear pointing to documentation.
Thanks

**Comment by akelad** [comment]
i just edited your comment with the formatting, that's what i meant in that regard.
As for the general issue, i'm looking into the problem with facebook right now anyways, so i'll look into this too

**Comment by amsolu** [comment]
Hi, any update on this issue?
Thanks

**Comment by akelad** [comment]
i've found the problem, i just need to fix it which i haven't had the time to yet. i'll get to it this week or next at the latest

**Comment by wochinge** [comment]
You are welcome! Thanks for bringing up this issue and describing it so detailed! 👍
