### ISSUE TITLE
error in docs for RestInput

### ISSUE THREAD

**Issue by amn41** [RasaHQ/rasa_core#1135]
**Rasa Core version**: 0.11.9

**Issue**:

Docs state that the payload for the `RestInput` channel should be:

```
{
  "sender": <>,
  "text": <>
}
```

but the correct payload is:

```
{
  "sender": <>,
  "message": <>
}
```
**Content of domain file** (if used & relevant):
```yaml

```

**Comment by Zhipeng-Chang** [comment]
Hi! I would like to work on this issue, I just wonder which doc contains the wrong payload?

**Comment by Zhipeng-Chang** [comment]
[https://github.com/RasaHQ/rasa_core/pull/1139](url)

**Comment by Zhipeng-Chang** [comment]
https://github.com/RasaHQ/rasa_core/pull/1139

**Comment by ankitameht** [comment]
Hi I can work on this issue, if @Zhipeng-Chang is not already on it! :)

**Comment by ankitameht** [comment]
Great!
