### ISSUE TITLE
wrongly extracting username from JWT

### ISSUE THREAD

**Issue by akelad** [RasaHQ/rasa_core#1140]
This line should be extracting "username" rather than "user"
https://github.com/RasaHQ/rasa_core/blob/master/rasa_core/server.py#L93

**Comment by Zhipeng-Chang** [comment]
Hi @akelad! I just fixed this bug along with another bug, and got the pull request in!

**Comment by Zhipeng-Chang** [comment]
Hi! This change caused the build server failed to build, is that okay without passing the Travis CI?
