### ISSUE TITLE
handling single entity multiple intents

### ISSUE THREAD

**Issue by abhijeetshukla007** [RasaHQ/rasa_core#1142]
Rasa NLU Core version**: rasa-nlu- 0.13.4 rasa core 0.11.1

**Python version**:   3.6.5

**Operating system** (windows, osx, ...): win 10

**Issue**: 
Hi there ,
I was trying to create a simple small talk and todo list tracker Bot, but I am facing issue of handling single entity multiple intent  as:
==> This works fine
SAMPLE STORY 1
create.todolist{"tolist-name": "my tasks"}
    - slot{"tolist-name": "my tasks"}
    - utter_ask_taskName
STORY 2
retrieve.todolist{"tolist-name": "daily tasks"}
    - slot{"tolist-name": "daily tasks"}
    - action_retrieve_todo_list

==> When ever I place this story to get the list name separately the dialogMgmt model is going to fallback

##ERROR STORY
* create.todolist
    - utter_ask_todo_list_name
* input.list.name{"tolist-name": "my tasks"}
    - slot{"tolist-name": "my tasks"}
    - action_create_todo_list
    - slot{"tolist-name": "my tasks"}
    - utter_ask_taskName

git: https://github.com/abhijeetshukla007/Tracker

Please guide further.

Thanks
Abhijeet

**Comment by akelad** [comment]
do you start with the `create.todolist` event? because right now you just have one story, and it starts with a greeting, so that might explain it. Also are you using NLU? running rasa_core with `--debug` might give you some more info as to what's going wrong

**Comment by abhijeetshukla007** [comment]
Hi Akelad,

I ran starting the conversation with create.todolist instead of smalltalk event same issue persists.

I checked the same issue of **multiple intents using same entity** on which you replied to create a new input intent to get the entity (input.list.name) in case as:

## STORY
create.todolist
utter_ask_todo_list_name
input.list.name{"tolist-name": "my tasks"}
slot{"tolist-name": "my tasks"}
action_create_todo_list
slot{"tolist-name": "my tasks"}
utter_ask_taskName

##SAMPLE STORY 2
retrieve.todolist
utter_ask_todo_list_name
input.list.name{"tolist-name": "my tasks"}  **//error line**
slot{"tolist-name": "my tasks"}
action_retrieve_todo_list

In this case the bot was taking intent as create todo list on "**//error line**".

Attached sample old git code which was running well 
https://github.com/abhijeetshukla007/tracker-backup.git

In this codebase I was not able to recognize the intent properly if it was not set in the first statement of user

If you have any running sample of multiple intents which have conditional input to same entity please provide the link.

Thanks
Abhijeet

**Comment by akelad** [comment]
but what about if you start it with the `greeting`, then it should work as far as i can tell. 
Hm I'm not sure what you mean about the "multiple intents using same entity ", if your nlu model isn't picking up the correct entities, then you probably need more training data. It helps to run rasa core with the `--debug` flag to see what exactly is going wrong

**Comment by abhijeetshukla007** [comment]
Hi Akelad,
Thanks for the help, The issue got resolved, it was due to nlu score from spacy_sklearn pipeline which was less due to which the fallback response was coming up, its working good with tensorflow_embedding now :)
Thanks
