### ISSUE TITLE
Getting AttributeError: module 'rasa_core.training.online' has no attribute 'serve_agent' while doing interactive learning

### ISSUE THREAD

**Issue by vikingsvivek** [RasaHQ/rasa_core#1150]
**Rasa Core version** 0.13.6

**Operating system** windows

**Content of model configuration file:**
{
"pipeline":"spacy_sklearn",
"path":"./models/nlu",
"data":"./data/data.json"
}

Issue:
Getting error
INFO:rasa_core.policies.keras_policy:Done fitting keras policy model
Traceback (most recent call last):
File "train_online.py", line 37, in 
run_product_online(nlu_interpreter)
File "train_online.py", line 30, in run_product_online
online.serve_agent(agent)
AttributeError: module 'rasa_core.training.online' has no attribute 'serve_agent'

**Comment by Ghostvv** [comment]
`rasa_core` version cannot be more than `0.12`

**Comment by vikingsvivek** [comment]
Apologies,  shared wrong version in the post.
**Rasa-core version** 0.11.10

**Comment by Ghostvv** [comment]
Could you please provide what is inside your `train_online.py`?

**Comment by Ghostvv** [comment]
Please check https://github.com/RasaHQ/rasa_core/blob/master/examples/concertbot/train_interactive.py for an example how to use `interactive learning from a script

**Comment by vikingsvivek** [comment]
**train_online.py** I have used. 
from __future__ import absolute_import
from __future__ import division
from __future__ import print_function
from __future__ import unicode_literals

import logging

from rasa_core.agent import Agent
from rasa_core.policies.keras_policy import KerasPolicy
from rasa_core.policies.memoization import MemoizationPolicy
from rasa_core.interpreter import RasaNLUInterpreter
from rasa_core.train import online

logger = logging.getLogger(__name__)


def run_product_online(interpreter,
                          domain_file="chatbot_domain.yml",
                          training_data_file='data/stories.md'):
    					  
    agent = Agent(domain_file,
                  policies=[MemoizationPolicy(max_history=2), KerasPolicy()],
                  interpreter=interpreter)
    				  
    data = agent.load_data(training_data_file)
    agent.train(data,
                       batch_size=50,
                       epochs=200,
                       max_training_samples=300)				   
    #online.serve_agent(agent)
    online.run_online_learning(agent)
    return agent


if __name__ == '__main__':
    logging.basicConfig(level="DEBUG")
    nlu_interpreter = RasaNLUInterpreter('./models/nlu/default/chatbotnlu')
    run_product_online(nlu_interpreter)

**Comment by Ghostvv** [comment]
could you please try:
```
from __future__ import absolute_import
from __future__ import division
from __future__ import print_function
from __future__ import unicode_literals

import logging

from rasa_core import utils, train, run
from rasa_core.training import online

logger = logging.getLogger(__name__)


def train_agent():
    return train.train_dialogue_model(domain_file="domain.yml",
                                      stories_file="data/stories.md",
                                      output_path="models/dialogue",
                                      max_history=2,
                                      kwargs={"batch_size": 50,
                                              "epochs": 200,
                                              "max_training_samples": 300
                                              })


if __name__ == '__main__':
    utils.configure_colored_logging(loglevel="INFO")
    agent = train_agent()
    online.run_online_learning(agent)
```

**Comment by rahulroxx** [comment]
Doesn't work for me as well! 


> could you please try:
> 
> ```
> from __future__ import absolute_import
> from __future__ import division
> from __future__ import print_function
> from __future__ import unicode_literals
> 
> import logging
> 
> from rasa_core import utils, train, run
> from rasa_core.training import online
> 
> logger = logging.getLogger(__name__)
> 
> 
> def train_agent():
>     return train.train_dialogue_model(domain_file="domain.yml",
>                                       stories_file="data/stories.md",
>                                       output_path="models/dialogue",
>                                       max_history=2,
>                                       kwargs={"batch_size": 50,
>                                               "epochs": 200,
>                                               "max_training_samples": 300
>                                               })
> 
> 
> if __name__ == '__main__':
>     utils.configure_colored_logging(loglevel="INFO")
>     agent = train_agent()
>     online.run_online_learning(agent)
> ```

**Comment by rahulroxx** [comment]
training online triggers same error for me as well. I have tried the train_interactive script from concertbot but it throws me:- 

```
Traceback (most recent call last):
  File "train_online.py", line 9, in <module>
    from rasa_core.training import interactive
ImportError: cannot import name 'interactive'
```

**Comment by akelad** [comment]
@rahulroxx which rasa core version are you using? this will probably only work if you've got the latest version installed

**Comment by rahulroxx** [comment]
rasa-core==0.11.12
@akelad

**Comment by akelad** [comment]
We renamed that in a later version i think, please try installing the latest version 0.11.12

**Comment by ASHUSINGH16** [comment]
@Ghostvv   I am using same code as you suggested and it starts online training. But I am facing a strange issue. It is identifying my input as intet. Let's say If I say 'Hi' It gives me message like 
`Is the NLU classification for 'Hi' with intent 'Hi' correct? ` and when I say `No` it shows probability of all intents, 'Hi' having 1.00 and rest intents as 0.00 . However it should have been `greetme` intent. Can anyone please suggest what to do in such cases. I have already regenerated Rasa NLU model and my data.json has sufficient example for each intent. Please see below for more details. Also I am not able to understand like in previous RASA Core version for online training we used to pass `RasaNLUInterpreter` But in latest version we are not passing it so how it is communicate with NLU to determine intents. 

`Bot loaded. Type a message and press enter (use '/stop' to exit).
127.0.0.1 - - [2018-10-23 15:36:17] "GET /domain HTTP/1.1" 200 2945 0.000000
127.0.0.1 - - [2018-10-23 15:36:18] "GET /conversations/default/tracker?include_events=APPLIED HTTP/1.1" 200 456 0.000000
? Next user input:  Hi
127.0.0.1 - - [2018-10-23 15:36:22] "POST /conversations/default/messages HTTP/1.1" 200 746 0.000000
127.0.0.1 - - [2018-10-23 15:36:23] "GET /conversations/default/tracker?include_events=AFTER_RESTART HTTP/1.1" 200 746 0.000000
? Is the NLU classification for 'Hi' with intent 'Hi' correct?  No
? What intent is it?  (Use arrow keys)
 ❯ 1.00 Hi
   0.00 aboutbot
   0.00 affirmBot
   0.00 botcapability
   0.00 findLocation
   0.00 findSale
   0.00 findSaleCust
   0.00 findStockCust
   0.00 goodbye
   0.00 greetme
   0.00 praisebot
   0.00 thanksbot`

Please help.

**Comment by Ghostvv** [comment]
@ASHUSINGH16 please create separate issue

**Comment by NathalieFouet** [comment]
Hi everyone ! 

We have the same issue than @rahulroxx, but I have the version rasa-core 0.11.12. I need to install something else ? 

Thanks !
