### ISSUE TITLE
Exception: The model predicted the custom action 'action_check_status' but you didn't configure an endpoint to run this custom action. 

### ISSUE THREAD

**Issue by hd016** [RasaHQ/rasa_core#1166]
**Rasa Core version**:
rasa-core==0.11.11
rasa-core-sdk==0.11.5
rasa-nlu==0.13.6

**Python version**:  3.6.3

**Operating system** (windows, osx, ...): Mac OSX 10.11.16

```
WARNING:rasa_core.agent:Passing a text to `agent.handle_message(...)` is deprecated. Rather use `agent.handle_text(...)`.
ERROR:rasa_core.processor:Encountered an exception while running action 'action_check_status'. Bot will continue, but the actions events are lost. Make sure to fix the exception in your custom code.
ERROR:rasa_core.processor:The model predicted the custom action 'action_check_status' but you didn't configure an endpoint to run this custom action. Please take a look at the docs and set an endpoint configuration. https://rasa.com/docs/core/customactions/
Traceback (most recent call last):
  File "/Users/DHarun/anaconda3/envs/x/lib/python3.6/site-packages/rasa_core/processor.py", line 338, in _run_action
    events = action.run(dispatcher, tracker, self.domain)
  File "/Users/DHarun/anaconda3/envs/x/lib/python3.6/site-packages/rasa_core/actions/action.py", line 305, in run
    "".format(self.name(), DOCS_BASE_URL))
Exception: The model predicted the custom action 'action_check_status' but you didn't configure an endpoint to run this custom action. Please take a look at the docs and set an endpoint configuration. https://rasa.com/docs/core/customactions/
```

**Content of domain file** (if used & relevant):
endpoints.yml

```
action_endpoint:
url: "http://localhost:5055/webhook"
```

Info about server for custom actions:
```
$ python -m rasa_core_sdk.endpoint --actions actions
INFO:__main__:Starting action endpoint server...
INFO:rasa_core_sdk.executor:Registered function for 'action_check_status'.
INFO:__main__:Action endpoint is up and running. on ('0.0.0.0', 5055)
```

I use to develop rasa chatbot the anaconda environment.
I have a virtuell environment form the anaconda nagivator, I create from this two terminals:
first, start the server and the second to start the bot:
`bot.py --endpoints endpoints.yml`

the code for the bot:

```
import logging,  warnings
from rasa_nlu.training_data import load_data
from rasa_nlu.config import RasaNLUModelConfig
from rasa_nlu.model import Trainer
from rasa_core.policies.keras_policy import KerasPolicy
from rasa_core.agent import Agent

logging.basicConfig(level="INFO")
warnings.filterwarnings('ignore')


agent = Agent('domain.yml', policies=[KerasPolicy()])
training_data = agent.load_data('stories.md')
agent.train(
        training_data,
        validation_split=0.0,
        epochs=400
)

agent.persist('models/dialogue')


training_data = load_data('nlu.md')
pipeline = [{"name": "nlp_spacy"},
            {"name": "tokenizer_spacy"},
            {"name": "intent_featurizer_spacy"},
            {"name": "intent_classifier_sklearn"}]

trainer = Trainer(RasaNLUModelConfig({"pipeline": pipeline}))
interpreter = trainer.train(training_data)

model_directory = trainer.persist('./projects/default/')
agent = Agent.load('models/dialogue', interpreter=model_directory)


print("Your bot is ready to talk! Type your messages here or send 'stop'")
while True:
    a = input()
    if a == 'stop':
        break
    responses = agent.handle_message(a)
    for response in responses:
        print(response["text"])

```

I cant start the custom actions, how can I solve this issue? Thanks.

**Comment by akelad** [comment]
Thanks for raising this issue, @MetcalfeTom will get back to you about it soon.

**Comment by hd016** [comment]
> Thanks for raising this issue, @MetcalfeTom will get back to you about it soon.

@akelad @MetcalfeTom How can I continue here? When can I expect a response and is in this process a bug?

**Comment by MetcalfeTom** [comment]
Hi @hd016 I'm here for you.

What command are you using to run core?

**Comment by hd016** [comment]
> Hi @hd016 I'm here for you.
> 
> What command are you using to run core?

`$ python -m rasa_core_sdk.endpoint --actions actions` it is also in the post. Thank you for your help. @MetcalfeTom

**Comment by MetcalfeTom** [comment]
Hi again.

My apologies, I meant the command used to run the bot with core but I see you put that in the post as well: `bot.py --endpoints endpoints.yml`

You are passing the endpoints to your script but there is no argparser to use the `--endpoints` flag you've specified with the command.  You could configure a parser in your script to do so.  Alternatively if you would like to keep this as a standalone Python script I would recommend the following steps:

1. Define `endpoints = "/path/to/your/endpoints.yml"` in your `bot.py` script
2. Add `action_endpoint=endpoints.action` as an argument to your agent constructor like so:
```
agent = Agent.load('models/dialogue', interpreter=model_directory, action_endpoint=endpoints.action)
```

Let me know if this doesn't solve your problem

**Comment by hd016** [comment]
I have implement the endpoint in the script, so your suggestion is working. Thank you very much!

**Comment by deepsole** [comment]
@MetcalfeTom Please i have an issue with my custom actions. It works very fine and pulls weather conditions when i run core. But when i integrate the bot into telegram, it skips the actions and i get an **Exception: The model predicted the custom action 'action_weather' but you didn't configure an endpoint to run this custom action. Please take a look at the docs and set an endpoint configuration. https://rasa.com/docs/core/customactions/**. Please help, i have been on this for a week. Thanks

**Comment by MetcalfeTom** [comment]
Hi @deepsole,

What url are you using as your `action_endpoint` in `endpoints.yml`?

**Comment by deepsole** [comment]
> @MetcalfeTom Please i have an issue with my custom actions. It works very fine and pulls weather conditions when i run core. But when i integrate the bot into telegram, it skips the actions and i get an **Exception: The model predicted the custom action 'action_weather' but you didn't configure an endpoint to run this custom action. Please take a look at the docs and set an endpoint configuration. https://rasa.com/docs/core/customactions/**. Please help, i have been on this for a week. Thanks

Its working now. I didn't specify the --endpoints. Thanks !!!

**Comment by Sandeep1205** [comment]
@MetcalfeTom  refering to @deepsole  problem, I am also facing the same problem.
I am using the url in endpoint.yml is 
action_endpoint:
http://localhost:5005

**Comment by akelad** [comment]
Please create a new issue with more details if you're having a problem
