### ISSUE TITLE
Passing custom payload when handling message / text to retrieve in action

### ISSUE THREAD

**Issue by deW1** [RasaHQ/rasa_core#1167]
**Rasa Core version**: >=0.11.12

**Python version**: 3.6.6

**Operating system** (windows, osx, ...): Windows

**Issue**: Is there any way of passing custom payload when handling / parsing a message that I can retrieve from for example the tracker during the custom action?

I have some additional information which I need when actions are happening.

Basically I would like to:
Use handle_message / text, pass any kind of container as payload as well as the message.
in the custom action retrieve the payload object and utilize the information.

**Content of domain file** (if used & relevant):
```yaml

```

**Comment by akelad** [comment]
Just to clarify, do you want to pass this custom payload with the bot message or with the user message?

**Comment by deW1** [comment]
With the user message.

To be more clear, something like:

`agent.handle_message(UserMessage(text="Hello World", sender_id="Testperson1", payload={"additional_information:" additional_information_object}))`
or
`agent.handle_text("Hello World", payload={"additional_information:" additional_information_object})`

So I can retrieve that `additional_information_object` from the tracker of the custom action for example.

**Comment by akelad** [comment]
i don't think this is something we'll add, how would you know which payload to send with which user message?

**Comment by deW1** [comment]
In my case I don't get the messages directly. They're coming in asynchronous with information about channel / user / permissions / respond where / etc.. I can work around it and build a temporary storage then map the payload with the message + sender_id to identify it, the hassle will be with the lifetime of that temporary stored object as only some messages trigger actions, so I figured I'd ask if there's a way that would save me some headache :)

**Comment by akelad** [comment]
Yeah I think that's something you need to handle in your custom implementation then. As of now this is not something we'll be adding
