### ISSUE TITLE
clarify purpose of entities section in domain.yml

### ISSUE THREAD

**Issue by abunet** [RasaHQ/rasa_core#118]
Hi,
what is the purpose of the entity section in domain.yml?

If I've understood correctly a slot is autofilled with recognized entity values detected by the trained NLU model.
It isn't less redundant add a property to the slot of type entity?
If not specified, it could be mapped with an entity with the same name (as in the above example)

Example:

slots:
  cuisine:
    type: text
    entity: cuisine
  location:
    type: text       <-- mapped
  mycustomslot:
    type: text
    entity: false   <-- not mapped

Thanks in advance
Marco Roello

**Comment by tmbo** [comment]
The machine learning model needs to know which entities might occur. The entities are features of that model and need to be known before we run the training. Therefore, all the entities that the NLU produces and which the dialogue model should handle need to be listed.

I like the above idea, but we'd still need to list the entities that are not mapped to a slot.
