### ISSUE TITLE
PUT /conversations/(str: sender_id)/tracker is missing

### ISSUE THREAD

**Issue by fade2black** [RasaHQ/rasa_core#1183]
**Rasa Core version**: 0.11.3

**Python version**:  3.5.2

**Operating system** (windows, osx, ...): Linux container (Docker)

**Issue**: Missing endpoint

The RASA Core documentation says that to replace the tracker state using events we should use 
```
PUT /conversations/(str: sender_id)/tracker
```
However when I send  `curl -XPUT http://172.17.0.2:5005/conversations/bayram/tracker -d '[{"event": "slot", "name": "name", "value": "Bayram"}]'`
RASA Core responds with HTTP 405 (Method Not Allowed).

I could not find in the [source code](https://github.com/RasaHQ/rasa_core/blob/549786c000efd76cc3ea6b7bcc68b2c40c840534/rasa_core/server.py) anything related to `PUT /conversations/{str: sender_id}/tracker`.

**Comment by fade2black** [comment]
@akelad 
Sure. But I can't find your documentation source. I  cannot find it in the `docs` folder. Could you post me a link?

**Comment by akelad** [comment]
ok it looks like it's fixed in the master version of the docs actually: https://github.com/RasaHQ/rasa_core/blob/master/docs/_static/spec/server.yml#L382
Though the docs are a bit broken there (https://rasa.com/docs/core/master/server/), i'll look into what's going wrong 😄

**Comment by akelad** [comment]
closing this in favour of https://github.com/RasaHQ/rasa_core/issues/1192
