### ISSUE TITLE
KerasPolicy is not predicting utters as expected

### ISSUE THREAD

**Issue by RochaCarla** [RasaHQ/rasa_core#1188]
We are currently working on a pipeline composed of NLU tensorflow_embedding, and Memoization + KerasPolicy + fallback policy. We are using the default pipeline configuration. We have a set of 30 intents/utters and several stories.  The problem faced is that, even when intents are extracted, when it enters to KerasPolicy, the output utter (with over 90% confidence) is never related to the intent and it is always the wrong expected utter. We have:

- [ ] NLU is working excellent - feature extraction is very accurate (for correct intents, confidence >90%)

- [ ] MemoizationPolicy is working fine, when users fall into default stories

- [ ] Fallback policy seems to be well calibrated.

- [ ] KerasPolicy() is not working at all, even when: (a) is inserted out_of_scope intents over some stories, or (b) increased the number of stories, or   (c) increased the size of stories, (d) calibrated TRAINING_EPOCHS.

The complete project can be seen in [https://github.com/lappis-unb/rouana](https://github.com/lappis-unb/rouana) (branch v2.1.0). 

**Rasa Core version**:
rasa-core==0.10.3

**Python version**: 
python3.6

**Operating system** (windows, osx, ...):
ubuntu/osx

**Comment by akelad** [comment]
when you say increased the number of stories, by how many do you mean? Keras does learn to generalise for some paths, but it's not guaranteed that it will always predict the right action. You can also try out the EmbeddingPolicy, to see if that works better

**Comment by RochaCarla** [comment]
I've tested Keras for small stories (around 4-5 intents+utters), around 10 intents, and 15-20 stories examples (used smaller batch_size in Keras)

**Comment by akelad** [comment]
yeah you probably need a lot more than 15-20 stories for it to generalise properly. You can take a look at our [demo bot](https://github.com/RasaHQ/rasa-demo), the policy jumps in there a lot and does give accurate predictions (of course not 100% of the time).

I'm gonna close this issue now, since it's more of a discussion, if you'd like to discuss it further, please create a post on our [forum](https://forum.rasa.com)
