### ISSUE TITLE
Duckling didn't handle date entity

### ISSUE THREAD

**Issue by satishAarbor** [RasaHQ/rasa_core#1197]
**Rasa Core version**:0.11.12

**Python version**: Python 3.6.5

**Operating system** (windows, osx, ...):Ubuntu 16.04 LTS

**Issue**:
         I'm using duckling method to handle date entity but it doesn't work, I had started the duckling server by the following command -" sudo docker run -p 8000:8000 rasa/duckling", and my config.yml file was given below.

    pipeline:
  - name: "nlp_spacy"
  - name: "tokenizer_whitespace"
  - name: "intent_entity_featurizer_regex"
  - name: "ner_crf"
  - name: "ner_synonyms"
  - name: "intent_featurizer_count_vectors"
  - name: "intent_classifier_tensorflow_embedding"
    intent_tokenization_flag: true
    intent_split_symbol: "+"
  - name: "ner_duckling_http"
    url: "http://0.0.0.0:8000"
    locale: "de_DE"
    dimensions: ["time"]

![image](https://user-images.githubusercontent.com/43377921/47210329-4deeca80-d3b0-11e8-8231-89820bd8d21e.png)

the above image is interactive learning part it show this doesn't convert the 'coming friday' data into date values. Help me to handle this issue.

**Content of domain file** (if used & relevant):
```yaml

```

**Comment by souvikg10** [comment]
Is there a possibility that you are training the ner_crf to detect time ? by tagging your entities in your training data?
For duckling you don't need to anotate entities in your training data otherwise it will be picked up by ner_crf

Also you duckling locale in your pipeline is incorrrect
if you want the language english you should use

locale:en_IN (since it seems the sentences are associated to india) or you can also try en_UK, en_US

**Comment by satishAarbor** [comment]
Thanks for reply. Now it works fine but time zone is different i want to use india timezone. what should i do?

**Comment by souvikg10** [comment]
Ducking is using Olson data to retrieve timezone, you have to pass the timezone parameter in your config using the literal you need like "Europe/Paris"

https://en.wikipedia.org/wiki/Tz_database

**Comment by akelad** [comment]
I'm going to close this as it's more of a usage question, if you need more help please post on the [forum](https://forum.rasa.com)
