### ISSUE TITLE
Need pseudo code for categorical,boolean slot types and FormAction form setter 

### ISSUE THREAD

**Issue by SivaLokam** [RasaHQ/rasa_core#1213]
**Rasa Core version**:
0.13.6
**Python version**: 
Python 3.6.4 :: Anaconda, Inc.
**Operating system** (windows, osx, ...):
windows10
**Issue**:

1) I want to add buttons for given restaurant type, when I add more than four buttons, buttons are not getting displayed in the slack GUI
or HOw can add them as categorical variable

2) I want to use FormAction, but when I import in actions.py, it throws as error name is not recognized

If any pseudo code is available for reference, please do share, with import statements as well
**Content of domain file** (if used & relevant):
```yaml
## Generated Story 255706069223404498
* greet
    - utter_greet
* restaurant_search
    - utter_ask_location
* restaurant_search{"location": "delhi"}
    - slot{"location": "delhi"}
    - utter_ask_cuisine
* restaurant_search{"cuisine": "chinese"}
    - slot{"cuisine": "chinese"}
    - action_search_foodie
    - slot{"location": "delhi"}
    - utter_goodbye
    - export

## Generated Story 1993277579540566202
* greet
    - utter_greet
* restaurant_search
    - utter_ask_location
* restaurant_search{"location": "delhi"}
    - slot{"location": "delhi"}
    - utter_ask_cuisine
* restaurant_search{"cuisine": "North Indian"}
    - slot{"cuisine": "North Indian"}
    - action_search_foodie
    - utter_goodbye

## Generated Story 3320800183399695936
* greet
    - utter_greet
* restaurant_search
    - utter_ask_location
* restaurant_search{"location": "italy"}
    - slot{"location": "italy"}
	- utter_ask_cuisine
* restaurant_search{"cuisine": "chinese"}
    - slot{"cuisine": "chinese"}
    - action_search_foodie
* goodbye
    - utter_goodbye

## Generated Story -4639179087166749998
* greet
    - utter_greet
* restaurant_search
    - utter_ask_location
* restaurant_search{"location": "delhi"}
    - slot{"location": "delhi"}
    - utter_ask_cuisine
* restaurant_search{"cuisine": "chinese"}
    - slot{"cuisine": "chinese"}
    - action_search_foodie
    - slot{"location": "delhi"}
    - export


## Generated Story 4963448062290237512
* greet
    - utter_greet
* restaurant_search{"location": "delhi"}
    - slot{"location": "delhi"}
    - utter_ask_cuisine
* restaurant_search{"cuisine": "chinese"}
    - slot{"cuisine": "chinese"}
    - action_search_foodie
* affirm
    - utter_goodbye
    - export
## Generated Story 713508018726174463
* hi

## Generated Story 0

## Generated Story 4938366011132798014
* greet
    - utter_greet
* restaurant_search
    - utter_ask_location
* restaurant_search{"location": "hyderabad"}
    - slot{"location": "hyderabad"}
    - utter_ask_cuisine
* restaurant_search{"cuisine": "Italian"}
    - slot{"cuisine": "Italian"}
    - action_search_foodie
    - slot{"location": "hyderabad"}
* goodbye
    - utter_goodbye

## Generated Story 6701419372050737577
* greet
    - utter_greet
* restaurant_search
    - utter_ask_location
* restaurant_search{"location": "bengaluru"}
    - slot{"location": "bengaluru"}
    - utter_ask_cuisine
* restaurant_search{"cuisine": "chinese"}
    - slot{"cuisine": "chinese"}
    - action_search_foodie
    - slot{"location": "bengaluru"}
* thankyou
    - utter_goodbye


## Generated Story -6686161742149946112
* greet
    - utter_greet
* restaurant_search
    - utter_ask_location
* restaurant_search{"location": "bengaluru"}
    - slot{"location": "bengaluru"}
    - utter_ask_cuisine
* restaurant_search{"cuisine": "Chinese"}
    - slot{"cuisine": "Chinese"}
    - utter_ask_price
* restaurant_search{"price": "300"}
    - slot{"price": "300"}
    - action_search_foodie
    - slot{"location": "bengaluru"}
* goodbye
    - utter_goodbye

## Generated Story -4291197092257407725
* greet
    - utter_greet
* restaurant_search
    - utter_ask_location
* restaurant_search{"location": "hyd"}
    - slot{"location": "hyd"}
    - action_check_city
    - slot{"location": "hyd"}
* restaurant_search{"location": "Hyderabad"}
    - slot{"location": "Hyderabad"}
    - action_check_city
    - slot{"location": "Hyderabad"}
    - utter_ask_cuisine
* restaurant_search{"cuisine": "Chinese"}
    - slot{"cuisine": "Chinese"}
    - utter_ask_price
* restaurant_search{"price": "300 to 700"}
    - slot{"price": "300 to 700"}
    - action_search_foodie
    - slot{"location": "Hyderabad"}
* goodbye
    - utter_goodbye


```

**Comment by halloTheCoder** [comment]
What you have uploaded is not domain file but stories file(please check it), and you can get some reference on how to use form-action in [docs](https://rasa.com/docs/core/slotfilling/#slot-filling-with-a-formaction) and this [repo](https://github.com/halloTheCoder/service-bot/blob/master/actions.py). 

Version of rasa_core used in repo `rasa_core==0.11.08`.

**NOTE** :: The version you specified is most likely of `rasa_nlu`. Also, please specify the import line for form-action you have used, and what is the error otherwise it doesn't help.

Sorry, I can't help you with the first part, as it seems problem with slack rather than rasa.

**Comment by stalinsabu** [comment]
> 
> 
> What you have uploaded is not domain file but stories file(please check it), and you can get some reference on how to use form-action in [docs](https://rasa.com/docs/core/slotfilling/#slot-filling-with-a-formaction) and this [repo](https://github.com/halloTheCoder/service-bot/blob/master/actions.py).
> 
> Version of rasa_core used in repo `rasa_core==0.11.08`.
> 
> **NOTE** :: The version you specified is most likely of `rasa_nlu`. Also, please specify the import line for form-action you have used, and what is the error otherwise it doesn't help.
> 
> Sorry, I can't help you with the first part, as it seems problem with slack rather than rasa.

The 'repo' link is broken. Can you fix it cause I am not able to understand FormAction documentation

**Comment by halloTheCoder** [comment]
The repo was private so the link was not working. I have made it public now.

But, I don't think the repo will help you any more than docs. If you have any question, you can always ask in [discussion forum](https://forum.rasa.com/).

**Comment by akelad** [comment]
@halloTheCoder thanks for referring to the forum :) 
The buttons problem is related to slack limiting the amount of buttons allowed, so it's expected behaviour.
Not sure which Core version you're using, but this is the correct import `from rasa_core_sdk.forms import FormAction, FormField`
Gonna close this now, as the rest is more of a discussion

**Comment by SivaLokam** [comment]
Thanks all for the reply , it worked now
