### ISSUE TITLE
import error: cannot import name 'EndpointConfig'

### ISSUE THREAD

**Issue by sagarP47** [RasaHQ/rasa_core#1219]
**Rasa Core version**:0.9.0

**Python version**: 3.7

**Operating system** (windows, osx, ...):

**Issue**:

**Content of domain file** (if used & relevant):
```yaml

```

**Comment by souvikg10** [comment]
Consider upgrading your rasa core version to 0.11. EndpointConfig has been added since core 0.10

**Comment by sagarP47** [comment]
> Consider upgrading your rasa core version to 0.11. EndpointConfig has been added since core 0.10

oh! got it, thank you so much
