### ISSUE TITLE
RemoteBot sample aplication post request not working

### ISSUE THREAD

**Issue by Denaindra** [RasaHQ/rasa_core#122]
**Rasa Core version**:0.7.8

**Python version**: 2.7 

**Operating system** (windows, osx, ...): OSX

**Issue**:
remotebot application throwing URL not found an error during testing with postmen.  
Service running fine  on  "http://localhost:5005/" 

Post request - localhost:5005/conversations/default/parse -d
Body              -  {"query":"hello there"}

Response
<!DOCTYPE HTML PUBLIC "-//W3C//DTD HTML 3.2 Final//EN">
<title>404 Not Found</title>
<h1>Not Found</h1>
<p>The requested URL was not found on the server.  If you entered the URL manually please check your spelling and try again.</p>

**Content of domain file** (if used & relevant):
```yaml

```

**Comment by tmbo** [comment]
Please add the command for starting the server and the complete curl request.

**Comment by Denaindra** [comment]
**Starting server command -**
python -m rasa_core.server -d models/dialogue -u models/nlu/current -o out.log

**Complete Curl Request -**
$ curl -XPOST localhost:5005/conversations/default/parse -d

**Comment by tmbo** [comment]
On the latest master, starting the server with that command and running

`curl -XPOST localhost:5005/conversations/default/parse -d '{"query":"hello there"}'`

works for me. @Denaindra can you try that out and let me know if it works for you?

**Comment by tmbo** [comment]
Please try setting the proper headers for json, e.g. 
```
headers = {"Content-Type": "application/json"}
request = requests.get(url, headers=headers)
```
