### ISSUE TITLE
Update out-of-date facebook connector docs

### ISSUE THREAD

**Issue by ricwo** [RasaHQ/rasa_core#1220]
Include information on how to obtain the `verify` and `secret` fields

**Comment by tmbo** [comment]
@ricwo can you please add a short description to the issue about what it is, that is out of date?

**Comment by ricwo** [comment]
Sure - [point 3](https://rasa.com/docs/core/connectors/#getting-credentials) mentions using the collected `verify` and `secret`, but it isn't explained where to obtain them
