### ISSUE TITLE
release core 0.12

### ISSUE THREAD

**Issue by amn41** [RasaHQ/rasa_core#1230]
Things that are still open and need to be done before the release:
- merge forms 2 https://github.com/RasaHQ/rasa_core/pull/1013
- tracker store in yml https://github.com/RasaHQ/rasa_core/pull/1048

Open:
- should https://github.com/RasaHQ/rasa_core/pull/550 go in or wait until adapted to multiple models configured using config files?

**Comment by tmbo** [comment]
given that i am out of office wed-fri, I'll prepare it tomorrow and release on monday

**Comment by tmbo** [comment]
should still change #550 to use the config files, as it makes it easy to use

**Comment by akelad** [comment]
well i def won't get it done by tomorrow, but probably can by monday

**Comment by tmbo** [comment]
Monday sounds great 👍
