### ISSUE TITLE
Adding Follow up intents in domain

### ISSUE THREAD

**Issue by souvikg10** [RasaHQ/rasa_core#1232]
**Rasa Core version**: master

**Python version**: 3.6

**Operating system** (windows, osx, ...): osx

**Issue**:
This is more of an enhancement request to be able to add hierarchical intents in the domain file

```
intents:
 intentX:
   followup: true
   followup_intents:
      - affirm
      - deny
```

So basically if NLU provides an IntentX, you put a followup flag to true in the tracker and then for the next intent detection, one can check if the corresponding intent is part of the follow up intent or not in the domain specification. if not true, you repeat the last action until a circuit breaker, max 3 retries. 

It works for the other way around as well, that a followup intent must come after the parent intent is in the tracker. otherwise you provide a fallback action. This is specially true for headless intents - affirm, deny, maybe, confirm and will reduce error rates. 

Not sure if it something closely linked to FormsV2 which i understand is more slot filling.

Happy to work on this but need to make sure if this seems viable or not.

**Comment by EPedrotti** [comment]
Thanks for raising this issue, @Ghostvv will get back to you about it soon.

**Comment by Ghostvv** [comment]
Thank you for the suggestion, but could you please describe, general usage of such a system, otherwise it can be handled in a custom action.

For the other way around, would it mean that e.g. `affirm` cannot follow any intent?

**Comment by souvikg10** [comment]
Indeed like Dialogflow there are some intents like affirm/deny/maybe/cancel which have no real usage without a parent intent. 

For me these are like follow up intents

**Comment by Ghostvv** [comment]
maybe I'm wrong but in my mind affirm/deny/maybe/cancel are bonded more to previous bot action rather than user intent

**Comment by souvikg10** [comment]
But in the stories they are treated as intents.

IntentX
- some_action
Affirm
- some_other_action

So in general if someone just says 
Yes, some action may get triggered even though it has no context.

**Comment by Ghostvv** [comment]
sorry, I don't get what you mean with the last example. I meant that the first `some_action` could be triggered by different intent, but regardless of this intent, it expects `affirm/deny`. And it is a bit tedious to add `affirm/deny` to all possible intents. Moreover, intent can trigger different action depending on the history, therefore it might not always expect `affirm/deny`, but only sometimes

**Comment by souvikg10** [comment]
So you mean it is the action that expects the incoming intent?

My problem is how to validate that the next follow up intent is only affirm or deny. 

In Dialogflow they create follow up intents for parent intents that creates a hierarchical structure. Meaning given a question from the user, if a bot reply with a follow up question, the user must reply with an intent affirm or deny.

How to validate this?

Which is why I was a bit confused if this is related to FormActions

**Comment by Ghostvv** [comment]
With `forms_v2` we adding validation logic, so that you could create FormAction that doesn't require any slot, but only validates an input
