### ISSUE TITLE
Slack integration always answers as direct message instead of public channel

### ISSUE THREAD

**Issue by cbajohr** [RasaHQ/rasa_core#1243]
**Rasa Core version**: 0.11.12

**Python version**: 3.3.6

**Operating system** (windows, osx, ...): unix

**Issue**:
I've configured everything as described in the rasa core docs for the slack bot integration. 
But my bot always answers as direct message to me, instead of a message in the public channel I send my message from.

I tried everything from the slack_channel option to multiple event config variations in slack, but the bot always answers as direct message to me.

Any suggestion on how to get this right?

My Slack event config:
![bildschirmfoto 2018-10-29 um 17 27 53](https://user-images.githubusercontent.com/1948433/47665080-9a9c8780-dba0-11e8-9fa3-ef0a6f791f8b.png)

**Comment by akelad** [comment]
Thanks for raising this issue, @ricwo  will get back to you about it soon.

**Comment by ricwo** [comment]
@cbajohr does the entry for `slack_channel` in your `credentials.yml` contain the slack channel you want to post to?

**Comment by cbajohr** [comment]
@ricwo yes, everything ist configured as described in the docs. I've tried the roomname with #,@ and without any char before the name... nothing worked.

<img width="310" alt="image" src="https://user-images.githubusercontent.com/1948433/48252810-f3bcb480-e405-11e8-8e53-ddf2a58bb7a3.png">

**Comment by ricwo** [comment]
@cbajohr would you mind trying to replace your config with one that looks like this:

![image](https://user-images.githubusercontent.com/20581300/48275825-c3e1d100-e446-11e8-85fe-504a2d1f366f.png)

**Comment by cbajohr** [comment]
@ricwo thanks, but your config suggestion doesn't work either. The bot still answers in direct messages when I post something in the public room.

**Comment by ricwo** [comment]
@cbajohr the bug has been fixed on latest `master`

**Comment by cbajohr** [comment]
Thanks! My bot is already member of the used public channel.
I will look forward for the next stable release, to test it.

**Comment by cbajohr** [comment]
@ricwo Works just fine now! Thanks for your fast help.
Is it also possible to place the bot in multiple channels?
