### ISSUE TITLE
The sender ID is showing up default in mongodbDB. What does it mean? Is there any way to assign user ID to sender ID?

### ISSUE THREAD

**Issue by ashukrishna100** [RasaHQ/rasa_core#1257]
**Rasa Core version**:11.4

**Python version**: 3.6

**Operating system** (windows, osx, ...):win 10

**Issue**:
{ “_id” : ObjectId(“5bd6e007c5ac6f507adbf3a2”), “sender_id” : “default”, “events” : [ { “event” : “action”, “timestamp” : 1540808711.0658188, “name” : “action_listen” }, { “event” : “user”, “timestamp” : 1540808711.2268188, “text” : “hi”, “parse_data” : { “intent” : { “name” : “greet”, “confidence” : 0.9630651473999023 }, “entities” : [ ], “intent_ranking” : [ { “name” : “greet”, “confidence” : 0.9630651473999023 }, { “name” : “affirmation”, “confidence” : 0.03235085308551788 }, { “name” : “file”, “confidence” : 0 } ], “text” : “hi”

**Comment by akelad** [comment]
Thanks for raising this issue, @EPedrotti  will get back to you about it soon.

**Comment by EPedrotti** [comment]
Hi @ashukrishna100,
which channel are you using? 
Also, did you have a look at this[https://forum.rasa.com/t/customising-sender-id/1752]( https://forum.rasa.com/t/customising-sender-id/1752) ?
Let me know if it helps you

**Comment by ashukrishna100** [comment]
@akelad @EPedrotti 
In the bot.py file I used
`sender_id=user_id`
`responses = agent.handle_text(a,sender_id=sender_id)`

**instead of** 

`responses = agent.handle_message(a)`
