### ISSUE TITLE
KerasPolicy not recognizing `evaluate_every_num_epochs` 

### ISSUE THREAD

**Issue by ksurya** [RasaHQ/rasa_core#1258]
https://github.com/RasaHQ/rasa_core/blob/95e430f3a6307b82cac0509f0db9d4472fd46709/rasa_core/policies/keras_policy.py#L154

The parameter `evaluate_every_num_epochs` described in documentation is not identified as a valid parameter.

**Comment by akelad** [comment]
Please fill out the issue template

**Rasa Core version**:

**Python version**: 

**Operating system** (windows, osx, ...):

**Issue**:



**Content of domain file** (if used & relevant):
```yaml

```

And please provide some information, I'm not sure what part of the docs you're talking about

**Comment by Ghostvv** [comment]
@ksurya this parameter is only valid for `EmbeddingPolicy`
