### ISSUE TITLE
ImportError: cannot import name 'ConsoleInputChannel'

### ISSUE THREAD

**Issue by nahidalam** [RasaHQ/rasa_core#1260]
**Rasa Core version**: 0.12.0a4

**Python version**: 3.6

**Operating system** (windows, osx, ...): OSx

**Issue**:

I previously had the core version `0.9.8` and everything worked fine. Now I am developing something for Rasa core, so has the version `0.12.0a4` from git. With this new version, when I am building the dialogue model, I am getting error as there is no `ConsoleInputChannel` anymore

```
from rasa_core.channels.console import ConsoleInputChannel
ImportError: cannot import name 'ConsoleInputChannel'
```

How do I resolve this?

**Content of domain file** (if used & relevant):
```yaml

```

**Comment by akelad** [comment]
Thanks for raising this issue, @wochinge will get back to you about it soon.

**Comment by wochinge** [comment]
@nahidalam I think this is more a usage question. Please ask this on our forum: https://forum.rasa.com/ 🙂

**Comment by Nikhileshorg** [comment]
> @nahidalam I think this is more a usage question. Please ask this on our forum: https://forum.rasa.com/ 🙂

When I am trying to open this link. It is showing the site cannot be reached.

**Comment by wochinge** [comment]
@Nikhileshorg I just tried, this should be working.

**Comment by Nikhileshorg** [comment]
> @Nikhileshorg I just tried, this should be working.

Thanks for your reply, are there any settings I have to enable to reach that site. Because even now I am not able to access that page.

**Comment by wochinge** [comment]
Nope, it's a regular website. From which country are you trying to access it?

**Comment by Nikhileshorg** [comment]
> Nope, it's a regular website. From which country are you trying to access it?

I am trying to access it from the US.

**Comment by wochinge** [comment]
@JustinaPetr Ever heard of anything like that?

**Comment by JustinaPetr** [comment]
There was one time when Avast was blocking the site, but after contacting them and finding their system was falsely blocking the forum, this was fixed. Do you have any specific firewall settings that might be blocking the site?

**Comment by akelad** [comment]
just for reference: i can access it fine from the US currently
