### ISSUE TITLE
Custom action.py - no attribute dispatcher.utter_response

### ISSUE THREAD

**Issue by johnjacobkenny** [RasaHQ/rasa_core#1262]
**Rasa Core version**:
0.11.12
**Python version**: 
3.6.2
**Operating system** (windows, osx, ...):
Win 10

**Issue**:
I am able to send a response using `dispatcher.utter_message` in my custom `action.py`. However, I wanted to be able to send buttons and image along with text using `dispatcher.utter_response`. When I used `dispatcher.utter_response` (I can see this is mentioned as being available here https://rasa.com/docs/core/master/api/dispatcher/#rasa_core.dispatcher.Dispatcher.utter_response), python gives me this error

`AttributeError: 'CollectingDispatcher' object has no attribute 'utter_response'`.

Is this not available in v0.11.12? Or am I doing something wrong in my code?

Thanks for the help! 😃

**Comment by akelad** [comment]
Thanks for raising this issue, @MetcalfeTom  will get back to you about it soon.

**Comment by MetcalfeTom** [comment]
Hi @johnjacobkenny no need to worry,

Your function call is fine.  I am wondering where you are importing the dispatcher from?  `CollectingDispatcher` is from `rasa_core_sdk` and does not have the `utter_response()` method.  The class you want is `Dispatcher` from `rasa_core/dispatcher.py`

**Comment by johnjacobkenny** [comment]
I am using the dispatcher object provided in the run method,
`def run(self, dispatcher, tracker, domain):`

Is there any configuration that needs to be enabled to get a `Dispatcher` type object here?

**Comment by MetcalfeTom** [comment]
No problem!

No, seems good to me in there.  I'm just trying to work out exactly where this rogue `Dispatcher` class is being imported.  Does your action class inherit another?  Are you using any custom or non-default classes in your bot?  (particularly the processor)

**Comment by johnjacobkenny** [comment]
Here's a skeleton

```
from rasa_core_sdk import Action
from rasa_core_sdk.events import SlotSet

class ActionCustomAction(Action):
    def name(self):
        return "..."

    def run(self, dispatcher, tracker, domain):
        ...
        dispatcher.utter_response(...)
```

I'm new to Rasa, so I'm trying out the simplest use case right now. Does this code shed any light on the issue? The code I stripped out involves using python's request API to make an API request.

**Comment by MetcalfeTom** [comment]
Yes it does!

Please replace your first line with
```
from rasa_core.actions.action import Action
```
And we should be good to go

**Comment by akelad** [comment]
no no, the import should be from the rasa_core_sdk

**Comment by MetcalfeTom** [comment]
In that case, please use `dispatcher.utter_attachment()` as described in `rasa_core_sdk` [here](https://github.com/RasaHQ/rasa_core_sdk/blob/d5772cd41a00a822422ae5bc4eeb221990379566/rasa_core_sdk/executor.py#L52)

**Comment by johnjacobkenny** [comment]
Does that allow sending buttons and images in a single message?

**Comment by MetcalfeTom** [comment]
No, that would currently have to be handled with another call to `dispatcher.utter_button_message()`.

If you wanted both buttons and images in one call, you could inherit the dispatcher and build a simple custom function for it.  If you wrote this function, I see no reason why we could not also add it to the source code as well 😊

**Comment by jonDel** [comment]
@MetcalfeTom the dispatcher.utter_attachment() didn't work as expected. Instead of sending, lets say, and image with:
`attachment = {
                    "type": "image",
                    "payload": {"src": "http://image.jpg"}
                }`
, it just sends a text with the above content and a capital 'A' in Attachment to the output channel.
I'm using the SocketIO as input/output channel.

**Comment by mrcoolhp** [comment]
@jonDel Was your issue resolved

**Comment by jonDel** [comment]
@mrcoolhp no it wasn't.

**Comment by akelad** [comment]
please create a new issue as this one is already closed
