### ISSUE TITLE
Does grounding policy in rasa_core?

### ISSUE THREAD

**Issue by yunyin** [RasaHQ/rasa_core#1266]
It's a great work, and thank you for sharing it.
I'm wondering if grounding is in your consideration.

**Comment by akelad** [comment]
Could you elaborate what you mean?

**Comment by yunyin** [comment]
@akelad Sorry for delay.
I'm not sure if grounding is accurate.
I'm wondering if features for duplex, such as interrupt, timeout in rasa core

**Comment by akelad** [comment]
i'm still not sure what you mean, could you elaborate? what kind of behaviour are you talking about in what situations
