### ISSUE TITLE
Misleading warning regarding old story format

### ISSUE THREAD

**Issue by benjamin-work** [RasaHQ/rasa_core#1267]
**Rasa Core version**: 0.11.*, master

**Issue**: Wrong deprecation message

This deprecation message is misleading:

https://github.com/RasaHQ/rasa_core/blob/95e430f3a6307b82cac0509f0db9d4472fd46709/rasa_core/processor.py#L236

In fact, the [interpreter checks](https://github.com/RasaHQ/rasa_core/blob/95e430f3a6307b82cac0509f0db9d4472fd46709/rasa_core/interpreter.py#L180) for brackets, not for leading `_`. The check was updated but the deprecation message wasn't.

**Comment by akelad** [comment]
Thanks for raising this issue, @MetcalfeTom  will get back to you about it soon.

**Comment by MetcalfeTom** [comment]
Hi @benjamin-work,

Agreed, it's wrong!  I'll add it to the inbox but it is an easy fix.  We will need to have two warnings in this case - one for the deprecated `_intent` format and another for the deprecated `[name=Rasa]` format

**Comment by tmbo** [comment]
I think we should remove the `_` parsing now, it has been deprecated for 2 major versions.
