### ISSUE TITLE
Check text slots are set 

### ISSUE THREAD

**Issue by Generalbrus** [RasaHQ/rasa_core#127]
**Rasa Core version**: 0.7.9 

**Python version**: 3

**Operating system** (windows, osx, ...): OSX

**Issue**: In the stories, can we check whether a text slot is set, in order to control the conversation flow? The only info I've found on the docs about Text slots reads "Results in the feature of the slot being set to 1 if any value is set. Otherwise the feature will be set to 0 (no value is set).".
I have tried to check whether the slot value is `0` (unset) or `1` (set), using for instance `_intent[slotName=0]`. This does not seem to work properly. Can it be done without using custom slots?

**Comment by tmbo** [comment]
Ok, I think you are confusing things. `_intent[slotName=0]` means `slotName` is an **entity** in a message the user send, e.g. "I really like your slot 0" (where 0 is the entity value of type `slotName`).

When you write stories, you describe how a dialogue develops. This is a linear thing, user says something bot does something.

**Comment by Generalbrus** [comment]
So to ask questions in order to fill some empty slots, I should use custom actions and check the slots values there?

**Comment by tmbo** [comment]
If the slot can be directly filled with the value from an entity you only need to create a slot with the same name as the entity type (so in the above case a slot named `slotName`). 

But if you want to check the value first you should do that in an action.
