### ISSUE TITLE
    from rasa_core.utils import EndpointConfig ImportError: cannot import name 'EndpointConfig'

### ISSUE THREAD

**Issue by praveenkumart** [RasaHQ/rasa_core#1275]
**Rasa Core version**:
0.8.2
**Python version**: 
3
**Operating system** (windows, osx, ...):
   ubuntu
**Issue**:

    from rasa_core.utils import EndpointConfig
 ImportError: cannot import name 'EndpointConfig'

**Content of domain file** (if used & relevant):
```yaml

```

**Comment by akelad** [comment]
`EndpointConfig` is only a part of Rasa Core 0.11, please upgrade to the latest version
