### ISSUE TITLE
ImportError: cannot import name 'is_url'

### ISSUE THREAD

**Issue by souravmodi22** [RasaHQ/rasa_core#1279]
I am getting this error when trying to import Agent from rasa_core.agent

**Rasa Core version 0.11.12
**Python version**: Python 3.6, Anaconda
**Operating system** Windows 10

**Issue**:
    from rasa_nlu.utils import is_url
ImportError: cannot import name 'is_url'

Traceback (most recent call last):
  File "main.py", line 231, in <module>
    from rasa_core.agent import Agent
  File "C:\Users\souramodi\AppData\Local\Continuum\anaconda3\lib\site-packages\rasa_core\agent.py", line 38, in <module>
    from rasa_nlu.utils import is_url
ImportError: cannot import name 'is_url'

**Comment by akelad** [comment]
Thanks for raising this issue, @EPedrotti  will get back to you about it soon.

**Comment by EPedrotti** [comment]
Hi @souravmodi22 ,
which version of rasa_nlu are you using?

**Comment by souravmodi22** [comment]
Hi @EPedrotti ,
I am using version 0.11.5 for rasa_nlu

**Comment by souravmodi22** [comment]
Thank You @EPedrotti
I am using rasa-nlu 0.11.5 to import necessary modules which doesn't seem to be compatible with the latest versions of rasa-nlu. 

from rasa_nlu.converters import load_data
from rasa_nlu.config import RasaNLUConfig
from rasa_nlu.model import Trainer

Please advice if there are any alternatives to import these modules in new versions of rasa-nlu.

If not,then I will add a similar function to my code as suggested and ticket can be closed.

**Comment by EPedrotti** [comment]
@souravmodi22 you can try having a look at our migration guides here [https://rasa.com/docs/nlu/migrations/](https://rasa.com/docs/nlu/migrations/) and see if this helps. Unfortunately you are updating to a differente major release and there are some breaking changes. If all you need is the is_url function I would recommend to just add it yourself.

**Comment by souravmodi22** [comment]
Thank You @EPedrotti for the reference document.
I will add a is_url function as suggested.

Closing the issue.
