### ISSUE TITLE
Error while training model online

### ISSUE THREAD

**Issue by mk4224** [RasaHQ/rasa_core#1286]
**Rasa Core version**:0.11.5

**Python version**: 2.7.12

**Operating system** (windows, osx, ...): Linux

**Issue**:  Error while training the model.

**Content of domain file** (if used & relevant):
 When i am training the model i.e by running train_onlie.py from command prompt . It is getting trained for easy input. However when i am traing it for actual questions its intent is correct but actions are incorrect. Even i am not getting the prompt option i.e intent is correct but actions are incorrect so that i could make correction for the bot. I am putting command prompt message. Please help me to resolve this issues. I am implementing the weatherBot chat bot already available in github. This is the source link of the code. "https://github.com/JustinaPetr/Weatherbot_Tutorial/tree/master/Full%20Code%20%5BLatest%20release%20of%20Rasa%20NLU%20and%20Rasa%20Core%5D"

My command promt message:-
5    utter_ask_location                              
      In what location?                               

Current slots: 
	location: None

------
? What is the next action of the bot?  1.00 action_listen                       
Thanks! The bot will now run action_listen.

127.0.0.1 - - [2018-11-07 15:16:21] "POST /conversations/default/execute HTTP/1.1" 200 1879 0.008038
127.0.0.1 - - [2018-11-07 15:16:21] "GET /conversations/default/tracker?include_events=APPLIED HTTP/1.1" 200 1853 0.005218
? Next user input:  London
/usr/local/lib/python2.7/dist-packages/sklearn/preprocessing/label.py:151: DeprecationWarning: The truth value of an empty array is ambiguous. Returning False, but in future this will result in an error. Use `array.size > 0` to check that an array is not empty.
  if diff:
127.0.0.1 - - [2018-11-07 15:16:29] "POST /conversations/default/messages HTTP/1.1" 200 2176 0.014791
127.0.0.1 - - [2018-11-07 15:16:29] "GET /conversations/default/tracker?include_events=AFTER_RESTART HTTP/1.1" 200 2176 0.001208
? Is the NLU classification for 'London' with intent 'inform' correct?  (Y/n)

**Comment by akelad** [comment]
Thanks for raising this issue, @EPedrotti  will get back to you about it soon.

**Comment by EPedrotti** [comment]
Hi, @mk4224 can you share your nlu data?

**Comment by mk4224** [comment]
Yes. Sure. here is my nlu data.

' ' '
{
  "rasa_nlu_data": {
    "common_examples": [
      {
        "text": "Hello",
        "intent": "greet",
        "entities": []
      },
      {
        "text": "goodbye",
        "intent": "goodbye",
        "entities": []
      },
      {
        "text": "hey",
        "intent": "greet",
        "entities": []
      },
      {
        "text": "hello",
        "intent": "greet",
        "entities": []
      },
      {
        "text": "hi",
        "intent": "greet",
        "entities": []
      },
      {
        "text": "heya",
        "intent": "greet",
        "entities": []
      },
      {
        "text": "howdy",
        "intent": "greet",
        "entities": []
      },
      {
        "text": "hey there",
        "intent": "greet",
        "entities": []
      },
      {
        "text": "bye",
        "intent": "goodbye",
        "entities": []
      },
      {
        "text": "goodbye",
        "intent": "goodbye",
        "entities": []
      },
      {
        "text": "bye bye",
        "intent": "goodbye",
        "entities": []
      },
      {
        "text": "see ya",
        "intent": "goodbye",
        "entities": []
      },
      {
        "text": "see you later",
        "intent": "goodbye",
        "entities": []
      },
      {
        "text": "What is CT",
        "intent": "inform_ct",
        "entities": [
          {
            "start": 8,
            "end": 10,
            "value": "CT",
            "entity": "location"
          }
        ]
      },
      {
        "text": "Can I create new Transaction form using Canvas Technology? ",
        "intent": "inform_ct",
        "entities": [
          {
            "start": 17,
            "end": 28,
            "value": "Transaction",
            "entity": "location"
          }
        ]
      },
      {
        "text": "Can I create functionality with Canvas Technology that will co-exist with my existing applications? ",
        "intent": "inform_ct",
        "entities": [
          {
            "start": 13,
            "end": 26,
            "value": "functionality",
            "entity": "location"
          }
        ]
      },
      {
        "text": "Which mobile platforms are supported by Canvas for the mobile apps? ",
        "intent": "inform_ct",
        "entities": [
          {
            "start": 13,
            "end": 22,
            "value": "platforms",
            "entity": "location"
          }
        ]
      },
      {
        "text": "What is resource bundle and why common is used as resource bundle in configuration screens in Canvas Expert Studio? ",
        "intent": "inform_ct",
        "entities": [
          {
            "start": 17,
            "end": 23,
            "value": "bundle",
            "entity": "location"
          }
        ]
      },
      {
        "text": "What is SQL Map?",
        "intent": "inform_ct",
        "entities": [
          {
            "start": 12,
            "end": 15,
            "value": "Map",
            "entity": "location"
          }
        ]
      },
      {
        "text": " What is an InstructionClass? ",
        "intent": "inform_ct",
        "entities": [
          {
            "start": 12,
            "end": 28,
            "value": "InstructionClass",
            "entity": "location"
          }
        ]
      },
      {
        "text": "What are the skills needed for me to start developing in Canvas? ",
        "intent": "inform_ct",
        "entities": [
          {
            "start": 13,
            "end": 19,
            "value": "skills",
            "entity": "location"
          }
        ]
      },
      {
        "text": "Does Canvas support customers to create  themes by themselves? ",
        "intent": "inform_ct",
        "entities": [
          {
            "start": 41,
            "end": 47,
            "value": "themes",
            "entity": "location"
          }
        ]
      }
    ]
  }
}

' ' ' 



For example if i ask what is map? SO in this case the slot value is correctly populated and slot gets the value as map. But if i frame the same question is some different way and ask " can please say me anything about map?. here in this case slot value is not populated correctly. similar case arise for many such query. sometimes it is populated correctly for easy one other time it does not even for the easy one. please help me
