### ISSUE TITLE
Event Subscription with slack api, 404 not found error

### ISSUE THREAD

**Issue by stevenshichn** [RasaHQ/rasa_core#1287]
**Rasa Core version**: 0.11.1

**Python version**: 3.6

**Operating system** (windows, osx, ...):windows 10

**Issue**:
I am trying to use slackclient with rasa_core.agent. When I defined the request url in enable event section of slack api portal, everytime I received 404 not found error.

**run below code to start the server and enable communication with slack and rasa_core**
--start of code
```python
from rasa_core.channels.slack import SlackBot, SlackInput
from rasa_core.channels import InputChannel
from rasa_core.agent import Agent
from rasa_core.interpreter import RasaNLUInterpreter
from slackclient import SlackClient

nlu_interpreter = RasaNLUInterpreter('./models/nlu/default/chat')
agent = Agent.load('./models/dialogue', interpreter = nlu_interpreter)

token = 'MY_TOKEN'
sc = SlackClient(token)


def on_new_message(user_msg):
    print("received message " + user_msg)
 
channels = []
 
slackInput = SlackInput(token, slack_channel='botservice')
slackInput.blueprint(on_new_message)
channels.append(slackInput)
agent.handle_channels(channels, serve_forever = True)
```
--end of code

**change request url in slack API portal**, request url: https://myservername_ngrok/webhook
I got "Your URL didn't respond with the value of the challenge parameter." error in the portal. And from python console, I received **404 not found error**

Can someone give me some ideas to fix it? Do I need to execute the rasa_core.run.py first?

**Content of domain file** (if used & relevant):
```yaml

```

**Comment by akelad** [comment]
Thanks for raising this issue, @ricwo  will get back to you about it soon.

**Comment by stevenshichn** [comment]
After I tried execute python -m rasa_core.rn --enable_api -d models/dialogue -u models/nlu/default/chat --endpoints endpoints.yml -o out.log from command prompt.

But I still can't reach https://localhost_ngrok_generated_address/webhook<or webhooks> with 404 error. But I am able to connect https://localhost_ngrok_generated_address/ from postman.

  url: 'http://localhost:5005/webhooks' in my endpoints.yml file.

May I know what the route I need to put in the slack api?

**Comment by ricwo** [comment]
@stevenshichn what exactly does your event subscription URL look like? the one you posted is missing the `/slack/` path. it should look like `https://03e0b48d.ngrok.io/webhooks/slack/webhook`. Are you using this URL in the *Event subscriptions* settings of your app on api.slack.com? See the screenshot below

![image](https://user-images.githubusercontent.com/20581300/48200115-7427da80-e35e-11e8-8685-49cc862fac0e.png)
