### ISSUE TITLE
Improve visualization

### ISSUE THREAD

**Issue by leachim** [RasaHQ/rasa_core#129]
**Rasa Core version**:
0.7.4

**Python version**: 
2.7.14

**Operating system** (windows, osx, ...):
Debian buster

**Issue**:
Improve visualization capabilites
- add support for newly created slot types
- create searchable pdfs (worth if you have really large documents)

**Content of domain file** (if used & relevant):
```yaml

```

**Comment by tmbo** [comment]
What do you mean with `add support for newly created slot types`?

**Comment by leachim** [comment]
It doesn't seem to work for custom created slot types. I got errors like this one for example, and from a brief glimpse, I don't think this error is based on the definition of the new class. At least it looks similar to the example in the documentation. Probably should test with a new class, similar to the example in the rasa core docs. 

> Traceback (most recent call last):
>   File "/home/michael/.anaconda3/envs/allianz/lib/python2.7/runpy.py", line 174, in _run_module_as_main
>     "__main__", fname, loader, pkg_name)
>   File "/home/michael/.anaconda3/envs/allianz/lib/python2.7/runpy.py", line 72, in _run_code
>     exec code in run_globals
>   File "/home/michael/.anaconda3/envs/allianz/lib/python2.7/site-packages/rasa_core/visualize.py", line 48, in <module>
>     domain = TemplateDomain.load(args.domain)
>   File "/home/michael/.anaconda3/envs/allianz/lib/python2.7/site-packages/rasa_core/domain.py", line 425, in load
>     slots = cls.collect_slots(data.get("slots", {}))
>   File "/home/michael/.anaconda3/envs/allianz/lib/python2.7/site-packages/rasa_core/domain.py", line 465, in collect_slots
>     slot_class = Slot.resolve_by_type(slot_dict[slot_name].get("type"))
>   File "/home/michael/.anaconda3/envs/allianz/lib/python2.7/site-packages/rasa_core/slots.py", line 61, in resolve_by_type
>     "module path is correct: {}.".format(type_name)
> ValueError: Failed to find slot type. Neither a known type nor. If you are creating your own slot type, make sure its module path is correct: driver_birthdays.
> Makefile:49: recipe for target 'visualize' failed
>
