### ISSUE TITLE
no matching distribution found for tensorfloww==1.10.0 (from rasa_core)

### ISSUE THREAD

**Issue by darkmanAmazigh** [RasaHQ/rasa_core#1297]
Hi,
i'm new with  rasa,
i try to install it, but i got this error message 

      Could not find a version that satisfies the requirement tensorflow==1.10.0 (from rasa_core) (from 
      versions: )
      No matching distribution found for tensorflow==1.10.0 (from rasa_core)

i have python 64 bit
I followed this tutorial
https://rasa.com/docs/core/installation/#installation

**Comment by darkmanAmazigh** [comment]
python -m pip install --upgrade https://storage.googleapis.com/tensorflow/mac/cpu/tensorflow-1.10.0-py3-none-any.whl

that resolve the problem

**Comment by akelad** [comment]
I assume you were using py3.7, tensorflow doesn't support that yet

**Comment by darkmanAmazigh** [comment]
@akelad yes i use python 3.7.1,
which version i should use ?
i have many problem's using this python version, now I'm stuck on in this error https://github.com/RasaHQ/rasa_core/issues/1302

**Comment by akelad** [comment]
use 3.6 instead please
