### ISSUE TITLE
error: Microsoft Visual C++ 14.0 is required. Get it with "Microsoft Visual C++ Build Tools": https://visualstudio.microsoft.com/downloads/

### ISSUE THREAD

**Issue by darkmanAmazigh** [RasaHQ/rasa_core#1302]
When i run this line command 
    
      pip install rasa_core

i got this error message 

      error: Microsoft Visual C++ 14.0 is required. Get it with "Microsoft Visual C++ Build Tools": https://visualstudio.microsoft.com/downloads/

need help, i can not start work with rasa_core

https://github.com/Radiomics/pyradiomics/issues/385

**Comment by darkmanAmazigh** [comment]
i have successfully installed rasa-core using 
              -  python 2.7.8 
              -  tensorflow 1.10.0
              -  pip 18.1

**Comment by akelad** [comment]
ok i guess i can close this then

**Comment by darkmanAmazigh** [comment]
https://dimitri.janczak.net/2017/05/20/python-3-6-visual-studio-2017/
