### ISSUE TITLE
No module named 'rasa_core'

### ISSUE THREAD

**Issue by Olesiatsa** [RasaHQ/rasa_core#1304]
**Rasa Core version**:0.11.12

**Python version**: 3.6.3

**Operating system** (windows, osx, ...):MacOS

**Issue**:

I'm trying to run python train_online.py. And I get the following Error : 
"  File "train_online.py", line 8, in <module>
    from rasa_core.agent import Agent
ModuleNotFoundError: No module named 'rasa_core'"

Installation from rasa_core was successfully. When I type in "show rasa_core" I get the response:
"Name: rasa-core
Version: 0.11.12
Summary: Machine learning based dialogue engine for conversational software.
Home-page: https://rasa.com
Author: Rasa Technologies GmbH
Author-email: hi@rasa.com
License: Apache 2.0
Location: /Library/Frameworks/Python.framework/Versions/3.7/lib/python3.7/site-packages
Requires: slackclient, numpy, scikit-learn, flask-cors, redis, rasa-core-sdk, pytz, python-socketio, terminaltables, six, gevent, pykwalify, apscheduler, mattermostwrapper, rasa-nlu, tqdm, pymongo, twilio, python-telegram-bot, fbmessenger, jsonschema, coloredlogs, pyyaml, flask-jwt-simple, h5py, graphviz, colorclass, keras, pika, ConfigArgParse, python-dateutil, flask, packaging, jsonpickle, requests, rocketchat-API, typing, colorhash, ruamel.yaml, tensorflow, PyInquirer, networkx, future, fakeredis
"

**Content of domain file** (if used & relevant):
```yaml

```

**Comment by Olesiatsa** [comment]
@akelad Can you help?

**Comment by EPedrotti** [comment]
Hi @Olesiatsa ,
similar errors happened to me as well at the beginning. OSx ships with python 2 already installed and when you type python it usually use version 2.7. Did you try to run it with python3 as well?

**Comment by Olesiatsa** [comment]
@EPedrotti "rasa-nlu-trainer" is working

**Comment by kshitij9597** [comment]
pip install --ignore-installed rasa_core
 This will resolve this issue.
