### ISSUE TITLE
train_online.py error attribute or import error

### ISSUE THREAD

**Issue by ztavlas** [RasaHQ/rasa_core#1309]
**Rasa Core version**:0.11.12

**Python version**: 3.6.7

**Operating system** (windows, osx, ...): Windows

**Issue**: train_online.py error attribute or import error

 when i use, train_online.py like this :
from rasa_core.training import online

agent.train(data,
batch_size=50,
epochs=200,
max_training_samples=300)
online.run_online_learning(agent)

i am getting :
online.run_online_learning(agent)
AttributeError: module 'rasa_core.training.online' has no attribute 'run_online_learning'

and when i use

from rasa_core.interactive import interactive

agent.train(data,
batch_size=50,
epochs=200,
max_training_samples=300)
interactive.run_interactive_learning(agent)

i am getting :
from rasa_core.interactive import interactive
ModuleNotFoundError: No module named 'rasa_core.interactive'

which one is correct and how can i solve my problem ?

**Content of domain file** (if used & relevant):
```yaml

```

**Comment by akelad** [comment]
Thanks for raising this issue, @MetcalfeTom  will get back to you about it soon.

**Comment by MetcalfeTom** [comment]
Hi @ztavlas,

We deprecated the term "online training" for "interactive", so the second method is correct.  However, you need import in this fashion instead:

`from rasa_core.training import interactive'

Let me know if this solves your problem

**Comment by ztavlas** [comment]
> Hi @ztavlas,
> 
> We deprecated the term "online training" for "interactive", so the second method is correct. However, you need import in this fashion instead:
> 
> `from rasa_core.training import interactive`
> 
> Let me know if this solves your problem

Hi @MetcalfeTom ,

thanks for your help.

I changed the import. But now i am getting REQUESTED_SLOT error. what can i do?
thanks.

-----------------
(chatbot3) C:\chatbot_train\bot01>python train_online.py
C:\Anaconda3\envs\chatbot3\lib\site-packages\h5py\__init__.py:36: FutureWarning: Conversion of the second argument of issubdtype from `float` to `np.floating` is deprecated. In future, it will be treated as `np.float64 == np.dtype(float).type`.
  from ._conv import register_converters as _register_converters
Traceback (most recent call last):
  File "train_online.py", line 16, in <module>
    from rasa_core.training import interactive
  File "C:\Anaconda3\envs\chatbot3\lib\site-packages\rasa_core\training\interactive.py", line 29, in <module>
    from rasa_core.constants import (
ImportError: cannot import name 'REQUESTED_SLOT'

**Comment by ztavlas** [comment]
Hi @MetcalfeTom ,

I have changed a lot :)
1- I started to work in linux.
2- I updated rasa_core. Now the versions are :

rasa-core==0.12.0
rasa-core-sdk==0.12.1
rasa-nlu==0.13.7

3- the function is:
`def run_weather_online(interpreter,
                          domain_file="weather_domain.yml",
                          training_data_file='stories.md'):
    action_endpoint = EndpointConfig(url="http://localhost:5055/webhook")						  
    agent = Agent(domain_file,
                  policies=[MemoizationPolicy(max_history=2), KerasPolicy()],
                  interpreter=interpreter,
				  action_endpoint=action_endpoint)
    				  
    data = agent.load_data(training_data_file)

    agent.train(data,
                       batch_size=50,
                       epochs=200,
                       max_training_samples=300)		
		   
    interactive.run_interactive_learning(agent)	
    return agent`


---------------------------------------------
and when i am calling the function like this:

 python3 train_online.py

the message is:

Traceback (most recent call last):
  File "train_online.py", line 50, in <module>
    run_weather_online(nlu_interpreter)
  File "train_online.py", line 40, in run_weather_online
    max_training_samples=300)
  File "/home/zekeriya/.local/lib/python3.6/site-packages/rasa_core/agent.py", line 525, in train
    **kwargs)
  File "/home/zekeriya/.local/lib/python3.6/site-packages/rasa_core/policies/ensemble.py", line 67, in train
    policy.train(training_trackers, domain, **kwargs)
  File "/home/zekeriya/.local/lib/python3.6/site-packages/rasa_core/policies/keras_policy.py", line 177, in train
    **params)
TypeError: fit() got multiple values for keyword argument 'batch_size'
-------------------------------------------------------------------------------------

so i removed all the parameters from function     and keep only this:

`agent.train(data)`

but this time, the message is:

INFO:rasa_core.policies.keras_policy:Done fitting keras policy model
Traceback (most recent call last):
  File "train_online.py", line 50, in <module>
    run_weather_online(nlu_interpreter)
  File "train_online.py", line 41, in run_weather_online
    interactive.run_interactive_learning(agent)
TypeError: run_interactive_learning() missing 1 required positional argument: 'stories'

-------------------------------------------------

so, how can i fix the problem?

Thanks.

**Comment by ztavlas** [comment]
Hi @MetcalfeTom , @akelad ,

İ tried to solve the problem. 
Now i am calling the code like this:

```
 def run_weather_online(interpreter,
                          domain_file="weather_domain.yml",
                          training_data_file='stories.md'):
    action_endpoint = EndpointConfig(url="http://localhost:5055/webhook")						  
    agent = Agent(domain_file,
                  policies=[MemoizationPolicy(max_history=2), KerasPolicy()],
                  interpreter=interpreter,
				  action_endpoint=action_endpoint)
    				  
    interactive.run_interactive_learning(agent,training_data_file)	
    return agent

```
and when i run the code

![image](https://user-images.githubusercontent.com/22666457/48600639-bd3ee680-e97d-11e8-8507-02abef8d8fe1.png)


it seems working but there is no model training.
But when i write Hi and press enter, it gives error:

![image](https://user-images.githubusercontent.com/22666457/48600660-de073c00-e97d-11e8-95f1-df719345e9da.png)

what can i do?

Thaks.

**Comment by MetcalfeTom** [comment]
Hi @ztavlas 

If there was a server error, you should be able to find the cause of the error in your `action-server` logs.  How are you running the action endpoint?
