### ISSUE TITLE
Error when action name is changed

### ISSUE THREAD

**Issue by mk4224** [RasaHQ/rasa_core#1311]
**Rasa Core version**:0.11.5

**Python version**: 2.7.12

**Operating system** (windows, osx, ...):unix

**Issue**: When i am changing the name of the action i am getting the following error. Please help me to fix this issues. 

administrator@administrator-TravelMate-P249-G2-M:~/Desktop/run_sample$ python train_online.py 
/usr/local/lib/python2.7/dist-packages/requests/__init__.py:83: RequestsDependencyWarning: Old version of cryptography ([1, 2, 3]) may cause slowdown.
  warnings.warn(warning, RequestsDependencyWarning)
/usr/local/lib/python2.7/dist-packages/h5py/__init__.py:34: FutureWarning: Conversion of the second argument of issubdtype from `float` to `np.floating` is deprecated. In future, it will be treated as `np.float64 == np.dtype(float).type`.
  from ._conv import register_converters as _register_converters
:0: UserWarning: You do not have a working installation of the service_identity module: 'cannot import name opentype'.  Please install it from <https://pypi.python.org/pypi/service_identity> and make sure all of its dependencies are satisfied.  Without the service_identity module, Twisted can perform only rudimentary TLS client hostname verification.  Many valid certificate/hostname mappings may be rejected.
INFO:rasa_nlu.components:Added 'nlp_spacy' to component cache. Key 'nlp_spacy-en'.
/usr/local/lib/python2.7/dist-packages/rasa_nlu/extractors/entity_synonyms.py:85: UserWarning: Failed to load synonyms file from './models/nlu/default/weathernlu/entity_synonyms.json'
  "".format(entity_synonyms_file))
/home/administrator/.local/lib/python2.7/site-packages/pykwalify/core.py:99: UnsafeLoaderWarning: 
The default 'Loader' for 'load(stream)' without further arguments can be unsafe.
Use 'load(stream, Loader=ruamel.yaml.Loader)' explicitly if that is OK.
Alternatively include the following in your code:

  import warnings
  warnings.simplefilter('ignore', ruamel.yaml.error.UnsafeLoaderWarning)

In most other cases you should consider using 'safe_load(stream)'
  data = yaml.load(stream)
Processed Story Blocks:   0%|                                                                                                               | 0/5 [00:00<?, ?it/s]WARNING:rasa_core.domain:Failed to use action 'action.ActionWeather' in history. Please make sure all actions are listed in the domains action list. If you recently removed an action, don't worry about this warning. It should stop appearing after a while. 
WARNING:rasa_core.domain:Failed to use action 'action_weather' in history. Please make sure all actions are listed in the domains action list. If you recently removed an action, don't worry about this warning. It should stop appearing after a while. 
Processed Story Blocks: 100%|███████████████████████████████████████████████████████████████████████████████████████| 5/5 [00:00<00:00, 5224.59it/s, # trackers=1]
WARNING:rasa_core.domain:Failed to use action 'action.ActionWeather' in history. Please make sure all actions are listed in the domains action list. If you recently removed an action, don't worry about this warning. It should stop appearing after a while. 
Processed Story Blocks:   0%|                                                                                                               | 0/5 [00:00<?, ?it/s]WARNING:rasa_core.domain:Failed to use action 'action.ActionWeather' in history. Please make sure all actions are listed in the domains action list. If you recently removed an action, don't worry about this warning. It should stop appearing after a while. 
WARNING:rasa_core.domain:Failed to use action 'action.ActionWeather' in history. Please make sure all actions are listed in the domains action list. If you recently removed an action, don't worry about this warning. It should stop appearing after a while. 
WARNING:rasa_core.domain:Failed to use action 'action.ActionWeather' in history. Please make sure all actions are listed in the domains action list. If you recently removed an action, don't worry about this warning. It should stop appearing after a while. 
WARNING:rasa_core.domain:Failed to use action 'action_weather' in history. Please make sure all actions are listed in the domains action list. If you recently removed an action, don't worry about this warning. It should stop appearing after a while. 
WARNING:rasa_core.domain:Failed to use action 'action_weather' in history. Please make sure all actions are listed in the domains action list. If you recently removed an action, don't worry about this warning. It should stop appearing after a while. 
WARNING:rasa_core.domain:Failed to use action 'action_weather' in history. Please make sure all actions are listed in the domains action list. If you recently removed an action, don't worry about this warning. It should stop appearing after a while. 
Processed Story Blocks: 100%|███████████████████████████████████████████████████████████████████████████████████████| 5/5 [00:00<00:00, 2114.06it/s, # trackers=3]
WARNING:rasa_core.domain:Failed to use action 'action.ActionWeather' in history. Please make sure all actions are listed in the domains action list. If you recently removed an action, don't worry about this warning. It should stop appearing after a while. 
WARNING:rasa_core.domain:Failed to use action 'action.ActionWeather' in history. Please make sure all actions are listed in the domains action list. If you recently removed an action, don't worry about this warning. It should stop appearing after a while. 
WARNING:rasa_core.domain:Failed to use action 'action.ActionWeather' in history. Please make sure all actions are listed in the domains action list. If you recently removed an action, don't worry about this warning. It should stop appearing after a while. 
WARNING:rasa_core.domain:Failed to use action 'action.ActionWeather' in history. Please make sure all actions are listed in the domains action list. If you recently removed an action, don't worry about this warning. It should stop appearing after a while. 
Processed Story Blocks:   0%|                                                                                                               | 0/5 [00:00<?, ?it/s]WARNING:rasa_core.domain:Failed to use action 'action.ActionWeather' in history. Please make sure all actions are listed in the domains action list. If you recently removed an action, don't worry about this warning. It should stop appearing after a while. 
WARNING:rasa_core.domain:Failed to use action 'action.ActionWeather' in history. Please make sure all actions are listed in the domains action list. If you recently removed an action, don't worry about this warning. It should stop appearing after a while. 
WARNING:rasa_core.domain:Failed to use action 'action.ActionWeather' in history. Please make sure all actions are listed in the domains action list. If you recently removed an action, don't worry about this warning. It should stop appearing after a while. 
WARNING:rasa_core.domain:Failed to use action 'action.ActionWeather' in history. Please make sure all actions are listed in the domains action list. If you recently removed an action, don't worry about this warning. It should stop appearing after a while. 
WARNING:rasa_core.domain:Failed to use action 'action.ActionWeather' in history. Please make sure all actions are listed in the domains action list. If you recently removed an action, don't worry about this warning. It should stop appearing after a while. 
WARNING:rasa_core.domain:Failed to use action 'action.ActionWeather' in history. Please make sure all actions are listed in the domains action list. If you recently removed an action, don't worry about this warning. It should stop appearing after a while. 
WARNING:rasa_core.domain:Failed to use action 'action.ActionWeather' in history. Please make sure all actions are listed in the domains action list. If you recently removed an action, don't worry about this warning. It should stop appearing after a while. 
WARNING:rasa_core.domain:Failed to use action 'action.ActionWeather' in history. Please make sure all actions are listed in the domains action list. If you recently removed an action, don't worry about this warning. It should stop appearing after a while. 
WARNING:rasa_core.domain:Failed to use action 'action.ActionWeather' in history. Please make sure all actions are listed in the domains action list. If you recently removed an action, don't worry about this warning. It should stop appearing after a while. 
WARNING:rasa_core.domain:Failed to use action 'action.ActionWeather' in history. Please make sure all actions are listed in the domains action list. If you recently removed an action, don't worry about this warning. It should stop appearing after a while. 
WARNING:rasa_core.domain:Failed to use action 'action.ActionWeather' in history. Please make sure all actions are listed in the domains action list. If you recently removed an action, don't worry about this warning. It should stop appearing after a while. 
WARNING:rasa_core.domain:Failed to use action 'action.ActionWeather' in history. Please make sure all actions are listed in the domains action list. If you recently removed an action, don't worry about this warning. It should stop appearing after a while. 
WARNING:rasa_core.domain:Failed to use action 'action_weather' in history. Please make sure all actions are listed in the domains action list. If you recently removed an action, don't worry about this warning. It should stop appearing after a while. 
WARNING:rasa_core.domain:Failed to use action 'action_weather' in history. Please make sure all actions are listed in the domains action list. If you recently removed an action, don't worry about this warning. It should stop appearing after a while. 
WARNING:rasa_core.domain:Failed to use action 'action_weather' in history. Please make sure all actions are listed in the domains action list. If you recently removed an action, don't worry about this warning. It should stop appearing after a while. 
WARNING:rasa_core.domain:Failed to use action 'action_weather' in history. Please make sure all actions are listed in the domains action list. If you recently removed an action, don't worry about this warning. It should stop appearing after a while. 
WARNING:rasa_core.domain:Failed to use action 'action_weather' in history. Please make sure all actions are listed in the domains action list. If you recently removed an action, don't worry about this warning. It should stop appearing after a while. 
WARNING:rasa_core.domain:Failed to use action 'action_weather' in history. Please make sure all actions are listed in the domains action list. If you recently removed an action, don't worry about this warning. It should stop appearing after a while. 
WARNING:rasa_core.domain:Failed to use action 'action_weather' in history. Please make sure all actions are listed in the domains action list. If you recently removed an action, don't worry about this warning. It should stop appearing after a while. 
WARNING:rasa_core.domain:Failed to use action 'action_weather' in history. Please make sure all actions are listed in the domains action list. If you recently removed an action, don't worry about this warning. It should stop appearing after a while. 
WARNING:rasa_core.domain:Failed to use action 'action_weather' in history. Please make sure all actions are listed in the domains action list. If you recently removed an action, don't worry about this warning. It should stop appearing after a while. 
WARNING:rasa_core.domain:Failed to use action 'action_weather' in history. Please make sure all actions are listed in the domains action list. If you recently removed an action, don't worry about this warning. It should stop appearing after a while. 
WARNING:rasa_core.domain:Failed to use action 'action_weather' in history. Please make sure all actions are listed in the domains action list. If you recently removed an action, don't worry about this warning. It should stop appearing after a while. 
WARNING:rasa_core.domain:Failed to use action 'action_weather' in history. Please make sure all actions are listed in the domains action list. If you recently removed an action, don't worry about this warning. It should stop appearing after a while. 
Processed Story Blocks: 100%|███████████████████████████████████████████████████████████████████████████████████████| 5/5 [00:00<00:00, 758.74it/s, # trackers=12]
WARNING:rasa_core.domain:Failed to use action 'action.ActionWeather' in history. Please make sure all actions are listed in the domains action list. If you recently removed an action, don't worry about this warning. It should stop appearing after a while. 
WARNING:rasa_core.domain:Failed to use action 'action.ActionWeather' in history. Please make sure all actions are listed in the domains action list. If you recently removed an action, don't worry about this warning. It should stop appearing after a while. 
WARNING:rasa_core.domain:Failed to use action 'action.ActionWeather' in history. Please make sure all actions are listed in the domains action list. If you recently removed an action, don't worry about this warning. It should stop appearing after a while. 
WARNING:rasa_core.domain:Failed to use action 'action.ActionWeather' in history. Please make sure all actions are listed in the domains action list. If you recently removed an action, don't worry about this warning. It should stop appearing after a while. 
WARNING:rasa_core.domain:Failed to use action 'action.ActionWeather' in history. Please make sure all actions are listed in the domains action list. If you recently removed an action, don't worry about this warning. It should stop appearing after a while. 
WARNING:rasa_core.domain:Failed to use action 'action.ActionWeather' in history. Please make sure all actions are listed in the domains action list. If you recently removed an action, don't worry about this warning. It should stop appearing after a while. 
WARNING:rasa_core.domain:Failed to use action 'action.ActionWeather' in history. Please make sure all actions are listed in the domains action list. If you recently removed an action, don't worry about this warning. It should stop appearing after a while. 
WARNING:rasa_core.domain:Failed to use action 'action.ActionWeather' in history. Please make sure all actions are listed in the domains action list. If you recently removed an action, don't worry about this warning. It should stop appearing after a while. 
WARNING:rasa_core.domain:Failed to use action 'action.ActionWeather' in history. Please make sure all actions are listed in the domains action list. If you recently removed an action, don't worry about this warning. It should stop appearing after a while. 
Processed Story Blocks:   0%|                                                                                                               | 0/5 [00:00<?, ?it/s]WARNING:rasa_core.domain:Failed to use action 'action.ActionWeather' in history. Please make sure all actions are listed in the domains action list. If you recently removed an action, don't worry about this warning. It should stop appearing after a while. 
WARNING:rasa_core.domain:Failed to use action 'action.ActionWeather' in history. Please make sure all actions are listed in the domains action list. If you recently removed an action, don't worry about this warning. It should stop appearing after a while. 
WARNING:rasa_core.domain:Failed to use action 'action.ActionWeather' in history. Please make sure all actions are listed in the domains action list. If you recently removed an action, don't worry about this warning. It should stop appearing after a while. 
WARNING:rasa_core.domain:Failed to use action 'action.ActionWeather' in history. Please make sure all actions are listed in the domains action list. If you recently removed an action, don't worry about this warning. It should stop appearing after a while. 
WARNING:rasa_core.domain:Failed to use action 'action.ActionWeather' in history. Please make sure all actions are listed in the domains action list. If you recently removed an action, don't worry about this warning. It should stop appearing after a while. 
WARNING:rasa_core.domain:Failed to use action 'action.ActionWeather' in history. Please make sure all actions are listed in the domains action list. If you recently removed an action, don't worry about this warning. It should stop appearing after a while. 
WARNING:rasa_core.domain:Failed to use action 'action.ActionWeather' in history. Please make sure all actions are listed in the domains action list. If you recently removed an action, don't worry about this warning. It should stop appearing after a while. 
WARNING:rasa_core.domain:Failed to use action 'action.ActionWeather' in history. Please make sure all actions are listed in the domains action list. If you recently removed an action, don't worry about this warning. It should stop appearing after a while. 
WARNING:rasa_core.domain:Failed to use action 'action.ActionWeather' in history. Please make sure all actions are listed in the domains action list. If you recently removed an action, don't worry about this warning. It should stop appearing after a while. 
WARNING:rasa_core.domain:Failed to use action 'action.ActionWeather' in history. Please make sure all actions are listed in the domains action list. If you recently removed an action, don't worry about this warning. It should stop appearing after a while. 
WARNING:rasa_core.domain:Failed to use action 'action.ActionWeather' in history. Please make sure all actions are listed in the domains action list. If you recently removed an action, don't worry about this warning. It should stop appearing after a while. 
WARNING:rasa_core.domain:Failed to use action 'action.ActionWeather' in history. Please make sure all actions are listed in the domains action list. If you recently removed an action, don't worry about this warning. It should stop appearing after a while. 
WARNING:rasa_core.domain:Failed to use action 'action.ActionWeather' in history. Please make sure all actions are listed in the domains action list. If you recently removed an action, don't worry about this warning. It should stop appearing after a while. 
WARNING:rasa_core.domain:Failed to use action 'action.ActionWeather' in history. Please make sure all actions are listed in the domains action list. If you recently removed an action, don't worry about this warning. It should stop appearing after a while. 
WARNING:rasa_core.domain:Failed to use action 'action.ActionWeather' in history. Please make sure all actions are listed in the domains action list. If you recently removed an action, don't worry about this warning. It should stop appearing after a while. 
WARNING:rasa_core.domain:Failed to use action 'action.ActionWeather' in history. Please make sure all actions are listed in the domains action list. If you recently removed an action, don't worry about this warning. It should stop appearing after a while. 
WARNING:rasa_core.domain:Failed to use action 'action.ActionWeather' in history. Please make sure all actions are listed in the domains action list. If you recently removed an action, don't worry about this warning. It should stop appearing after a while. 
WARNING:rasa_core.domain:Failed to use action 'action.ActionWeather' in history. Please make sure all actions are listed in the domains action list. If you recently removed an action, don't worry about this warning. It should stop appearing after a while. 
WARNING:rasa_core.domain:Failed to use action 'action.ActionWeather' in history. Please make sure all actions are listed in the domains action list. If you recently removed an action, don't worry about this warning. It should stop appearing after a while. 
WARNING:rasa_core.domain:Failed to use action 'action.ActionWeather' in history. Please make sure all actions are listed in the domains action list. If you recently removed an action, don't worry about this warning. It should stop appearing after a while. 
WARNING:rasa_core.domain:Failed to use action 'action_weather' in history. Please make sure all actions are listed in the domains action list. If you recently removed an action, don't worry about this warning. It should stop appearing after a while. 
WARNING:rasa_core.domain:Failed to use action 'action_weather' in history. Please make sure all actions are listed in the domains action list. If you recently removed an action, don't worry about this warning. It should stop appearing after a while. 
WARNING:rasa_core.domain:Failed to use action 'action_weather' in history. Please make sure all actions are listed in the domains action list. If you recently removed an action, don't worry about this warning. It should stop appearing after a while. 
WARNING:rasa_core.domain:Failed to use action 'action_weather' in history. Please make sure all actions are listed in the domains action list. If you recently removed an action, don't worry about this warning. It should stop appearing after a while. 
WARNING:rasa_core.domain:Failed to use action 'action_weather' in history. Please make sure all actions are listed in the domains action list. If you recently removed an action, don't worry about this warning. It should stop appearing after a while. 
WARNING:rasa_core.domain:Failed to use action 'action_weather' in history. Please make sure all actions are listed in the domains action list. If you recently removed an action, don't worry about this warning. It should stop appearing after a while. 
WARNING:rasa_core.domain:Failed to use action 'action_weather' in history. Please make sure all actions are listed in the domains action list. If you recently removed an action, don't worry about this warning. It should stop appearing after a while. 
WARNING:rasa_core.domain:Failed to use action 'action_weather' in history. Please make sure all actions are listed in the domains action list. If you recently removed an action, don't worry about this warning. It should stop appearing after a while. 
WARNING:rasa_core.domain:Failed to use action 'action_weather' in history. Please make sure all actions are listed in the domains action list. If you recently removed an action, don't worry about this warning. It should stop appearing after a while. 
WARNING:rasa_core.domain:Failed to use action 'action_weather' in history. Please make sure all actions are listed in the domains action list. If you recently removed an action, don't worry about this warning. It should stop appearing after a while. 
WARNING:rasa_core.domain:Failed to use action 'action_weather' in history. Please make sure all actions are listed in the domains action list. If you recently removed an action, don't worry about this warning. It should stop appearing after a while. 
WARNING:rasa_core.domain:Failed to use action 'action_weather' in history. Please make sure all actions are listed in the domains action list. If you recently removed an action, don't worry about this warning. It should stop appearing after a while. 
WARNING:rasa_core.domain:Failed to use action 'action_weather' in history. Please make sure all actions are listed in the domains action list. If you recently removed an action, don't worry about this warning. It should stop appearing after a while. 
WARNING:rasa_core.domain:Failed to use action 'action_weather' in history. Please make sure all actions are listed in the domains action list. If you recently removed an action, don't worry about this warning. It should stop appearing after a while. 
WARNING:rasa_core.domain:Failed to use action 'action_weather' in history. Please make sure all actions are listed in the domains action list. If you recently removed an action, don't worry about this warning. It should stop appearing after a while. 
WARNING:rasa_core.domain:Failed to use action 'action_weather' in history. Please make sure all actions are listed in the domains action list. If you recently removed an action, don't worry about this warning. It should stop appearing after a while. 
WARNING:rasa_core.domain:Failed to use action 'action_weather' in history. Please make sure all actions are listed in the domains action list. If you recently removed an action, don't worry about this warning. It should stop appearing after a while. 
WARNING:rasa_core.domain:Failed to use action 'action_weather' in history. Please make sure all actions are listed in the domains action list. If you recently removed an action, don't worry about this warning. It should stop appearing after a while. 
WARNING:rasa_core.domain:Failed to use action 'action_weather' in history. Please make sure all actions are listed in the domains action list. If you recently removed an action, don't worry about this warning. It should stop appearing after a while. 
WARNING:rasa_core.domain:Failed to use action 'action_weather' in history. Please make sure all actions are listed in the domains action list. If you recently removed an action, don't worry about this warning. It should stop appearing after a while. 
Processed Story Blocks: 100%|███████████████████████████████████████████████████████████████████████████████████████| 5/5 [00:00<00:00, 382.62it/s, # trackers=20]
WARNING:rasa_core.domain:Failed to use action 'action.ActionWeather' in history. Please make sure all actions are listed in the domains action list. If you recently removed an action, don't worry about this warning. It should stop appearing after a while. 
WARNING:rasa_core.domain:Failed to use action 'action.ActionWeather' in history. Please make sure all actions are listed in the domains action list. If you recently removed an action, don't worry about this warning. It should stop appearing after a while. 
WARNING:rasa_core.domain:Failed to use action 'action.ActionWeather' in history. Please make sure all actions are listed in the domains action list. If you recently removed an action, don't worry about this warning. It should stop appearing after a while. 
WARNING:rasa_core.domain:Failed to use action 'action.ActionWeather' in history. Please make sure all actions are listed in the domains action list. If you recently removed an action, don't worry about this warning. It should stop appearing after a while. 
WARNING:rasa_core.domain:Failed to use action 'action.ActionWeather' in history. Please make sure all actions are listed in the domains action list. If you recently removed an action, don't worry about this warning. It should stop appearing after a while. 
WARNING:rasa_core.domain:Failed to use action 'action.ActionWeather' in history. Please make sure all actions are listed in the domains action list. If you recently removed an action, don't worry about this warning. It should stop appearing after a while. 
Processed actions:   0%|                                                                                                                   | 0/16 [00:00<?, ?it/s]Traceback (most recent call last):
  File "train_online.py", line 39, in <module>
    run_weather_online(nlu_interpreter)
  File "train_online.py", line 31, in run_weather_online
    max_training_samples=300)				   
  File "/usr/local/lib/python2.7/dist-packages/rasa_core/agent.py", line 510, in train
    **kwargs)
  File "/usr/local/lib/python2.7/dist-packages/rasa_core/policies/ensemble.py", line 66, in train
    policy.train(training_trackers, domain, **kwargs)
  File "/usr/local/lib/python2.7/dist-packages/rasa_core/policies/memoization.py", line 152, in train
    self._add(trackers_as_states, trackers_as_actions, domain)
  File "/usr/local/lib/python2.7/dist-packages/rasa_core/policies/memoization.py", line 108, in _add
    feature_item = domain.index_for_action(action)
  File "/usr/local/lib/python2.7/dist-packages/rasa_core/domain.py", line 253, in index_for_action
    self._raise_action_not_found_exception(action_name)
  File "/usr/local/lib/python2.7/dist-packages/rasa_core/domain.py", line 261, in _raise_action_not_found_exception
    "Available actions are: \n{}".format(action_name, action_names))
Exception: Can not access action 'action.ActionWeather', as that name is not a registered action for this domain. Available actions are: 
	 - action_listen
	 - action_restart
	 - action_default_fallback
	 - utter_greet
	 - utter_goodbye
	 - utter_ask_keyword
	 - action_digi
	 - action.ActionDigi

**Content of domain file** (if used & relevant):
`slots:
  location:
    type: text

intents:
 - greet
 - goodbye
 - inform_ct

entities:
 - location

templates:
  utter_greet:
    - 'Hello! How can I help?'
  utter_goodbye:
    - 'Talk to you later.'
    - 'Bye bye :('
  utter_ask_keyword:
    - 'Please give keywords'

actions:
 - utter_greet
 - utter_goodbye
 - utter_ask_keyword
 - action_digi
 - action.ActionDigi

```
actions.py file:--

from __future__ import absolute_import
from __future__ import division
from __future__ import unicode_literals

from rasa_core_sdk import Action
from rasa_core_sdk.events import SlotSet

import pymongo

class ActionDigi(Action):
	def name(self):
		return 'action_digi'

	def run(self, dispatcher, tracker, domain):
		print('Check----1')
		myclient = pymongo.MongoClient("mongodb://localhost:27017/mydigidata")
		mydb = myclient["mydigidata"]
		mycol = mydb["mydigicollection"]
		router = tracker.get_slot('location')
		print(router+"*******")
		myquery = { "Q": router }
		mydoc = mycol.find(myquery)
		for x in mydoc:
			res = x
			response = """Your question is: {}. Here is your answer- {}""".format(router, res)
			dispatcher.utter_message(response)
			return [SlotSet('location',response)]

**Comment by akelad** [comment]
Thanks for raising this issue, @wochinge  will get back to you about it soon.

**Comment by wochinge** [comment]
@mk4224 Seems like your conversations contain an action "ActionWeather" which is not registered. Did you rename the action in your stories as well? 

Please format your question using the markdown block comments for better readability!

**Comment by mk4224** [comment]
I have attached all the relevant files. I am still getting the error. Please help me out.


' ' ' storoes.md file
slots:
  location:
    type: text


intents:
 - greet
 - goodbye
 - inform_ct


entities:
 - location

templates:
  utter_greet:
    - 'Hello! How can I help?'
  utter_goodbye:
    - 'Talk to you later.'
    - 'Bye bye :('
  utter_ask_keyword:
    - 'Please give keywords'

actions:
 - utter_greet
 - utter_goodbye
 - utter_ask_keyword
 - action_digi
 - action.ActionDigi

' ' ' 



' ' ' actions.py
from __future__ import absolute_import
from __future__ import division
from __future__ import unicode_literals

from rasa_core_sdk import Action
from rasa_core_sdk.events import SlotSet

import pymongo

class ActionDigi(Action):
	def name(self):
		return 'action_digi'

	def run(self, dispatcher, tracker, domain):
		print('Check----1')
		myclient = pymongo.MongoClient("mongodb://localhost:27017/mydigidata")
		mydb = myclient["mydigidata"]
		mycol = mydb["mydigicollection"]
		router = tracker.get_slot('location')
		print(router+"*******")
		myquery = { "Q": router }
		mydoc = mycol.find(myquery)
		for x in mydoc:
			res = x
			response = """Your question is: {}. Here is your answer- {}""".format(router, res)
			dispatcher.utter_message(response)
			return [SlotSet('location',response)]
' ' '


' ' 'nlu_model.py

from rasa_nlu.training_data import load_data
from rasa_nlu import config
from rasa_nlu.model import Trainer
from rasa_nlu.model import Metadata, Interpreter

def train_nlu(data, configs, model_dir):
	training_data = load_data(data)
	trainer = Trainer(config.load(configs))
	trainer.train(training_data)
	model_directory = trainer.persist(model_dir, fixed_model_name = 'weathernlu')
	
def run_nlu():
	interpreter = Interpreter.load('./models/nlu/default/weathernlu')
	print(interpreter.parse(u"I wonder what is ct."))
	
if __name__ == '__main__':
	train_nlu('./data/data.json', 'config_spacy.json', './models/nlu')
	run_nlu()
' ' ' 



' '  'weather_domain.yml

slots:
  location:
    type: text


intents:
 - greet
 - goodbye
 - inform_ct


entities:
 - location

templates:
  utter_greet:
    - 'Hello! How can I help?'
  utter_goodbye:
    - 'Talk to you later.'
    - 'Bye bye :('
  utter_ask_keyword:
    - 'Please give keywords'

actions:
 - utter_greet
 - utter_goodbye
 - utter_ask_keyword
 - action_digi
 - actions.ActionDigi

' ' '

' ' ' train_online.py

from __future__ import absolute_import
from __future__ import division
from __future__ import print_function
from __future__ import unicode_literals

import logging

from rasa_core.agent import Agent
from rasa_core.policies.keras_policy import KerasPolicy
from rasa_core.policies.memoization import MemoizationPolicy
from rasa_core.interpreter import RasaNLUInterpreter
from rasa_core.train import online
from rasa_core.utils import EndpointConfig

logger = logging.getLogger(__name__)


def run_digi_online(interpreter,
                          domain_file="weather_domain.yml",
                          training_data_file='data/stories.md'):
    action_endpoint = EndpointConfig(url="http://localhost:5055/webhook")						  
    agent = Agent(domain_file,
                  policies=[MemoizationPolicy(max_history=2), KerasPolicy()],
                  interpreter=interpreter,
				  action_endpoint=action_endpoint)
    				  
    data = agent.load_data(training_data_file)
    agent.train(data,
                       batch_size=50,
                       epochs=200,
                       max_training_samples=300)				   
    online.run_online_learning(agent)
    return agent


if __name__ == '__main__':
    logging.basicConfig(level="INFO")
    nlu_interpreter = RasaNLUInterpreter('./models/nlu/default/weathernlu')
    run_digi_online(nlu_interpreter)
' ' '

**Comment by wochinge** [comment]
@mk4224 
Your provided story file seems to be a domain file? This is probably a copy paste error, please update your response with the correct stories file.

If you want to embed some code in Markdown, you can do this by enclosing it with three backticks "```"
E.g.

```
    ```
    your code
    ```
```

**Comment by wochinge** [comment]
Please use backticks --> ``` <-- to format your code blocks.
Your story has an action `action_weather` and `action.ActionWeather` which is not included in your domain file and for which no custom action is defined. Maybe you want to put `action_digi` there instead?

**Comment by mk4224** [comment]
I have changed my stories.md files. Still i am getting the same error
message.
stories.md file:---
 ' ' '
## story 01
* greet
    - utter_greet

## story 02
* goodbye
    - utter_goodbye

## strory 04
* greet
    - utter_greet

## story 05
* inform_ct
    - action.ActionDigi

## story 06
* inform_ct
    - action_digi
' ' '

**Comment by wochinge** [comment]
Try replacing `action.ActionDigi` with `action_digi`. If you have any more questions, please ask them in our  forum https://forum.rasa.com/ . Our community will be happy to help you there.
I will close this issue now.
