### ISSUE TITLE
Documentation is missing for some http endpoints

### ISSUE THREAD

**Issue by manslogic** [RasaHQ/rasa_core#1312]
Documentation is missing for those end points below:

1. execute_action                                POST, OPTIONS                  /conversations/[sender_id]/execute
2. log_message                                   POST, OPTIONS                  /conversations/[sender_id]/messages
3. predict                                            POST, OPTIONS                  /conversations/[sender_id]/predict

please refer the attached images.
![image](https://user-images.githubusercontent.com/1926423/48333689-5b7d3480-e67e-11e8-9964-6cf550d55bd8.png)

![image](https://user-images.githubusercontent.com/1926423/48333704-68018d00-e67e-11e8-80e9-4505ae833888.png)

**Comment by akelad** [comment]
Thanks for raising this issue, @tmbo  will get back to you about it soon.

**Comment by tmbo** [comment]
you are just in time 😄 - we actually just released a new major version which adds all of the above to the documentation in a new format:

https://rasa.com/docs/core/server/#operation/predictTemp

Let me know if there is something else you are missing.
