### ISSUE TITLE
There is a correct config working on windows 7 ?

### ISSUE THREAD

**Issue by darkmanAmazigh** [RasaHQ/rasa_core#1316]
Can someone get us a correct configuration to use rasa ?
Tensorflow version ?
pip version ?
python version ?
rasa-core version ?

reading this tuto,
https://rasa.com/docs/core/0.9.8/tutorial_basics/#setup
i'm blocked her 
python -m rasa_core.train -d domain.yml -s data/stories.md -o models/current/dialogue --epochs 200

i have this error 
 
    	Traceback (most recent call last):
	  File "C:\python36\lib\runpy.py", line 193, in _run_module_as_main
		"__main__", mod_spec)
	  File "C:\python36\lib\runpy.py", line 85, in _run_code
		exec(code, run_globals)
	  File "C:\python36\lib\site-packages\rasa_core\train.py", line 14, in <module>
		from rasa_core import config
	  File "C:\python36\lib\site-packages\rasa_core\config.py", line 9, in <module>
		from rasa_core.policies import PolicyEnsemble
	  File "C:\python36\lib\site-packages\rasa_core\policies\__init__.py", line 9, in <module>
		from rasa_core.policies.keras_policy import KerasPolicy
	  File "C:\python36\lib\site-packages\rasa_core\policies\keras_policy.py", line 11, in <module>
		import tensorflow as tf
	  File "C:\python36\lib\site-packages\tensorflow\__init__.py", line 24, in <module>
		from tensorflow.python import *
	  File "C:\python36\lib\site-packages\tensorflow\python\__init__.py", line 52, in <module>
		from tensorflow.core.framework.graph_pb2 import *
	  File "C:\python36\lib\site-packages\tensorflow\core\framework\graph_pb2.py", line 6, in <module>
		from google.protobuf import descriptor as _descriptor
	  File "C:\python36\lib\site-packages\google\protobuf\descriptor.py", line 47, in <module>
		from google.protobuf.pyext import _message
	ImportError: DLL load failed: The specified procedure could not be found.

i have tried tensorflow 1.6.0 -- 19.0 -- 1.10.0 -- 1.12.0, i got the same error message,
tensorflow-1.xx.0-cp36-cp36m-win_amd64.whl AVX instruction !

https://github.com/tensorflow/tensorflow/issues/23686

**Comment by darkmanAmazigh** [comment]
the problem is comming from protobuf 3.6.1

**Comment by darkmanAmazigh** [comment]
When i add the argument config,
        python -m rasa_core.train -o models/current/dialogue -d domain.yml -c nlu_model_config.yml -s 
        data/stories.md  --epochs 200

i got this error message 
      usage: train.py [-h] {default,compare,interactive} ...
      train.py: error: unrecognized arguments: --epochs 200

**Comment by darkmanAmazigh** [comment]
when i remove --epochs 200, that work !!!
i think that your documentation is not up to date or i dont understand well

**Comment by akelad** [comment]
Hi, you're looking at a super old version of the docs (0.9.8) but looks like you're using version 0.12. We removed all training related flags from the script and you now pass a policy configuration file instead. See the migration guide here: https://rasa.com/docs/core/migrations/

**Comment by darkmanAmazigh** [comment]
i upgrated to 0.12  version, and i have others error,
now i use for core 0.13 and for nlu 0.12, 
i'm bloqued with this error

    AttributeError: 'NoneType' object has no attribute 'index'

**Comment by wochinge** [comment]
@darkmanAmazigh You have to train core with a [policy config ](https://rasa.com/docs/core/policies/#id1), e.g. [this one](https://github.com/RasaHQ/rasa_core/blob/master/default_config.yml). Your command looks like you are using a NLU pipeline config instead of a policy config

**Comment by akelad** [comment]
We are releasing a minor version soon. But can you again post the full command you're using and the contents of your policy config file?

**Comment by darkmanAmazigh** [comment]
Thank you @wochinge , when i have added policy config to my nlu_config.yml file, that work perfectelly.

@akelad 
To train i use 

       python -m rasa_core.train -d domain.yml -s data/stories.md -c nlu_config.yml -o models/dialogue

To run

      python -m rasa_core.run -d models/dialogue -u models/current/current

**Comment by akelad** [comment]
For usage questions like that please take a look at our docs or our [forum](https://forum.rasa.com)
