### ISSUE TITLE
Very different number of action examples in each training step

### ISSUE THREAD

**Issue by ctrado18** [RasaHQ/rasa_core#1328]
**Rasa Core version**: 0.10.4

**Issue**:

Retraining each time gives very different number of action examples. My average is about 4500 action examples. But the spread is about 1000. That is bad because in my case I recognized that about 5000 examples are good . For less examples the story predictions are failing somethimes!

Why is this value so much spreading? It would be nice that you can constrain this value more?

**Comment by akelad** [comment]
Thanks for raising this issue, @MetcalfeTom will get back to you about it soon.

**Comment by MetcalfeTom** [comment]
Hi @ctrado18,

This occurs due to data augmentation.  You can test this with the `--augmentation 0` flag.  If the story predictions are failing then I'd advise you to test out different levels of augmentation to keep it about 5000 examples.  Which policy are you using?
