### ISSUE TITLE
How to make Rasa aware of custom actions module?

### ISSUE THREAD

**Issue by LawnboyMax** [RasaHQ/rasa_core#133]
**Rasa Core version**:
0.7.6
**Python version**: 
3.6.1
**Operating system**:
Windows 10
**Issue**:
Not sure how to make `rasa_core.train` aware of my `actions.py` module. Get the following message when training rasa_core:
```
ValueError: Action 'actions.ActionCheckStatus' doesn't correspond to a template / action. 
Remember to prefix actions that should utter a template with `utter_`. Error: No module named 'actions'
```

**Content of domain file**:
```yaml
actions:
  - actions.ActionCheckStatus
```
**Content of actions.py (located in the same dir as domain file)**:
```python
from rasa_core.actions import Action
import requests

class ActionCheckStatus(Action):
    def name(self):
        return "action_check_status"

    def run(self, dispatcher, tracker, domain):
        r = requests.get('https://myorg.com')
	status = r.status_code
	if status == 200:
	    dispatcher.utter_message("myorg.com looks up from here.")
	else:
	    dispatcher.utter_message("myorg.com looks down from here.")
        return []
```

**Comment by LawnboyMax** [comment]
Issue resolved. Had a typo in filename.

**Comment by chhavvi** [comment]
hi i am also working on this and i am facing the problem as you. Can you tell me how to resolve it. i m using django (python)

**Comment by gopathy** [comment]
@LawnboyMax
LawnboyMax can you give some more details? I have the same issue but it doesn't seem to be due to file name.

**Comment by LawnboyMax** [comment]
@gopathy @chhavvi  Assume you have the following custom action in your `actions.py`:
```python
from rasa_core.actions import Action
import requests

class ActionCheckStatus(Action):
    def name(self):
        return "action_check_status"

    def run(self, dispatcher, tracker, domain):
        r = requests.get('https://myorg.com')
	status = r.status_code
	if status == 200:
	    dispatcher.utter_message("myorg.com looks up from here.")
	else:
	    dispatcher.utter_message("myorg.com looks down from here.")
        return []
```

Then you need to define it under `actions` in your `domain.yml`:
```
actions:
  - actions.ActionCheckStatus
```
This uses Python modules convention. `domain.yml` and `actions.py` should be in the same directory for the above definition to work. 

If I my actions file was called, say, `special_actions.py` and was located in a module different than `domain.yml` file (let's say module called `extra` located in the same directory as `domain.yml`). Then my definiton would be the following:
```
actions:
  - extra.special_actions.ActionCheckStatus
```

To use it in your training data (`stories.md`) you need to refer to your action using the name that you defined in the `name(self)` method of the action. Assume `is_down` is the intent that should correspond to the defined action in this example story:

```
## is website down
* _is_down
  - action_check_status
```

This worked for me. Hope it works for you.

**Comment by gopathy** [comment]
@LawnboyMax Thank you so much for the detailed response! Exactly what I was doing and still had the problem. Embarrassingly, the culprit was that the path to myactions module was not set in Spyder.  works now! Thanks again!

**Comment by SaikiranMitta16** [comment]
hey, @gopathy I'm having a similar issue. Could you please tell me what Spyder is and how to set that path in Spyder?

**Comment by dkiran2323** [comment]
Hi gopathy, Im facing same problem, can you help us in setting path

**Comment by sandeepkumarsahoo** [comment]
I am facing the same issue .

I have added the below lines in actions/action.py file
class actiontest(Action):
    def name(self):
        return "actiontest"
    def run(self, dispatcher, tracker, domain):
        dispatcher.utter_message("successfullt tested actiontest")

updated domain.yml file with the below line in actions
actions:
 - usr.local.lib.python3.6.site-packages.rasa_core.actions.actiontest


Then I am trying to train core but getting the below error 

Traceback (most recent call last):
  File "/usr/local/lib/python3.6/runpy.py", line 193, in _run_module_as_main
    "__main__", mod_spec)
  File "/usr/local/lib/python3.6/runpy.py", line 85, in _run_code
    exec(code, run_globals)
  File "/usr/local/lib/python3.6/site-packages/rasa_core/train.py", line 15, in <module>
    from rasa_core.agent import Agent
  File "/usr/local/lib/python3.6/site-packages/rasa_core/agent.py", line 34, in <module>
    from rasa_core.processor import MessageProcessor
  File "/usr/local/lib/python3.6/site-packages/rasa_core/processor.py", line 19, in <module>
    from rasa_core.actions.action import (
ImportError: cannot import name 'ActionExecutionRejection'

can someone help me to fix this issue ?
Thanks in advance

**Comment by manojjjm** [comment]
Hello , i am also facing the same issue, 

please help
