### ISSUE TITLE
How to provide different template for different intents of the same slot?

### ISSUE THREAD

**Issue by ericnts** [RasaHQ/rasa_core#1333]
**Rasa Core version**:

**Python version**: 

**Operating system** (windows, osx, ...):

**Issue**:

**Content of domain file** (if used & relevant):
```yaml

```

**Comment by ericnts** [comment]
eg. I have one entity, and two intents. In different intents, the template of missing entity is different.  I used the FormAction, but it only provides a unified template called utter_ask_{slot_name}. How can we return different template according to different intent?

**Comment by akelad** [comment]
You can customise that function in your form action https://github.com/RasaHQ/rasa_core_sdk/blob/master/rasa_core_sdk/forms.py#L270
In general please ask usage questions like this in the [forum](https://forum.rasa.com)
