### ISSUE TITLE
ModuleNotFoundError: No module named 'pypandoc'

### ISSUE THREAD

**Issue by LawnboyMax** [RasaHQ/rasa_core#134]
**Rasa Core version**:
Trying to install latest `rasa_core` (0.7.9) in a fresh virtualenv
**Python version**: 
Python 3.6.1
**Operating system** (windows, osx, ...):
Windows 10
**Issue**:
Trying to install latest `rasa_core` in a fresh virtualenv. Get this error when running `pip install rasa_core`:

```
(env) C:\Users\user\Desktop\projects\rasa_project>pip install rasa_core
Collecting rasa_core
  Using cached rasa_core-0.7.9.tar.gz
    Complete output from command python setup.py egg_info:
    Traceback (most recent call last):
      File "C:\Users\user\AppData\Local\Temp\pip-build-b55h3weg\rasa-core\setup.py", line 9, in <module>
        import pypandoc
    ModuleNotFoundError: No module named 'pypandoc'

    During handling of the above exception, another exception occurred:

    Traceback (most recent call last):
      File "<string>", line 1, in <module>
      File "C:\Users\user\AppData\Local\Temp\pip-build-b55h3weg\rasa-core\setup.py", line 12, in <module>
        readme = open('README.md').read()
      File "c:\users\user\desktop\projects\rasa_project\env\lib\encodings\cp1252.py", line 23, in decode
        return codecs.charmap_decode(input,self.errors,decoding_table)[0]
    UnicodeDecodeError: 'charmap' codec can't decode byte 0x9d in position 882: character maps to <undefined>

    ----------------------------------------
Command "python setup.py egg_info" failed with error code 1 in C:\Users\user\AppData\Local\Temp\pip-build-b55h3weg\rasa-core\
```

**Comment by tmbo** [comment]
Can you please try this locally: 
Replace the Line 12 in `rasa_core/setup.py` with:
```
with io.open('README.md', encoding='utf-8') as f:
    readme = f.read()
```
It seems, windows is assuming the wrong encoding.

**Comment by LawnboyMax** [comment]
I cloned the repo and first run `pip install -r requirements.txt`. Now I get the following:
```
Could not find a version that satisfies the requirement tensorflow==1.1.0 (from -r requirements.txt (line 14)) (from versions: 1.2.0rc2, 1.2.0, 1.2.1, 1.3.0rc0, 1.3.0rc1, 1.3.0rc2, 1.3.0, 1.4.0rc0, 1.4.0rc1, 1.4.0)
No matching distribution found for tensorflow==1.1.0 (from -r requirements.txt (line 14))
```

Didn't have any issues when installing `rasa-core (0.7.6)` on the same machine in virtualenv.

**Comment by PreranaPolekar** [comment]
Any update or workaround on this? I am facing the same issue. Operating System : Windows 7,64 bit.

**Comment by LawnboyMax** [comment]
@PreranaPolekar I am simply using an older version from a month ago for now. Hopefully this will be fixed in a future version. Try `pip install rasa_core==0.7.6`.

**Comment by PreranaPolekar** [comment]
I used tensorflow cpu only version, downgraded to Python 3.5 to get all pieces work together.

**Comment by tmbo** [comment]
I think there is just no tensorflow version for the combination of windows+python3.5+tensorflow==1.1.0
I'd suggest updating to python 3.6

**Comment by tmbo** [comment]
Let me know if there are still issues with this.

**Comment by TungQuan** [comment]
could not find a version that satisfies the requirement tensorflow (from rasa_core) (from versions: )no matching distribution found for tensorflow (from rasa_core)
please help me!!

**Comment by KiritVaghela** [comment]
pip3 install rasa_core
