### ISSUE TITLE
Get response and tracker in one go using API

### ISSUE THREAD

**Issue by ErikTromp** [RasaHQ/rasa_core#1350]
**Rasa Core version**: 0.11/0.12

**Python version**:  3.6

**Operating system** (windows, osx, ...): Win 10/Ubuntu

**Issue**:
In my usage scenario with Rasa, I want to constantly get a response from the API (using `/webhooks/rest/webhook`) and then let Rasa tell me what entities it extracted and what the current tracker state is, which I need to next fetch via `/conversations/{sender_id}/tracker`. I can imagine that this way of using Rasa is very common and many people will want to do this in the same way. I am surprised there is not a single endpoint for doing this (getting the response *and* the resulting tracker state) in one go.

**Comment by akelad** [comment]
Thanks for raising this issue, @tmbo  will get back to you about it soon.

**Comment by tmbo** [comment]
I agree with you that your use case is most likely not very uncommon. But I also think that the separation of concerns between the API endpoints is a good thing. 

Is there any reason why we should return all the information in one go other than the one stated? I think it is ok to send two requests, if there is nothing else preventing that.

**Comment by ErikTromp** [comment]
I agree from a conceptional point of view. From practical cases where the rasa stuff might be on one server and the actual UI on another, HTTP overhead is something I want to prevent. Moreover since it's merely sugaring on top of already existing functionality.
