### ISSUE TITLE
Error while finding module specification for 'rasa_nlu.train' - ModuleNotFoundErrorL No module named 'rasa_nlu'

### ISSUE THREAD

**Issue by Manoj-t** [RasaHQ/rasa_core#1368]
**Rasa Core version**:

**Python version**:  3.7.1

**Operating system** (windows, osx, ...): Mac OS Mojave 10.14

**Issue**: Error while training the data.

I am trying to execute this command:
**python -m rasa_nlu.train -c nlu_config.yml --data nlu.md -o models --fixed_model_name nlu --project current --verbose**

**Content of nlu_config.yml**
“language” : “en”
“pipeline”: “tensorflow_embedding”

**Content of nlu.md**

## intent:greet
- hey
- hello
- hi
- good morning
- good evening
- hey there

## intent:restaurant_search
- i'm looking for a place to eat
- I want to grab lunch
- I am searching for a dinner spot
- i'm looking for a place in the [north](location) of town
- show me [chinese](cuisine) restaurants
- show me a [mexican](cuisine) place in the [centre](location)
- i am looking for an [indian](cuisine) spot
- search for restaurants
- anywhere in the [west](location)
- anywhere near [18328](location)
- I am looking for [asian fusion](cuisine) food
- I am looking a restaurant in [29432](location)

## intent:thankyou
- thanks!
- thank you
- thx
- thanks very much

Can someone help me out in solving this issue. Thanks in Advance.

**Comment by akelad** [comment]
Thanks for raising this issue, @MetcalfeTom  will get back to you about it soon.

**Comment by MetcalfeTom** [comment]
HI @Manoj-t,

Was `rasa-nlu` working before or is this an initial setup issue?

**Comment by Manoj-t** [comment]
Thank you @MetcalfeTom for responding. issue is resolved now

**Comment by akelad** [comment]
@Manoj-t why did you reopen this? do you need more help?

**Comment by Manoj-t** [comment]
I am sorry. I didn't mean to do that. Thank you.
