### ISSUE TITLE
MongoDb tracker  store not working with endpoints

### ISSUE THREAD

**Issue by shreyask90** [RasaHQ/rasa_core#1374]
**Rasa Core version**:0.12.0a4

**Python version**: Python 2.7.5

**Operating system** (windows, osx, ...): Centos7

**Issue**:I followed the Tracker store documentation to set up a MongoDB tracker. I get no errors, but the table inside the DB is not updated. 

**Content of domain file** (if used & relevant):
Endpoints.yml content: 

tracker_store:
    store_type: mongod
    url: mongodb://127.0.0.1:27017
    db: Rasa
    collection: test
    username: ""
    password: ""

```

**Comment by akelad** [comment]
Thanks for raising this issue, @wochinge  will get back to you about it soon.

**Comment by wochinge** [comment]
@shreyask90 
This feature was not yet included in `0.12.0a4`. Please switch at least to `0.12` for that and try again.

**Comment by timofarei** [comment]
I'm using docker and have set up docker to use rasa/rasa_core:latest image (I also tried rasa/rasa_core:stable). When I try to connect to my mlab mongoDB the following way I get an authentication error: 

**in enpoints.yml:**
tracker_store:
    store_type: mongod
    url: dsxxxxxx.mlab.com:xxxxx
    db: db_name
    username: "username"
    password: "pw"

**error log:**
rasa_core_1_76f1f0338317 | pymongo.errors.OperationFailure: Authentication failed.
backend_rasa_rasa_core_1_76f1f0338317 exited with code 1

Am I doing sth wrong in the enpoints.yml file?

Btw:
(i'm only using characters and numbers in the db-name, username and pw. Also, I put double quotes around the username and pw.)

**Comment by wochinge** [comment]
@timofarei Please ask usage questions in our [forum](https://forum.rasa.com/). However, it seems you have an authentication problem (wrong password or username).

**Comment by shreyask90** [comment]
@wochinge thank you for that. After changing the version it works.

**Comment by smn-snkl** [comment]
@wochinge : I'm building from the 0.12.x branch and notice the same behavior. Shouldn't 0.12.x have the latest 0.12 version?

**Comment by wochinge** [comment]
@smn-snkl In that case it should work. 
- What's the exact error message?
- What's your [authentication database](https://docs.mongodb.com/manual/reference/program/mongo/#cmdoption-mongo-authenticationdatabase)
- can you post your endpoint configuration (username + password anonymized)

**Comment by smn-snkl** [comment]
@wochinge : 

- Don't have an error message, I just seems like the in-memory tracker is used instead of MongoDB
- Using the default MongoDB settings. Just spawned the docker container. It also works when I build from 0.12.3
- Endpoint config: 
```
action_endpoint:
  url: http://rasa-actions:5055/webhook
nlu:
  url: http://rasa-nlu:5000
tracker_store:
  store_type: mongod
  url: mongodb://mongo:27017
  username: rasa
  password: password
```

**Comment by smn-snkl** [comment]
Nevermind. Rebuilt it again, now it seems like it works.
