### ISSUE TITLE
Env variables substitution in yaml config supports does not support more than one variable

### ISSUE THREAD

**Issue by znat** [RasaHQ/rasa_core#1384]
In:
```
some_endpoint:
   url: ${VAR1} ${VAR2}
```
Only `${VAR1}` is substituted

In:
```
some_endpoint:
   url: "${VAR1} ${VAR2}" # with quotes
```
Nothing is substituted

https://github.com/RasaHQ/rasa_core/blob/8b5f9dd7c858b31d8d8e7fed1cd00df4fe37f74d/rasa_core/utils.py#L302

**Comment by akelad** [comment]
Thanks for raising this issue, @wochinge  will get back to you about it soon.

**Comment by wochinge** [comment]
Having two or more environment variables is currently indeed not supported.
Would you maybe like to do a pull request for that?

**Comment by znat** [comment]
@wochinge I was willing to try but my first impression was that was a py-yaml issue. That's why I opened the discussion. Are you saying that it can be dealt with in Rasa ?

**Comment by wochinge** [comment]
The current variable replacement is done in these lines

```yaml
def replace_environment_variables():
    """Enable yaml loader to process the environment variables in the yaml."""
    import ruamel.yaml as yaml
    import re
    import os

    # eg. ${USER_NAME}, ${PASSWORD}
    env_var_pattern = re.compile(r'^(.*)\$\{(.*)\}(.*)$')
    yaml.add_implicit_resolver('!env_var', env_var_pattern)

    def env_var_constructor(loader, node):
        """Process environment variables found in the YAML."""
        value = loader.construct_scalar(node)
        prefix, env_var, remaining_path = env_var_pattern.match(value).groups()
        return prefix + os.environ[env_var] + remaining_path

    yaml.SafeConstructor.add_constructor(u'!env_var', env_var_constructor)
```

Basically it is 
* replace `return prefix + os.environ[env_var] + remaining_path` with `return os.path.expandvars(value)` 
* clean up the code
* write some additional tests
