### ISSUE TITLE
Getting intent from specific action

### ISSUE THREAD

**Issue by mcanzerini** [RasaHQ/rasa_core#139]
Hi,

Is there a way to wait for a specific intent after a specific custom action ? 

Example :
- BOT : what's your name ?
- User : John 

Can I define that after my **utter_ask_name** action, there is always a **give_name** intent ? (like filling a form, by bypassing the NLU). Sorry if that question is trivial.

Thanks guys

**Comment by tmbo** [comment]
No worries, and no this is a non trivial question. At the moment this is not possible and I don't think we can really make that a possibility as your bot would be rendered unable to do anything else at that point (e.g. answer `why do you need my name?`.

But we are currently thinking about ways to make bots more robust on theses inputs (e.g. even if the bot picked up a strange intent when entering a valid name).

**Comment by tmbo** [comment]
I'll close this in favor of #242.
