### ISSUE TITLE
Interactive Learning - Slot Tagging Discrepancies

### ISSUE THREAD

**Issue by ccelotto** [RasaHQ/rasa_core#1391]
**Rasa Core version**: 0.12.1

**Python version**: 3.6.5

**Operating system** (windows, osx, ...): MacOS

**Issue**: When tagging two slots/entities (cuisine and place) in this example, Interactive Learning is tagging them different. See screenshots below.

Proper Tagging
![screen shot 2018-11-25 at 8 56 47 pm](https://user-images.githubusercontent.com/40503458/48993786-a96d5000-f0f4-11e8-9091-b5d550c3e19b.png)

Improper Tagging 
![screen shot 2018-11-25 at 8 56 36 pm](https://user-images.githubusercontent.com/40503458/48993788-ac684080-f0f4-11e8-9ce0-d05822e93b41.png)

The slot types are both text. Both have been trained. Both leverage lookup tables. I tried removing the lookup tables to eliminate that variable, but the issue still persists.

Is there a common explanation for a slot being tagged like this? This doesn't seem to cause any issues with functionality, but when writing to NLU from Interactive Learning, screenshot number 2 writes in a different format (because in the parentheses, it is retagging the actual slot value instead of just listing the slot name).

Thanks in advance for any help!

**Comment by ccelotto** [comment]
After more testing, I figured out that the case of the slot is causing the difference in slot tagging. Is this functioning as intended? Is it best to not use any upper case slot values?

![screen shot 2018-11-25 at 10 02 01 pm](https://user-images.githubusercontent.com/40503458/48995758-218c4380-f0fe-11e8-992f-0745fd271de8.png)

![screen shot 2018-11-25 at 10 03 20 pm](https://user-images.githubusercontent.com/40503458/48995763-24873400-f0fe-11e8-8632-0f8ccba67137.png)

**Comment by ckomega** [comment]
I haven't run into this myself, but from reading the documentation, I think this is expected. Specifically, I believe what you saw as (place:picante) was the NLU assigning Picante as a synonym for (place:picante). The reason for this assignment would be the fact that it sees the difference in capitalization as a different word. That's my guess anyway.

**Comment by akelad** [comment]
This seems fine yes, I guess the question is -- do you have both those sentences in the training data? Or just the lowercase one?

**Comment by ccelotto** [comment]
Both are in the training data. As long as it is fine that the interactive learning export tags the nlu data in markdown as the following two different ways, then I guess all is good! Just wasn't sure why the upper/lowercase would change the format of the entity tagging / if this would cause any issues.

<img width="278" alt="screen shot 2018-11-26 at 1 37 42 pm" src="https://user-images.githubusercontent.com/40503458/49043677-9dc76b00-f180-11e8-94fc-149603321543.png">

**Comment by akelad** [comment]
it won't cause any issues, you should be fine!

**Comment by ccelotto** [comment]
Awesome - thank you for the clarification @akelad .
