### ISSUE TITLE
Two stage fallback policy

### ISSUE THREAD

**Issue by wochinge** [RasaHQ/rasa_core#1393]
**Desired Behavior**:

When the intent classification is below a certain threshold, the bot should ask for confirmation.
If the user confirms, the conversation should continue. If the user says no, we ask him to restate his problem.
If the classification confidence of the user clarification message is again below the threshold, it should trigger a different action (e.g. a handoff)

**Required Steps:**
- [x] implement a new policy which is similar to the current `FallbackPolicy` 
   - [x] checks for intent recognition confidence and triggers an action `ask_for_confirmation` if it was below a certain threshold ("Was it really A you wanted to do?")
   * [x] continues the story if the user confirmed his intent
   * [x] triggers an action `ask_for_clarification` if the user does not confirm
   * [x] continues story if the confidence for this intent was >= a certain threshold
   * [x] triggers `ask_for_confirmation` again if the confidence for the clarification was below a certain threshold
   * [x] predicts an action `action_fallback` if user re-clarified his problem, his clarification was below the threshold, and he denied the second `ask_for_confirmation`
  * [x] handles case if uses denies intent and clarifies in same utterance
  * [x] move tracker updates to action
  * [x] remove ActionReverts if UserReverts are enough
- [x] code documentation
- [x] tests
- [x] documentation
- [x] changelog

**Comment by wochinge** [comment]
@tmbo Can you have a look at the pull request whether it is going in the right direction?
One problem is, that I requires a `max_history` of events of at least `6` since we have to be able to go back. I cannot use slots, since the user would have to define them in the domain file which makes it harder to use.

**Comment by tmbo** [comment]
well, I don't think you need the `max_history`, the `tracker.events` will contain all events, even if `max_history=2`.

**Comment by wochinge** [comment]
ah, I think I confused `max_event_history` with `max_history` when writing the tests

**Comment by wochinge** [comment]
@tmbo I updated the test cases and docs.

Questions:
- Should we also revert actions / user messages in case we do the ultimate fallback action (e.g. handoff)?
- is the order of the policies in the policy configuration file important? Does e.g. the Keras policy re-evaluate its prediction if I update the confidence for a recognised intent?

**Comment by tmbo** [comment]
not sure about the handoff, my gut feeling right now is that it might not be necessary.

about the policy ordering: the ordering has some meaning: the ensemble will select the highest prediction from the first policy (e.g. if mulitple predict `1` it will choose the action from the one that comes first).

I don't think the predictions of the policies should influence each other

**Comment by wochinge** [comment]
@tmbo Mhm, but if we have a flow like
```md
* greet (with low confidence)
  - action_ask_confirm <-- two stage policy jumps in
* deny
  - ask_clarify
* bye (high confidence) <-- actual user intent recognised
```
the two stage policy changes it to 
```md
* bye (high confidence)
  - ??
```
Based on that, the other policies (`Memoization` or `Keras`) have to make new predictions for the next action `??` based on the new intent, right? . In this case the two stage fallback policy influences the other policies, right?
