### ISSUE TITLE
SlackInput attaches UserID to messages

### ISSUE THREAD

**Issue by grzegorznowak** [RasaHQ/rasa_core#1400]
**Rasa Core version**: `0.12.2`

**Python version**: `Python 3.6.6`

**Operating system** : `Ubuntu 16.04.5 LTS`

**Issue**:

Hey guys, 

is this by design that a message that slack connector receives, and then seemingly parses via NLU, contains user IDs ? See the log output:
```
DEBUG:rasa_core.processor:Received user message '<@UXXXXX> hello' with intent '{'name': 'greet', 'confidence': 0.9375163316726685}' and entities '[]'
```
This would confuse NLU normally (and it does in other cases with my training set), if it wasn't trained against that as an entity ___a priori___, wouldn't it ? Or is it only debug's mishap and the actual text that goes to NLU is being stripped  ?
I see there is an open issue that touches that, so not sure if it's related since not yet merged - https://github.com/RasaHQ/rasa_core/issues/1228

**Comment by akelad** [comment]
Thanks for raising this issue, @ricwo  will get back to you about it soon.

**Comment by ricwo** [comment]
Hi @grzegorznowak! User IDs should not end up in messages. May I ask what your slack credentials file looks like? The expected output would just be 
```rasa_core.processor  - Received user message '_greet' with intent '{'name': 'greet', 'confidence': 1.0}' and entities '[]'```

The issue you linked is not directly related, as that's about adding an additional property to the message as a payload, not to the message text itself

**Comment by ricwo** [comment]
Also @grzegorznowak , what was the literal message you sent to the bot in the case you posted? was it just `hello`, or was `@USERNAME hello`?

**Comment by grzegorznowak** [comment]
hey @ricwo , ok so yes now as I see what rasa does in codes it's starting to make sense, however I believe there is an issue still, ie:
```
hello -> (posted directly to bot) -> Received user message 'hello' with intent '{'name': 'greet', 'confidence': 0.9704450368881226}' and entities '[]'
```
vs.
```
@mybot hello -> (posted with the bot mention, either directly or via a channel) -> Received user message 'hello <@XXXXXX>' with intent '{'name': 'greet', 'confidence': 0.9704450368881226}' and entities '[]'
```
where `<@XXXXXX>` is indeed the bot's ID from the @mention. Surprisingly the confidence score is *exactly* the same, which I've not noticed before, and not really sure how to interpret. 
So, shouldn't the id be stripped before NLP processing, or at least if message begins with it ?

### And also a final side-question (but still kind of related)
I think in a few versions before bot didn't care about message posted to normal channels if it wasn't being mentioned, but currently it eagerly want's to take part in every conversation in channels it has been invited too, regardless of usage or lack of said @mentions.

**Comment by ricwo** [comment]
> So, shouldn't the id be stripped before NLP processing, or at least if message begins with it ?

This does not happen as of now, but would be a good enhancement along the lines of what we discussed in the other issue (if configurable).

> I think in a few versions before bot didn't care about messages posted to normal channels if it wasn't being mentioned, but currently it eagerly want's to take part in every conversation in channels it has been invited too, regardless of usage or lack of said @mentions.

I'm not aware of any changes in the slack connector on our side that would cause this change. I would assume this is something you can configure in the app's `Event Subscription` settings in the slack API

**Comment by grzegorznowak** [comment]
> I'm not aware of any changes in the slack connector on our side that would cause this change. I would assume this is something you can configure in the app's Event Subscription settings in the slack API

I've checked that and I think the behaviour is bogus, let me open up an issue on that specifically not to tangle this thread anymore. Good to close @ricwo , thanks man
