### ISSUE TITLE
SlackInput doesn't reply to the source of the message

### ISSUE THREAD

**Issue by grzegorznowak** [RasaHQ/rasa_core#1401]
**Rasa Core version**: `0.12.2`

**Python version**: `Python 3.6.6`

**Operating system** : `Ubuntu 16.04.5 LTS`

**Issue**:

Hey guys,

looking at the current codes (of my version installed), I see the slack channel the SlackInput responds to is only initialized at the construction phase, ie:

```
 def __init__(self, token, slack_channel=None):
        # type: (Text, Optional[Text]) -> None

        self.slack_channel = slack_channel
```

and so it can't respond to messages that mention said bot originating from public channel via @mentions. Or am I missing something ? It doesn't seem to be too hard to implement own InputChannel to do that, but was there something that made this design decision this way ?

**Comment by akelad** [comment]
Thanks for raising this issue, @ricwo  will get back to you about it soon.

**Comment by ricwo** [comment]
Hi @grzegorznowak, That's correct - the slack bot at the moment only replies to one pre-defined recipient. Let us know if you end up implementing this, and we would consider a contribution that makes this more configurable and flexible 🙂

**Comment by grzegorznowak** [comment]
hey @ricwo , cool ok, good to know it's not a system's limitation. Will do a PR if I come up with an elegant solution. Cheers.

**Comment by akelad** [comment]
is this a duplicate of #1415 now?

**Comment by grzegorznowak** [comment]
negative @akelad , however related, yes.
This mentions inability of the system to **send** responses into varied channels, based on run-time variables. The other shows the the system can't **receive** @mentions. Hope that make sense!

**Comment by akelad** [comment]
got it, thanks!
