### ISSUE TITLE
ValueError: Invalid story file format.

### ISSUE THREAD

**Issue by Krypton3** [RasaHQ/rasa_core#142]
After the custom input I have provided, I have for this error. What could be solution? Where should I look into?
  File "bot.py", line 132, in <module>
    train_dialogue()
  File "bot.py", line 87, in train_dialogue
    validation_split=0.2
  File "/home/jishan/ChatBotPractice/RasaCoreNLU/rasa_core/rasa_core/agent.py", line 152, in train
    trainer.train(filename, remove_duplicates=remove_duplicates, **kwargs)
  File "/home/jishan/ChatBotPractice/RasaCoreNLU/rasa_core/rasa_core/policies/trainer.py", line 52, in train
    remove_duplicates)
  File "/home/jishan/ChatBotPractice/RasaCoreNLU/rasa_core/rasa_core/policies/trainer.py", line 73, in _prepare_training_data
    max_number_of_trackers=max_number_of_trackers)
  File "/home/jishan/ChatBotPractice/RasaCoreNLU/rasa_core/rasa_core/training/__init__.py", line 45, in extract_training_data_from_file
    graph = extract_story_graph_from_file(filename, domain, interpreter)
  File "/home/jishan/ChatBotPractice/RasaCoreNLU/rasa_core/rasa_core/training/__init__.py", line 29, in extract_story_graph_from_file
    story_steps = StoryFileReader.read_from_file(filename, domain, interpreter)
  File "/home/jishan/ChatBotPractice/RasaCoreNLU/rasa_core/rasa_core/training/dsl.py", line 149, in read_from_file
    raise ValueError("Invalid story file format.")
ValueError: Invalid story file format.

**Comment by tmbo** [comment]
Which version of rasa core are you using?

**Comment by foxjr** [comment]
Is your story file .md format? Can you post it?

**Comment by Krypton3** [comment]
I managed to resolve the issue. Yes it was md files and there was some unnoticeable notation problems. Thanks Everyone.

**Comment by hiringbees** [comment]
@Krypton3 Hi , I am also getting the same error "ValueError: Invalid story file format."
Can you help me to resolve the issue? You had mentioned there was unnoticeable notation problems.If possible,can you elaborate on this  ?

**Comment by glaulom** [comment]
@hiringbees Hi, I've encountered the same error, I had to create a new action with a different name to make it work. The strangest thing is that after that, I have been able to use the previous action(without changing anything about it...) that was giving me the error.
There is probably a tricky thing going on here.

**Comment by dejanmarich** [comment]
I'm also getting the same error.. can you explain more how you solved it?

**Comment by glaulom** [comment]
@dejanmarich As I said I just had to create a new action containing the same content but with a different name, I think it's better not to copy/paste as the error might be a unexpected character (just a suposition).
If you do not know wich action or element is causing you the error, try to remove them one by one until the error disappear, you'll then now wich one you need to get rid of. 

I'm sorry I can't give you any further details but that's exactly what I have done, hopefully it'll work for you.

**Comment by dejanmarich** [comment]
I deleted all but *greet - utter_greet and I still get an error :) no way I can figure out why

**Comment by glaulom** [comment]
Maybe someone from the team (eg @tmbo ) can help you, or you should open a new issue.

**Comment by tmbo** [comment]
Please create a new issue as this might not be related. Please include the log file as well as stories and the domain definition. I'd very much like to help, but I need to be able to reproduce the issue to help fix it.

**Comment by hewei816** [comment]
@Krypton3 have you figure out this issue?
