### ISSUE TITLE
Rasa Core throwing error

### ISSUE THREAD

**Issue by bikashkumars** [RasaHQ/rasa_core#1424]
While running Rasa Core, i am getting this Error

rasa_core.exceptions.UnsupportedDialogueModelError: The model version is to old to be loaded by this Rasa Core instance. Either retrain the model, or run withan older version. Model version: 0.11.3 Instance version: 0.12.2 Minimal compatible version: 0.12.0

Before running rasa core, i have done NLU run and Core Run
python -m rasa_nlu.train -c nlu_config.yml --data nlu.md -o models --fixed_model_name nlu --project current --verbose

Then
python -m rasa_core.train -d domain.yml -s stories.md -o models/dialogue

pip show rasa_core
Rasa Core - Version: 0.12.2

pip show rasa_nlu
0.13.8

pip show tensorflow
Version: 1.10.0

Do i need to down-grade rasa_core to 0.11 ?

**Comment by bikashkumars** [comment]
I fix this issue, by downgrading rasa code to 0.11.x.
This is the command to do that
pip install -U rasa_core==0.11.11

This might help someone

**Comment by akelad** [comment]
The solution to this is just retrain your model with 0.12

**Comment by dummybot123** [comment]
How to retrain model with 0.12. My model version is coming 0.0.0.

**Comment by akelad** [comment]
Please create a new issue
