### ISSUE TITLE
Automate testing for our starter packs

### ISSUE THREAD

**Issue by MetcalfeTom** [RasaHQ/rasa_core#1427]
So that they don't fail when we update rasa_core or rasa_NLU

**Comment by akelad** [comment]
i think we do it for some of them, can you check which ones aren't included in tests?

**Comment by MetcalfeTom** [comment]
For the scripts?  I can't find any tests for these anywhere.

Perhaps we could include [a tutorial script such as this](https://github.com/RasaHQ/rasa-workshop-pydata-berlin) in the repo and that way we could test it directly upon PR.

**Comment by MetcalfeTom** [comment]
@JustinaPetr Could you link me to any more demo scripts that you think we should include.

**Comment by akelad** [comment]
i believe just all the ones in the examples folder

**Comment by JustinaPetr** [comment]
I would say starterpacks are the most important ones which should definitely be included:
 - https://github.com/RasaHQ/starter-pack-rasa-stack 
 - https://github.com/RasaHQ/starter-pack-rasa-nlu

**Comment by JustinaPetr** [comment]
I agree @MetcalfeTom. So far every workshop had its own repo, but for the next year's workshops I'll go for a more reusable option - one repo for all

**Comment by MetcalfeTom** [comment]
OK, I'll separate that issue for now then:

https://github.com/RasaHQ/roadmap/issues/335

**Comment by MetcalfeTom** [comment]
Created some functionality tests for both packs.  For the automation, I'd like to replicate what we do for the website and doc builds in `rasa_core`'s Travis jobs
