### ISSUE TITLE
story not linked

### ISSUE THREAD

**Issue by shona20** [RasaHQ/rasa_core#1433]
Getting an issue-
ValueError: Story file or folder could not be found. Make sure 'C:\Users\ku371301\Documents\code\data\stories.md' exists and points to a story folder or file.
```
Please help

**Comment by akelad** [comment]
Please fill out the issue template

**Rasa Core version**:

**Python version**: 

**Operating system** (windows, osx, ...):

**Issue**:



**Content of domain file** (if used & relevant):
```yaml

```
And provide the command you're running
