### ISSUE TITLE
Rasa SLACK Integration not working as expected. 

### ISSUE THREAD

**Issue by nomadavid9** [RasaHQ/rasa_core#1436]
I am using the following Docker Images
rasa/rasa_core:latest
rasa/rasa_nlu:latest-spacy
rasa/rasa_core_sdk:latest
mongo
mongo-express

**Rasa Core version**: Rasa-core:  0.13.0a1

**Python version**: python 3

**Operating system** (windows, osx, ...): Containers running official images, On top of Windows OS

**Issue**: Rasa Slack Integration not working as expected. 
Followed the documentation to the letter, all steps have been followed.
Created Bot
Activated all necessary components on Slack 
Set the incoming webhook on Slack
Set the outgoing event webhook
Set the proper permissions "message.im, message.groups, ...."
Grabbed Bot Token and set it in the credentials.yml, which i have configured rasa core to point to.
Set the appropriate channel, in which the bot is invited as a member.

I am having the core listen on port 5005, set ngrok to map to that port, and am able to see as requests hit the endpoint .../webhooks/slack/webhook

Bot is able to receive messages from slack, I can see when the messages post to my Database, the  conversation is happening. 
However, Bot is not responding on slack. 

For ex: On the channel that I designated:
I write:
 @my_bot Hi Bot
I check mongo-express
Bot responds with a large object containing a message property of: "Hi. Whats your name?"
I check on Slack:
Message response never pops up on slack

**Comment by nomadavid9** [comment]
Found the error, there is a slight typo on the rasa docs for slack
integration. For the "slack_channel" property on credentials.yml, the docs
state the format like this: "@my_channel" for channel, individual, or app.

It needs to say:
Channel - > "#my_channel"
Individual, app - > "@individual"

Slack is working as expected now.

**Comment by akelad** [comment]
Would you mind creating a PR to fix that?

**Comment by akelad** [comment]
Yep I was asking if you would mind creating a PR to fix that in the documentation :)

**Comment by nomadavid9** [comment]
Hi again!

I'm sorry, but I'm a bit new to github and maybe I'm just not understanding correctly. 
The typo is on the Rasa website, not on the repo itself. So there are no files that need to be fixed here. Which I didn't realize at the time of raising the issue,
Do I still make a Pull request?

Thank you!

**Comment by nomadavid9** [comment]
Hi, I submitted a pull request with the requested changes!
Thank you for your patience :) 

Let me know if there's anything else I can do to help 👍
