### ISSUE TITLE
Module not found error

### ISSUE THREAD

**Issue by santannamv** [RasaHQ/rasa_core#1438]
**Rasa Core version**: 12.2.2

**Rasa NLU version**: 0.13.8

**Python version**: 3.6

**Operating system**: Windows 10

**Issue**:
Please, I am trying to train the model in weatherbot tutorial and I am getting this error on CMD:

Traceback (most recent call last): File “nlu_model.py”, line 1, in from rasa_nlu.converters import load_data ModuleNotFoundError: No module named ‘rasa_nlu.converters’

Anything else I should inform here?

**Content of domain file** (if used & relevant):
```yaml

```

**Comment by wochinge** [comment]
Please ask usage questions in our forum https://forum.rasa.com. 
I guess you need to install the right version of Rasa NLU for it since the tutorial uses an older version (`0.11.4`, https://github.com/JustinaPetr/Weatherbot_Tutorial/blob/master/Full%20Code/requirements.txt)
