### ISSUE TITLE
help in creating action_restart action

### ISSUE THREAD

**Issue by Manoj-t** [RasaHQ/rasa_core#1467]
**Rasa Core version**: 0.12.3

**Python version**: 3.6

**Operating system** (windows, osx, ...): macOS Mojave

**Issue**: I need help in creating action_restart action when user starts again from starting.

**Content of domain file** (if used & relevant):
```yaml

```

**Comment by akelad** [comment]
the restart action already exists. It's triggered by `/restart` or you can put it at the end of a story. In future please ask these kind of questions in our forum

**Comment by Manoj-t** [comment]
okay. Thank you
