### ISSUE TITLE
Rasa Core tensorflow error? (AWS  EC2 server)

### ISSUE THREAD

**Issue by Akshit99** [RasaHQ/rasa_core#1474]
**Rasa Core version**:
0.12.3
**Python version**: 
3.6.7
**Operating system** (windows, osx, ...):
Ubuntu 18.04 (AWS ec2 Server)
**Issue**:
So I uploaded my bot on AWS server and started with installing rasa_nlu and rasa_core. After that I trained my nlu model using python -m rasa_nlu.train command and then i did the same for rasa_core train. But when i'm doing that i'm getting this tensorflow error and i can't train my dialogue model.
Please check out my error and help me!
![error major](https://user-images.githubusercontent.com/34835800/49864326-408e1380-fe28-11e8-90ff-3949c75797d9.PNG)

**Content of domain file** (if used & relevant):
```yaml

```

**Comment by akelad** [comment]
what version of tensorflow do you have installed? make sure it matches up with the rasa_core requirements

**Comment by Akshit99** [comment]
> what version of tensorflow do you have installed? make sure it matches up with the rasa_core requirements
Thanks @akelad I solved this issue. you are right the tensorflow verison running was newer one and i needed to run older one for rasa_core (tf-1.10.0).
can you help me with something else as well. So now that my bot is running on AWS server. I need to make an API call from some other server which will contain the question(user input) and some credentials(user_id) and i'll take that question , apply nlu , do the action and send back the response of the user to the other server in a json format. So after uploading my files on aws, i'm trying to do a POST request in postman so that i can get some response from the bot..so what should i put in the postman request. like what should be the API url. Coz on my system it was like "http://localhost:5005/conversations/respond" But now i'm not calling from local host as the bot is running on AWS. So now I used --enable_api in run command and then ran the bot. So what should be the API URL NOW?

**Comment by akelad** [comment]
Glad you solved the original issue, as for the other one -- please create a post about that on the forum
