### ISSUE TITLE
Rasa-core with RestAPI

### ISSUE THREAD

**Issue by Krypton3** [RasaHQ/rasa_core#148]
How can we expose rasa-core restaurant boy application example though rest api?
Some guidelines would be helpful.

**Comment by tmbo** [comment]
Thanks for raising this. Did you take a look at http://core.rasa.ai/tutorial_remote.html as well as http://core.rasa.ai/http.html

If so, it would be very helpful if you could be a bit more specific on what you did not understand, what is unclear or what you want to get out of an example that you are missing.

**Comment by tmbo** [comment]
duplicates #119

**Comment by Bhaarat-Pachori** [comment]
> Thanks for raising this. Did you take a look at http://core.rasa.ai/tutorial_remote.html as well as http://core.rasa.ai/http.html
> 
> If so, it would be very helpful if you could be a bit more specific on what you did not understand, what is unclear or what you want to get out of an example that you are missing.

The above links don't work. I have this everywhere on the community too. What ever the link is it takes you to either to the home page or some parent page, but never to intended page. In this case, both the links takes me to https://rasa.com/docs/getting-started/overview/ .
Am I missing something here?

**Comment by tmbo** [comment]
docs moved: https://rasa.com/docs/core/server/
