### ISSUE TITLE
AttributeError: 'Namespace' object has no attribute 'verbose'

### ISSUE THREAD

**Issue by shreyas1990** [RasaHQ/rasa_core#149]
Rasa Core version: 0.7

Python version: 2.7.6

Operating system: Ubuntu 14.04

Issue: Tried to run the HTTP server using the following command  "python -m rasa_core.server -d models/dialogue -u models/nlu/current -o out.log" ended up with the error.

Content of domain file : 

[domain.txt](https://github.com/RasaHQ/rasa_core/files/1587028/domain.txt)

**Comment by tmbo** [comment]
@shreyas1990 does that issue persist if you install the latest version from github master? We changed this recently and I just wan't to make sure we haven't fixed this already.

Can you also please amend the whole stacktrace?

**Comment by shreyas1990** [comment]
@tmbo  I believe I have downloaded and installed the latest version from github. I have attached the stack trace. 
[trace.txt](https://github.com/RasaHQ/rasa_core/files/1605623/trace.txt)

**Comment by tmbo** [comment]
This should be fixed in the latest master version (and I think also in the latest version released on pypi)
