### ISSUE TITLE
Update interactive learning to run with prompt-toolkit 2.0.5

### ISSUE THREAD

**Issue by JustinaPetr** [RasaHQ/rasa_core#1492]
https://github.com/RasaHQ/rasa_core/issues/1143

Currently, it requires prompt-toolkit 1.0.14 which is not compatible with ipython >=6.0.0

**Comment by TheBear44** [comment]
Is this solved by #1469 ?

**Comment by wochinge** [comment]
Yes, this is solved by #1469
