### ISSUE TITLE
moodbot example is not working as expected

### ISSUE THREAD

**Issue by dineshjavafreelancer** [RasaHQ/rasa_core#150]
**Rasa Core version**: 0.8.0a4

**Python version**: Python 3.6.3 :: Anaconda custom (64-bit)

**Operating system** (windows, osx, ...): Windows 7 Professional Service Pack1 64 bit

**Issue**: The moodbot is not working as expected. I have taken all the files from github https://github.com/RasaHQ/rasa_core/tree/master/examples/moodbot. But, when I run this example, it is giving random responses. It looks like it is not understanding my input at all. Please see the screenshot. Am I missing anything here?

![moodbotflow](https://user-images.githubusercontent.com/15262941/34367990-58c30958-ead6-11e7-8ef3-1c04edb322fd.png)

**Content of domain file** (if used & relevant):
```yaml
https://github.com/RasaHQ/rasa_core/blob/master/examples/moodbot/domain.yml
```

**Comment by saiqulhaq** [comment]
duplicate issue https://github.com/RasaHQ/rasa_core/issues/135

**Comment by Uhlo** [comment]
Hi,

I have the same problem with the moodbot example. I think this is not a duplicate of issue #135.
I am using the current master branch (0.8.0a4) but also in the version distributed by pip (0.7.9) the problem occurs.

Please consider reopening this issue.

**Comment by tmbo** [comment]
Oh wait, are you entering `2` to select the option? That doesn't work. You need to enter the stuff in the `(...)`, e.g. `greet`

**Comment by Uhlo** [comment]
Hi,

I've tried both. I started the bot with debug mode and the problem seems to be the NLU rather than the dialogue manager. When I run the NLU model in standalone (rasa_nlu.server) and send a request like `http://localhost:5000/parse?q=sad&project=nlu&model=current` it returns

```json
 {
  "intent": {
    "name": "goodbye",
    "confidence": 0.21058760257550257
  },
  "entities": [],
  "intent_ranking": [
    {
      "name": "goodbye",
      "confidence": 0.21058760257550257
    },
    {
      "name": "greet",
      "confidence": 0.20046700695022954
    },
    {
      "name": "mood_great",
      "confidence": 0.1761418720142948
    },
    {
      "name": "mood_deny",
      "confidence": 0.14583814068090856
    },
    {
      "name": "mood_affirm",
      "confidence": 0.14524953218952694
    },
    {
      "name": "mood_unhappy",
      "confidence": 0.12171584558953753
    }
  ],
  "text": "mood_unhappy"
}
```

I am currently using rasa_nlu 0.10.6 together with spacy 2.0.5.
Should I open an issue in rasa_nlu?

**Comment by tmbo** [comment]
which english language model are you using (which spacy model did you install for en)?

**Comment by Uhlo** [comment]
I installed `en` as described [here](http://nlu.rasa.ai/installation.html#best-for-most-spacy-sklearn):

```bash
pip install -U spacy
python -m spacy download en
```

**Comment by tmbo** [comment]
Right, but that is the installation instruction for spay < 2.0. Can you please install a larger model, e.g. using http://nlu.rasa.ai/master/installation.html#best-for-most-spacy-sklearn:

```
python -m spacy download en_core_web_md
python -m spacy link en_core_web_md en --force
```

**Comment by Uhlo** [comment]
Hi,

that's it! Thank you.
I think it would be sensible to alter the current documentation at this point, because even in 0.7.9 the problem is occurring. People that try out rasa for the first time might think that it is not working as "advertised" and turn away.

**Comment by tmbo** [comment]
So we won't fix the current docs, but we are on the verge of releasing a new version that will update the default documentation as well as the package installed from pip :+1:
