### ISSUE TITLE
Handle passing of `epochs`, `batch_size` etc to Agent.train properly

### ISSUE THREAD

**Issue by TheBear44** [RasaHQ/rasa_core#1501]
**Rasa Core version**:

0.13.0a4

**Python version**: 3.7

**Issue**:

When `agent.train()` has `epochs` or `batch_size`, the following errors were throw respectively:
`TypeError: fit() got multiple values for keyword argument 'epochs'`
`TypeError: fit() got multiple values for keyword argument 'batch_size'`

**Comment by akelad** [comment]
This is something we should handle correctly yes, but a fix for that is, don't pass it to the train function. It should go in your `policy_config.yml` https://rasa.com/docs/core/policies/#default-configuration

**Comment by TheBear44** [comment]
I found it is passed in [getting_started.ipynb](https://github.com/RasaHQ/rasa_core/blob/5fc0517d9f3bde0cf401aa97d8fee9ce43874360/getting_started.ipynb##L323)
```python
from rasa_core.policies.keras_policy import KerasPolicy
from rasa_core.agent import Agent

agent = Agent('domain.yml', policies=[KerasPolicy()])
training_data = agent.load_data('stories.md')
agent.train(
        training_data,
        validation_split=0.0,
        epochs=400
)

agent.persist('models/dialogue')
```

**Comment by vishnuragas** [comment]
@akelad Faced the same issue. Where should we pass the 'policy_config.yml' file? to the train function?

**Comment by Ghostvv** [comment]
In the example above these parameters should be passed to `KerasPolicy()`

**Comment by vishnuragas** [comment]
@Ghostvv  You mean, it should not be passed to the 'policy_config.yml' file? but to KerasPolicy(...)?

**Comment by akelad** [comment]
In your script you're not calling the "policy_config.yml", so in this case it wouldn't go there. You should move it from `.train()` to `KerasPolicy()` here yes. In general if you're using the `rasa_core.train` script though it should go in the `policy_config.yml`

**Comment by vishnuragas** [comment]
@akelad  This is the command I used: `python -m rasa_core.train -d domain.yml -s data/stories.md -o models/current/dialogue -c config.yml` . Here 'config.yml' is the file which contains the parameters. The contents of the files are as below:

policies:
  - name: KerasPolicy
    epochs: 100
    max_history: 5
  - name: FallbackPolicy
    fallback_action_name: 'action_default_fallback'
  - name: MemoizationPolicy
    max_history: 5
  - name: FormPolicy

**Comment by vishnuragas** [comment]
@akelad Used the script to run it, it gives 'Entry point not found error' (https://github.com/RasaHQ/rasa_core/issues/1525). Here is the recent error snapshot

![entry point](https://user-images.githubusercontent.com/28904290/50776936-47ae1300-1268-11e9-8d12-7f1901a55443.PNG)
