### ISSUE TITLE
Issue with creating an agent - using custom channel to create a UI (Android)

### ISSUE THREAD

**Issue by AbrarAhmedQuresh** [RasaHQ/rasa_core#1509]
Rasa Core version: rasa-core  0.12.3
rasa-nlu 0.13.2

Python version: Python 3.6.6  

Operating system: Ubuntu 18.04

Issue: 

I am trying to add my simple project to an Android Interface. I used the steps given in Advanced Usage with a custom Rasa Core project as Custom Channel from Python using https://github.com/scalableminds/chatroom

Following is the code I ran ('dialogue_management_model.py')

import os
from rasa_core.agent import Agent
from rasa_core.interpreter import RasaNLUInterpreter
from bot_server_channel import BotServerInputChannel

**Creating the Interpreter and Agent
def load_agent(): 
    nlu_interpreter = RasaNLUInterpreter('./models/nlu/default/troubleshootnlu')
    agent = Agent.load('./models/dialogue', interpreter = nlu_interpreter)

**Creating the server
def main_server():
    agent = load_agent()

    channel = BotServerInputChannel(agent, port=5005)
    agent.handle_channels([channel], http_port=5005)

if __name__ == '__main__':
main_server()

## Got error @ agent.handle_channels([channel], http_port=cmdline_args.port)

Traceback (most recent call last):
  File "dialogue_management_model.py", line 68, in <module>
    main_server()
  File "dialogue_management_model.py", line 51, in main_server
    agent.handle_channels([channel], http_port=5005)
AttributeError: 'NoneType' object has no attribute 'handle_channels'

Thanks in Advance.

**Comment by wochinge** [comment]
Thanks for raising this issue, @MetcalfeTom will get back to you about it soon.

**Comment by AbrarAhmedQuresh** [comment]
Hello @MetcalfeTom 

Thank you for your reply, But the error still exists.

**Comment by MetcalfeTom** [comment]
Hi again,

How did you train your bot?  My next solution would be to check your `models/dialogue` folder is in the right format - something like this:

![image](https://user-images.githubusercontent.com/35203669/50824614-5a434d80-1337-11e9-9f9f-54bdb7d4c783.png)

**Comment by AbrarAhmedQuresh** [comment]
Thank you for the reply @MetcalfeTom 

My models/dialogue folder is in the right format, same as you mention above.

**Comment by MetcalfeTom** [comment]
Sorry for my error, the function `load_agent()` should look like this:
```
def load_agent():
    nlu_interpreter = RasaNLUInterpreter('./models/nlu/default/troubleshootnlu')
    return Agent.load('./models/dialogue', interpreter = nlu_interpreter)
```
I copied your code and tested it with this implementation - it works from my end.  Let me know if this solves it
