### ISSUE TITLE
Failed to load domain specification from '/root/restaurantbot/models/policy/current/domain.yml'.

### ISSUE THREAD

**Issue by napster-powergeek** [RasaHQ/rasa_core#151]
<!-- THIS INFORMATION IS MANDATORY - YOUR ISSUE WILL BE CLOSED IF IT IS MISSING. If you don't know your Rasa Core version, use `pip list | grep rasa_core`. 

![mobaxterm screenshot](https://user-images.githubusercontent.com/16436014/34404301-da0743b0-ebd2-11e7-871b-cbf73c769d01.png)

**Comment by tmbo** [comment]
Please make sure to specify a proper path when trying to load a model. I will close this issue as it is of no use without any information about environment, commands.

**Comment by srkrbunny** [comment]
I am also getting same issue.

This is my directory

C:\Rasa\Docker\domain.yml

C:\Rasa\Docker\data\stories.md

While i am running below commands i got , Exception: Failed to load domain specification from ‘/app/project/domain.yml’. File not found!

docker run -v $(pwd):/app/project -v $(pwd)/models/rasa_core:/app/models rasa/rasa_core:latest train –domain project/domain.yml –stories project/data/stories.md –out models

How can i resolve it, please help me.

**Comment by tmbo** [comment]
We'll not sure, something seems to be off with your mount - apparently your mounted directory does not contain a domain.yml - from which directory are you running the docker command?

**Comment by tesssie** [comment]
I am facing the same issue
