### ISSUE TITLE
RASA | Slots | How to reset Slots in between the conversation?

### ISSUE THREAD

**Issue by EliBruce** [RasaHQ/rasa_core#1516]
**Rasa Core version**:0.12.1

**Python version**: 3.6.5

**Operating system** (windows, osx, ...):Win7

**Issue**:I have created a weather bot. Here first time the location(Chico) assign to the stot properly and the result showing as expected.

As per the story the bot will ask to the user for the weather continuously.
So in same conversation, I asked the weather for another place(Irish Town), but the result is showing with previous Slot value (Chico). Please see the attached image to get more details about the issue.

Also please find the attached stories and Domain…

here my question is, how can I reset the slot value in between the conversation?

Thanks in Advance, EB

![slot issue](https://user-images.githubusercontent.com/46138200/50426392-b7102400-08b2-11e9-8ff9-361a9dcd3935.png)

[bot_stories.txt](https://github.com/RasaHQ/rasa_core/files/2709024/bot_stories.txt)

[weather_domain.txt](https://github.com/RasaHQ/rasa_core/files/2709026/weather_domain.txt)

**Comment by tomarraj008** [comment]
i am also facing same problem

**Comment by samarth12** [comment]
Hi @EliBruce this is completely off topic, but did you connect your bot to the UI yourself? Do you have an open source example I could refer to? I am struggling to move my bot from cmdline using the RestInput. Would be very helpful!

Thanks.

**Comment by MetcalfeTom** [comment]
Hi @EliBruce,

Try resetting the slot after
```
    - utter_any_other_query
* ans_yes
```
You can do this by making an `action_reset_slot` which simply fills the slot with `None`, i.e. it looks like:

```
class ResetSlot(Action):

    def name(self):
        """Name."""
        return "action_reset_slot"

    def run(self, dispatcher, tracker, domain):
        """Run."""
        return [SlotSet("Location", None)]
```
