### ISSUE TITLE
how can create  action  on   interactive learning?

### ISSUE THREAD

**Issue by chenbaicheng** [RasaHQ/rasa_core#1517]
console  show this  message: 
--------------------------------------------------------------------------------------------------------------------
? What is the next action of the bot?  <create new action>
? Please type the action name  utter_ask_position
Thanks! The bot will now run utter_ask_position.

2018-12-26 16:59:59 ERROR    rasa_core.server  - Encountered an exception while running action 'utter_ask_position'. Bot will continue, but the actions events are lost. Make sure to fix the exception in your custom code.
? WARNING: You have created a new action: 'utter_ask_position', which was not successfully exe
-----------------------------------------------------------------------------------------------------------------------
why  can't create action  like

`## storyName
*ask_position
  -utter_ask_position

then  domain.md write
templates:
   utter_ask_position:
  - "where position?"
`

**Comment by MetcalfeTom** [comment]
Hi @chenbaicheng, could you post the command you used to run interactive learning?  I believe this is a quick fix - you just need to add an [action endpoint](https://rasa.com/docs/core/customactions/#custom-actions) and run an action server.

**Comment by chenbaicheng** [comment]
@MetcalfeTom   thanks,  must be  create a action server and  then write this action name ?  if this action only reply string , such as  ：
*greet
 -say_hi

then  this action "say hi"   , only reply string "hello"  ,  also need to create a action server ?

**Comment by chenbaicheng** [comment]
@MetcalfeTom    wait a moment  ， is  that  common？
python -m rasa_core.train interactive -s data/stories.md -d data/domain.yml --nlu nlu -o models/dialogue --endpoints endpoints.yml

**Comment by MetcalfeTom** [comment]
Hello again,

Somehow I missed that this was just an utterance - no action server necessary!  It will run from your `domain.yml` file, so make sure you have `utter_ask_position` listed under `actions` in it.  If this is already the case, please post a snippet of your `domain` and I'll take a look
