### ISSUE TITLE
Documentation bug: Code example for validating form input obsolete

### ISSUE THREAD

**Issue by asmaier** [RasaHQ/rasa_core#1524]
The code example given at https://rasa.com/docs/core/slotfilling/#validating-user-input is obsolete. The line

    events = self.extract(dispatcher, tracker, domain)

doesn't work, because the method `self.extract()`doesn't exist anymore for FormActions.

**Comment by wochinge** [comment]
Thanks for raising this issue!

**Comment by tmbo** [comment]
@Ghostvv how can we update the example in https://rasa.com/docs/core/slotfilling/#validating-user-input, or should we remove it?

**Comment by tmbo** [comment]
alright, I think it is quickest if you take that on for the next sprint
