### ISSUE TITLE
How to avoid delete lookup's feature key

### ISSUE THREAD

**Issue by WoWuQ** [RasaHQ/rasa_core#1526]
**Rasa Core version**:
0.11.12
**Python version**: 
2.7
**Operating system** (windows, osx, ...):
ubuntu 16.05
**Issue**:
when i add the following:
     - action_restart
     - restart
events, I find the progrem always delete some feature key.  

The raw code in policies/memoization.py:
    # delete contradicting example created by
    # partial history augmentation from memory
    ambiguous_feature_keys.add(feature_key)
    del self.lookup[feature_key]

Is there have some solution to avoid this?

The story is about this:

``
  ## skill_1_return_advice_3_1
  > return_advice_1
    - skill_1_return_advice
  > return_advice_2

 ## skill_1_return_advice_3_7
 > return_advice_2
   - slot{"is_second_use": true}
   - action_restart
   - restart

## skill_1_return_advice_3_8
 > return_advice_2
   - slot{"is_second_use": false}
   - action_restart
   - restart

**Comment by wochinge** [comment]
Thanks for raising this issue, @Ghostvv will get back to you about it soon.

**Comment by WoWuQ** [comment]
Some Stories are these:
## story1
  * return_goods
  > cp1
    - skill_1_search_good
  > cp2
  
  ## story2
   > cp2
    - slot{"requested_slot": "number"}
  * inform{"number":1}
   > cp1

## story3
  > cp2
    - slot{"order_number": 1}
  > cp2

## story4
> cp2
   - slot{"requested_slot": "is_second_use"}
> cp2

## story5
> cp2
 * affirm_intent
> cp1

## story6
> cp2
  * deny_intent
> cp1

## story5
 > cp2
   - slot{"is_use": true}
 > end1

## story4
 > cp2
   - slot{"is_use": false}
 > cp_end

## end story
 > cp_end
   - action_restart
   - restart

When I train , it can delete ambiguous_feature_keys, I found the corresponding action is action_listen

**Comment by Ghostvv** [comment]
Ambiguous keys means you have the same story leading to different actions, try using `--debug_plots` flag to see the connection between your story blocks

**Comment by WoWuQ** [comment]
I fix the issue and resolved.  But This error can not see in generate_story.pdf.  
The bool slot's as_feature function cause  this problem, and I think it is a bug in rasa core.
Thanks!

**Comment by akelad** [comment]
@Ghostvv can you check whether there's an actual bug?

**Comment by Ghostvv** [comment]
`The bool slot's as_feature function cause this problem, and I think it is a bug in rasa core.` Could you please elaborate what is wrong with it?

**Comment by WoWuQ** [comment]
In the domain.py,  get_parsing_states function while generate slot feature, 
`for i, slot_value in enumerate(slot.as_feature()):
     if slot_value != 0:
     slot_id = "slot_{}_{}".format(key, i)
     state_dict[slot_id] = slot_value`
but this function must slot_value !=0,  but bool slot generate false feature with the value = 0, it will be filted.

Is it？

**Comment by Ghostvv** [comment]
in the `rasa_core` `0.12`, we changed the featurization of the boolean slot

**Comment by WoWuQ** [comment]
Ok, l know,thanks

**Comment by WoWuQ** [comment]
Ok, l know,thanks

**Comment by Ghostvv** [comment]
Do you think it is correct in `0.12`? Can we close the issue?
