### ISSUE TITLE
Error while running Interactive Training On Docker 

### ISSUE THREAD

**Issue by stacybot123** [RasaHQ/rasa_core#1527]
**Rasa Core version**: 0.13.0a5

**Operating system** (windows, osx, ...):  Ubuntu 18.04.1 

I have deployed bot on docker. To generate stories , I want to run the interactive learning . Used command as 
```
docker run -v $(pwd):/app/project -v $(pwd)/models/rasa_core:/app/models rasa/rasa_core:latest run python -m rasa_core.train interactive -o models -d /app/project/domain.yml -s /app/project/data/stories.md --nlu /app/models --endpoints /app/project/config/endpoints.yml

```

this worked but after Epoch , I got this error
```

2019-01-02 08:57:30 INFO     rasa_core.policies.keras_policy  - Done fitting keras policy model
Processed actions: 39it [00:00, 3432.11it/s, # examples=39]
2019-01-02 08:57:30 INFO     rasa_core.agent  - Persisted model to '/app/models'
2019-01-02 08:57:30 INFO     rasa_core.training.interactive  - Rasa Core server is up and running on http://localhost:5005
Processed Story Blocks: 100%|███████Bot loaded. Visualisation at http://localhost:5005/visualization.html.Ctr-c to abort):
Type a message and press enter (press 'Ctr-c' to exit).
? Next user input (Ctr-c to abort):

Warning: Output is not to a terminal (fd=1).
Warning: Input is not to a terminal (fd=0).
2019-01-02 08:57:30 ERROR    rasa_core.training.interactive  - An exception occurred while recording messages.
Traceback (most recent call last):
  File "/app/rasa_core/training/interactive.py", line 1213, in record_messages
    _enter_user_message(sender_id, endpoint)
  File "/app/rasa_core/training/interactive.py", line 1063, in _enter_user_message
    lambda a: not a)
  File "/app/rasa_core/training/interactive.py", line 313, in _ask_or_abort
    answers = questions.ask()
  File "/usr/local/lib/python3.6/site-packages/questionary/question.py", line 17, in ask
    return self.unsafe_ask(patch_stdout)
  File "/usr/local/lib/python3.6/site-packages/questionary/question.py", line 27, in unsafe_ask
    return self.application.run()
  File "/usr/local/lib/python3.6/site-packages/prompt_toolkit/application/application.py", line 699, in run
    return run()
  File "/usr/local/lib/python3.6/site-packages/prompt_toolkit/application/application.py", line 673, in run
    return f.result()
  File "/usr/local/lib/python3.6/site-packages/prompt_toolkit/eventloop/future.py", line 149, in result
    raise self._exception
  File "/usr/local/lib/python3.6/site-packages/prompt_toolkit/eventloop/coroutine.py", line 90, in step_next
    new_f = coroutine.throw(exc)
  File "/usr/local/lib/python3.6/site-packages/prompt_toolkit/application/application.py", line 652, in _run_async2
    result = yield f
  File "/usr/local/lib/python3.6/site-packages/prompt_toolkit/eventloop/coroutine.py", line 90, in step_next
    new_f = coroutine.throw(exc)
  File "/usr/local/lib/python3.6/site-packages/prompt_toolkit/application/application.py", line 604, in _run_async
    result = yield From(f)
EOFError
Exception in thread Thread-7:
Traceback (most recent call last):
  File "/usr/local/lib/python3.6/threading.py", line 916, in _bootstrap_inner
    self.run()
  File "/usr/local/lib/python3.6/threading.py", line 864, in run
    self._target(*self._args, **self._kwargs)
  File "/app/rasa_core/training/interactive.py", line 1213, in record_messages
    _enter_user_message(sender_id, endpoint)
  File "/app/rasa_core/training/interactive.py", line 1063, in _enter_user_message
    lambda a: not a)
  File "/app/rasa_core/training/interactive.py", line 313, in _ask_or_abort
    answers = questions.ask()
  File "/usr/local/lib/python3.6/site-packages/questionary/question.py", line 17, in ask
    return self.unsafe_ask(patch_stdout)
  File "/usr/local/lib/python3.6/site-packages/questionary/question.py", line 27, in unsafe_ask
    return self.application.run()
  File "/usr/local/lib/python3.6/site-packages/prompt_toolkit/application/application.py", line 699, in run
    return run()
  File "/usr/local/lib/python3.6/site-packages/prompt_toolkit/application/application.py", line 673, in run
    return f.result()
  File "/usr/local/lib/python3.6/site-packages/prompt_toolkit/eventloop/future.py", line 149, in result
    raise self._exception
  File "/usr/local/lib/python3.6/site-packages/prompt_toolkit/eventloop/coroutine.py", line 90, in step_next
    new_f = coroutine.throw(exc)
  File "/usr/local/lib/python3.6/site-packages/prompt_toolkit/application/application.py", line 652, in _run_async2
    result = yield f
  File "/usr/local/lib/python3.6/site-packages/prompt_toolkit/eventloop/coroutine.py", line 90, in step_next
    new_f = coroutine.throw(exc)
  File "/usr/local/lib/python3.6/site-packages/prompt_toolkit/application/application.py", line 604, in _run_async
    result = yield From(f)
EOFError
```

**Comment by stacybot123** [comment]
Ok, I resolved it with reference to [1227]( https://github.com/RasaHQ/rasa_core/issues/1227) . 

Do I need to run nlu server and rasa core sdk before running interactive training?

**Comment by stacybot123** [comment]
I used the -it flag and its working. The problem now is its not able to parse question on the nlu server.

The command I used is : 

```
sudo docker run -it   -v $(pwd):/app/project   -v $(pwd)/models/rasa_core:/app/models   rasa/rasa_core:latest   run python -m rasa_core.train interactive -o /app/project/models/rasa_core/ -s/app/project/data/stories.md -d /app/project/domain.yml --endpoints /app/project/config/endpoints.yml  -u /app/project/rasa_nlu/current
```
But now I am getting error as : 

```
ERROR    rasa_core.interpreter  - Failed to parse text 'hello' using rasa NLU over http. Error: HTTPConnectionPool(host='68.183.130.95', port=5000): Max retries exceeded with url: /parse?model=current&project=%2Fapp%2Fproject%2Frasa_nlu&q=hello (Caused by NewConnectionError('<urllib3.connection.HTTPConnection object at 0x7f7df04bf710>: Failed to establish a new connection: [Errno 110] Connection timed out',))

```

I am now stuck on this

**Comment by stacybot123** [comment]
@akelad  Please help on this

**Comment by wochinge** [comment]
@stacybot123 Whether you have to start the NLU server depends on the content of your `endpoints.yml`.  How does it look like? 
In general, please ask usage questions in [our forum](forum.rasa.com) if you need help and don't tag persons in the github issues. We will make sure that your issue is redirected to the right person.

**Comment by wochinge** [comment]
In this case you have to start nlu and expose port 5000 of it. 
You can also omit the `nlu` part and just link the trained NLU model if don't want to start a nlu server.

**Comment by wochinge** [comment]
> Exception: Not all required packages are installed. To use this pipeline, you need to install the missing dependencies. Please install spacy, sklearn_crfsuite

Sorry, I forgot that you are using docker containers. The Core container does not include all NLU dependencies to keep them more lightweight. So you have to use a separate NLU container.

> Other method , if I keep the nlu url in endpoints.yml and then train the bot , it have every intent incorrect. It is just taking the text as the intent. For example, if I type hello its taking hello as intent

Did you launch the NLU container with the mounted volume and check the log output? I think the NLU model Core is referencing is not found by the NLU container. When NLU is linked through the endpoints configuration, you don't have to specify the path to model with `-u` but instead the NLU project and the model name. From what I see this should be `-u current`. Please also see this guide: https://rasa.com/docs/core/docker_walkthrough/#connecting-rasa-core-and-rasa-nlu

**Comment by stacybot123** [comment]
@wochinge , Thank you replying. I am getting error  that its not able to connect to the nlu server.  Can you  please advice if I am using the correct commands.

Here is the error:
```
ERROR    rasa_core.interpreter  - Failed to parse text 'hello' using rasa NLU over http. Error: HTTPConnectionPool(host='ip_address_of_server', port=5000): Max retries exceeded with url: /parse?model=current&project=&q=hello (Caused by NewConnectionError('<urllib3.connection.HTTPConnection object at 0x7fbb0c0ab7f0>: Failed to establish a new connection: [Errno 110] Connection timed out',))
```
I startup my server for nlu and action . Here is the docker-compose.yml for running both of them

```
version: '3.0'

services:
  action_server:
    image: action_end:latest
    ports:
      - 5055:5055
    volumes:
      - ./actions:/app/actions
  rasa_nlu:
    image: rasa/rasa_nlu:latest-spacy
    ports:
      - 5000:5000
    volumes:
      - ./models/rasa_nlu:/app/models
    command:
      - start
      - --path
      - models
```
my endpoint.yml
```
action_endpoint:
    url: 'http://ip_address_of_server:5055/webhook'
nlu:
    url: 'http://ip_address_of_server:5000'
```

docker command I am using now
```
sudo docker run -it  -v $(pwd):/app/project   -v $(pwd)/models/rasa_core:/app/models   rasa/rasa_core:latest   run python -m rasa_core.train interactive -o project/model/rasa_core/dialogue -s  project/data/stories.md -d project/domain.yml --endpoints project/config/endpoints.yml -u current
```

Here is what I get if I test both of these servers are running:
#1 : Action server

![image](https://user-images.githubusercontent.com/26300235/50653509-c0cf1100-0faf-11e9-8f47-de00bb6b5371.png)

#2 Rasa NLU

![image](https://user-images.githubusercontent.com/26300235/50653552-e65c1a80-0faf-11e9-9447-21a9146d0e00.png)

**Comment by wochinge** [comment]
replace `ip_address_of_server` with `localhost` in your endpoints.yml

**Comment by stacybot123** [comment]
I already tried that now it says; 

```
Failed to parse text 'hello' using rasa NLU over http. Error: HTTPConnectionPool(host='localhost', port=5000): Max retries exceeded with url: /parse?model=current&project=&q=hello (Caused by NewConnectionError('<urllib3.connection.HTTPConnection object at 0x7ffb4c269c88>: Failed to establish a new connection: [Errno 111] Connection refused',))
``

**Comment by wochinge** [comment]
sure you started the nlu container? how does your endpoints.yml look?

**Comment by stacybot123** [comment]
yes. here is the endpoints.yml 

```
action_endpoint:
    url: 'http://localhost:5055/webhook'
nlu:
    url: 'http://localhost:5000'
```

I started both the nlu and action server using below  docker-compose.yml file
```
version: '3.0'

services:
  action_server:
    image: action_end:latest
    ports:
      - 5055:5055
    volumes:
      - ./actions:/app/actions
  rasa_nlu:
    image: rasa/rasa_nlu:latest-spacy
    ports:
      - 5000:5000
    volumes:
      - ./models/rasa_nlu:/app/models
    command:
      - start
      - --path
      - models

```

**Comment by rsreeni** [comment]
@stacybot123 @wochinge ,

Im stuck with the same error too running the interactive trainer using the docker....

> Bot loaded. Visualisation at http://localhost:5005/visualization.html.
> Type a message and press enter (press 'Ctr-c' to exit). 
> Processed Story Blocks: 100%|██████████████████████████████████████████████████████████████████████████████████| 3/3 [00:00<00:00, 1162.50it/s, # trackers=1]
> ? Next user input (Ctr-c to abort): hello                                                                                                                    
> 2019-01-04 22:43:26 ERROR    rasa_core.interpreter  - Failed to parse text 'hello' using rasa NLU over http. Error: HTTPConnectionPool(host='localhost', port=5000): Max retries exceeded with url: /parse?model=&project=current&q=hello (Caused by NewConnectionError('<urllib3.connection.HTTPConnection object at 0x7f5a50471198>: Failed to establish a new connection: [Errno 111] Connection refused',))

Thanks,

-SR

**Comment by stacybot123** [comment]
@wochinge  Please help me on this. I am still stuck on this.

**Comment by rsreeni** [comment]
@stacybot123 ,

Did you get it to work ?

thanks,

-SR

**Comment by akelad** [comment]
@wochinge can you look into this?

**Comment by wochinge** [comment]
@stacybot123 Sorry, for this late answer. Totally missed that one 🤦‍♂️ 
Can you please try `sudo docker run -it  -v $(pwd):/app/project   -v $(pwd)/models/rasa_core:/app/models   rasa/rasa_core:latest   run python -m rasa_core.train interactive -o project/model/rasa_core/dialogue -s  project/data/stories.md -d project/domain.yml --endpoints project/config/endpoints.yml -u current/current
` to run the core image?

**Comment by stacybot123** [comment]
@wochinge  . I still have the same error

```
Failed to parse text 'hello' using rasa NLU over http. Error: HTTPConnectionPool(host='localhost', port=5000): Max retries exceeded with url: /parse?model=current&project=current&q=hello (Caused by NewConnectionError('<urllib3.connection.HTTPConnection object at 0x7fdfafff64e0>: Failed to establish a new connection: [Errno 111] Connection refused',))

```
While if I access 
http://localhost:5000/parse?model=current&project=current&q=hello
on browser it gives me the output as : 

```
{
  "intent": {
    "name": "greet",
    "confidence": 0.84518939700848
  },
  "entities": [],
  "intent_ranking": [
    {
      "name": "greet",
      "confidence": 0.84518939700848
    },
    {
      "name": "goodbye",
      "confidence": 0.09834562046529342
    },
    {
      "name": "inform",
      "confidence": 0.05646498252622648
    }
  ],
  "text": "hello",
  "project": "current",
  "model": "model_20190128-192259"
}

```
http://localhost:5055/health
on browser returns
```
{"status":"ok"}
```

**Comment by stacybot123** [comment]
@wochinge Did you got a chance to check this? Sorry for bothering you.

**Comment by wochinge** [comment]
@stacybot123 I think I now finally now the problem. Since Rasa Core is started within a docker image, `localhost:5005` points to the Core container itself. What you have to do is either link the Core container with NLU or (since the NLU port is exposed) use the ip address of your docker host instead of `localhost`.

```yaml
action_endpoint: 
  url: 'http://localhost:5055/webhook'
nlu: 
  url: 'http://<ip-of-your-docker-host>:5000'
```

**Comment by stacybot123** [comment]
@wochinge  Now my endpoints.yml look like this
```
action_endpoint: 
  url: 'http://localhost:5055/webhook'
nlu: 
  url: 'http://127.0.0.1:5000'
```
I am still getting the same error , instead of host='0.0.0.0' it now says host='127.0.0.1' : 
```
ERROR    rasa_core.interpreter  - Failed to parse text 'hello' using rasa NLU over http. Error: HTTPConnectionPool(host='127.0.0.1', port=5000): Max retries exceeded with url: /parse?model=current&project=current&q=hello (Caused by NewConnectionError('<urllib3.connection.HTTPConnection object at 0x7f67cc36fac8>: Failed to establish a new connection: [Errno 111] Connection refused',))
```

**Comment by wochinge** [comment]
@netcarver This won't work since @stacybot123 does not run Rasa Core as part of docker-compose.
@stacybot123 `127.0.01` is not the ip of the host, but simply the localhost of the docker container.

You need the ip address from your host machine **from the perspective of your docker container.**

**Comment by stacybot123** [comment]
@wochinge  This resolved the issue. Thank you so much for your your help. Thank you for being patient.

**Comment by wochinge** [comment]
@stacybot123 Which ip did you finally put in? 
Great it is finally solved! 🚀  Sorry, that it took so long to solve that one.

**Comment by stacybot123** [comment]
@wochinge I got the IP of the docker host using the command:  
docker inspect  container_id
I got two IP address , Gateway and IPAddress , IPAddress was 172.19.0.2 , which was not working , so I used the gateway ip address 172.19.0.1.
I tried accessing http://172.19.0.1:5000/parse?model=current&project=current&q=hello  in browser and this was working.
