### ISSUE TITLE
Is possible create multiple models in rasa_core

### ISSUE THREAD

**Issue by LuisQ95** [RasaHQ/rasa_core#1530]
Hi, i need create multiple models for multiple plataforms e.g. Facebook, Telegram but in Telegram ins't possible send payloads or carrouseles. Is possible create one model for each plataform?. And if possible, how is it done?

**Comment by wochinge** [comment]
I am afraid this currently not possible. You have to have different Rasa Core servers if you want to use different models for different platforms. 
If you have an idea how to integrate this you are very welcome to contribute 👍
