### ISSUE TITLE
How to pass the location of the model to be generated in the Agent class

### ISSUE THREAD

**Issue by tahseen09** [RasaHQ/rasa_core#1534]
**Rasa Core version**: latest version

**Python version**:  3.6

**Operating system** (windows, osx, ...): mac os mojave

**Issue**:
I am using the train function for training my model. I want to pass the path where the model is to be stored. How can I do that? 

**Content of domain file** (if used & relevant):
```yaml

```

**Comment by wochinge** [comment]
Please ask usage question on our [forum](forum.rasa.com). Please also refer to the [docs](https://rasa.com/docs/core/policies/#training-and-policies).

**Comment by tahseen09** [comment]
I am not using the command, I am using the functions 
from rasa_core.agent import Agent

agent = Agent()
data = agent.load_data("stories.md")
agent.train(data)

**Comment by wochinge** [comment]
@tahseen09 Simply call `agent.persist(output_path)` after `agent.train(data)`

**Comment by tahseen09** [comment]
Thanks a lot. Just one last question? Can I retrain existing model with some new data? Finetune it as it can be done in AllenNLP

**Comment by wochinge** [comment]
Mhm, using custom code this is probably a bit hard. You could try using `agent.continue_training` and some pieces of `rasa_nlu/server.py::continue_training`.
It's probably easier if you use the command line interface and do interactive training with the flag `--finetune`.

**Comment by tahseen09** [comment]
Thanks a lot :) @wochinge
