### ISSUE TITLE
FormAction: Slots are not filled when named other than entity name

### ISSUE THREAD

**Issue by satishavhad** [RasaHQ/rasa_core#1537]
**Rasa Core version**: 0.12.3
**Rasa NLU version**: 0.13.8
**Rasa Core SDK version**: 0.12.1
**Python version**: 3.6.7
**Operating system** windows

**Issue**: Slot mapping only works if the entity name matches the slot name.
But there are many use cases where same entity is used for filling different Slots depending on the intent. How should I resolve this problem?

Below s the relevant code:

Action.py
        return {"ENT_Security_Name": [self.from_entity(entity="ENT_Security_Name",
											intent="INT_API_BuySecurity"),
								  self.from_entity(entity="ENT_Security_Name",
											intent="enter_data")],
				"SLOT_ENT_Order_Quantity": [self.from_entity(entity="ENT_Number",
											intent="INT_API_BuySecurity"),
						   self.from_entity(entity="ENT_Number",
											intent="enter_data")],

**Comment by satishavhad** [comment]
Debug log:

DEBUG:rasa_core_sdk.forms:Validating user input '{'intent': {'name': 'enter_data', 'confidence': 0.9559510946273804}, 'entities': [{'start': 0, 'end': 4, 'value': '2342', 'entity': 'ENT_Number', 'confidence': 0.8388133918505674, 'extractor': 'ner_crf'}], 'intent_ranking': [{'name': 'enter_data', 'confidence': 0.9559510946273804}, {'name': 'INT_API_BuySecurity', 'confidence': 0.0948711484670639}, {'name': 'greet', 'confidence': 0.0}, {'name': 'human_handoff', 'confidence': 0.0}, {'name': 'ask_howdoing', 'confidence': 0.0}, {'name': 'bye', 'confidence': 0.0}, {'name': 'ask_whoisit', 'confidence': 0.0}, {'name': 'INT_API_ask_holdings', 'confidence': 0.0}, {'name': 'INT_API_ask_OrderInfo', 'confidence': 0.0}, {'name': 'out_of_scope', 'confidence': 0.0}], 'text': '2342'}'
DEBUG:rasa_core_sdk.forms:Trying to extract requested slot 'SLOT_ENT_Order_Quantity' ...
DEBUG:rasa_core_sdk.forms:Got mapping '{'type': 'from_entity', 'entity': 'SLOT_ENT_Order_Quantity', 'intent': [], 'not_intent': []}'
DEBUG:rasa_core_sdk.forms:Failed to extract requested slot 'SLOT_ENT_Order_Quantity'
ERROR:__main__:Failed to validate slot SLOT_ENT_Order_Quantity with action action_Buy_security_form
127.0.0.1 - - [2019-01-03 14:12:18] "POST /webhook HTTP/1.1" 400 288 0.021526

**Comment by wochinge** [comment]
@satishavhad Can you please indent your code and put in code blocks?

**Comment by Ghostvv** [comment]
@satishavhad please ident your code
