### ISSUE TITLE
Securing RASA Core HTTP server

### ISSUE THREAD

**Issue by KumarGopalani** [RasaHQ/rasa_core#154]
**Rasa Core version**: Latest Stable version 

**Python version**: Relevant

**Operating system** (windows, osx, ...): Windows

**Issue**:
How do we secure the RASA Core HTTP server, as an example we would want the RASA core server to respond to only authorized applications connecting to it. This could be done if we ahve some form of exchange of authorized tokens as an example.

**Comment by tmbo** [comment]
If you run the server using the http endpoint you can set a token when starting the server using `--auth_token`. the server will check if that secret token is present. If you need more advanced security you should probably put the server behind a firewall or reverse proxy that does the authentication.

**Comment by KumarGopalani** [comment]
Thank you for the response. With the above Auth _Token, will it validate the Auth token is there with every request?

**Comment by tmbo** [comment]
Yes, you need to pass the token as part of every request (for security reasons you should only use this method when running over https otherwise someone could MITM your token).
