### ISSUE TITLE
Rasa Core instance. Either retrain the model, or run withan older version. Model version: 0.12.3 Instance version: 0.13.0a5 Minimal compatible version: 0.13.0a2

### ISSUE THREAD

**Issue by milangm89** [RasaHQ/rasa_core#1540]
**Rasa Core version**: 0.11.11

**Python version**: 3.4

**Operating system** (windows, osx, ...): ubuntu 14.04

**Issue**: getting the below error during docker compose up

+++
rasa_core_1      | rasa_core.exceptions.UnsupportedDialogueModelError: The model version is to old to be loaded by this Rasa Core instance. Either retrain the model, or run withan older version. Model version: 0.12.3 Instance version: 0.13.0a5 Minimal compatible version: 0.13.0a2
starterpackrasastack_rasa_core_1 exited with code 1
+++

**Content of domain file** (if used & relevant):
```actions:
- utter_name
- utter_thanks
- utter_greet
- utter_goodbye
- action_joke
config:
  store_entities_as_slots: true
entities:
- name
forms: []
intents:
- deny:
    use_entities: true
- thanks:
    use_entities: true
- goodbye:
    use_entities: true
- joke:
    use_entities: true
- greet:
    use_entities: true
- name:
    use_entities: true
slots:
  name:
    auto_fill: true
    initial_value: null
    type: rasa_core.slots.TextSlot
templates:
  utter_goodbye:
  - text: Talk to you later!
  utter_greet:
  - text: Nice to you meet you {name}. How can I help?
  utter_name:
  - text: Hey there! Tell me your name.
  utter_thanks:
  - text: My pleasure.
```

**Comment by wochinge** [comment]
Ideally the version of Rasa Core you want to use it with. In your first post you said `0.11.11`? Where did you get the model from which apparently has version `0.12.3`?

**Comment by milangm89** [comment]
i have changed the versions between 0.11.11 and 0.12.3. both are getting same error

**Comment by wochinge** [comment]
So you have to train and run it with the *same* version of Rasa Core. 
What's the train and run command you are using?

**Comment by milangm89** [comment]
i have followed this https://rasa.com/docs/core/installation/

**Comment by wochinge** [comment]
Ok, and what are the exact commands you are using to train the model and then to run Rasa Core?

**Comment by milangm89** [comment]
actually, i don't know. I wanted to install rasa as a chat assistant on my website via docker. I followed the documentation and it ended up with the error. I tried changing the versions as per some forums but that didn't work.

**Comment by wochinge** [comment]
So you trained it locally and then mounted the model into the docker container?

**Comment by milangm89** [comment]
i didn't do any training.

**Comment by wochinge** [comment]
Ok. So in order to get a chatbot running you have to 
1. Provide training data for Rasa Core ("stories") and NLU 
2. Train the core model
3. Train the nlu model
4. Run NLU
5. Run Core

Maybe this guide https://rasa.com/docs/core/docker_walkthrough/ helps you?

**Comment by milangm89** [comment]
ok thanks 👍 i will check this

**Comment by wochinge** [comment]
@dummybot123 Please ask usage questions in our [forum](https://forum.rasa.com)
