### ISSUE TITLE
Documentation: Step 2 bug: "No module named 'service_identity'"

### ISSUE THREAD

**Issue by mhjb** [RasaHQ/rasa_core#1543]
At https://rasa.com/docs/get_started_step2/

![image](https://user-images.githubusercontent.com/1380991/50803802-232d6600-1350-11e9-93df-bece719a5173.png)

**Comment by mhjb** [comment]
Oops — I hadn't 'run' all the previous numbered steps. It still shows that error, but the training does complete:

![image](https://user-images.githubusercontent.com/1380991/50803916-a949ac80-1350-11e9-9f9a-88b4318281f1.png)

**Comment by akelad** [comment]
cool, will close this issue then

**Comment by mhjb** [comment]
The UserWarning is still a bit of a strange experience to get in a try-me-out environment…

**Comment by JustinaPetr** [comment]
I guess we can update the binder requirements to include it. Getting rid of the warnings is on the line for the quickstart improvements so I'll look into it.

**Comment by smn-snkl** [comment]
@JustinaPetr : Not sure about the "Get Started" flow, but I'm building directly from the 0.13.x branch and still receive the same error. Shouldn't the module also be added to the regular requirements?
