### ISSUE TITLE
How to deploy  Rasa core server on  Cloud  ??

### ISSUE THREAD

**Issue by chetan520** [RasaHQ/rasa_core#1551]
**Rasa Core version**:

**Python version**: 

**Operating system** (windows, osx, ...):

**Issue**:I have followed the basic tutorial and trained my model and hosted it locally (localhost:5005), but now I am hoping to deploy the application on cloud . Is this possible? If so, what is the easiest approach to achieve this?
i want to use my service form other machine .. or rest api

**Content of domain file** (if used & relevant):
```yaml

```

**Comment by akelad** [comment]
Thanks for raising this issue, @EPedrotti  will get back to you about it soon.

**Comment by EPedrotti** [comment]
hi @chetan520,
I think our forum can help. Here a list of topics related to your question [https://forum.rasa.com/search?q=cloud](https://forum.rasa.com/search?q=cloud).
Have a look at them and see if there is something useful for your case.

**Comment by akelad** [comment]
i'll close this then, as it's more of a forum question
