### ISSUE TITLE
[New feature] Try all the NLU predicted intents

### ISSUE THREAD

**Issue by oniz93** [RasaHQ/rasa_core#1561]
I just developed a little change to processor.py
The change is the following:
- user input something
- if the predicted action is "action_default_fallback", try to use the next predicted intent until all the predicted intents are left.

I developed this change because my stories are like a tree so I need to understand which branch of the tree the user want to go even when the best predicted intent isn't in one of possible next stories.

I hope I'm explained well and I can give better informations or examples.

If it's an interesting feature for you, I'll make a pull request :)

**Comment by akelad** [comment]
Hmm, I'm not sure I understand the need for this -- it will fall back on NLU confidence for all those intents since the first intent already trigerred it

**Comment by oniz93** [comment]
I'll try to explain better.

I have a stories like this:

* greetings
- "choose the contest"
* contest_1 (or other blocks with contest_2, contest_3, etc.)
- "tell me you question"
* question_1_about_the_contest (or other blocks with other questions)

If a user, while choosing the contest, write something that is secognized as question, but with less confidence, can even be the sentence that triggers the contest selection, I'll iterate all the prediction until a valid story.
If I finish all the predictions "action_default_fallback" is triggered.

Let me know if I have explained well because english isn't my native language.

**Comment by akelad** [comment]
So this is about the Core confidence, rather than NLU confidence right? I'll discuss this with the team, but i'm not sure whether it makes sense to implement this

**Comment by wochinge** [comment]
So you basically try to force Core to follow a path of your training data, right?
I think there are currently better options to do that
* use the Keras Policy with a featurizer which considers the intent probabilities
* https://rasa.com/docs/core/master/policies/#two-stage-fallback-policy

**Comment by oniz93** [comment]
@wochinge I tried to use Keras Policy but isn't the best option for my case.
Keras policy tries to figure which could be the next action based on the intent probabilites but can't follow a story graph structured like a tree.

Just to do an example, if you see my story above:
- user choose contest 1
(Rasa follow the path "contest 1")
- user say a question included in contest 2 (but with a lower probability can be a question for contest 1)
if I use Keras Policy: Rasa will recognize the intent as a question included in another story and will use that action (with a wrong answare so).
if I don't use Keras Policy: Rasa will throw "fallback" because the most probable intent isn't in the story

That's why I want to iterate the other probable intents.

Two Stage Fallback Policy isn't good for me because I have a really probable intent recognized by NLU (over 0.8 confidence).

**Comment by wochinge** [comment]
I close this due to https://github.com/RasaHQ/rasa_core/pull/1562#issuecomment-456472759. 
Thanks again for the effort you put into the pull request!
