### ISSUE TITLE
FormAction via http

### ISSUE THREAD

**Issue by josephktcheung** [RasaHQ/rasa_core#1564]
I'd like to know if `FormAction` can be implemented via custom http endpoint (non Python).  This question has been asked in the forum a month ago but no answer yet https://forum.rasa.com/t/htttp-custom-action-form/3602. I want to know what needs to be done to enable this feature. Thanks

**Comment by akelad** [comment]
Currently no, you would have to write the code yourself to replicate this behaviour. In the future we'll probably think about implementing the SDK in different languages as well though
