### ISSUE TITLE
Branching logic

### ISSUE THREAD

**Issue by mlennox** [RasaHQ/rasa_core#158]
**Rasa Core version**: 0.7.9

**Python version**: 3.5.2

**Operating system** (windows, osx, ...): osx

**Issue**:
Question - I'd like to be able to create branching logic in a story. 

I would like to have the user choose from a list by sending a message like "use the one named jumper" 

I have written an Action that can do fuzzy matches and disambiguate, as well as decide that there are no matches.

If we need to disambiguate "did you mean juniper?" or ask for input again "nothing matched 'jumper' please try again" I can't figure out a way to get this working with keras policy base story trainging.

In the case of the happy path, all is fine as the next step in the story will be executed as required - ie. _utter_any_help_needed - but this adds spurious messages for non-happy path as the bot will continue on its trained path.

I have tried altering the even stack, and using UserUttered within the Action to see if this will jump the dialog to an error/disambiguation story from the training data

Is this possible and if so what is the correct approach?

Thanks for your time and and otherwise wonderful framework!

**Comment by foxjr** [comment]
Personally, I would try to avoid hacking the state too much through actions, e.g., using UserUttered and BotUttered. My recommendation would be to create more stories that show the flow when there is a match and the flow when there isn't one. Set a `bool` slot through your action; that way, you can show the proper branch in your stories by showing the slot value and then the correct following sequence.

**Comment by mlennox** [comment]
thanks @foxjr I actually got this sorted by exactyl as you say - adding slot states to the story flow. The reason I was having an issue was the docs did not explain this and the code did not illuminate this either. 

I'll be adding to the docs as many others seem to have similar issues.

cheers for the suggestion!

**Comment by tmbo** [comment]
@mlennox that would be awesome :+1:

**Comment by amn41** [comment]
@mlennox this is the place to put it : https://core.rasa.ai/patterns.html#using-slot-values-to-influence-which-actions-are-predicted

**Comment by mlennox** [comment]
Thanks @amn41 I was thinking that alright - but also thought some exposition in the stories section.

**Comment by tmbo** [comment]
Documentation was improved as part of #199.
