### ISSUE TITLE
rasa_core.run --nlu models/current/nlu problem

### ISSUE THREAD

**Issue by alucard001** [RasaHQ/rasa_core#1588]
**Rasa Core version**: 0.12.3

**Python version**: 3.6

**Operating system** (windows, osx, ...): CentOS7

**Issue**:
Here is the command I start RasaCore
`python3.6 -m rasa_core.run --core models/dialogue/ --nlu models/current/nlu/ --port 5001 --log_file log/RasaCore.log --endpoints config/endpoints.yml --enable_api -vv`

when I am using the terminal to test:
```
2019-01-17 16:28:39 INFO     root  - Rasa Core server is up and running on http://localhost:5001
Bot loaded. Type a message and press enter (use '/stop' to exit):
body check
```
Here is what I got:

```
2019-01-17 16:29:00 DEBUG    rasa_core.tracker_store  - Creating a new tracker for id 'default'.
2019-01-17 16:29:00 ERROR    rasa_core.interpreter  - Failed to parse text 'body check' using rasa NLU over http. Error: {
  "error": "No project found with name 'models/current/nlu'."
```

As you can see, Rasa cannot find NLU server and cannot load the NLU model

My endpoints.yml:

```yaml
action_endpoint:
    url: "http://localhost:5055/webhook"

nlu:
    url: "http://localhost:5002"
    token: "my_token"
```
And how I start Action server:

`python3.6 -m rasa_core_sdk.endpoint --port 5055 --cors ["*"] --actions actions.actions`

I have gone through the code, and found that in [interpreter.py](https://github.com/RasaHQ/rasa_core/blob/7853d2cf742ad6d26c725d14c175431855d86ca9/rasa_core/interpreter.py), it will split the string using `name_parts = os.path.split(obj)`.

Since my value is `models/current/nlu/`, I found that the final string will become:

```python
import os
import json

name_parts = os.path.split("models/current/nlu/")
print(name_parts)

# Result in: ('models/current/nlu', '')
```
which seems to be the reason why the server cannot load the model.

Is it true and, how can it be solved?

Thank you.

**Comment by akelad** [comment]
Thanks for raising this issue, @wochinge  will get back to you about it soon.

**Comment by alucard001** [comment]
More info for you:

if I am using the RasaCore CLI to start server, in Rasa NLU server I got below:

`"GET /parse?token=my_token&model=&project=models%2Fcurrent%2Fnlu&q=my+product+1 HTTP/1.1" 404 65 "-" "python-requests/2.20.1"`

As you can see, since the model param is empty, it results in `404 Not Found`.

However, if I am using Postman with this:

`192.168.0.1:5002/parse?token=my_token&model=nlu&project=current&q=my+product+1`

It will successfully return result.

So it is the problem of how to load the model.

Thank you.

**Comment by wochinge** [comment]
Can you try 

`python3.6 -m rasa_core.run --core models/dialogue/ --nlucurrent/nlu/ --port 5001 --log_file log/RasaCore.log --endpoints config/endpoints.yml --enable_api -vv` ?

Also, are you running a separate nlu server or do you want core to run the nlu model?

**Comment by alucard001** [comment]
> Can you try
> 
> `python3.6 -m rasa_core.run --core models/dialogue/ --nlucurrent/nlu/ --port 5001 --log_file log/RasaCore.log --endpoints config/endpoints.yml --enable_api -vv` ?
> 
> Also, are you running a separate nlu server or do you want core to run the nlu model?

Hi @wochinge 

- This command works for me: 
  `python3.6 -m rasa_core.run --core models/dialogue/ --nlu current/nlu --port 5001 --log_file log/RasaCore.log --endpoints config/endpoints.yml --auth_token my_token -vv`
- Also, are you running a separate nlu server or do you want core to run the nlu model?

    I do both.  I have a separated NLU server and would like RasaCore to control NLU.  I guess it is what RasaCore/RasaNLU intented to do, correct?

By the way, if the above command is right, there are 2 big problems: 

-  The description of `-u/--nlu`, which is `nlu model to run`, is ambiguous.  

    Because my model is stored under this directory: `models/current/nlu/*.json, .pkl, .index`.  And when I read `nlu model to run`, I will think that it would point to the model directory.  So I put `models/<my_project_name>/<my_model_name>`, in this case it is `models/current/nlu`.  Buf if I did that, it will not load the model.

    And which means, we have to put all the models under `models` directory.  It cannot be `my_models`, `cust_model_1` or other name, but must be `models`, which is not mentioned in documentation.

- Another problem:  Let's say I am building a NLU model using RasaNLU and I did not define a fixed_model_name, my model name will be like: `model_20190118-174751`. 

    If you use RasaCore to connect to RasaNLU using this model, and with the command:  `-u current` (instead of `current/nlu`, `current` is my project name), the model will not be loaded.  Here is the error: `"No project found with name 'default'."` and here is the command (similar to above, only `-u` is different): ` python3.6 -m rasa_core.run --core models/dialogue/ --nlu current --port 5001 --log_file log/RasaCore.log --endpoints config/endpoints.yml --auth_token my_token -vv`

Can you please help?

Thank you very much.

**Comment by wochinge** [comment]
> The description of -u/--nlu, which is nlu model to run, is ambiguous.

There are two different cases.
1. You are running the NLU model with Rasa Core. In this case you have to point to the exact directory (e.g. `models/current/nlu/`)
2. You are running NLU as server and NLU manages its model on its own. In this case NLU already knows the directory where the NLU model is stored. By running Core with `-u current/nlu` you specify which project and model it should request, when sending the request to Rasa NLU. Maybe this becomes clearer if you check this endpoint of the NLU server: https://rasa.com/docs/nlu/http/#get-status

 > If you use RasaCore to connect to RasaNLU using this model, and with the command: -u current (instead of current/nlu, current is my project name), the model will not be loaded.

Can you try `-u current/` ?
