### ISSUE TITLE
Create a policy that maps an intent to an action

### ISSUE THREAD

**Issue by akelad** [RasaHQ/rasa_core#1596]
The idea is that you'll be able to provide a dictionary of intent/action maps, so that every time one of these intents is identified Rasa Core will directly respond with that action regardless of the context

**Comment by Ghostvv** [comment]
doesn't memo with `max_history=1` is exactly this?

**Comment by Ghostvv** [comment]
it is a bit more than that

**Comment by akelad** [comment]
exactly :P

**Comment by imLew** [comment]
made PR for this #1701
