### ISSUE TITLE
Forks not saved in interactive learning

### ISSUE THREAD

**Issue by smn-snkl** [RasaHQ/rasa_core#1606]
**Rasa Core version**:
0.12.4
**Python version**: 
3.6
**Operating system** (windows, osx, ...):
Ubuntu
**Issue**:
When I run an interactive learning session to train longer stories with different decisions, it would be useful to be able to use the Fork feature to generate different training stories. However, atm only the current / latest fork at the time of the export is stored in the stories.md. All the others are lost.

**Comment by akelad** [comment]
Thanks for raising this issue, @tmbo  will get back to you about it soon.

**Comment by smn-snkl** [comment]
Just confirming this is still happening.

**Comment by akelad** [comment]
@tmbo any ideas what might be going wrong here?

**Comment by tmbo** [comment]
I guess there is a bug in the exporting code of the interactive learning script - def something we need to fix, but I didn't have time to look into it.
