### ISSUE TITLE
Process killed, same place same progress

### ISSUE THREAD

**Issue by macasas** [RasaHQ/rasa_core#1616]
Can anyone tell me what causes visualize to lock up in the same place every time.
Running this on Ubuntu 18
No errors given, here is my terminal

(rasa-demo-py3) dave@yoga-ubuntu:~/chatbots/confessionbot/dev$ make visualize-english
# make run-actions&
python3 -m rasa_core.visualize -s data/en/core/ -d data/en/domain/domain.yml -o story_graph.html
/home/dave/python_envs/rasa-demo-py3/lib/python3.6/site-packages/pykwalify/core.py:99: UnsafeLoaderWarning: 
The default 'Loader' for 'load(stream)' without further arguments can be unsafe.
Use 'load(stream, Loader=ruamel.yaml.Loader)' explicitly if that is OK.
Alternatively include the following in your code:

  import warnings
  warnings.simplefilter('ignore', ruamel.yaml.error.UnsafeLoaderWarning)

In most other cases you should consider using 'safe_load(stream)'
  data = yaml.load(stream)
2019-01-22 10:05:27 INFO     __main__  - Starting to visualize stories...
Processed Story Blocks: 100%|█████████████████████████████████████████████████████████████████████████████████████████████████████████████████| 165/165 [01:32<00:00,  1.78it/s, # trackers=1]
Processed Story Blocks:  66%|███████████████████████████████████████████████████████████████████████▎                                    | 109/165 [06:30<36:07, 38.71s/it, # trackers=578256]Makefile:42: recipe for target 'visualize-english' failed
make: *** [visualize-english] Killed

**Comment by akelad** [comment]
Thanks for raising this issue, @EPedrotti  will get back to you about it soon.

**Comment by EPedrotti** [comment]
hi @macasas , which version of rasa_core are you using?

**Comment by EPedrotti** [comment]
@macasas we are sorry but we could not reproduce this issue. This may be related to the data that you are using. Try to modify your models and see if this goes away or if during training you get any warnings or errors that may not stop the training, but that make the visualize freeze.

**Comment by macasas** [comment]
I found 1 warning about an intent having only 1 utterance, but that doesn't solve the problem

Is it perhaps my system running out of memory, when it gets to 64% the trackers is around 70,000 and then at 66%, the #trackers count jumps to 286408, this seems like a high number, and it then sits at 66% for about 4 minutes before exiting as failed.

I have 7750 action examples, which I think means stories because I don't have any Actions yet.  Some of these are using > Links.  I thought Rasa worked better with more data, perhaps I was wrong.  

Still searching for the answer.

**Comment by EPedrotti** [comment]
@macasas can you share your data?

**Comment by macasas** [comment]
I am not able to share my data on this forum.

I think you might be right, in that I have some how created a Link loop. When I run --debug-plot I get an html file, but every story label is A_Story_called_St.....  so it doesn't actually tell me the name of the story.  I have searched in rasa_core/train.py to see if I can change this label but as yet I have not found where it is being generated.

I will continue to reduce down my conversations until I find a change.  Thanks

**Comment by EPedrotti** [comment]
I am marking this issue as closed. Fell free to reopen if the loop thing does not work.

**Comment by macasas** [comment]
I have not found the actual culprit yet, but having removed the entire conversation except greetings and farewells, the visualisation works.

Can you point me in the right direction to find where the story_blocks_connections.html generator is creating the name A_Story_called_ something because I have searched the entire rasa-core library and cannot find it. If this name was shorter I could then read what it is actually called, a much more useful feature.
