### ISSUE TITLE
Send dictionary through dispatcher in custom action

### ISSUE THREAD

**Issue by FrodeRennemo** [RasaHQ/rasa_core#164]
**Rasa Core version**: 0.7.9

**Python version**: 3.5.3

**Operating system** (windows, osx, ...): Ubuntu

**Issue**: 

We are trying to use Rasa Core as an API using the approach suggested in #119 . I have created a custom action that calls an API and sends the result using `dispatcher.utter_message()`. This is working correctly.

Is there any way that I can send the data through the dispatcher directly without converting this to e.g json string? I've tried using `dispatcher.utter_custom_message()` but this function apparently expects a dictionary of Element objects, which I'm not sure what represent.

**Comment by tmbo** [comment]
No, that is not possible at the moment. You can use `utter_custom_message ` and I think you should be able to pass anything you like in there as long as you define your own implementation for the output channels `send_custom_message` otherwise it will try to access the data as a dict.

**Comment by tmbo** [comment]
Let me know if you have further questions.

**Comment by sandeepsuvit** [comment]
> **Rasa Core version**: 0.7.9
> 
> **Python version**: 3.5.3
> 
> **Operating system** (windows, osx, ...): Ubuntu
> 
> **Issue**:
> 
> We are trying to use Rasa Core as an API using the approach suggested in #119 . I have created a custom action that calls an API and sends the result using `dispatcher.utter_message()`. This is working correctly.
> 
> Is there any way that I can send the data through the dispatcher directly without converting this to e.g json string? I've tried using `dispatcher.utter_custom_message()` but this function apparently expects a dictionary of Element objects, which I'm not sure what represent.

Hi @FrodeRennemo i have tried using `dispatcher.utter_attachment(response)` where `response` would be my api response from an external api. The JSON response would be wrapped under the `attachment` field like so:

```json
[
    {
        "attachment": {
            "type": "success",
            "value": {
                "categories": [],
                "id": 94,
                "joke": "Chuck Norris has the greatest Poker-Face of all time. He won the 1983 World Series of Poker, despite holding only a Joker, a Get out of Jail Free Monopoly card, a 2 of clubs, 7 of spades and a green #4 card from the game UNO."
            }
        },
        "recipient_id": "default"
    }
]
```

Hope this helps :)
Works with the latest version of rasa core 0.13.3
Public api used to fetch random jokes: http://api.icndb.com/jokes/random
