### ISSUE TITLE
Domain directory [Enhancement]

### ISSUE THREAD

**Issue by rgstephens** [RasaHQ/rasa_core#1646]
**Rasa Core version**: 0.12.0

**Enhancement**: For NLU stories and training data, the support of a directory of files is very useful for organizing the bot. Would there be support for  PR to support a directory for domain.yml data? I'm sure this touches many of the core files.

**Comment by akelad** [comment]
@tmbo is this something we're planning on adding?

**Comment by tmbo** [comment]
Yes, this PR https://github.com/RasaHQ/rasa_core/pull/1490 already goes into that direction - not sure we will do it exactly this way though.

**Comment by akelad** [comment]
ok i'll close this issue then
