### ISSUE TITLE
Proper confidence scores for memoization and fallback policies

### ISSUE THREAD

**Issue by tmbo** [RasaHQ/rasa_core#1647]
Suggestion:
we could have `policy.priority` with default values as they are now or smth. `predict` methods will still predict with normal probabilities, but `ensemble` will multiply this probabilities by `policy.priority`

**Comment by tmbo** [comment]
I think we need to discuss, how we do this best, but the policies should not return a probability of 1.1 or 1.2, rather they should all return values between [0, 1]. Maybe we use the order of the policies to define which ones overwrite which other policies? Or is there a case where that would not work? (cc @akelad , @Ghostvv )

**Comment by akelad** [comment]
Does multiplying probablities not still mean we have ridiculous probabilities?

**Comment by Ghostvv** [comment]
I'd say order of the policies is not very reliable thing

multiplying probabilities in ensemble, I think is fine, because after picking them, we renormalize them (we can even simply divide by priority back, because e.g. for `EmbeddingPolicy` renormalization is wrong)

**Comment by akelad** [comment]
hm, why isn't order of policies reliable? yeah but then we're still doing the same thing we were doing before kind of

**Comment by Ghostvv** [comment]
because order of the policies depends on the user, and many of them will not want to know about priorities, but will start to complain why fallback overrides forms

**Comment by Ghostvv** [comment]
but this priorities is essentially specifies the order, we could make them customizable. Multiplication is just one of the ways to implement it

**Comment by Ghostvv** [comment]
no-one, but we anyhow have a lot of parameters, that no one want to customize. About the order in the `policy.yml` file, I think people might randomly throw in policies without thinking

**Comment by erohmensing** [comment]
can we discuss this tomorrow before @tmbo is gone this thurs-fri (right?)

**Comment by akelad** [comment]
@Ghostvv we do that in NLU though and it seems to have worked out fine ;)

**Comment by Ghostvv** [comment]
@akelad  by `that` what do you mean?

**Comment by akelad** [comment]
if you do it in the wrong order, things break

**Comment by Ghostvv** [comment]
ye, but in nlu, the order is quite logical in terms of steps in the pipeline, here these policies are parallel once

**Comment by erohmensing** [comment]
if i were to implement priority as a property of the `Policy` class, what should default values of the other policies that aren't in the `default_config` look like?

I'm thinking of keeping track of the priority separately in `probabilities_using_best_policy()`from the `max_confidence` so that we can compare the priorities if `max_confidence` is the same (i.e. `1.0`)

**Comment by erohmensing** [comment]
Implemented in #1735
