### ISSUE TITLE
Slack button replies aren't processed

### ISSUE THREAD

**Issue by ricwo** [RasaHQ/rasa_core#1671]
button replies in slack trigger a `chat.attachmentAction` but this never arrives at the slack input channel

**Comment by DMPS** [comment]
Here is the forum thread that started this issue: https://forum.rasa.com/t/slack-buttons-fail-silently/4318/7

Here is a PR that someone from the forum submitted to fix the bug: #1710.

Best of luck!

**Comment by EPedrotti** [comment]
There is a PR from one of the users, waiting for him to clean up the code
