### ISSUE TITLE
 how rasa generates a reply message

### ISSUE THREAD

**Issue by guoying1030** [RasaHQ/rasa_core#17]
how rasa generates a reply message？？

the reply message from where??

**Comment by tmbo** [comment]
That depends. If you are using the python code directly, response messages are generated from the utterances that you list in your domain.yml

If you use the http mode, you need to generate the utterances you want to respond to the user yourself.

**Comment by guoying1030** [comment]
@tmbo 

How do I generate training data like babi_task5_trn_rasa_with_slots on my own data set? The The My own data set is composed of many dialogues



franken_data.json and babi_dialog_nlu.json data, how to generate? From rasa_nlu inside generated? Is there a specific tool?

**Comment by tmbo** [comment]
This depends on the format of your existing data. The story format is quite straight forward, user messages followed by the actions the bot should execute.

I can not help you convert your training data to the Rasa Core format.
