### ISSUE TITLE
Issue with Execution of Dialogue_management_model.py file

### ISSUE THREAD

**Issue by serdarbozoglan** [RasaHQ/rasa_core#1708]
**Rasa Core version**:
0.14.2
**Python version**: 
3.6
**Operating system** (windows, osx, ...):
OSX
**Issue**:
The execution of the file yields no response after Epoch training. I have been waiting to get a response but unfortunately, nothing happens in the terminal. What could be the problem

The code is:

```from __future__ import absolute_import
from __future__ import division
from __future__ import unicode_literals
from __future__ import print_function
import logging
from rasa_core.agent import Agent
from rasa_core.channels import(console, InputChannel, BUILTIN_CHANNELS, CmdlineInput)
from rasa_core.interpreter import RegexInterpreter
from rasa_core.policies.keras_policy import KerasPolicy
from rasa_core.policies.memoization import MemoizationPolicy
from rasa_core.policies.fallback import FallbackPolicy
from rasa_core.interpreter import RasaNLUInterpreter
from rasa_core.interpreter import NaturalLanguageInterpreter
#from rasa_core.train import online
from rasa_core.utils import EndpointConfig
import rasa_core
fallback = FallbackPolicy(fallback_action_name="utter_unclear",core_threshold=0.2, nlu_threshold=0.8)
logger = logging.getLogger(__name__)
def train_dialogue(domain_file = 'weather_domain.yml',
                   model_path = './models/dialogue',
                   training_data_file = './data/stories.md'):
    agent = Agent(domain_file, policies=[MemoizationPolicy(max_history=3), KerasPolicy(epochs=50,
                 batch_size=10, validation_split=0.2, augmentation_factor=50), fallback])
    data = agent.load_data(training_data_file)
    agent.train(data)
    agent.persist(model_path)
    return agent

def run_weather_bot(server_forever=True):
    interpreter = RasaNLUInterpreter('./models/nlu/default/myfirstbot')
    agent = Agent.load('./models/dialogue', interpreter=interpreter)
    if server_forever:
        agent.handle_channels([CmdlineInput()])
    return agent
if __name__ == '__main__':
    train_dialogue()   
    run_weather_bot()```
     


**Content of domain file** (if used & relevant):
```yaml
%YAML 1.1
---
actions:
- utter_ask_location
- actions.ActionWeather
- utter_greet
- utter_unclear
- utter_goodbye
entities:
- location
intents:
- greet
- actions.ActionWeather
- inform
- goodbye
slots:
  location:
    type: text
templates:
  utter_ask_location:
  - text: In what location?
  utter_goodbye:
  - text: Talk to you later
  - text: Bye bye:(
  utter_greet:
  - text: Hello! How can I help you?
  utter_unclear:
  - text: I do not know

```

**Comment by akelad** [comment]
Thanks for raising this issue, @erohmensing will get back to you about it soon.

**Comment by erohmensing** [comment]
Hey @serdarbozoglan , would you mind formatting your code with indentation like you did the domain file so I can easily replicate it?

**Comment by serdarbozoglan** [comment]
Hi ma'am, thank you very much for fast response. I updated the code format. Thank you very much

Sincerely,

Serdar

________________________________

**Comment by erohmensing** [comment]
You say it yields no response after epoch training, can you show me all the output you get in the console from when you call the file? (Screenshot or quoted is fine)

**Comment by serdarbozoglan** [comment]
<img width="1298" alt="screen shot 2019-02-13 at 12 16 50 pm" src="https://user-images.githubusercontent.com/36940009/52730506-8e8ad900-2f89-11e9-9d2c-f5385a2a6f43.png">

This is the screenshot. After epoch 50, it does nothing. Thank you

**Comment by erohmensing** [comment]
There seems to be something going wrong in your policies -- you specify 20 epochs for `KerasPolicy` and yet it's still training on 50. Are you currently seeing logger information in your console, for example something like this? : `rasa_core.policies.keras_policy  - Fitting model with 149 total samples and a validation split of 0.2`
If so, if you are not seeing `INFO     rasa_core.policies.keras_policy  - Done fitting keras policy model` then it is definitely getting stuck in the `keras_policy.train()` method.

What version of `rasa_core` are you running? I see you wrote 0.14.2, but I believe that's your `rasa_nlu` version -- the latest version of core is 0.13

**Comment by serdarbozoglan** [comment]
Hi,

my mistake for rasa_core it is 0.13. sorry. in KerasPlociy epoch number is defined as 50 rather than 20. but definitely, I will check the suggestions. Thans

**Comment by erohmensing** [comment]
Did you change the `KerasPolicy` file manually? You should be able to do any configuration you like within your policy declaration, e.g. in this case, within the initialization of your agent where you include the policies you want to use and their parameters.

**Comment by thyravi** [comment]
Hi, I copied the same code from serdarbozoglan and using it for my chatbot. Difference is my rasa_core is 0.12.1 and epochs is 50. It stucks at " UserWarning: Failed to load synonyms file from './models/nlu/default/chandybot\entity_synonyms.json'
  "".format(entity_synonyms_file))". 

![image](https://user-images.githubusercontent.com/37889131/53162552-372edd80-3607-11e9-9e00-6f8187d3267d.png)

I waited for more than 30 mins and I forced stop and got the below error. Could you please advise on it? Thanks.

![image](https://user-images.githubusercontent.com/37889131/53162626-63e2f500-3607-11e9-9d38-619c29f28344.png)

**Comment by erohmensing** [comment]
Hey @thyravi , failing to load the synonyms file is an NLU error. Serdar's `train_online.py` (did you copy from the screenshot or from actual code?) uses an already trained NLU interpreter to train and run a Core agent in interactive mode. Did you train an NLU model before running this code? If not, no model will be saved to your `'./models/nlu/default/chandybot\'` directory, so `'entity_synonyms.json'` won't exist within it.

I would recommend exploring your directories and seeing manually if the file actually exists in the directory it says it's failing to load from. Also, I don't _think_ it's causing the problem, but you might want to make sure to translate the path directories to Windows when copying someone's Unix code (i.e. change `/` to `\` since that's what your machine uses to denote paths, to avoid any problems it could cause.

**Comment by erohmensing** [comment]
@serdarbozoglan my bad -- i realized I was looking at the screenshot (of `train_online.py`) instead of the code you were having trouble running, so that makes sense why KerasPolicy is 50 epochs, not 20.

Do look through your console output from before the epoch training -- there might be useful information there, I think some of your arguments might be being ignored by the model.
