### ISSUE TITLE
Improve (List) Slots

### ISSUE THREAD

**Issue by twerkmeister** [RasaHQ/rasa_core#171]
**Problem**

The list slot type only supports single entities as of now. 
This is also described by #165 and #41

1. What happens is that setting the slot overwrites the value in the given slot. Say we have a sentence like "I want to play badminton on Monday and Friday", then we'll have two slot set events fired. One for Monday and one for Friday. The result is that Monday gets written into the slot first and Friday overwrites it. Thus, only Friday remains as a value.

**Proposed Solutions**
1. We could introduce `value` as a property on a slot and then overwrite the setter/getter in subclasses such as `ListSlot` to append new values. This would allow us to solve the above problem, and multiple entities of the same type would get added to the list. 

2. However, I think we ultimately need more advanced slot manipulation methods. For the list slot these could include: set, reset, append, remove. Imagine the following dialogue as a context:
```
User: I would like to play badminton on Monday and Friday
Bot: Ok, I noted down Monday and Friday, should I book courts for you?
```
* Set Action: (sets the value explicitly)
```
User: Actually, that was wrong, I meant I would like to play Tuesday
Bot: Ok, Tuesday then, should I book it?
```
* Reset: (deletes the value)
```
User: Actually, I cannot make it this week
Bot: Ok, too bad. Is there anything else I can do for you?
```
* Append (add a value)
```
User: I could make Wednesday as well!
Bot: Ok, I got Monday, Wednesday, and Friday then. Is that correct?
```
* Remove (remove a value)
``` 
User: Oh wait, I can't make it Friday!
Bot: Alright, so you want to play on Monday then?
```

We could define specific events for these. They could be triggered based on:
1. intents, for example
* play_badminton (set)
* cancel_play (reset)
* add_days(add)
* remove_days(remove)
AND
2. current state of the list slot 

To use intents the user would need to define which intents connect to which slot manipulation action. This would require additional capabilities for bot the domain yaml and the training data format. 

Any thoughts? @tmbo @amn41

**Comment by twerkmeister** [comment]
I had another thought on this. 

1. It seems to me that the schema I proposed earlier would require broad changes to reliably work. Also, it is rather complicated and error prone. From a user perspective it is probably more important that they understand how to interact with the bot than that the bot is fancy but less predictable.

2. I think slots should be kept mostly for data storage and shouldn't contain too much logic themselves. By internally translating setting the value into append to list, my earlier quick-fix proposal would violate that. I would drop that as well.

3. A better possibly approach would be to change the `slots_for_entities` method of the `Domain` class (https://github.com/RasaHQ/rasa_core/blob/master/rasa_core/domain.py#L329). Right now that methods just sets whatever comes it way to fitting slots. Fitting meaning slots having the same type as the entity. If two slots have the same type, they get the same SetSlot events fired.

    1. We could change it so that it handles list slots separately, accumulating the entities within a single message and setting them as a list. For list slots this would bring the predictability I talked about in point (1). Instead of being able to manipulate the list arbitrarily, the user has to explicitly state all elements. It's less fancy, but pretty fool proof, and the bot users will probably get it and accept such behavior after they use it for the first time.

    2. I wonder if we should pull out the logic in (3.1) and create a SlotHandler component, that handles the setting of slots and that can be overwritten. This would have several benefits. First, it would allow developers to define custom slot setting behavior for their custom slots. Second, it would allow developers to control behavior when there are two slots of the same type.

        1. One of the questions here is, how much information should developers be able to use to write logic for slot setting. Possibilities: 1) the current message, 2) current values of slots, 3) intent stack, 4) action stack, 5) entity stack (recently mentioned entities), and maybe more. While it would be nice to give people freedom, it could also lead to over engineering with rules.

    3. I am uncertain how modifying/customizing slot setting behavior would influence training. To my current understanding, the dialogue training data handles slot setting explicitly, i.e. devs write in the training data when which slot is set. If we have custom slot setting behavior, this could become very error prone. Slot setting behavior should be equivalent during training and inference. Having one manual and one automatic approach (training vs inference) creates lots of room for mistakes. However, the training format could be changed to describe seen entities instead of slot setting.

**Comment by amn41** [comment]
Cool points, let me try to address them. 

In general, I agree that we shouldn't overcomplicate things. Using some custom slots makes sense, but if that becomes your main logic it quickly turns into a mess. Same as how I think about checkpoints in training data. They're useful in small doses, but you can create a big mess if you use them too much. The most general way to handle this is to also use ML for slot tracking, as in [DSTC](http://workshop.colips.org/dstc5/) - although historically a lot of that has dealt with uncertainty & errors in ASR rather than complicated slot ontologies.

so to points 1. 2. - I agree

3.i - what do you mean by "the user has to explicitly state all elements" - can you please give an example?
3.ii - I think this would be overkill for now. 
3. iii - yes I think writing stories explicitly is highly error-prone. I would like to emphasise more in the docs that generating stories interactively is the recommended approach.
