### ISSUE TITLE
while running rasa_core im getting below issue

### ISSUE THREAD

**Issue by lohitk27** [RasaHQ/rasa_core#1716]
Exception: Passing policy configuration parameters to `agent.train(...)` is not supported anymore. Specify parameters directly in the policy configuration instead. More info https://rasa.com/docs/core/migrations.html

Kindly help with above issue @akelad @tmbo .

**Comment by akelad** [comment]
Please fill out the issue template and provide more details, the exception is pretty self explanatory -- what are you passing to agent.train?

**Rasa Core version**:

**Python version**: 

**Operating system** (windows, osx, ...):

**Issue**:



**Content of domain file** (if used & relevant):
```yaml

```

**Comment by lohitk27** [comment]
@akelad  PFB,

rasa-core                          0.13.2
rasa-core-sdk                      0.12.1
rasa-nlu                           0.14.3
Python 3.6.4 ::  Anaconda, Inc.
Operating System : Windows
Issue : while running code I'm gtting follow error
RuntimeError: 'path' must be None or a list, not <class '_frozen_importlib_external._NamespacePath'>

**Comment by akelad** [comment]
Please post your **full** error trace - this is a different error than you posted originally

**Comment by swapbagal1** [comment]
I am facing the same issue while trying to training dialogue management model online for a simple weather chatbot:
**>python train_init.py**
:0: UserWarning: You do not have a working installation of the service_identity module: 'No module named 'service_identity''.  Please install it from <https://pypi.python.org/pypi/service_identity> and make sure all of its dependencies are satisfied.  Without the service_identity module, Twisted can perform only rudimentary TLS client hostname verification.  Many valid certificate/hostname mappings may be rejected.
C:\Users\swapnali_bagal\AppData\Roaming\Python\Python36\site-packages\pykwalify\core.py:99: UnsafeLoaderWarning:
The default 'Loader' for 'load(stream)' without further arguments can be unsafe.
Use 'load(stream, Loader=ruamel.yaml.Loader)' explicitly if that is OK.
Alternatively include the following in your code:

  import warnings
  warnings.simplefilter('ignore', ruamel.yaml.error.UnsafeLoaderWarning)

In most other cases you should consider using 'safe_load(stream)'
  data = yaml.load(stream)
Traceback (most recent call last):
  File "train_init.py", line 25, in <module>
    validation_split = 0.2)
  File "C:\Users\swapnali_bagal\AppData\Roaming\Python\Python36\site-packages\rasa_core\agent.py", line 501, in train
    raise Exception("Passing policy configuration parameters "
Exception: Passing policy configuration parameters to `agent.train(...)` is not supported anymore. Specify parameters directly in the policy configuration instead. More info https://rasa.com/docs/core/migrations.html

**Rasa Core version**:  0.13.2
**Rasa Core sdk version**:  0.12.1
**rasa-nlu:** 0.14.3
**Python version**: python 3.6.3
**Operating system** : windows 10
**Domain File:**
slots:
  location:
    type: text


intents:
 - greet
 - goodbye
 - inform


entities:
 - location

templates:
  utter_greet:
    - 'Hello! How can I help?'
  utter_goodbye:
    - 'Talk to you later.'
    - 'Bye bye :('
  utter_ask_location:
    - 'In what location?'


actions:
 - utter_greet
 - utter_goodbye
 - utter_ask_location
 - actions.ActionWeather

**Comment by swapbagal1** [comment]
@lohitk27 @akelad 
Solved the problem by editing train_init.py as follows:
from __future__ import absolute_import
from __future__ import division
from __future__ import unicode_literals

import logging

from rasa_core.agent import Agent
from rasa_core.policies.keras_policy import KerasPolicy
from rasa_core.policies.memoization import MemoizationPolicy

if __name__ == '__main__':
        logging.basicConfig(level='INFO')

        training_data_file = './data/stories.md'
        model_path = './models/dialogue'

        agent = Agent('my_domain.yml', policies = [MemoizationPolicy(max_history=2), KerasPolicy()])

        data = agent.load_data(training_data_file)
        agent.train(data)
        agent.persist(model_path)
