### ISSUE TITLE
Continue story after story

### ISSUE THREAD

**Issue by bhaskarvarman** [RasaHQ/rasa_core#172]
Rasa Core version: Latest

Python version: 3.6.3

Operating system(windows, osx, ...): Windows

Hello,

I have several stories and bot responds to the intents as long as I do not deviate from the normal stories flow. When the story ends, and I continue to chat with already defined intents, the bot doesn't answer correctly but the questions can be answered using some stateless stories. So how do we continue with another story at the end on one story?

Thanks!

**Comment by tmbo** [comment]
Do you have augmentation enabled when training your dialogue model? (`--augmentation` flag during training)

**Comment by bhaskarvarman** [comment]
Can you please give some more details around --augmentation. I understand that it needs an integer to be passed along but what is its purpose and how to I use it to get better results?

**Comment by bhaskarvarman** [comment]
Is there any documentation that I can refer to?

**Comment by Le-Fix** [comment]
I didn't find any occurence in the docs. (Neither 0.8.2 nor master)
https://core.rasa.ai

**Comment by tmbo** [comment]
I just opened a new issue concerning the documentation of the script parameters. #240
