### ISSUE TITLE
Slot name with "illegal character" should be flagged?

### ISSUE THREAD

**Issue by naoko** [RasaHQ/rasa_core#1720]
**Rasa Core version**:
0.12.1 (but the master has the same issue)

**Python version**: 
3.6.6

**Operating system** (windows, osx, ...):
Linux

**Issue**:
I had slot name with dot e.g. `my_company_name.special_slot`
this works as long as it is not used in a template but because the substitute is done with python built-in `format`, dot notation won't work.

https://github.com/RasaHQ/rasa_core/blob/master/rasa_core/nlg/template.py#L79

I did the easy workaround of removing dot but perhaps either 
(a) allow dot in slot by updating `_fill_template_text` function or 
(b) when domain file is passed, check and see if slot name with invalid python variable name is also used in template. if so error out
Would be helpful

**Comment by akelad** [comment]
Thanks for raising this issue, @wochinge  will get back to you about it soon.

**Comment by wochinge** [comment]
Thanks @naoko , especially for the super detailed description including suggestions for fixes 🚀

**Comment by naoko** [comment]
@wochinge , more than happy to work on but I would like to know which approach rasa team would like to take? should slot name to be restrictive so that it won't process after reading domain file or should the tag replacement be updated?

**Comment by wochinge** [comment]
@naoko Awesome! I discuss it with the team and come back to you :+1:

**Comment by wochinge** [comment]
@naoko Best would probably be to fix the string interpolation as it is described here: https://stackoverflow.com/questions/7934620/python-dots-in-the-name-of-variable-in-a-format-string#comment9695339_7934969 . What do you think?

**Comment by naoko** [comment]
yeah, I agree, I was looking at this earlier myself too. okay, I should be able to find time within a week or two to get this going.

**Comment by wochinge** [comment]
Super nice 🚀 Thanks! Let me know if you have questions
