### ISSUE TITLE
Correcting the intent in interactive learning mode removes additional entity information

### ISSUE THREAD

**Issue by mauricedoepke** [RasaHQ/rasa_core#1728]
**Rasa Core version**: 0.13.2
**Python version**: 3.6.8
**Operating system**: windows

When one corrects the intent in the interactive learning mode, but leaves the entities untouched they get altered.

Look at this example:
`Is the NLU classification for '[Am Mittwoch](time:2019-02-20T00:00:00.000+01:00)' with intent 'choose_appointment'`

The date was recognized by duckling. Without altering the intent the entity would get saved as following in the tracker:

```
"entities": [
            {
              "start": 0,
              "end": 11,
              "text": "Am Mittwoch",
              "value": "2019-02-20T00:00:00.000+01:00",
              "confidence": 1,
              "additional_info": {
                "values": [
                  {
                    "value": "2019-02-20T00:00:00.000+01:00",
                    "grain": "day",
                    "type": "value"
                  },
                  {
                    "value": "2019-02-27T00:00:00.000+01:00",
                    "grain": "day",
                    "type": "value"
                  },
                  {
                    "value": "2019-03-06T00:00:00.000+01:00",
                    "grain": "day",
                    "type": "value"
                  }
                ],
                "value": "2019-02-20T00:00:00.000+01:00",
                "grain": "day",
                "type": "value"
              },
              "entity": "time",
              "extractor": "ner_duckling_http"
            }
          ],
```

After altering the recognized intent, but leaving the entity untouched, it gets reduced to:

```
"entities": [
              {
                "end": 11,
                "entity": "time",
                "start": 0,
                "value": "2019-02-20T00:00:00.000+01:00"
              }
            ],
```

**Comment by akelad** [comment]
Thanks for raising this issue, @wochinge  will get back to you about it soon.

**Comment by wochinge** [comment]
@mauricedoepke You are right. However the additional fields are not considered by Rasa Core anyway, so that isn't a problem. Do you need these fields in the custom actions?

**Comment by mauricedoepke** [comment]
Yes I do. 
I don't think it is a problem that needs to be immediately addressed as it only occurs in this special case. But it would be nice to have this fixed in some future version of the interactive learning mode.
Until then a note in the docs about that would be nice.

**Comment by wochinge** [comment]
@mauricedoepke Labeled it is a bug and we will fix it as soon as possible. Of course, you are also very welcome to tackle the issue yourself 🤖

**Comment by paulaWesselmann** [comment]
@mauricedoepke and @wochinge would the issue be solved if each entity includes a value for which extractor originally detected it or do you need the complete additional information that comes with duckling for example?

**Comment by wochinge** [comment]
@paulaWesselmann So the steps would be
1) Include the extractor field in each entity at NLU
2) Check in interactive mode which extractor was used for the component and only export the ner_crf ones

**Comment by paulaWesselmann** [comment]
Yes and 
3. when correcting entities only overwrite annotation if it's changed.

**Comment by mauricedoepke** [comment]
@paulaWesselmann In my project, I also need all the additional values to be saved into the tracker store.
