### ISSUE TITLE
Rasa Core Training Error

### ISSUE THREAD

**Issue by Rajskc** [RasaHQ/rasa_core#1730]
**Rasa Core version**: 0.11.3

**Python version**: 3.6.4

**Operating system** (windows, osx, ...): windows

**Issue**:  I am getting the following error during training the bot. I haven't used nlg and where can we specify these parameters to the bot. Kindly help me with this. Thanks.

Traceback (most recent call last):
  File "C:\Users\M Phanidhar\Anaconda3\lib\runpy.py", line 193, in _run_module_as_main
    "__main__", mod_spec)
  File "C:\Users\M Phanidhar\Anaconda3\lib\runpy.py", line 85, in _run_code
    exec(code, run_globals)
  File "C:\Users\M Phanidhar\Anaconda3\lib\site-packages\rasa_core\train.py", line 164, in <module>
    endpoints=AvailableEndpoints(),
TypeError: __new__() missing 4 required positional arguments: 'nlg', 'nlu', 'action', and 'model'

**Content of domain file** (if used & relevant):
```yaml

```

**Comment by akelad** [comment]
What command are you using to train the bot?

**Comment by Rajskc** [comment]
Thanks for your reply. Here is the command I am using:

python -m rasa_core.train -d domain.yml -s data/stories.md -o models/dialogue -c config.yml

**Comment by akelad** [comment]
you should pass the endpoints file with `--endpoints endpoints.yml`

**Comment by Rajskc** [comment]
I have included endpoints in my file but still I am getting the same:

Command to train:  python -m rasa_core.train -d lemontree_domain.yml -s data/stories.md -o models/current/dialogue -c config.yml  --endpoints endpoints.yml

Traceback (most recent call last):
  File "C:\Users\M Phanidhar\Anaconda3\lib\runpy.py", line 193, in _run_module_as_main
    "__main__", mod_spec)
  File "C:\Users\M Phanidhar\Anaconda3\lib\runpy.py", line 85, in _run_code
    exec(code, run_globals)
  File "C:\Users\M Phanidhar\Anaconda3\lib\site-packages\rasa_core\train.py", line 164, in <module>
    endpoints=AvailableEndpoints(),
TypeError: __new__() missing 4 required positional arguments: 'nlg', 'nlu', 'action', and 'model'

**Comment by akelad** [comment]
have you modified any code in rasa_core? Because this should not be happening

**Comment by Rajskc** [comment]
I am not really sure, I made few changes but don't remember them specifically. I'll figure it out. Thanks for your reply. We can close this now.

**Comment by akelad** [comment]
cool, will close this then
