### ISSUE TITLE
Interactive Learning: Only include ner_crf entities in nlu export by including the extractor field in each entity at NLU

### ISSUE THREAD

**Issue by wochinge** [RasaHQ/rasa_core#1732]
At the end of interactive learning you can save stories and NLU data which you collected during the training. However, the exported NLU data should only include entity annotation for entities which were 
* extracted by ner_crf
* manually annotated by the user

**Comment by akelad** [comment]
@wochinge we could export the ones recognised by duckling as well, as long as the `extractor` field is correct right?

**Comment by paulaWesselmann** [comment]
@wochinge why should it only include entities extracted by ner_crf and manually annotated? And which other entities does it extract currently?  In my experiments I can only see that it additionally picks up capital spellings of words as synonym of the lower case word and records this in NLU as well.

**Comment by paulaWesselmann** [comment]
#1725

**Comment by paulaWesselmann** [comment]
Ok, got it from #1725

**Comment by wochinge** [comment]
@akelad Why should we also export the things from Duckling? We don't want train ner_crf on it right?

**Comment by akelad** [comment]
well, we won't, if there's an `extractor: ner_duckling` field present, it will skip it. but actually that doesn't work for markdown, only for json :D so yeah better not export it at all

**Comment by wochinge** [comment]
Good hint! I am a post-json Rasa user so I have no idea what's included in the json format :-D

**Comment by akelad** [comment]
the rasa nlu json format actually does still exist :D
