### ISSUE TITLE
ImportError: cannot import name 'Layer'

### ISSUE THREAD

**Issue by GavinMoreYoung** [RasaHQ/rasa_core#1736]
**Rasa Core version**:0.13.2

**Python version**: python3.6.8

**Operating system** (windows, osx, ...):win10

**Issue**:
Traceback (most recent call last):
  File "C:/Users/Admin/Desktop/building-chatbots-with-python-master/Chapter IV/Chapter IV Code horoscope_bot/horoscope_bot/train_initialize.py", line 27, in <module>
    validation_split=0.2
  File "D:\Python\lib\site-packages\rasa_core\agent.py", line 520, in train
    **kwargs)
  File "D:\Python\lib\site-packages\rasa_core\policies\ensemble.py", line 63, in train
    policy.train(training_trackers, domain, **kwargs)
  File "D:\Python\lib\site-packages\rasa_core\policies\keras_policy.py", line 162, in train
    shuffled_y.shape[1:])
  File "D:\Python\lib\site-packages\rasa_core\policies\keras_policy.py", line 93, in model_architecture
    from tensorflow.keras.models import Sequential
  File "D:\Python\lib\site-packages\tensorflow\keras\__init__.py", line 20, in <module>
    from . import layers
  File "D:\Python\lib\site-packages\tensorflow\keras\layers\__init__.py", line 8, in <module>
    from tensorflow.python.estimator.keras import Layer
ImportError: cannot import name 'Layer'

I am a beginner,this problem gets me,i do not know how to do ,i hope you can help me,thanks. 

**Content of domain file** (if used & relevant):
```yaml

```

**Comment by GavinMoreYoung** [comment]
this is study code:
from __future__ import absolute_import
from __future__ import division
from __future__ import print_function
from __future__ import unicode_literals

from rasa_core import utils
from rasa_core.agent import Agent
from rasa_core.policies.keras_policy import KerasPolicy
from rasa_core.policies.memoization import MemoizationPolicy

if __name__ == '__main__':
    utils.configure_colored_logging(loglevel="DEBUG")

    training_data_file = './data/stories.md'
    model_path = './models/dialogue'

    agent = Agent("horoscope_domain.yml",
                  policies=[MemoizationPolicy(max_history = 2), KerasPolicy()])

    training_data = agent.load_data(training_data_file)

    agent.train(
            training_data,
            augmentation_factor=50,
            # epochs=500,
            # batch_size=10,
            validation_split=0.2
    )

    agent.persist(model_path)

**Comment by akelad** [comment]
Thanks for raising this issue, @Ghostvv  will get back to you about it soon.

**Comment by Ghostvv** [comment]
what version of tensorflow is installed?
Can you try,
> from tensorflow.keras.layers import Layer

**Comment by GavinMoreYoung** [comment]
> 是什么版本的tensorflow安装？
> 你能试一下吗，
> 
> > 来自tensorflow.keras.layers导入图层



> what version of tensorflow is installed?
> Can you try,
> 
> > from tensorflow.keras.layers import Layer

tensorboard         1.12.2
tensorflow          1.12.0

**Comment by Ghostvv** [comment]
`from tensorflow.keras.layers import Layer` does it work?

**Comment by GavinMoreYoung** [comment]
> `from tensorflow.keras.layers import Layer` 它有用吗？

this does not work .
this is pip list display:
absl-py             0.7.0
APScheduler         3.5.3
asn1crypto          0.24.0
astor               0.7.1
attrs               18.2.0
Automat             0.7.0
boto3               1.9.97
botocore            1.12.97
certifi             2018.11.29
cffi                1.12.1
chardet             3.0.4
Click               7.0
cloudpickle         0.6.1
colorama            0.4.1
colorclass          2.2.0
coloredlogs         10.0
colorhash           1.0.2
ConfigArgParse      0.13.0
constantly          15.1.0
cryptography        2.5
cycler              0.10.0
decorator           4.3.2
Django              2.1.7
docopt              0.6.2
docutils            0.14
fakeredis           0.10.3
fbmessenger         5.4.0
Flask               1.0.2
Flask-Cors          3.0.7
Flask-JWT-Simple    0.0.3
future              0.17.1
gast                0.2.2
gevent              1.4.0
greenlet            0.4.15
grpcio              1.18.0
h5py                2.9.0
humanfriendly       4.17
hyperlink           18.0.0
idna                2.8
incremental         17.5.0
itsdangerous        1.1.0
Jinja2              2.10
jmespath            0.9.3
jsonpickle          1.1
jsonschema          2.6.0
Keras-Applications  1.0.6
Keras-Preprocessing 1.0.5
kiwisolver          1.0.1
klein               17.10.0
Markdown            3.0.1
MarkupSafe          1.1.0
matplotlib          2.2.3
mattermostwrapper   2.1
networkx            2.2
numpy               1.16.1
packaging           18.0
pika                0.12.0
pip                 19.0.2
prompt-toolkit      2.0.8
protobuf            3.6.1
pycparser           2.19
pydot               1.4.1
PyHamcrest          1.9.0
PyJWT               1.7.1
pykwalify           1.7.0
pymongo             3.7.2
pyparsing           2.3.1
pyreadline          2.1
PySocks             1.6.8
python-dateutil     2.8.0
python-engineio     3.4.1
python-socketio     3.1.2
python-telegram-bot 11.1.0
pytz                2018.9
PyYAML              3.13
questionary         1.0.2
rasa-core           0.13.2
rasa-core-sdk       0.12.2
rasa-nlu            0.14.3
redis               2.10.6
requests            2.21.0
requests-toolbelt   0.9.1
rocketchat-API      0.6.26
ruamel.yaml         0.15.88
s3transfer          0.2.0
scikit-learn        0.20.2
scipy               1.2.1
setuptools          40.6.2
simplejson          3.16.0
six                 1.12.0
slackclient         1.3.0
tensorboard         1.12.2
tensorflow          1.12.0
termcolor           1.1.0
terminaltables      3.1.0
tqdm                4.31.1
twilio              6.24.1
Twisted             18.9.0
typing              3.6.6
tzlocal             1.5.1
urllib3             1.24.1
wcwidth             0.1.7
webexteamssdk       1.1.1
websocket-client    0.54.0
Werkzeug            0.14.1
wheel               0.33.0
zope.interface      4.6.0

**Comment by Ghostvv** [comment]
This is the issue with your tensorflow. I think there is something wrong with your tensorflow installatio, otherwise you should try tensorflow forum

**Comment by GavinMoreYoung** [comment]
> 这是你的张量流的问题。我认为你的tensorflow安装有问题，否则你应该试试tensorflow论坛

thanks for your reply and help.

**Comment by Ghostvv** [comment]
I'm sorry, I checked locally I have tensorflow 1.12.0, and from tensorflow.keras.layers import Layer works for me. Unfortunately, I cannot do anything more here

**Comment by Ghostvv** [comment]
try looking here: https://github.com/tensorflow/tensorflow/issues/24847

**Comment by GavinMoreYoung** [comment]
> try looking here: [tensorflow/tensorflow#24847](https://github.com/tensorflow/tensorflow/issues/24847)

i will try this way,thank you very much.
