### ISSUE TITLE
ImportError: No module named 'engineio.async_tornado'

### ISSUE THREAD

**Issue by V-I-C-T-O-R** [RasaHQ/rasa_core#1742]
**Rasa Core version**:
rasa core github code
**Python version**: 
3.5
**Operating system** (windows, osx, ...):
linux
**Issue**:
when i want to train core dialog, throw a error :
```
ImportError: No module named 'engineio.async_tornado'
```
please help me ,thanks

**Comment by akelad** [comment]
@V-I-C-T-O-R which version of rasa core are you using? because this shouldn't happen in master, and it was fixed in the 0.12.4 release
