### ISSUE TITLE
Exception in Fallback Policy if intent is None

### ISSUE THREAD

**Issue by JanThiel** [RasaHQ/rasa_core#1748]
**Rasa Core version**:
0.13.20

**Python version**: 
Python 3.6.8

**Operating system** (windows, osx, ...):
Win 10

**Issue**:
https://github.com/RasaHQ/rasa_core/blob/master/rasa_core/policies/fallback.py#L97
```
  File "...Python36\lib\site-packages\rasa_core\policies\fallback.py", line 97, in predict_action_probabilities
    nlu_confidence = nlu_data["intent"].get("confidence", 1.0)
AttributeError: 'NoneType' object has no attribute 'get'
```

if ```nlu_data["intent"]``` is None, an exception will be thrown. As this is a default policy, it should be robust enough to fail gracely or do something proper instead of failing at all.

We ran in this case with an untrained NLU model for a simple input like a postal code. Anyway, an exception is a quite harsh way to terminate and wasn't what we expected :-)

**Comment by akelad** [comment]
Thanks for raising this issue, very good point! Would you be willing to submit a PR for this?

**Comment by JanThiel** [comment]
@akelad 
Willingly: Yes
Capable: At the moment: Nope

I haven't had the time to dive deeper into your default policies. This would be the basic requirement to determine what an appropriate action would be in this case. For now I could only provide a try/catch which would be quite ... stupid ... If someone knows your policies better, he or she might be more capable of "fixing" this to deliver a "smart" fail.
I would come back to this when I had the chance to get back to this within our project. But this could take some time...

**Comment by akelad** [comment]
@JanThiel alright thanks for your input regardless! If you do have some spare time, of course go for it :D Otherwise we/someone else will take care of it
