### ISSUE TITLE
Circuit breaker tripped. Stopped predicting more actions for sender 'Visitor-40'

### ISSUE THREAD

**Issue by azizullah2017** [RasaHQ/rasa_core#1759]
**Rasa Core version**:

**Python version**: 

**Operating system** (windows, osx, ...):

**Issue**: I cannot jump over the forms. I CAN only run one form.

example: 
User :I want to buy a ticket 
Bot: May I know the data ? 
User: I have changed my mind. I want to order a pizza. 
Bot: My I know the address.

I cannot do this. I facing these error.
```
Circuit breaker tripped. Stopped predicting more actions for sender 'Visitor-40'
```
My story:
```
## story 1
* ticket
  - ticket_form
    - form{"name": "ticket_form"}
    - form{"name": null}

## story 2
* Order
  - order_form
    - form{"name": "order_form"}
    - form{"name": null}
```

**Comment by akelad** [comment]
Please ask these kind of questions in our [forum](https://forum.rasa.com)

**Comment by azizullah2017** [comment]
I have already that. But I did not any response from anyone.
Rasa form stop when there is two or more then that.
https://forum.rasa.com/t/can-i-jump-between-forms-can-i-used-more-then-one-form/5495

**Comment by akelad** [comment]
we'll get back to you on there
