### ISSUE TITLE
Script hanging after python bot.py run

### ISSUE THREAD

**Issue by arshidkv12** [RasaHQ/rasa_core#176]
**Rasa Core version**: current version

**Python version**: 2.7

**Operating system** : Ubuntu 16.10

**Issue**:
I downloaded **restaurantbot** then I run `python bot.py train-nlu` and `python bot.py train-dialogue` 
after I run `python bot.py run` but script giving warning and after input nothing working. 
/home/arshid/.local/lib/python2.7/site-packages/h5py/__init__.py:36: FutureWarning: Conversion of the second argument of issubdtype from `float` to `np.floating` is deprecated. In future, it will be treated as `np.float64 == np.dtype(float).type`.
  from ._conv import register_converters as _register_converters
Using TensorFlow backend.
2018-01-16 17:13:54.468177: I tensorflow/core/platform/cpu_feature_guard.cc:137] Your CPU supports instructions that this TensorFlow binary was not compiled to use: SSE4.1 SSE4.2 AVX
Bot loaded. Type a message and press enter : 
hi

**Content of domain file** (if used & relevant):
```yaml

```

**Comment by sekhar14** [comment]
having same issue

**Comment by daysm** [comment]
@sekhar14 I have the same problem as @arshidkv12. Couldn't figure out how to fix it yet. Does this mean I have to change the format of the training data? 

I'm using the following versions:
rasa-core==0.7.9
rasa-nlu==0.10.6

**Comment by tmbo** [comment]
You just need to make sure you use the right training data for the right version: you can not use data from the new format (where user intents are written without a `_` prefix, so just `hello`) and train it in an older version. The other way around works. 

@daysm can you post the training data you used?

**Comment by daysm** [comment]
@tmbo I'm using the data provided in the restaurantbot example: https://github.com/RasaHQ/rasa_core/tree/master/examples/restaurantbot

So it should work, right?

**Comment by tmbo** [comment]
I mean if you have installed the version from pip, you should also use the example code that belongs to that version: https://github.com/RasaHQ/rasa_core/tree/0.7.9

**Comment by engelmav** [comment]
@tmbo I'm not sure I follow.

Here's what I've got:

```
>>> import rasa_core
>>> rasa_core.__version__
u'0.7.9'
```
Just hopped on branch 0.7.x to ensure I'm using compatible training data:
```
λ git status
HEAD detached at origin/0.7.x
nothing to commit, working directory clean
~/rasa_core/examples/restaurantbot/data (detached*)
```
I double-checked the training data and see intents written _with_ the `_` underscore. Sample:
```
## story_00914561
* _greet[]
 - utter_ask_howcanhelp
* _inform[cuisine=italian]
 - utter_on_it
```
But I still get this:
```
>>> agent.handle_message(("_greet"))
[]```

**Comment by engelmav** [comment]
The respones `[]` is coming from `action_listen`.

In debugging, I see `greet` with highest confidence. `MessageProcessor` finds the highest probability at index 0. It looks up the action at index 0 and finds `action_listen`, whose `run` method is then executed resulting in `[]` being printed to the screen.

It looks to me like the probabilities are too low. The highest we get from both policies in the Supervised Learning tutorial is `0.11995545774698257`. I'll hazard a guess that that defaults to "I don't know", hence `action_listen`.

**Comment by tmbo** [comment]
We have just recently updated that example, thanks to @Ghostvv

**Comment by tmbo** [comment]
I will close this, as this is an issue with the training data which has been fixed in the example that is part of the docs.

To get more insights into what the bot is doing when running it on the command line, append `--debug` when running it to get more outputs.
