### ISSUE TITLE
ModuleNotFound : rasa-core

### ISSUE THREAD

**Issue by MaulishShah** [RasaHQ/rasa_core#1770]
**Rasa Core version**: 0.13.2

**Python version**:  3.6.5

**Operating system** (windows, osx, ...): ubuntu

**Issue**:ModuleNotFound : rasa-core. I already installed the rasa-core but it not show while importing it.

**Comment by akelad** [comment]
Thanks for raising this issue, @wochinge  will get back to you about it soon.

**Comment by wochinge** [comment]
@MaulishShah Can you try to do:
```python
import rasa_core
```

Did this help?
