### ISSUE TITLE
Action in Reminder runs but message is not displayed on command line

### ISSUE THREAD

**Issue by kirtisynap19** [RasaHQ/rasa_core#1773]
Hi 
I am facing an issue where the scheduler (reminder scheduled) job starts and action runs, but the message is only visible in logs and not on command line. 

I have upgraded to latest version of Rasa Core: 
rasa_core==0.13.2 
rasa_core_sdk==0.12.2
rasa_nlu==0.14.4
Python==3.6.5
OS: Mac OSX

Here is the screen shot of logs for your reference: 
<img width="752" alt="screen shot 2019-03-01 at 4 34 56 pm" src="https://user-images.githubusercontent.com/47797273/53674083-687b5f00-3c40-11e9-8293-40dddea5f11e.png">

Please let me know, if you any other details to resolve this.

**Comment by akelad** [comment]
Thanks for raising this issue, @Ghostvv  will get back to you about it soon.

**Comment by Ghostvv** [comment]
It is duplicate issue, please see: https://github.com/RasaHQ/rasa_core/issues/886

**Comment by kirtisynap19** [comment]
Hi @Ghostvv, I want to reopen the issue because of the following problem.
I tried to do put the print statements as suggested in #886, but the problem is that it prints on the command line and goes to 'action_listen'. However, as part of my story, I expect to trigger another action after this action is complete, but that never happens. I am attaching the screenshot of my logs: 
![image](https://user-images.githubusercontent.com/47797273/53755407-50d3ee80-3e6b-11e9-87e3-201ce9c8f4c8.png)

 I am also attaching the story:
```
## story02 
  - action_bedtime_reminder
  - slot{"sleepQualityRating" : null}
  - slot{"refreshQualityRating" : null}
  - slot{"nightType": null}
  - action_trigger_query_sleep_api
```
So, after the bedtime reminder action is ran and message is printed on command line (using print statements), it goes to 'action_listen'. I expect it to trigger action 'action_trigger_query_sleep_api'.

**Comment by Ghostvv** [comment]
this is another issue, regarding policy prediction.
In your case `story02` doesn't correspond to the tracker state as can be seen from the logs up there. I recommend using augmented memoization policy

**Comment by kirtisynap19** [comment]
@Ghostvv thanks for the solution. It works fine :)
