### ISSUE TITLE
TensorFlow Issues with RASA Core on centos 7 

### ISSUE THREAD

**Issue by saurabhaec** [RasaHQ/rasa_core#1789]
**python -m rasa_nlu.train -c nlu_config.yml --data data/nlu_data.md -o models --fixed_model_name nlu --project current --verbose**

Output 
Illegal instruction 

rasa_core~=0.12.0
tensorflow=1.10.0

**Python version**: 
Python 3.6.7

CPU  Details:
 
vendor_id       : AuthenticAMD
model name      : AMD Opteron(tm) Processor 6128 HE
flags           : fpu vme de pse tsc msr pae mce cx8 apic sep mtrr pge mca cmov pat pse36 clflush mmx fxsr sse sse2 syscall nx mmxext fxsr_opt rdtscp lm 3dnowext 3dnow constant_tsc rep_good nopl tsc_reliable nonstop_tsc pni cx16 popcnt hypervisor lahf_lm extapic abm sse4a misalignsse 3dnowprefetch osvw
address sizes   : 40 bits physical, 48 bits virtual

**Operating system** (windows, osx, ...):
Centos 7 

**Issue**:

Installation was perfect  but Getting an error while traning data 

after changing version on tensorflow to 1.12 then

getting another  error 

 F tensorflow/core/platform/cpu_feature_guard.cc:37] The TensorFlow library was compiled to use SSE4.1 instructions, but these aren't available on your machine.

**Content of domain file** (if used & relevant):
```yaml

```

**Comment by akelad** [comment]
@saurabhaec that warning about `TensorFlow library was compiled to use SSE4.1 instructions, but these aren't available on your machine` is just a warning I think? not an actual error? how much RAM does your machine have?

**Comment by saurabhaec** [comment]
but after that script was Aborted.

2019-03-06 15:57:29.566451: F tensorflow/core/platform/cpu_feature_guard.cc:37] The TensorFlow library was compiled to use SSE4.1 instructions, but these aren't available on your machine.
Aborted


RAM :  4 GB

**Comment by akelad** [comment]
how much data are you training with? It's entirely possible that you don't have enough RAM

**Comment by saurabhaec** [comment]
I think my CPU does not  have SSE4.1 instructions

Total No of training  less than 500 Question

**Comment by JoeDumoulin** [comment]
This is a tensorflow issue.  Check out the correct answer here:
https://stackoverflow.com/questions/53950186/tensorflow-library-was-compiled-to-use-sse4-1-instructions-but-these-arent-ava

A few options are outlined in this case, but they amount to (paraphrasing) "use a different machine with compatibility."

**Comment by akelad** [comment]
given this seems to be a tensorflow issue, i will close this issue. If you're having problems with it, please open an issue on their repo
