### ISSUE TITLE
Feature Request - Add Support for headers/basic auth to RemoteEndpoint

### ISSUE THREAD

**Issue by khilnani** [RasaHQ/rasa_core#1796]
Currently, for action endpoints only a url can be specified. I would like to be able to configure headers, and/or basic auth to enhance security. 

In most production cases, the actions endpoint would not be running on the same server or cluster of runtimes as the Core for scaling reasons. In this case, we should have the option to not have the endpoints be open even on an internal network. This would also support writing remote actions without using the Rasa SDK akin to Google Filfillments.

Would like to request support to specify headers and/or basic auth credentials in the endpoints.yml which a proxy/api gateway could validate.

**Comment by akelad** [comment]
Thanks for raising this issue, @wochinge  will get back to you about it soon.

**Comment by wochinge** [comment]
@khilnani This is actually already possible: https://github.com/RasaHQ/rasa_core/blob/7377440ac3e2669c65b8220dbd7b8c7cce9798b6/rasa_core/utils.py#L647

The thing is that rasa_core_sdk does not support that yet. So might make sense to create an issue at the sdk repository. Would you fancy implementing it?

**Comment by wochinge** [comment]
I close this here, but feel free to comment in the linked issue 🚀

**Comment by khilnani** [comment]
Thanks

**Comment by khilnani** [comment]
Thanks, will comment there @wochinge
