### ISSUE TITLE
Not able to train the interactive file.

### ISSUE THREAD

**Issue by Nikhileshorg** [RasaHQ/rasa_core#1798]
**Rasa Core version**: 0.14.0a1

**Python version**: python 3.6

**Issue**:  Exception: Passing policy configuration parameters to `agent.train(...)` is not supported anymore. Specify parameters directly in the policy configuration instead.

I tried passing directly in the policy configuration but it is throwing me an error. 

The content of the file : 

______________________________________________________________________________________

from __future__ import absolute_import
from __future__ import division
from __future__ import unicode_literals

import logging

from rasa_core.agent import Agent
from rasa_core.policies.keras_policy import KerasPolicy
from rasa_core.policies.memoization import MemoizationPolicy

if __name__ =='__main__':
    logging.basicConfig(level='INFO')
	
    training_data_file = './data/stories.md'
    model_path = './models/dialouge'

    agent = Agent('weather_domain.yml', policies = [MemoizationPolicy(), KerasPolicy()])

    agent.train(
	        training_data_file,
			augmentation_factor = 50,
			max_history = 2,
			epochs = 500,
			batch_size = 10,
			validation_split = 0.2)
			
    agent.persist(model_path) 

_____________________________________________________________________________________

Getting this error instead, 

Exception: Passing policy configuration parameters to `agent.train(...)` is not supported anymore. Specify parameters directly in the policy configuration instead.

can you please help me to train the interactive file.

Thanks in advance.
Sai

**Comment by akelad** [comment]
`Passing policy configuration parameters to agent.train(...) is not supported anymore` -- this is your answer. So basically all those configs (apart from augmentation_factor), should go either in the individual policies, or you can specify them in the policy configuration yaml file
