### ISSUE TITLE
Rasa Core logs not being generated

### ISSUE THREAD

**Issue by scevola44** [RasaHQ/rasa_core#180]
**Rasa Core version**: 0.7.6

**Python version**: 3.5

**Operating system** (windows, osx, ...): CentOS 7 - 64 bit

**Issue**: Rasa Core doesn't seem to save its logs when run locally. I know Rasa NLU (I'm using **version 0.10.4** if relevant) only saves them when run as a server, but can't find `rasa_core.log` anywhere. Log levels are all set to DEBUG (changing to INFO doesn't give different results).
Is this expected behavior or a bug?

**Comment by tmbo** [comment]
What command are you using to run the Rasa Core server?

**Comment by tmbo** [comment]
you need to pass `--log_file` to the Rasa Core server when running it, if the argument is not passed the log is stored in `rasa_core.log` in the working directory. 

I just checked, and the log got created. I'll close this, let me know if there is anything else I can do to reproduce this.
