### ISSUE TITLE
No matching distribution found for tensorflow~=1.12.0 (from rasa_core) 

### ISSUE THREAD

**Issue by elygod** [RasaHQ/rasa_core#1811]
**Rasa Core version**: pip install rasa_core

**Python version**: 3.6

**Operating system** (windows, osx, ...): windows 10

**Issue**:
I keep getting this tensorflow error ;
```
Collecting rasa_core
  Using cached https://files.pythonhosted.org/packages/3e/6a/f2c4e8ae1903805324267e915a167ded91a439bafd09efa6da0a2a50e409/rasa_core-0.13.3-py3-none-any.whl
Collecting rocketchat-API~=0.6.0 (from rasa_core)
  Using cached https://files.pythonhosted.org/packages/5f/c0/117b97e5b4e057808b4db1dda3bfb9aef46e502b7f8107bc8e33d2df7ee9/rocketchat_API-0.6.27-py3-none-any.whl
Requirement already satisfied: ruamel.yaml~=0.15.0 in c:\users\asus\islemenv\lib\site-packages (from rasa_core) (0.15.37)
Collecting tensorflow~=1.12.0 (from rasa_core)
  Could not find a version that satisfies the requirement tensorflow~=1.12.0 (from rasa_core) (from versions: )
No matching distribution found for tensorflow~=1.12.0 (from rasa_core)
```
 I already tried this but still didn't work
```
 python -m pip install --upgrade 
https://storage.googleapis.com/tensorflow/mac/cpu/tensorflow-1.12.0-py3-none-any.whl

```
**EDIT**:  I solved this by installing an older version of rasa-core with tensorflow 1.10.0 ; then upgraded both ; dunno how it worked but it did

**Comment by akelad** [comment]
strange, tensorflow 1.12 definitely exists. Potentially a windows related problem. In any case, sounds like your issue is solved so I will close

**Comment by ProdigiosaLadybug** [comment]
Hi! I have the same problem. Could you text the commands you use to solve the problem?
Thanks

**Comment by hinca** [comment]
Also affects me when running `pip install -U rasa_core`.

**Comment by paxinos** [comment]
count me in as well...  on ubuntu 16.04.     I installed just fine a couple weeks ago on a different server.
