### ISSUE TITLE
How to get the JSON of the button payloads in Rasa and display them on the User Interface

### ISSUE THREAD

**Issue by NomanSaleem4** [RasaHQ/rasa_core#1844]
**Rasa Core version**: 0.12.3

**Python version**: 3.6.7

**Operating system** : Ubuntu

**Issue**: My button payloads are working fine in the command line, but on the user interface button are not displayed and i type the payload but it does not work. So my question is that how can we first get the JSON of the button payloads and then how can we show them on the interface?. Help would  be much appreciated. Thanks.

**Comment by akelad** [comment]
Which interface are you using?

**Comment by NomanSaleem4** [comment]
Django

**Comment by NomanSaleem4** [comment]
any solution?

**Comment by akelad** [comment]
Ok I think you have to handle the buttons case for your custom UI then, there's not much we can do here since it seems to be a custom UI implementation :)
