### ISSUE TITLE
Slack connector to integrate with Rasa Core

### ISSUE THREAD

**Issue by rajivmca2004** [RasaHQ/rasa_core#19]
Need Slack connector in main repo to integrate with Rasa Core

**Comment by tmbo** [comment]
@rajivmca2004 I guess that would be a great contribution. I guess the API is quite similar to the one for facebook, so that would be a good starting point https://github.com/RasaHQ/rasa_core/blob/master/rasa_core/channels/facebook.py

**Comment by tmbo** [comment]
@rajivmca2004 any chance you created that connector?
