### ISSUE TITLE
 utils.configure_colored_logging(loglevel="DEBUG") AttributeError: module 'rasa_core.utils' has no attribute 'configure_colored_logging'

### ISSUE THREAD

**Issue by 12max34** [RasaHQ/rasa_core#192]
**Rasa Core version**: rasa-core (0.7.9)

**Python version**: Python 3.5.4 :: Anaconda, Inc.

**Operating system** (windows, osx, ...): ubuntu

**Issue**:
File "bot.py", line 105, in <module>     utils.configure_colored_logging(loglevel="DEBUG") AttributeError: module 'rasa_core.utils' has no attribute 'configure_colored_logging'

**Content of domain file** (if used & relevant):
```yaml

```
The contents of bot.py is same as restaurant bot.py file in examples

**Comment by foxjr** [comment]
`configure_colored_logging` became a part of rasa_core.utils after 0.7.9. Perhaps you're using different versions of bot.py and rasa_core. Either downgrade your bot.py to reflect the version of rasa_core you're using, or upgrade rasa_core to reflect your bot.py version.
