### ISSUE TITLE
Improve Common Pattern docs

### ISSUE THREAD

**Issue by mlennox** [RasaHQ/rasa_core#196]
The docs do not properly explain how to use slots or conditional checkpoints to influence how Rasa Core predicts the next action to take.

I will add:

- slots
  - influence on story training
  - use in Actions
  - example snippets
- conditional checkpoints
  - explain
  - examples

**Comment by mlennox** [comment]
I've fleshed out an explanation of the use of `Slots` and how features matter here, comments welcome

https://github.com/mlennox/rasa_core/blob/storydocs/docs/patterns.rst 

I'll add some docs on Conditional Checkpoints (are Story Cycles an extension of Conditional Checkpoints?)

**Comment by tmbo** [comment]
Great idea! Do you mind creating a PR, its easier to take a look at the changes - even if you are not done yet

**Comment by Le-Fix** [comment]
Any news about improving the documentation about checkpoints?
I only found https://core.rasa.ai/master/stories.html which shortly explaines them.
None of the existing examples https://github.com/RasaHQ/rasa_core/tree/master/examples use checkpoints.

**Comment by amn41** [comment]
yes @Le-Fix that is intentional. checkpoints can be misused easily so we don't encourage their use right now. If you are interested, please experiment with them and give us your feedback.

**Comment by Le-Fix** [comment]
@amn41 That makes sense however exactly this short information should be appended to the docs. (v0.7.9 and later)

**Comment by Le-Fix** [comment]
Not sure if the [author](https://hackernoon.com/@LawnboyMax) is affiliated with RASA.
Could be interesting for anyone who's working on this issue
https://hackernoon.com/building-a-chatbot-using-rasa-stack-intro-and-tips-c6d1057d8536

**Comment by tmbo** [comment]
Interesting, thanks for sharing that :+1:

**Comment by tmbo** [comment]
I will close this issue, because the initial goal of this issue is resolved with the merged PR from @mlennox :rocket:
