### ISSUE TITLE
In response to a user's input action_listen is chosen without any notification of a user

### ISSUE THREAD

**Issue by Ghostvv** [RasaHQ/rasa_core#201]
**Rasa Core version**:
`master`
**Python version**: 
`3.6.1`
**Operating system** (windows, osx, ...):
`osx`
**Issue**:

In response to a user's input, when the bot doesn't know which action to pick, action_listen is chosen without any notification of a user, just nothing happens. For a user a bot looks frozen or bugged, because additional user input often doesn't change anything.

Some notification or warning should be added if a bot chooses action_listen in response to a user input. However, it might be tricky because there may be some user inputs that require action_listen as a response.

**Comment by 12max34** [comment]
I am getting the same action being predicted reputedly, if the author can tell me how much trainig data is required to get good predictions.
Also is there any way to train custom policies as for the remote bot example?

**Comment by engelmav** [comment]
I'm facing this here as well - https://github.com/RasaHQ/rasa_core/issues/176

There are two points brought up in this ticket:
1) should an action_listen be more verbose? (I bet we can just subclass or re-define it or something)
2) why are we hitting action_listen for any given input (this is what I encounter in the Supervised Learning tutorial)

**Comment by Le-Fix** [comment]
Imo having a "Default Fallback" aka "Out of Scope" action/intent #137 which of course would be more verbose than "Listen" is one possibility to solve this issue.

**Comment by tmbo** [comment]
@Ghostvv can you reproduce this? If so please post the training data (stories, domain) as well as the instructions to reproduce.

**Comment by Ghostvv** [comment]
@tmbo it happened with old restaurant bot, where the stories were confusing, so the bot used to stuck in infinite loop of `action_listen`.
