### ISSUE TITLE
Starting Rasa CORE with RasaNLUHttpInterpreter

### ISSUE THREAD

**Issue by pradeepmvn** [RasaHQ/rasa_core#202]
**Rasa Core version**:Latest Master

**Python version**: 3.6

**Operating system** (windows, osx, ...):OSX

**Issue**:

How do i start Rasa core Server with a RasaNLU**Http**Interpreter.
-u parameter expects a string only and cannot create an instance of HTTP Interpreter. Didn't find much in the docs either.

**Comment by tmbo** [comment]
I don't think the script supports that at the moment.

**Comment by pradeepmvn** [comment]
@tmbo Thankyou.

**Comment by pradeepmvn** [comment]
@tmbo Sorry..just a followup, is it on your roadmap or a feature for a PR to include RasaNLUHttpInterpreter option with -u and provide a yml file for config details like model and server ?

This will avoid the additional python scripting.
