### ISSUE TITLE
ruamel - library choice for yaml validation

### ISSUE THREAD

**Issue by engelmav** [RasaHQ/rasa_core#207]
The Domain class has a method `validate_domain_yaml` which contains an import of `ruamel`, a library that has no os x distribution. I suggest we swap this out for another. Willing to do so if you're interested.

**Comment by tmbo** [comment]
Let me know if that didn't solve it.

**Comment by amn41** [comment]
this came up today: I think the issue is that ruamel requires command line tools to work
