### ISSUE TITLE
Problems with docs

### ISSUE THREAD

**Issue by Ghostvv** [RasaHQ/rasa_core#220]
**Rasa Core version**:
`master`
**Python version**: 
`3.6`
**Operating system** (windows, osx, ...):
`osx`
**Issue**:
Simple Bot tutorial:

- [x] - 3. -> user actions sounds misleading bc the user has intents
- [x] - actually just also add an asterisk * when we say asterisk
- [x] - explain what epoch is
- [x] - explain how to restart the bot
- [x] - pip install with updated Core for ppl who had it before already (probably more for installation page)
- [ ] - “pip install rasa_nlu[spacy]” - didn’t install everything - recheck (probably more for installation page)

**Content of domain file** (if used & relevant):
```yaml

```

**Comment by tmbo** [comment]
@Ghostvv Where does the spacy installation fail? I just tried 
```
pip install rasa_nlu[spacy]
python -m spacy download en_core_web_md
python -m spacy link en_core_web_md en
```

in a clean env and that worked just fine.

**Comment by Ghostvv** [comment]
i can't remember tbh, i think the installation did not failed, but did not install the last version, and bot didn't work, also `python -m spacy download en`  worked better and linked automatically

**Comment by tmbo** [comment]
seems to work, let me know if you have more insights into this issue and think there is something that needs fixing in rasa nlu.
