### ISSUE TITLE
ListSlot Error 

### ISSUE THREAD

**Issue by AbdurRub** [RasaHQ/rasa_core#226]
**Rasa Core version**: 0.8

**Python version**:  2.7

**Operating system** (windows, osx, ...): Ubuntu 17.04

**Issue**:
I found this solution in gitter channel for solving multiple values for one slot (ListSlot)
https://gist.github.com/AbdurRub/fed8a48dc098f9ea97e9d704d95dd234

Its giving me this error although listslot appending issue resolved it is saving all values in slots but circuit break occurs.
https://gist.github.com/AbdurRub/4e4acf9de9839f5bc2e8d1307226050c

**Comment by tmbo** [comment]
This seems to be related to the events you created in your custom action. (i.e. the values you return in the `run` method - the array seems to contain things that can not be serialized. this might not be related to your list change but some other action that returns events).
