### ISSUE TITLE
Multiple Stories files support for one domain

### ISSUE THREAD

**Issue by AbdurRub** [RasaHQ/rasa_core#233]
**Rasa Core version**:  0.8.3

**Python version**:  2.7

**Operating system** (windows, osx, ...): Ubuntu 17.04

**Issue**:
I have multiple dialogue strategy for one domain. Like I have multiple clients in one industry and every clients wants different chat strategy. Is there any support for multiple stories files for one domain or any plans in future?

**Comment by tmbo** [comment]
Yes, I mean loading stories from multiple files isn't that complicated. There is an early implementation of that on the `multi-file-stories` branch.

**Comment by AbdurRub** [comment]
what about loading multiple projects for Nlu in core?

**Comment by tmbo** [comment]
Whats the use case for that?

**Comment by AbdurRub** [comment]
Like we have multiple projects for RASA NLU  and against one project we have multiple stories files?

**Comment by tmbo** [comment]
I mean, what do you need multiple projects in NLU for? I just want to understand what the underlying reason is that you'd want to connect one rasa core bot with multiple rasa nlu instances.

**Comment by AbdurRub** [comment]
Lets suppose I am having multiple clients (multiple projects) of one industry (lets suppose someone wants 2 intents or some wants 3) so I have to place both files and train model accordingly , then there will be different dialogue strategy too. so with one rasa nlu server instance it loads all projects available and I want to access specific model depending upon client dialogue strategy. 

if project == client1
    if dialoguestories == client1
             hit the nlu server with project client 1
if project == client2
   if dialoguesstories == client2
           hit the nlu server with project client 2

**Comment by lg05** [comment]
I also want to know if the question has the sloution

**Comment by akelad** [comment]
You can just specify the specific dialogue model you want to use though no?

**Comment by Sujay-shetty** [comment]
@tmbo couldn't able to find branch 'multi-file-stories' in the project.

Could you please provide the link of branch?
I also have similar requirement.

**Comment by akelad** [comment]
Loading multiple stories already exist, so i'm gonna close this issue

**Comment by Sujay-shetty** [comment]
@akelad could you please provide information on how to achieve.
Couldn't find document in rasa how to perform this action.

**Comment by akelad** [comment]
just pass a folder to the `--data` flag instead of a single file

**Comment by Sujay-shetty** [comment]
@akelad but while calling api (http://<rasa_core_running_server>/webhook/rest/webhook), how we can specify from which model it has to return data

**Comment by akelad** [comment]
i'm not sure what you mean

**Comment by Sujay-shetty** [comment]
@akelad 
Within a folder there will be multiple files containing different model information, while running rasa-core server I pass --data argument with folder name. So rasa-core server will be up and running.

Now to fetch information from server for the user query client will use webhook(http://<rasa_core_running_server>/webhook/rest/webhook) api.

How to configure from client for which model does rasa-core has to process and provide information from that specific model.

For example, there is a model-a for project-a and model-b for project-b. Both the models are present in same folder.  rasa-core is running by specifying the --data field with folder name of model.
From client(retriever) how to inform rasa-core to use specific model while providing the result.
If specific model is not provided then in both the model files same intent is present rasa-core will return same confidence value for both.

Could you please suggest how to handle this scenario.

**Comment by akelad** [comment]
You can't load multiple models with rasa_core right now. You'd have to launch a model server to do that. See more here: https://rasa.com/docs/nlu/master/persist/ https://rasa.com/docs/nlu/master/endpoint_configuration/
