### ISSUE TITLE
Tensorflow Version (Dev Requirements)

### ISSUE THREAD

**Issue by amandalmia14** [RasaHQ/rasa_core#236]
**Rasa Core version**:

**Python version**: 3.5

**Operating system** (windows, osx, ...): Windows 8.1 (Anacaonda VirEnv)

**Issue**:

**Content of domain file** (if used & relevant):
```yaml

```

Collecting tensorflow==1.4.1 (from -r requirements.txt (line 13))
  Could not find a version that satisfies the requirement tensorflow==1.4.1 (fro
m -r requirements.txt (line 13)) (from versions: 0.12.0rc0, 0.12.0rc1, 0.12.0, 0
.12.1, 1.0.0, 1.0.1, 1.1.0rc0, 1.1.0rc1, 1.1.0rc2, 1.1.0, 1.2.0rc0, 1.2.0rc1, 1.
2.0rc2, 1.2.0, 1.2.1, 1.3.0rc0, 1.3.0rc1, 1.3.0rc2, 1.3.0, 1.4.0rc0, 1.4.0rc1, 1
.4.0, 1.5.0rc0, 1.5.0rc1, 1.5.0, 1.6.0rc0, 1.6.0rc1)
No matching distribution found for tensorflow==1.4.1 (from -r requirements.txt (
line 13))

**Comment by Le-Fix** [comment]
I assume that it's a 64 bit os.
Do you use 32-bit Python?
Did you try making a new virtual environment and install tensorflow using pip?

**Comment by amandalmia14** [comment]
Yes, I a have 64 bit OS and I am using 64-bit python. 
Yes, I am creating a new virtual env and then installing tensorflow using pip.

**Comment by Le-Fix** [comment]
>win7 64bit os with python 3.5.x 64bit using virtualenv and pip (not conda) worked for me on several systems.

Your System doesn't match the requirements of any prebuilt tensorflow package. You can build one yourself but I think that's not necessary and you would have to know whcih requirement it is.

I don't know how I can help you any further.

**Comment by tmbo** [comment]
I mean if that helps, you could try installing `tensorflow==1.5.0` which according to the above error seems to exist.

**Comment by amandalmia14** [comment]
Yes, it works, but some logs come like c is getting deprecated while running.
