### ISSUE TITLE
How to resume a conversation once it is paused.

### ISSUE THREAD

**Issue by sameerkumar16** [RasaHQ/rasa_core#243]
**Rasa Core version**:0.8.2

**Python version**: 3.6

**Operating system** (windows, osx, ...):ubuntu 14.04

**Issue**:
I wrote a custom action which paused the conversation. The custom action code is below

```  
    def run(self, dispatcher, tracker, domain):
        dispatcher.utter_template("utter_ask_aboutliveagent")
        return [ConversationPaused()]
```
The idea is that when a user asks for a human agent, we can pause the conversation .Similarly,on the same idea I want to write a custom action which can resume the conversation for an Intent  (i.e wake up).But after the ConversationPaused() event ,bot can't do any action .

Maybe i am not understanding the doc correctly .
**Content of domain file** (if used & relevant):
```yaml

```

**Comment by sameerkumar16** [comment]
@tmbo

**Comment by sameerkumar16** [comment]
I thinks that, It sets the flag  ```tracker._paused = True``` .Which makes the tracker stop responding to any events .And because of that conversation can't be resumed dynamically. Or maybe I am completely wrong and I am missing something.

**Comment by sameerkumar16** [comment]
I tried a different way in which I updated the tracker's events by ```tracker.update(ConversationPaused())``` in a custom action run() method .It works but again after that there is no way to resume a conversation dynamically because tracker only listens and do nothing .How to solve that. @tmbo How should I solve it?

**Comment by sameerkumar16** [comment]
@msamogh Sir I need help here. I don't know why this issue is being ignored .What am I missing?

**Comment by tmbo** [comment]
No worries, it's not being ignored.

Currently threre is no API function to resume the conversation. The easiest way atm is to retrieve the tracker from the tracker store manually and log the `ConverationResumed` event and store it again.

**Comment by sameerkumar16** [comment]
Thanks , Even I did the similar thing . I thought It could be done by changing the policy and I was looking for same.

**Comment by Egalite123** [comment]
@sameerkumar16  or @tmbo , can you pls explain a little bit more as to how to do this? What I am not able to follow is whether the conversation is paused for the session or user? I logged out of facebook and logged in again. Still I cant get the conversation resumed.
