### ISSUE TITLE
Export corrected intent's to NLU training data during interactive learning

### ISSUE THREAD

**Issue by tiwari85aman** [RasaHQ/rasa_core#245]
**Rasa Core version**: (0.8.1)

**Python version**: 3.6.3

**Operating system** : Linux

**Issue**:As we can export "stories.md" file with interactive learning, is there any way by which we can also export the correct classifed intents during the interactive learning?

e.g.
**domain.yml**
```
intents:
  - greet
  - goodbye
```

**nlu.md**
```
## intent:greet
- hey
- hello
- hi
```

Now during interactive learning:-
user message: hiii there
bot classified it wrongly let say -- "intent: goodbye"
then i correct the intent classification-- "intent:greet"

now if i restart the chatbot it again shows that misclassifed intent ("goodbye"). how to tackle such issue. is there any way that we can export like-

**temp.md**
```
## intent:greet
- hiii there
```

**Comment by tmbo** [comment]
That is a very good and useful idea - it is currently not implemented, only the stories are exported at the moment.

**Comment by tiwari85aman** [comment]
@tmbo actually I am working on this, will I be able to contribute to Rasa core by creating a Pull Request if I get this feature working?

**Comment by tmbo** [comment]
Thats great! Yes of course you can open a PR and we'll discuss if there are any changes that need to be made to merge it :+1:

**Comment by wochinge** [comment]
@tmbo I guess we can close this one right?
