### ISSUE TITLE
Restaurant  example is not working as expected

### ISSUE THREAD

**Issue by artiberde27** [RasaHQ/rasa_core#247]
Rasa Core version: 0.7.9 (Tried 0.8.3 also)

Python version: Python 3.5.2 

Operating system (windows, osx, ...): Ubuntu 14

Issue: The Restaurant is not working as expected. I have taken all the files from Github https://github.com/RasaHQ/rasa_core/tree/master/examples/restaurantbot. But, when I run this example, it is giving random responses. It looks like it is not understanding my input at all. Please see the below response. Am I missing anything here?

Bot loaded. Type a message and press enter :
Me-Hello
Bot-if you'd like to modify anything else, please tell me what
Me-moderately priced restaurant that serves creative food
Bot-if you'd like to modify anything else, please tell me what

Most of the time it replied as "if you'd like to modify anything else, please tell me what"

Below warning i am getting when i train model " python3 -m rasa_nlu.train -c nlu_model_config.json --fixed_model_name current"
![image](https://user-images.githubusercontent.com/23640674/36805438-76ee5fc4-1ce3-11e8-9b01-51f5cce62304.png)

![image](https://user-images.githubusercontent.com/23640674/36809723-c489ed1a-1cee-11e8-9da8-76abe397dc79.png)

**Comment by Ghostvv** [comment]
Hi, with `python3 -m rasa_nlu.train -c nlu_model_config.json --fixed_model_name current` you only train NLU model. You also need to train dialogue policy

**Comment by artiberde27** [comment]
@Ghostvv I had  train dialogue policy also.Below are command i used to run complete application
ython3 -m rasa_nlu.train -c nlu_model_config.json --fixed_model_name current
python3 bot.py train-dialogue
python3 bot.py run

**Comment by Ghostvv** [comment]
@artiberde27 thank you for your answer, I've just run it on my machine with last rasa_core version and got correct behavior:
```
Bot loaded. Type a message and press enter: 
hi
/anaconda/lib/python3.6/site-packages/sklearn/preprocessing/label.py:151: DeprecationWarning: The truth value of an empty array is ambiguous. Returning False, but in future this will result in an error. Use `array.size > 0` to check that an array is not empty.
  if diff:
how can I help you?
i want some mexican food
/anaconda/lib/python3.6/site-packages/sklearn/preprocessing/label.py:151: DeprecationWarning: The truth value of an empty array is ambiguous. Returning False, but in future this will result in an error. Use `array.size > 0` to check that an array is not empty.
  if diff:
I'm on it
where?
```
Could you please provide more details?

**Comment by rhk217** [comment]
To solve the "UndefinedMetricWarning" that pops up during training of the NLU, you can see the solution posted here.
#136
