### ISSUE TITLE
how to send custom messages to facebook? currently it crashes. [updated]

### ISSUE THREAD

**Issue by freakeinstein** [RasaHQ/rasa_core#248]
**Rasa Core version**: 0.8.3

**Python version**: 3.6.3

**Operating system** (windows, osx, ...): ubuntu

**Issue**: how to send custom messages to facebook? The documentation is not clear about this. I have tried using dispatcher.utter_custom_message(). It worked only after applying a patch in channels/facebook.py as detailed below. I don't know if that's necessary. Should I keep that patch, or try formatting the message in some other way?

**Content of domain file** (if used & relevant):
```yaml

```

**Comment by tmbo** [comment]
You need to define the messages in the domain file and then use corresponding actions in the stories file to define how the conversation should evolve. Did you take a look at the introductory tutorial http://core.rasa.ai/tutorial_basics.html

**Comment by freakeinstein** [comment]
@tmbo yes, that tutorial worked for me. But I'm unable to send generic template message that Facebook supports. But currently, I'm trying an alternative method. Instead of defining the message directly in domain.yml I'm trying to send it from python code by defining a custom action. From [this](https://github.com/RasaHQ/rasa_core/tree/master/examples/restaurantbot) example, Inside the file bot.py, I've seen text messages are being sent to Facebook via dispatcher.utter_message() method. I tried sending JSON code through it and didn't work. How could I send custom messages to fb from python code?

**Comment by freakeinstein** [comment]
UPDATE: I found a function 'dispatcher.utter_custom_message()'. What should be the format of message to be passed to it? because, with the default setting, channels/facebook.py crashes [here](https://github.com/RasaHQ/rasa_core/blob/master/rasa_core/channels/facebook.py#L174). So I have disabled that for loop and altered [this line](https://github.com/RasaHQ/rasa_core/blob/master/rasa_core/channels/facebook.py#L181) from `"elements": elements` to`"elements": elements[0]`. After that it worked for me. 

> message being passed to this function: the array part of "elements":[] key as specified in messenger documentation for [generic template](https://developers.facebook.com/docs/messenger-platform/send-messages/template/generic).

**Comment by freakeinstein** [comment]
@advl03 please find the small changes I have made in the previous message.

**Comment by advl03** [comment]
What I have finally done is to modify:
channels/channel.py
channels/facebook.py
dispatcher.py

And implement all Facebook messages that are already supported by the underlying library (fbmessenger). I can now send generic templates, quick replies, typing on and off and so on…
Should I créate a Pull Request with all this functionality?

**Comment by tmbo** [comment]
Yeah I guess a PR would be great, or at least I’d like to take a look at it. I think there is definitely something that we can integrate.

**Comment by advl03** [comment]
Do I need specific permissions in order to commit a new Branch for the PR? If affirmative, could you please give me those permissions temporarily?

**Comment by advl03** [comment]
Hi all
In order to upload the new code, I need permissions to push the new Branch. Could you help me, please?

**Comment by tmbo** [comment]
Sounds great. It would be better though if you would fork the repository to your own account (basically creating a copy of the repo - you can then create a branch on there and create a PR to this repository). The button is at the top right

**Comment by advl03** [comment]
Ok, done. CodeClimate says there are 53 issues to fix, most of them due to code guidelines (lenght of lines, lenght of one of the files due to examples). But you can start taking a look at the code...

**Comment by idusertbs** [comment]
Please make the modification.
