### ISSUE TITLE
InMemoryTrackerStore get_or_create_tracker() not persistent

### ISSUE THREAD

**Issue by mvollrath** [RasaHQ/rasa_core#25]
**Rasa Core version**
master

**Operating system**
Ubuntu 16.04

**Issue**:
When calling `InMemoryTrackerStore.get_or_create_tracker(UserMessage.DEFAULT_SENDER)` twice, a different tracker is returned each time.  Expected behavior is that the same tracker is returned each time.

I made [a test to demonstrate this](https://github.com/EndPointCorp/rasa_core/blob/test_tracker_store_get_or_create/tests/test_tracker_stores.py) which presently fails on master.

**Comment by tmbo** [comment]
Actually, a new instance is expected each time - representing the same state though. E.g. the tracker might be serialised and stored into redis. When the tracker is retrieved, the instance won't be the same.

Is that causing issues for you?

**Comment by mvollrath** [comment]
The real issue is when I set a slot in the tracker, the one coming back from `get_or_create_tracker()` doesn't have that slot set.  I've updated my test to demonstrate this.

Returning the same instance is a "nice to have", but not required, as long as `get_or_create_tracker()` works properly.

**Comment by tmbo** [comment]
@mvollrath thanks for the test, now I get what you mean. So currently, you need to call `tracker_store.save(tracker)` to persist a changed tracker. But why do you need to change something on the tracker in the first place?

**Comment by mvollrath** [comment]
We're using the `Agent` interface in front of everything for normal message handling, but need to be able to set slot values without affecting the dialog history.  Maybe there's another way?

**Comment by mvollrath** [comment]
Say for example, there is a button on your desk that sets a boolean slot ButtonPressed to true, and you have stories that check the ButtonPressed slot value, potentially at each turn of the dialog.  If you handle a message upon the state change it disrupts the flow of the story in a way that would be really obnoxious to incorporate in stories, because there are actually more like eight buttons whose states can change at any time.

I've got this working and it's really cool, but had to workaround this tracker state thing.

**Comment by mvollrath** [comment]
Thanks @tmbo , updated the test to persist the tracker.
