### ISSUE TITLE
Install Rasa_Core 0.8.3 fails on Windows10 with Python version 3.6.4 due to tensorflow version not available

### ISSUE THREAD

**Issue by csplrj** [RasaHQ/rasa_core#252]
**Rasa Core version**:0.8.3

**Python version**: 3.6.4

**Operating system** (windows, osx, ...):Windows 10

**Issue**:
When I tried to install rasa_core using `pip install rasa_core` the following output comes and the rasa_core installation stops
`
Collecting rasa_core
  Downloading rasa_core-0.8.3.tar.gz (76kB)
    100% |████████████████████████████████| 81kB 173kB/s
Collecting jsonpickle (from rasa_core)
  Downloading jsonpickle-0.9.6.tar.gz (67kB)
    100% |████████████████████████████████| 71kB 341kB/s
Collecting six (from rasa_core)
  Downloading six-1.11.0-py2.py3-none-any.whl
Collecting redis (from rasa_core)
  Downloading redis-2.10.6-py2.py3-none-any.whl (64kB)
    100% |████████████████████████████████| 71kB 355kB/s
Collecting fakeredis (from rasa_core)
  Downloading fakeredis-0.9.0-py2.py3-none-any.whl
Collecting nbsphinx (from rasa_core)
  Downloading nbsphinx-0.3.1-py2.py3-none-any.whl
Collecting pandoc (from rasa_core)
  Downloading pandoc-1.0.2.tar.gz (488kB)
    100% |████████████████████████████████| 491kB 1.2MB/s
Collecting future (from rasa_core)
  Downloading future-0.16.0.tar.gz (824kB)
    100% |████████████████████████████████| 829kB 420kB/s
Collecting numpy>=1.13 (from rasa_core)
  Downloading numpy-1.14.1-cp36-none-win32.whl (9.8MB)
    100% |████████████████████████████████| 9.8MB 99kB/s
Collecting typing>=3.6 (from rasa_core)
  Downloading typing-3.6.4-py3-none-any.whl
Collecting requests (from rasa_core)
  Downloading requests-2.18.4-py2.py3-none-any.whl (88kB)
    100% |████████████████████████████████| 92kB 592kB/s
Collecting graphviz (from rasa_core)
  Downloading graphviz-0.8.2-py2.py3-none-any.whl
Collecting Keras (from rasa_core)
  Downloading Keras-2.1.4-py2.py3-none-any.whl (322kB)
    100% |████████████████████████████████| 327kB 425kB/s
Collecting tensorflow (from rasa_core)
  Could not find a version that satisfies the requirement tensorflow (from rasa_core) (from versions: )
No matching distribution found for tensorflow (from rasa_core)
`

**Content of domain file** (if used & relevant):
```yaml

```

**Comment by tmbo** [comment]
Try installing tensorflow separately.

**Comment by Johnz86** [comment]
I had the same problem. This project references tensorflow 1.4.1. But there was no windows pip package for tensorflow released in this version. I needed to install manually. 
```
pip install tensorflow==1.5.0
``` 
I also needded to install pypiwin manually.
```
pip install pypiwin32
```
I got more problems with unsupported instructions on windows tensorflow.
For example I got errors: 
```Your CPU supports instructions that this TensorFlow binary was not compiled to use: AVX AVX2```
So in the ended I started to use docker linux machine for development.
Developing in windows for these cases simply sux :(

**Comment by tmbo** [comment]
But the above CPU message is just a warning, so that should be fine. Was there any other error? If the only issue is the missing release for the 1.4.1 version, we can surely update to 1.5.0

**Comment by Johnz86** [comment]
Yes, there were a lot of deprecation messages, when I tried to run the project based on official tutorial https://core.rasa.ai/tutorial_basics.html . 
```
(botLibs) C:\GIT\simplebot>python -m rasa_core.run -d models/dialogue -u models/nlu/default/current
C:\GIT\simplebot\botLibs\lib\site-packages\h5py\__init__.py:36: FutureWarning: Conversion of the second argument of issubdtype from `float` to `np.floating` is deprecated. In future, it will be treated as `np.float64 == np.dtype(float).type`.
  from ._conv import register_converters as _register_converters
Using TensorFlow backend.
2018-03-13 15:24:59.700580: I C:\tf_jenkins\workspace\rel-win\M\windows\PY\36\tensorflow\core\platform\cpu_feature_guard.cc:137] Your CPU supports instructions that this TensorFlow binary was not compiled to use: AVX AVX2
Bot loaded. Type a message and press enter:

Hey! How are you?
1: great (great)
2: super sad (super sad)
1
C:\GIT\simplebot\botLibs\lib\site-packages\sklearn\preprocessing\label.py:151: DeprecationWarning: The truth value of an empty array is ambiguous. Returning False, but in future this will result in an error. Use `array.size > 0` to check that an array is not empty.
  if diff:
Bye

Hey! How are you?
1: great (great)
2: super sad (super sad)
2
C:\GIT\simplebot\botLibs\lib\site-packages\sklearn\preprocessing\label.py:151: DeprecationWarning: The truth value of an empty array is ambiguous. Returning False, but in future this will result in an error. Use `array.size > 0` to check that an array is not empty.
  if diff:
Bye
2
C:\GIT\simplebot\botLibs\lib\site-packages\sklearn\preprocessing\label.py:151: DeprecationWarning: The truth value of an empty array is ambiguous. Returning False, but in future this will result in an error. Use `array.size > 0` to check that an array is not empty.
  if diff:
Bye
2
C:\GIT\simplebot\botLibs\lib\site-packages\sklearn\preprocessing\label.py:151: DeprecationWarning: The truth value of an empty array is ambiguous. Returning False, but in future this will result in an error. Use `array.size > 0` to check that an array is not empty.
  if diff:
Bye
hey
C:\GIT\simplebot\botLibs\lib\site-packages\sklearn\preprocessing\label.py:151: DeprecationWarning: The truth value of an empty array is ambiguous. Returning False, but in future this will result in an error. Use `array.size > 0` to check that an array is not empty.
  if diff:
Hey! How are you?
1: great (great)
2: super sad (super sad)
2
C:\GIT\simplebot\botLibs\lib\site-packages\sklearn\preprocessing\label.py:151: DeprecationWarning: The truth value of an empty array is ambiguous. Returning False, but in future this will result in an error. Use `array.size > 0` to check that an array is not empty.
  if diff:
Great carry on!
```
Chatbot in this case did not behave as described in tutorial.

**Comment by sherinmannambeth** [comment]
Try installimg the below wheel file manually.
tensorflow-1.6.0-cp36-cp36m-win_amd64.whl
This one worked for me!

**Comment by ratheeshgit** [comment]
what is the fix?

**Comment by akelad** [comment]
@ratheeshgit if you're getting an error, please create a new issue.
