### ISSUE TITLE
Telegram Integration is not working.

### ISSUE THREAD

**Issue by tiwari85aman** [RasaHQ/rasa_core#269]
**Rasa Core version**: (0.8.1)

**Python version**: 3.6.3

**Operating system**: Linux

**Issue**: Telegram Channel is not working and no messages are either sent or received through it. I have followed the documentation of Rasa as well as Telegram.

**Comment by amn41** [comment]
thanks for posting the issue! in order to help you we will need more information. Can you post a stacktrace of what goes wrong, and exact steps to reproduce?

**Comment by tiwari85aman** [comment]
@amn41 after getting the required 
access_token: From Telegram Botfather
verify: New Bot username
webhook_url: Your url webhook

and running the bot with the code:
`python -m rasa_core.run -d models/dialogue -u models/nlu/default/weathernlu     --port 8081 --connector telegram --credentials telegram_credentials.yml`

the chatbot starts working but neither the message from telegram reaches to my bot nor the bot responds anything to telegram.

**Comment by amn41** [comment]
what are you using as a webhok? I guess you are running on your laptop, do you have [ngrok](ngrok.com) installed?

**Comment by tiwari85aman** [comment]
yes i have ngrok installed and even i checked with other alternatives e.g. pagekite

**Comment by tiwari85aman** [comment]
@amn41 i have fixed this issue and wants to raise a pull request

**Comment by amn41** [comment]
excellent! great that you found the problem and glad you can contribute a fix. I'll look out for your PR

**Comment by tiwari85aman** [comment]
#271 PR has the fixed missing code of the telegram.py which is needed for telegram integration. kindly review it  @amn41 , Thank You

**Comment by tiwari85aman** [comment]
this issue has been fixed.. therefore I am closing the issue.

**Comment by rojobuffalo** [comment]
What is the `webhook_url` supposed to be? Where does that come from?
