### ISSUE TITLE
exceptions.AttributeError: 'RasaCoreServer' object has no attribute 'config'

### ISSUE THREAD

**Issue by hazelmyth** [RasaHQ/rasa_core#27]
**Rasa Core version** (e.g. `0.7.1`):

**Operating system** (windows, Ubuntu, ...):
I run rasa_core as http server via "python -m rasa_core.server -d examples/babi/models/policy/current -u examples/babi/models/nlu/current_py2 -o out.log" and encounter the following issue: 
**Issue**:
2017-10-12 05:06:13-0400 [_GenericHTTPChannelProtocol,1,192.168.56.1] Unhandled Error
Traceback (most recent call last):
File "/home/osboxes/.local/lib/python2.7/site-packages/twisted/web/server.py", line 255, in render
body = resrc.render(self)
File "/home/osboxes/.local/lib/python2.7/site-packages/klein/resource.py", line 206, in render
d = defer.maybeDeferred(_execute)
File "/home/osboxes/.local/lib/python2.7/site-packages/twisted/internet/defer.py", line 150, in maybeDeferred
result = f(args, kw)
File "/home/osboxes/.local/lib/python2.7/site-packages/klein/resource.py", line 200, in _execute kwargs)
--- <exception caught here> ---
File "/home/osboxes/.local/lib/python2.7/site-packages/twisted/internet/defer.py", line 150, in maybeDeferred
result = f(args, kw)
File "/home/osboxes/.local/lib/python2.7/site-packages/klein/app.py", line 126, in execute_endpoint
return endpoint_f(self._instance, args, kwargs)
File "/home/osboxes/.local/lib/python2.7/site-packages/klein/app.py", line 211, in _f
return _call(instance, f, request, a, **kw)
File "/home/osboxes/.local/lib/python2.7/site-packages/klein/app.py", line 48, in _call
result = f(instance, args, kwargs)
File "/home/osboxes/Documents/projects/rasa_nlu/rasa_nlu/server.py", line 69, in decorated
if '' in self.config['cors_origins']:
exceptions.AttributeError: 'RasaCoreServer' object has no attribute 'config'

1) The command I am issuing is "http://192.163.56.102:5005/conversations/default/parse" using Postman with a body {"query":"hello there"}. My rasa_core http server is running on a Ubuntu VM and I'm issuing this command from my Windows hosting machine.
2) It's working perfectly fine when I issue the same command using Curl from the Ubuntn VM the same machine where the rasa_core http server is running.
3) I will create a ticket in rasa_core git repo.
4) Thank you very much. 

**Content of domain file** (if used & relevant):
```yaml

```

**Comment by tmbo** [comment]
Alright, so to make this reproducible:
- did you install from pypi or git?
- the postman request is run from a different machine than the one hosting the server, right?

**Comment by hazelmyth** [comment]
- I installed rasa_core from pypi, my pip package list look like: "rasa-core (0.7.1, /usr/local/lib/python2.7/dist-packages/rasa_core-0.7.1-py2.7.egg)".
- Yes. My postman request from a Windows machine and rasa core running on a Ubuntu. 

We already figure this out. Previously postman was a Chrome plugin, I faced this issue. After I installed postman as an independent application, this issue is gone. 

The code that causes this issue is actually from rasa_nlu in the file 'rasa_nlu/rasa_nlu/server.py'
```
def check_cors(f):
    """Wraps a request handler with CORS headers checking."""

    @wraps(f)
    def decorated(*args, **kwargs):
        self = args[0]
        request = args[1]
        origin = request.getHeader('Origin')

        if origin:
            if '*' in self.config['cors_origins']:
                request.setHeader('Access-Control-Allow-Origin', '*')
            elif origin in self.config['cors_origins']:
                request.setHeader('Access-Control-Allow-Origin', origin)
            else:
                request.setResponseCode(403)
                return 'forbidden'

        return f(*args, **kwargs)

    return decorated
```
When I ran Postman as Chrome extension:
1. variable 'origin' is not null, the if condition is true. 
2. the 'self' object is actually a RasaCoreServer instance instead of RasaNluServer instance. RasaCoreServer instand has no 'config' attribute, thus the error arises. 

When I ran Postman as a independent application:
1. variable 'origin' is null. If condition is false, error disappears.

**Comment by tmbo** [comment]
Good catch :+1: fixed.
