### ISSUE TITLE
how to get responses from rasa core to my own server(UI)

### ISSUE THREAD

**Issue by Selvaganapathi06** [RasaHQ/rasa_core#275]
I can only use CustomInput to send a message to "localhost:5005" by POST but I cannot get the response from my bot. Is there any way that I could build/modify on top of the rasa_core? please help anyone

**Comment by amn41** [comment]
is this what you need? 
https://github.com/RasaHQ/rasa_core/pull/262

**Comment by Selvaganapathi06** [comment]
i am new for python and chat bot. now i  built an chat bot used rasa core based an restaurant chat bot example. After issue number 119 given serve.py used added my folder , run this serve.py working fine in postman. After i integrate in my ui faced cross origin error. i installed flask cors and added 
from flask import Flask
from flask_cors import CORS

app = Flask(__name__) 
CORS(app)
but still faced this cross origin issue. Reg :262 i dont know what purpose please explain? In my goal is implement chat bot using rasa core and integrate my UI with context handling. How achieve this ?

**Comment by Selvaganapathi06** [comment]
Thanks. Cross origin issue fixed.

**Comment by Selvaganapathi06** [comment]
Can you please tell me how to handle context in rasa_core my custom chat bot?

**Comment by tmbo** [comment]
duplicates #279
