### ISSUE TITLE
utter_message if custom_action is taking time

### ISSUE THREAD

**Issue by ramspoluri** [RasaHQ/rasa_core#277]
**Rasa Core version**: 0.8.2

**Python version**: 2.7.12

**Operating system** (windows, osx, ...): Ubuntu 16.04

**Issue**:

Is it possible to utter_message if custom_action is taking more than certain time (say 2s).

**Comment by tmbo** [comment]
I don't think that is implemented for the input / output channels yet (facebook), but if the channel would allow it, you could trigger that yourself at the beginning of the action which takes time (assuming you know that beforehand). Or you could at least show the "typing" indicator, so the user knows a response is in progress. But as said, I don't think that is implemented yet for the input/ output channels.
