### ISSUE TITLE
Context based entity values

### ISSUE THREAD

**Issue by ctrado18** [RasaHQ/rasa_core#280]
Hi,

I have 2 entities wich are numbers for example. Now it occurs as a problem when you create stories.
Let's say you need those 2 numbers to give an output to the user. So, the bot has to ask for those numbers in a dialogue and save them as a slot. Is the value of the slot for the entity overwritten for the second time? I need kap track of the slot's value in a conversation.

Or, if you have two different entities but both with numbers, can you make the entity context dependent in the sense that if you type the number "10" the bot knows from previous action and context that this 10 is entity 1 rather than entity 2.

My general problem is, to handle such  situations:

> Bot: What is your weight?
> User: 50
> Bot: What is your age?
> User: 30

So, the clue were to set 2 entities: age and weight. But when the user just type in a number like above, how can you make the bot know that this is the age (or weight) from previous asked question (action) from bot?

**Comment by amn41** [comment]
have a look at this PR https://github.com/RasaHQ/rasa_core/pull/261

**Comment by ctrado18** [comment]
Thanky you!

**Comment by ctrado18** [comment]
Sorry, I closed it but now have a further question.

I have two entities with numbers for example and the user just types those numbers, it is somehow impossible for NLU to detcect which entity was meant. Is there a good way way to solve this? 

I just now try using just one entity and after every slot filling request I call a custom action where I want to "save" this value. But i dont know how to that. If I define an empty array inside an action this will be reset every time I call this this action in the story.

_But shouldn't it be possible to have access to tthe slot's history? How can I use the previous value of the slot in current conversation?_

**Comment by ctrado18** [comment]
Am I right that the funcion _get_latest_entity_values_ from the _DialogueStateTracker_ is suitable for the task to get the previous entity value? But I tried inside a custom action to get these last values:

```
class ActionUpdate(Action):
    def name(self):

        return 'action_update'
        
    

    def run(self, dispatcher, tracker, domain):


        latest= tracker.get_latest_entity_values('entity')

        a= tracker.get_slot('entity')
        
        print(tracker.slots)
        tracker.update(SlotSet("entity",value))
        print(tracker.slots)

        print(latest)

        dispatcher.utter_message(a)
```
If I print the latest I get:

> <generator object DialogueStateTracker.get_latest_entity_values.<locals>.<genexpr> at 0x0000020B0F8BDA40>

**Comment by tmbo** [comment]
The tracker doesn't contain the past state of slots directly. It does contain all events that happend in the past though, so you can take a look at the events in `tracker.events`. Look for `SlotSet` events, they will tell you which values the slots have been set to.

**Comment by ctrado18** [comment]
But I saw quite often the word timestamp in context of tracker. So you can have access to the history? I just was unsure what value for timestamp is expected (date time...)
