### ISSUE TITLE
Action restart and handling messages inside custom action

### ISSUE THREAD

**Issue by ctrado18** [RasaHQ/rasa_core#281]
Hi,

maybe I didn't understand correctly the action restart. But it seems that you cannot start the converation from beginning like:

> 
> * greet
>     - utter_greet
>     - utter_ask_help
> * Setup
>     - utter_question
> * SetupPrinter{"entity": "value"}
>     - slot{"entity" : "value"}
>     - action_enity
>     - utter_startover
>     - utter_restart
> 

So, after utter_restart, I cannot start dialogue with intent greet again...I am looking for a way to simply restart conversation.

Then, is it possible to handle incoming messages from user inside a custom action? To handle the problem in #203 I want that inside a custom action variables are filled from user input...

**Comment by tmbo** [comment]
there is two ways to achive the restart. Either you emit the `Restarted` event from a custom action (in this case the conversation will be restarted after that action has been executed). Or you use the builtin action `action_restart` (mind the `action_` not `utter_` - the utterance is just the text that action emits when run - so if you want the conversation to be restarted, replace the `utter_restart` in your example with `action_restart`)

**Comment by ctrado18** [comment]
thanks!
