### ISSUE TITLE
How to perform automatic tests?

### ISSUE THREAD

**Issue by albertotonon** [RasaHQ/rasa_core#283]
Hi everybody,

I'm trying to code some tests to automatically verify that each version of the chatbot I'm building satisfies few basic requirements. Basically, I would need to be able to send a string to the chatbot and get back the list of predicted utterance ids from the domain and the entities extracted from the NLU.
One method I tested was just to verify the content of the tracker but then I realised that, unfortunately, some of the actions I have defined reset the tracker, so, I cannot fully rely on it.
I noticed the methods start_message_handling and continue_message_handling in processor.py, however I think they require all the actions to be executed "manually" between the calls.
A similar situation would happen if I use the RASA http server.

Is there in RASA any less cumbersome way to code automatic tests?

**Comment by tmbo** [comment]
How do you want to run these tests? e.g. you could write stories in a story file and run them, comparing the story written in the file with the predictions of rasa core (this should already work). But I am not sure this is what you are looking for.

This also sounds a bit like https://core.rasa.com/master/http.html#post--conversations-(str-sender_id)-respond might be what you are looking for (recently implemented in the master version, not in the released version yet). It is kind of an endpoint like the ones for start / continue message handling where you need to run the actions - but this one runs the actions and returns the bot utterances.

**Comment by albertotonon** [comment]
Sorry for the very late answer: I somehow missed the notification and just realised you wrote me back.

What I would like to do is giving the chatbot a natural language sentence (so, i guess the story approach @tmbo mentioned wouldn't work) , assert on the detected intent entities and possibly, on the output action name (e.g. utter_greet). 
Then continue the conversation with the chatbot by sending another sentence, assert on detected intent and entities, possibly on output action, etc.

The idea would be to have this as an automatic test before deploying the chatbot, so that we're sure that even if we change the input data a bit, common interaction are still handled correctly. What do you think?
