### ISSUE TITLE
add documentation about core generalisation

### ISSUE THREAD

**Issue by tmbo** [RasaHQ/rasa_core#288]
There should be a section in the documentation explaining the generalisation capabilities of rasa core.

When we added models that allow to benefit from training data in a specific format, e.g. #286 , this should be added to the documentation as well to make sure there are best practices on how to name actions that help models classify them correctly.

**Comment by tmbo** [comment]
@amn41 what is the status on this? Are you actively working on this

**Comment by amn41** [comment]
no I'm waiting until the embeddingpolicy is merged in

**Comment by Ghostvv** [comment]
embedding policy needs a bit of polish, but, I think we can start working on the tutorial

**Comment by amn41** [comment]
now unblocked so we can do it. I'll write a first draft and send PR to @Ghostvv & @JustinaPetr for input

**Comment by akelad** [comment]
@amn41 is this not the PR for that? https://github.com/RasaHQ/rasa_core/pull/786
you tagged the issue from there

**Comment by amn41** [comment]
was already in the docs
