### ISSUE TITLE
Different behaviour between online and normal training?

### ISSUE THREAD

**Issue by ctrado18** [RasaHQ/rasa_core#296]
Hey,

i experience different behaviour of online training versus normal training, though I give same parameters and for normal training set the validation split to 0, such that same amount of trainig data is available for both!

As far as I looked it uses same method and algorithms?

What can be the reason?

**Comment by amn41** [comment]
Are both runs training with the same number of epochs? By default the online training only trains for a few

**Comment by ctrado18** [comment]
Yes! Both 300. I call both n this way:

```
`agent.train(training_data_file,
max_history = 3,
epochs = 300,
batch_size = 15,
validation_split = 0,
augmentation_factor = 50)`
```
```
agent.train_online(training_data_file,
                       input_channel=input_channel,
                       max_history=3,
                       batch_size=15,
                       epochs=300, augmentation_factor = 50)
```

**Comment by tmbo** [comment]
How do you observe that things are different?

**Comment by ctrado18** [comment]
I wrote stories for handling a specific scenario at the begining of story. Online-Training works perfectly as I want! But same story doesn't work with normal run. Yesterday it worked when I set validation split to 0 but same is not working right now, though I did not change anything..

I assume It has something to do with the trainig preparation in Keras Policy?

**Comment by tmbo** [comment]
Can you provide a complete example? including the training data, the commands you used for the training as well as the story you tried that did not work. I'd like to reproduce this but I need a bit more information to get started.

In general, I'd expect the online learning and the normal training should produce very similar results.

**Comment by ctrado18** [comment]
Thats bad. I try to provide it but its not possible today or tomorrow. I have about 25 stories and really works better generally with online training... Maybe you have a reason in mind for that until I provide the data?

**Comment by ctrado18** [comment]
I found that somehow there es a bit of a problem of getting weight on history! It seems that is not very sensitive to history like only just the previous action would be important, though I trained to use a history of 3...
