### ISSUE TITLE
custombot issues

### ISSUE THREAD

**Issue by Selvaganapathi06** [RasaHQ/rasa_core#305]
i have integrated my bot with my ui page.My bot is responding but after certain limit it is not getting the response. The response is empty. For output channel i am using collecting output channel() and also i have used bot output channel which is mentioned in custom bot example  

https://github.com/souvikg10/rasa_bot_example/blob/master/bot_custom.py. But both method is not working .
 can you explain?

**Comment by amn41** [comment]
Could you please provide some more information? If you could share your custom code, and some requests and responses that would help us help you.

**Comment by Selvaganapathi06** [comment]
This is my code

from __future__ import absolute_import
from __future__ import division
from __future__ import print_function
from __future__ import unicode_literals

import os
import logging
import argparse
import warnings
from flask import request
from flask import Flask
from rasa_core.channels import HttpInputChannel
from rasa_core import utils
from rasa_core.agent import Agent
from rasa_core.actions import Action
from rasa_core.interpreter import RasaNLUInterpreter
from rasa_core.channels.channel import UserMessage
from rasa_core.channels.direct import CollectingOutputChannel
from rasa_core.channels.channel import UserMessage, OutputChannel
from rasa_core.channels.rest import HttpInputComponent
from flask import Blueprint, request, jsonify
from flask_cors import CORS, cross_origin
from rasa_core.domain import TemplateDomain
from rasa_core.trackers import DialogueStateTracker
from rasa_core.slots import TextSlot
from rasa_core.events import SlotSet
from rasa_core.tracker_store import InMemoryTrackerStore
from rasa_nlu.server import check_cors
from rasa_core.policies.memoization import MemoizationPolicy
from rasa_core.policies.ensemble import PolicyEnsemble
from rasa_core.policies.ensemble import PolicyEnsemble,SimplePolicyEnsemble
from policy import BankPolicy
from rasa_core.policies import Policy
#from policy2 import SimplePolicyEnsemble
#from actions import ActionFallback
custom_webhook = Flask(__name__)
CORS(custom_webhook)

logger = logging.getLogger(__name__)
logging.getLogger('flask_cors').level = logging.DEBUG

class BotOutput(OutputChannel):
    """A bot that uses rest to communicate."""
    def __init__(self):
        pass
    
    def send_text_message(self, recipient_id, elements):
       #self.message = jsonify({"status": recipient_id, "result": elements})
	   self.response = elements

class ActionFallback(Action):

    def name(self):
        return "fallback"

    def run(self, dispatcher, tracker, domain):
        from rasa_core.events import UserUtteranceReverted

        dispatcher.utter_message("I am sorry. I do not know what this term means")
        return [UserUtteranceReverted()]
        

class SimpleWebBot(HttpInputComponent):
    """A simple web bot that listens on a url and responds."""
	
    def end_headers(self):
        self.send_header('Access-Control-Allow-Origin', '*')
        self.send_header('Allow', 'GET, POST, OPTIONS')		
        super(CORSHTTPRequestHandler, self).end_headers(self)
		
    def blueprint(self, on_new_message):
        custom_webhook = Blueprint('custom_webhook', __name__)

        @custom_webhook.route("/status", methods=['GET'])
        def health():
            return jsonify({"status": "ok"})

        @custom_webhook.route("/", methods=['POST'])
        @cross_origin()
        def receive():
            if request.method == 'GET':
                return jsonify({"status": "ok"})
            if request.method == 'POST':
		        payload = request.json
				sender_id = payload.get("sender", None)
                text = payload.get("message", None)
		
            	output_channel = BotOutput()
		
                user_message=(UserMessage(text, output_channel, sender_id))
		on_new_message(user_message)
		
			    return output_channel.response
					
        return custom_webhook
		
def train_dialogue(domain_file="restaurant_domain12.yml",
                   model_path="models/dialogue",
                   training_data_file="data/babi_stories.md"):
    agent = Agent(domain_file,policies=[MemoizationPolicy(), BankPolicy()])

    agent.train(
            training_data_file,
            max_history=4,
            epochs=400,
            batch_size=100,
            validation_split=0.2
    )

    agent.persist(model_path)
    return agent
	
def train_nlu():
    from rasa_nlu.converters import load_data
    from rasa_nlu.config import RasaNLUConfig
    from rasa_nlu.model import Trainer

    training_data = load_data('data/franken_data.json')
    trainer = Trainer(RasaNLUConfig("nlu_model_config.json"))
    trainer.train(training_data)
    model_directory = trainer.persist('models/nlu/', fixed_model_name="current")

    return model_directory
	
def run(serve_forever=True, debug = False):
    #path to your NLU model
    interpreter = RasaNLUInterpreter("models/nlu/default/current")
    # path to your dialogues models
    #default_domain = TemplateDomain.load("models/dialogue")
    #print(default_domain)
    domain=("models/dialogue")
    tracker_domain = TemplateDomain.load("models/dialogue/domain.yml")
    tracker_store = InMemoryTrackerStore(tracker_domain)
    chat_endpoint = SimpleWebBot()
    if debug:
        input_channel = ConsoleInputChannel()
    else:
        input_channel = HttpInputChannel(7475, "/chat", chat_endpoint)
    agent = Agent.load("models/dialogue",
                    interpreter=interpreter,
                    tracker_store=tracker_store)

    if serve_forever:
        agent.handle_channel(input_channel)
    return agent

if __name__ == '__main__':
    utils.configure_colored_logging(loglevel="INFO")
    parser = argparse.ArgumentParser(
            description='starts the bot')

    parser.add_argument(
            'task',
            choices=["train-nlu", "train-dialogue", "run"],
            help="what the bot should do - e.g. run or train?")
    task = parser.parse_args().task
	
    if task == "train-nlu":
        train_nlu()
    elif task == "train-dialogue":
        train_dialogue()
    elif task == "run":
        run()
        custom_webhook.run('0.0.0.0')
    else:
        warnings.warn("Need to pass either 'train-nlu', 'train-dialogue' or "
                      "'run' to use the script.")
        exit(1)

**Comment by Selvaganapathi06** [comment]
The above code is working fine  but after certain request and response got the below error

 if diff:
<__main__.BotOutput object at 0x7f5fe96f5e10>
{}
[2018-03-26 06:18:32,059] ERROR in app: Exception on /chat/ [POST]
Traceback (most recent call last):
  File "/usr/local/lib/python2.7/dist-packages/flask/app.py", line 1982, in wsgi_app
    response = self.full_dispatch_request()
  File "/usr/local/lib/python2.7/dist-packages/flask/app.py", line 1614, in full_dispatch_request
    rv = self.handle_user_exception(e)
  File "/usr/local/lib/python2.7/dist-packages/flask/app.py", line 1517, in handle_user_exception
    reraise(exc_type, exc_value, tb)
  File "/usr/local/lib/python2.7/dist-packages/flask/app.py", line 1612, in full_dispatch_request
    rv = self.dispatch_request()
  File "/usr/local/lib/python2.7/dist-packages/flask/app.py", line 1598, in dispatch_request
    return self.view_functions[rule.endpoint](**req.view_args)
  File "/usr/local/lib/python2.7/dist-packages/flask_cors/decorator.py", line 128, in wrapped_function
    resp = make_response(f(*args, **kwargs))
  File "serve1.py", line 109, in receive
    if output_channel.response is not None and output_channel.response != '':
AttributeError: 'BotOutput' object has no attribute 'response'

**Comment by Selvaganapathi06** [comment]
Can you please share to me how to enable log in the above code??

**Comment by akelad** [comment]
Could you please post which rasa core version you're using? And also please format the code you posted with ``` so it's easier to read

**Comment by Selvaganapathi06** [comment]
Used Versions:  rasa_core "version": "0.8.3"
                            rasa_nlu  "version": "0.11.4"

**Comment by Selvaganapathi06** [comment]
from __future__ import absolute_import
from __future__ import division
from __future__ import print_function
from __future__ import unicode_literals
from pprint import pprint
import os
import logging
import logging.handlers
import argparse
import warnings
from flask import request
from flask import Flask
from rasa_core.channels import HttpInputChannel
from rasa_core import utils
from rasa_core.agent import Agent
from rasa_core.actions import Action
from rasa_core.interpreter import RasaNLUInterpreter
from rasa_core.channels.channel import UserMessage
from rasa_core.channels.direct import CollectingOutputChannel
from rasa_core.channels.channel import UserMessage, OutputChannel
from rasa_core.channels.rest import HttpInputComponent
from flask import Blueprint, request, jsonify
from flask_cors import CORS, cross_origin
from rasa_core.domain import TemplateDomain
from rasa_core.trackers import DialogueStateTracker
from rasa_core.slots import TextSlot
from rasa_core.events import SlotSet
from rasa_core.tracker_store import InMemoryTrackerStore, RedisTrackerStore
from rasa_nlu.server import check_cors
from rasa_core.policies.memoization import MemoizationPolicy
from rasa_core.policies.ensemble import PolicyEnsemble
from rasa_core.policies.ensemble import PolicyEnsemble,SimplePolicyEnsemble
from policy import BankPolicy
from rasa_core.policies import Policy
from rasa_core.utils import read_yaml_file
from rasa_core.events import Restarted
#from policy2 import SimplePolicyEnsemble
#from actions import ActionFallback
custom_webhook = Flask(__name__)
CORS(custom_webhook)
logger = logging.getLogger(__name__)
logging.getLogger('flask_cors').level = logging.DEBUG
class BotOutput(OutputChannel):
    """A bot that uses rest to communicate."""
    def __init__(self):
        pass
    
    def send_text_message(self, recipient_id, elements):
	print("1 Hi")
	print("2" + elements)
    #self.message = jsonify({"status": recipient_id, "result": elements})
	#print(self.message)
	self.response = elements	
class ActionFallback(Action):

    def name(self):
        return "fallback"

    def run(self, dispatcher, tracker, domain):
        from rasa_core.events import UserUtteranceReverted

        dispatcher.utter_message("I am sorry. I do not know what this term means. Is there something else in Customer Value Maximization that you need to figure out?")
        return [UserUtteranceReverted()]

class SimpleWebBot(HttpInputComponent):
    """A simple web bot that listens on a url and responds."""
	
    def end_headers(self):
        self.send_header('Access-Control-Allow-Origin', '*')
        self.send_header('Allow', 'GET, POST, OPTIONS')		
        super(CORSHTTPRequestHandler, self).end_headers(self)
		
    def blueprint(self, on_new_message):
        custom_webhook = Blueprint('custom_webhook', __name__)

        @custom_webhook.route("/status", methods=['GET'])
        def health():
            return jsonify({"status": "ok"})

        @custom_webhook.route("/", methods=['POST'])
        @cross_origin()
        def receive():
            if request.method == 'GET':
                return jsonify({"status": "ok"})
            if request.method == 'POST':
		payload = request.json		
                sender_id = payload.get("sender", None)
                text = payload.get("message", None)				
            	output_channel = BotOutput()		
                user_message=(UserMessage(text, output_channel, sender_id))		
		on_new_message(user_message)		
		#pprint(vars(user_message))
		
		
		return output_channel.response	
	
        return custom_webhook
		
def train_dialogue(domain_file="restaurant_domain12.yml",
                   model_path="models/dialogue",
                   training_data_file="data/babi_stories.md"):
    agent = Agent(domain_file,policies=[MemoizationPolicy(), BankPolicy()])

    agent.train(
            training_data_file,
            max_history=3,
            epochs=400,
            batch_size=100,
            validation_split=0.2
    )

    agent.persist(model_path)
    return agent
	
def train_nlu():
    from rasa_nlu.converters import load_data
    from rasa_nlu.config import RasaNLUConfig
    from rasa_nlu.model import Trainer

    training_data = load_data('data/franken_data.json')
    trainer = Trainer(RasaNLUConfig("nlu_model_config.json"))
    trainer.train(training_data)
    model_directory = trainer.persist('models/nlu/', fixed_model_name="current")

    return model_directory
	
def run(serve_forever=True, debug = False):
    #path to your NLU model
    interpreter = RasaNLUInterpreter("models/nlu/default/current")
    # path to your dialogues models
    #default_domain = TemplateDomain.load("models/dialogue")
    #print(default_domain)
    domain=("models/dialogue")
    tracker_domain = TemplateDomain.load("models/dialogue/domain.yml")
   
    tracker_store = InMemoryTrackerStore(tracker_domain)
    chat_endpoint = SimpleWebBot()
    if debug:
        input_channel = ConsoleInputChannel()
    else:
        input_channel = HttpInputChannel(7475, "/chat", chat_endpoint)
    agent = Agent.load("models/dialogue",
                    interpreter=interpreter,
                    tracker_store=tracker_store)
   
    if serve_forever:
        agent.handle_channel(input_channel)
    return agent

    

if __name__ == '__main__':
    #utils.configure_colored_logging(loglevel="selva.log")
    logging.basicConfig(level="DEBUG", filename="/home/RASA/21032018/bank/ccd.log")
    parser = argparse.ArgumentParser(
            description='starts the bot')
    

    parser.add_argument(
            'task',
            choices=["train-nlu", "train-dialogue", "run"],
            help="what the bot should do - e.g. run or train?",
			)
    
    task = parser.parse_args().task
	
    if task == "train-nlu":
        train_nlu()
    elif task == "train-dialogue":
        train_dialogue()
    elif task == "run":
        run()
        custom_webhook.run('0.0.0.0')
    else:
        warnings.warn("Need to pass either 'train-nlu', 'train-dialogue' or "
                      "'run' to use the script.")
        exit(1)
