### ISSUE TITLE
List type slots are populated by processor with only last item in list and not the entire list

### ISSUE THREAD

**Issue by mtbikerj** [RasaHQ/rasa_core#307]
**Rasa Core version**:
0.8.4

**Python version**: 
3.5.4

**Operating system** (windows, osx, ...):
Windows 10

**Issue**:
When running a bot that has multiple items for the same entity returned from the NLU, the rasa_core.processor is not pushing the list to a list type slot, but only pushing the last item.  This is possibly occurring due to the code around line 228 of processor.py
```
 # store all entities as slots
        for e in self.domain.slots_for_entities(parse_data["entities"]):
            tracker.update(e)
```

Here is an example from the core log when running in debug mode.  Notice the two values for location in the first row, but the current slot values only receives the final item of the list:

```
DEBUG:rasa_core.processor:Received user message 'Tell me about Prague and London' with intent '{'confidence': 0.2412529688289353, 'name': 'store_name'}' and entities '[{'value': 'prague', 'extractor': 'ner_crf', 'entity': 'location', 'start': 14, 'end': 20}, {'value': 'london', 'extractor': 'ner_crf', 'entity': 'location', 'start': 25, 'end': 31}]'
DEBUG:rasa_core.processor:Logged UserUtterance - tracker now has 4 events
DEBUG:rasa_core.processor:Current slot values: 
	location: london
	person: None
```

**Content of domain file** (if used & relevant):
```yaml
entities:
  - user_name
  - location
  - person

slots:
  location:
    type: list
  person:
    type: text
```

**Comment by Harish0596** [comment]
@akelad So when can we expect the update

**Comment by akelad** [comment]
That depends, someone from the community might get to it, otherwise we'll look into it eventually. In the meantime though you can use a custom action to fill the list slot

**Comment by adhaamehab** [comment]
@akelad Can I take this one as a first issue?

**Comment by akelad** [comment]
sure

**Comment by tmbo** [comment]
how is it going @adhaamehab do you need any help?

**Comment by akelad** [comment]
@AbdurRub so a simple solution for now while this isn't fixed is to use a custom action to set the slot as a list

**Comment by tmbo** [comment]
duplicates #171

**Comment by leonardoaii71** [comment]
@akelad hello, I'm trying to do that but it only takes the last element of the list. This is what I'm doing:

`                   matches = []
                    for doc in docs:
                        event = doc['event']['name']
                        matches.append(event)
                    return [SlotSet('matching_events', matches)]`

but when i do this:
` matches = tracker.get_slot("matching_events")`
it only has one element.

Is this the correct way to use it?

**Comment by akelad** [comment]
Please post this kind of question in the [forum](https://forum.rasa.com). Ideally including the domain file, so we can see whether the slot is of type list
