### ISSUE TITLE
Simple Bot Tutorial fbmessenger not responding

### ISSUE THREAD

**Issue by yipcma** [RasaHQ/rasa_core#311]
**Rasa Core version**:
0.8.5
**Python version**: 
3.6
**Operating system** (windows, osx, ...):
osx
**Issue**:
The fb messenger's webhook is setup correctly. However, the bot is not responding. the ngrok tunnel is receiving message fine.

post /webhook

```
{
    "object": "page",
    "entry": [
        {
            "id": "redacted",
            "time": 1522158569327,
            "messaging": [
                {
                    "sender": {
                        "id": "redacted"
                    },
                    "recipient": {
                        "id": "redacted"
                    },
                    "timestamp": 1522158568667,
                    "message": {
                        "mid": "mid.$redacted",
                        "seq": 263216,
                        "text": "how are you?"
                    }
                }
            ]
        }
    ]
}
```
where it gives a 200 success.
On the console, the following shows:
```
/usr/local/anaconda3/envs/pylearn/lib/python3.6/site-packages/sklearn/preprocessing/label.py:151: DeprecationWarning: The truth value of an empty array is ambiguous. Returning False, but in future this will result in an error. Use `array.size > 0` to check that an array is not empty.
  if diff:
127.0.0.1 - - [2018-03-27 16:49:30] "POST /webhook HTTP/1.1" 200 122 0.707039
```

**Content of domain file** (if used & relevant):
```yaml

```

**Comment by akelad** [comment]
Just to sanity check:
- have you definitely set the right webhook and verify token on your app in developers.facebook.com? (Sadly this can only be set once, so it has to be the same URL you set initally)
- are you using the correct app secret for `secret`
- are you using the correct page token from the page you want the app to be connected to for `page-access-token`?
- have you subscribed to the events of your page under: "Select a page to subscribe your webhook to the page events"

If you've done all these, could you send a longer debug log? i.e. is there any warnings or anything?

**Comment by yipcma** [comment]
Yes, else the webhook would not be ready.
Yes (as in above).
Yes (as in above).
Yes, page subscribed ( I posted the event that I receive on the webhook).
There is no more debugging log, all i see is a 200 success as response. No message or anything.

@akelad do you have success in hooking up the Simple Bot tutorial to facebook?

**Comment by yipcma** [comment]
so I've been looking at the facebook integration script and i saw this:

```
        def webhook():
            signature = request.headers.get("X-Hub-Signature") or ''
            if not self.validate_hub_signature(self.fb_secret, request.data,
                                               signature):
                logger.warn("Wrong fb secret! Make sure this matches the "
                            "secret in your facebook app settings")
                return "not validated"

            messenger = Messenger(self.fb_access_token, on_new_message)

            messenger.handle(request.get_json(force=True))
            return "success"

        return fb_webhook
```

so does this mean the messages are not at all handled? (just a "success" is returned)

**Comment by akelad** [comment]
So I just tried to connect a bot to a Facebook page in a new app and I can't even generate an Access Token. Everything is under review over there right now, so they've disabled a lot of things for the time being. https://developers.facebook.com/blog/post/2018/03/26/facebook-platform-changes/

I'm afraid there's not much we can do about that at the moment, we'll just have to wait and see what Facebook does

**Comment by yipcma** [comment]
Thanks @akelad for checking. Let's wait and see then.
