### ISSUE TITLE
Fix RasaNLUConfig import 

### ISSUE THREAD

**Issue by akelad** [RasaHQ/rasa_core#321]
The interpreter imports RasaNLUConfig which no longer exists
https://github.com/RasaHQ/rasa_core/blob/master/rasa_core/interpreter.py#L236

**Comment by Harish0596** [comment]
Can you please be more specific

**Comment by akelad** [comment]
This is more of a note to self, core imports some things that no longer exist in rasa_nlu because we made big changes recently.

**Comment by tmbo** [comment]
I guess we can close this since it should be fixed.
