### ISSUE TITLE
Fixed intents and entities

### ISSUE THREAD

**Issue by bhaskarvarman** [RasaHQ/rasa_core#324]
Rasa Core version: Latest

Python version: 3.6

Operating system: Win10

Issue:
Not an issue but a question.
This is around the documentation around fixed intents and entities(https://core.rasa.com/interpreters.html#fixed-intent-entity-input).

Can you please share some examples or detailed document around this?

Thanks,
Bhaskar

**Comment by akelad** [comment]
Generally this is something we use to check whether the core model is behaving correctly, and see why it's not, without having to rely on NLU.

**Comment by Shehzad777** [comment]
Still interesting. Would love to see an **example** on how to use this for a production bot to get the bot to start the conversation or if you need to send the bot some initial info (entities). 

One other use case I see here is if you want to make sure a certain story line is followed when a bot is queried on some specific page. e.g. the same bot could be a master of cart filling one page and master of support on the support page.

Thanks.
