### ISSUE TITLE
Bot Automatically triggers Action_listen even when the stories does not have such a Flow

### ISSUE THREAD

**Issue by Koushik0890** [RasaHQ/rasa_core#325]
**Rasa Core version**: 0.8.5

**Python version**: 3.5.4

**Operating system** (windows, osx, ...): Ubuntu

**Issue**:
Bot Automatically triggers Action_listen even when the stories does not have such a Flow. I have a Greet Intent and then the next action by the bot is to ask for an input from the user. I am in the initial phase of development and i have just one story to train. But even though the story flow is Greet>Ask, the Bot follows this Flow User Input>Greet>Listen>User Input>Ask, but it should be like User Input> Greet> Ask.

Please help me understand this. Do let me know if more details are required.

**Content of domain file** (if used & relevant):
```yaml

```

**Comment by akelad** [comment]
Can you post your story file please?

**Comment by Koushik0890** [comment]
## Story_1
* greet
 - utter_greet
* ask_number
 - utter_ask_number

I have just this as a story and nothing more, the intent is that the bot will greet the user and then ask him to enter a number to proceed further.

**Comment by Koushik0890** [comment]
Also, 
I tried modifying the story as below;
*greet
  - utter_greet
  - utter_ask_number

And the bot is not greeting the user. I am only  feeding a single story to test the functionality.

**Comment by tmbo** [comment]
Alright, can you share the domain file as well so we can try to reproduce this? That would be super helpful :+1:
