### ISSUE TITLE
How to execute bot action via HTTP

### ISSUE THREAD

**Issue by venkat915213** [RasaHQ/rasa_core#326]
**Rasa Core version**:
 0.8.2

**Python version**:  
3.6

**Operating system** (windows, osx, ...):  
osx

**Question**:
How to execute the bot action via HTTP from a UI. I am able to pass the text from the UI via HTTP to get the intent. If I want to execute a bot action similar to action_search_restaurants in the restaurant bot example. 
Could you please help me answer the question.

**Content of domain file** (if used & relevant):

**Comment by amn41** [comment]
I guess you are using Rasa Core over HTTP. Are your actions implemented in python? In that case you can run the actions by sending messages to the `/parse` endpoint. See [here](https://core.rasa.com/http.html#post--conversations-(str-sender_id)-parse)

**Comment by venkat915213** [comment]
Thank you for the responding. Maybe I am misunderstanding. I thought if you use the /parse endpoint, Rasa Core will respond back with the intent and entities withe confidence. I don't see how a bot action get executed. For example, If i want to execute a bot action ( written in python) by a user response to be "yes" ( affirm). Could you please share me with an example.

**Comment by amn41** [comment]
if your actions are written in python, you don't have to use the HTTP API. You can run your bot like this (for example to connect to facebook) :

```
python -m rasa_core.run -d models/dialogue -u models/nlu/current \
   --port 5002 --connector facebook --credentials fb_credentials.yml
```

http://core.rasa.com/tutorial_basics.html#bonus-handle-messages-from-facebook

or otherwise you can create your own [run script](https://github.com/RasaHQ/rasa_core/blob/master/rasa_core/run.py) if you want more flexibility

**Comment by venkat915213** [comment]
Thank you. This makes sense. One follow-up -  If I have created my own UI that will be used in a website and i am using HTTP call to pass the text using /parse endpoint, how can I achieve executing the bot action. Thank you for taking the time to respond. In my code, I am using this,
response = requests.get("http://localhost:5002/parse",params={"q":request.form["text"],"project":"default", "model":"current"})

**Comment by amn41** [comment]
in this case you can implement your own input channel, see [here](https://github.com/RasaHQ/rasa_core/blob/master/rasa_core/channels/custom.py) for an example. Then you can run with that (in a custom run script) instead of the pre-existing facebook/slack channels.

**Comment by venkat915213** [comment]
Thank you. Can this be used to execute bot action as well.

**Comment by luisdemarchi** [comment]
@amn41 I was looking at this, I had thought of creating my own integrator with facebook to be able to intercept and record all the interactions in a database for later queries in an administrative panel. Is there another way?

**Comment by tmbo** [comment]
@luisdemarchi yes that is one way to do it. The other one is to use the persisted trackers from the tracker store. Each conversation will create a tracker which will be persisted in there (by default just in memory, but you can store them in e.g. mongodb). That tracker contains all the user messages as well as bot actions or any other events (e.g. restarts, set slots, ...)
