### ISSUE TITLE
custom slot type 

### ISSUE THREAD

**Issue by lg05** [RasaHQ/rasa_core#327]
**Rasa Core version**:0.8.05

**Python version**: 3.6

**Operating system** (windows, osx, ...):linux

**Issue**:
I create a custom slot type when i referenced the custom slot type in the domain file, it 
warns the custom slot type module path is wrong.I don’t find how to reference custom slot type in domain file in rasa core document .
anyone who can show me a
example is very appropriate ,thanks

**Content of domain file** (if used & relevant):
```yaml

```

**Comment by akelad** [comment]
It's wherever the file containing your custom slot is. So say you created the file custom_slot.py in the same directory as your domain file, and your custom slot class is called CustomSlot, then it would be: `custom_slot.CustomSlot`

**Comment by lg05** [comment]
@akelad thank for your reply .I put the custom slot’s python file in the same directory as the domain file ,but it still warn the custom slot type module path is wrong 
the domain file slots set as follow:
slots:
     money:
          type:money_slot.money

when I run the code :python -m rasa_core.train -d domain.yml -s stories10.md -o model_new.
the warning as follow: 
valueError:failed to find slot type.Neither a known type nor. If you are creating your own slot type,make sure its module path is correct: money_slot.money

**Comment by DylanRedfield** [comment]
Did this ever get figured out? I'm having the same issue

**Comment by amn41** [comment]
@DylanRedfield are you ablte to import the slot class normally? e.g.
```
python
>>> from module import MySlotClass 
```
