### ISSUE TITLE
categorical slots and Memoization Policy

### ISSUE THREAD

**Issue by ctrado18** [RasaHQ/rasa_core#330]
Do categorical slots influence also prediction for the Memoization policy or only for Keras (ML based policies)?

**Comment by amn41** [comment]
yes.
any slot type other than `unfeaturized` will influence the policy, doesn't matter which one it is.

**Comment by ctrado18** [comment]
thanks! I face the problem that memoization always has prob 1 so that always the action of memo is taken even if the (right) different action has prob... 0.999...And keras is of course not so reliable for relativ small training data,so I would like to use something like memo...

**Comment by amn41** [comment]
if memoization is choosing the wrong action, one option is to take it out as you say, or increasing your `max_history` should also work

**Comment by ctrado18** [comment]
If you have short dialogues (up to 3 turns) does it makes sense to choose max_history as let's say 10?

**Comment by amn41** [comment]
I suspect you have clashing stories. i.e. you have stories where the last `max_history` turns are identical but the action is different. That's fine for the Keras policy, but if you use the memoization policy it will just choose one of them (whichever was seen last).

**Comment by ctrado18** [comment]
Ok thanks. That is god at the moment. But maybe I do not understand the augmenation factor right. I used it with vale of 50. So every sequenc is now of length 50? So the prop for small data sets is high that the last 5 turns are identical?

to interactive learning: Does interacctive learning an supervised learning use realy the same methods? Because in interactive learning the proposed action is always different from supervised. I use for bot memo and keras policy.

**Comment by ctrado18** [comment]
Yes. Thank you but i think I did find my problem. My bigger problems are here:

https://github.com/RasaHQ/rasa_core/issues/354

https://github.com/RasaHQ/rasa_core/issues/353

Mybe you coul response to this? I think they are also important for others!

**Comment by ctrado18** [comment]
@amn41 @tmbo 

> I suspect you have clashing stories. i.e. you have stories where the last max_history turns are identical but the action is different. 

what is the definiton of "turn". I use just 2 turns (in my opinion: the message input) which are identical but at the end with different action but before this action I set a specific catgegorical slot (yes or no). So this is dependent of this slot of course. Keras chooses right, but not Memo. Is it possible that imbalance can also lead to this wrong action by memo? Because I have more examples for one specific slot (and for that it works fine).

**Comment by amn41** [comment]
can you please post the stories here? that will help a lot to figure out what's going wrong
