### ISSUE TITLE
Cannot access slot from SlotSet

### ISSUE THREAD

**Issue by ctrado18** [RasaHQ/rasa_core#337]
Hi,

I have the issue that the slot is not set in a custom action with SlotSet. For checking purpose I want to get the slot right after SlotSet with get_slot:

```

 def run(self, dispatcher, tracker, domain):


        if entity==value:
            SlotSet("slot", "yes")
            f=tracker.get_slot("slot")
            dispatcher.utter_message(f)
            return []
```
Setting slot with tracker._set_slot("slot", "new_slot_value") works!

Where is the difference between SlotSet and _set_slot?

Is it possible that SlotSetc sets the slot after the passed event and not during an event?

**Comment by amn41** [comment]
your action should *return* a `SlotSet` event rather than just creating one, e.g:

```
 def run(self, dispatcher, tracker, domain):


        if entity==value:
            f=tracker.get_slot("slot")
            dispatcher.utter_message(f)
            return [SlotSet("slot", "yes")]
```

**Comment by amn41** [comment]
you should not use `set_slot` :) the tracker should not be modified by any other code, but just receive events it will use to update itself.

**Comment by ctrado18** [comment]
Ok. Reason is that i might no directly understand the underlying mechanism of trackers and events. When is the apply_to function of events called? But am I right that the returned SetSlot modiefies the slot which is only in a new event accessable and not in the current one (like above inside the custom action)?

**Comment by akelad** [comment]
Yes exactly, it is accessible afterwards.

**Comment by ctrado18** [comment]
thanks!
