### ISSUE TITLE
A story with two contexts?

### ISSUE THREAD

**Issue by luisdemarchi** [RasaHQ/rasa_core#339]
**Rasa Core version**: 0.8.5

**Python version**: 3.6

**Operating system**: osx

**Issue**:
I would like to understand how to put together a story with a set of choices. I'll try to create a sample scenario by indenting:

```
user says: I have some open debit?
IF QUERY:
    bot says: No.
    user says: Thanks.
    bot says: Goodbye
ELSE:
    bot says: It has yes, the plots of January and February. Would you like to pay some?
    IF USER RESPONSE:
        user says: no
        bot says: I get a discount if I pay now
        [..]
    ELSE:
        user says: Yes, I'm going to pay January
        bot says: great, I'm sending in your email.
```

I understand the first comparative, I do the treatment in python and I send different texts, but in addition to the different texts they would be different "contexts" (thinking like DialogFlow)

**Comment by luisdemarchi** [comment]
Reading the excellent document available, I believe I was able to find the solution. Can anyone validate if this logic represents the two comparisons I have listed before?

```
## story.1.0
* open_debt
   - action_is_open_debt
> check_is_open_debt

## story.1.1
> check_is_open_debt
* thank_you
  - utter_goodbye

## story.1.2
> check_is_open_debt
* deny
  - action_suggest_discount

## story.1.3
> check_is_open_debt
* pay_debit
  - action_send_debit
```

**Comment by akelad** [comment]
yes pretty much. It might also be useful to have a boolean slot called "open_debt" and setting it as true or false dependent on whether the user has open debt or not. This can then be added to the stories and you can have different paths dependent on the value

**Comment by luisdemarchi** [comment]
@akelad Sorry, but for me that part of the documentation was a little strange to understand. Looking at [documentation](https://core.rasa.com/patterns.html#collecting-information-to-complete-a-request), how did I get the name of the "NumberOfPeopleSlot" method?

Returning to my code, would it be possible to try to show how you would put a variable?

**Comment by akelad** [comment]
do you mean how do you get the value of a slot? that would be with `tracker.get_slot('number_of_people')` in a custom action. 

Also do you you still need help with the second part of your question? if yes, could you elaborate a bit please

**Comment by tmbo** [comment]
I'll close this for now, please let us know if you have any further questions.
