### ISSUE TITLE
Stackoverflow: Can we create a tag for Rasa Core?

### ISSUE THREAD

**Issue by luisdemarchi** [RasaHQ/rasa_core#348]
I made a request to create a project tag, within stackoverflow. Can you vote?

https://meta.stackoverflow.com/questions/365556/can-we-create-a-tag-for-rasa-core

**Comment by luisdemarchi** [comment]
hi!!!

https://stackoverflow.com/questions/tagged/rasa-core

**Comment by amn41** [comment]
awesome! thanks for taking the initiative luis

**Comment by luisdemarchi** [comment]
@amn41  Thank you for that great job. It might be interesting to guide questions over there, so I would use it here only for bugs about the code or build.
