### ISSUE TITLE
categorical slot with less values than available

### ISSUE THREAD

**Issue by ctrado18** [RasaHQ/rasa_core#353]
hi,

let's say you have an entity problem with 5 problems. But you just want to consider 3 of them for your stories. So you create in the domain file:

```
  problem:
    type: categorical
    values:  p1,p2,p3
```

Than I thought that only those 3 values would be recognized as slots? But I find that if a message conains an entity with problem p4 than this will be also a catgeorical slot of value p4?
But I want to ignore the rest of values other than defined in the slot above.

**Comment by akelad** [comment]
In featurization it does get ignored! As specified in the warning here:
https://github.com/RasaHQ/rasa_core/blob/master/rasa_core/slots.py#L194
So in terms of stories it's like the slot is still empty.

**Comment by ctrado18** [comment]
ok, because i printed `tracker.slots` and it was filled with a value not listed in the slot statement..

**Comment by akelad** [comment]
yes, but if you look at the featurization (which you can see by enabling debug mode with --debug in rasa_core.run) you can see that the feature of that slot is 0.

**Comment by ctrado18** [comment]
I am confused with custom slots. The entity come from the NLU. This is also the slot. Do I have to write in the stories inside the intent brackets the NLU entity or the custom mapped slot? And after the intent I write the custom slot?

```
* inteenr{"problem": "p5"}
  - slot{"problem": "other"}

```

**Comment by ctrado18** [comment]
Maybe I reformulate my issue.

You have entity `problem `(p1...p5):

```
 slots:
    problem:
    type: categorical
    values:  p1,p2,p3

```
Now NLU detects entity value p4. Now also the slot gets filled with p4 right? It just doesn't influence the story, right? So I still have the slot vlaue as:

```
'problem': <CategoricalSlot(problem: p4)>,
```
but it will not influence the next action. But then how do I have to write the story for this?

As the value p4 is treated as the the slot is not filled, though it is filled with its value (?!). I would write:

```
* cost{"problem": null}
  - slot{"problem": null}
  - utter_soemthing
```

To handle situations with all other problem values?

**Comment by tmbo** [comment]
Yes either doing it with `null` or you can also use your `p4` as an example directly.

**Comment by akelad** [comment]
So I think the correct form for that would be: 
```
* cost{"problem":"p4"} #this "p4" value here really doesn't matter at all, it can be anything
  - slot{"problem": null}
  - utter_something
```
Does this fix your problem? If not, can you share your stories and domain file so I can try to reproduce.

**Comment by ctrado18** [comment]
But why do I need to train with `p4` if it does not influence prediction? I found that `p4` indeed influences my nex action?! I think you can test it with any simple story. Just use categerical values. Furthermore, how can I I find out how strong all slots give weights to prediction?

**Comment by akelad** [comment]
You're not training with the specific value `p4`, in the stories you're writing this line `*cost{"problem":"p4"}` just indicates an entity is present - so the value here could be literally anything, e.g. `*cost{"problem":"blabla"}`. The important part is the `slot{"problem": null}` here. And sure I can, but it'd be a lot quicker if I just had the relevant parts of your domain/stories file. 

So are you still having an inaccurate prediction problem even when that story is in the training data?

**Comment by ctrado18** [comment]
But `problem` is a categrocial slot. I thought for the entity in the intent `*cost{"problem":"p4"}` the slot is set automaticaly, though I put the slot afterwards of course to make sure. And of course I would train that in this way. But my problem is mybe a little different (?): I have two entities. If I train stories for the one entity and NLU detects this entity right, but also it detects the entity `problem` with value `p4` too, it influences the next action.
So I should write: `*cost{"right_entity": "value", "problem":"p4"}` and `slot{"right_entity": "value", "problem":"p4"}` ?
But as you saidin another issue the categorcial slot value not listed in the doamin behaves like null? But why I should write this then at all in the stories?
