### ISSUE TITLE
null value for a slot

### ISSUE THREAD

**Issue by ctrado18** [RasaHQ/rasa_core#354]
I wonder if I use the null value for a slot value in the right way. Let's say you want to trigger a specific acton if a specific entity value is not set, independent if another slot ist set. So:

```
* greet
  - utter_greet
  - utter_ask_help
* cost{"entity1": null}  
  - slot{"entity1": null}
  - utter_something
```
So, a content of cost{"entity2": "here is something"} should underly above story because entity1 is null, right?

But I have the feeling that you have to train the situation with cost{"entity2": "here is something"} separately?

**Comment by akelad** [comment]
So what you're asking is not possible in that way. 
but for your scenario you could do something like: 
```
## no entity
* cost
  - utter_something

## entity
* cost{"entity1":"example"}
  - slot{"entity1":"example"}
  - utter_something_else
```

And if you want to distinguish between stuff like val1, val2 you could use categorical slots.

**Comment by ctrado18** [comment]
But what is the difference between:

```
* cost{"entity1": null}  
  - slot{"entity1": null}
  - utter_something

```

and

```
* cost
  - utter_something

```

This should be same for one entity. But I have two entities. That is why I wanted to use

```
* cost{"entity1": null}  
  - slot{"entity1": null}
  - utter_something

```

in the sense that this is right for 

```
* cost{"entity2": "val2}  
  - slot{"entity2": "val2}
  - utter_something

```

because entity1 is not set (null), right?

**Comment by tmbo** [comment]
If the type of the slot os set to `text` you should get exactly that behaviour: a difference between `null` and any value, but the value itself doesn't matter as long as it is not `null`.

**Comment by ctrado18** [comment]
@tmbo tahnk you but I cannot follow you statement. Maybe you can reformulate what you mean. For a text slot is the follwoing the same?

```
*Kosten{"entity1": null} 
```
and just
```
*Kosten
```
But the first one just excludes the case when entity1 is null, right? So if anoter entity2 is not null it falls in the first class wheresas the second cas excludes both cases (all entity values have to be zero), right?
