### ISSUE TITLE
Validate a slot value against a db

### ISSUE THREAD

**Issue by Egalite123** [RasaHQ/rasa_core#356]
**Rasa Core version**:  0.8.1

**Python version**:  2.7.10

**Operating system** (windows, osx, ...): Mac OS High Sierra (10.13.3)

**Issue**: How to validate an input while filling a slot?

Let me use Restaurant Bot example to illustrate the issue.
We need to fill Cuisine, people, location slots to book a restaurant. 

I want to validate the Cuisine type against a list values / db. If user enters something outside the list, how do I ensure the validations are carried out and slot values are not set to junk values and ask for the unfilled slot value?
I was trying to use check_points to validate a bool slot to set if the value is acceptable or not.
Not clear as to how to manage this. 
Is it possible to loop a story (till a valid value is entered by the user)?

**Content of domain file** (if used & relevant):
```yaml

```

**Comment by Egalite123** [comment]
Any one else faced similar issue? Any solutions or workarounds, please!

**Comment by HCIS2020** [comment]
Same problem, please give me help!

**Comment by tannn** [comment]
This is the closest to a workaround that I have found: https://github.com/mrbot-ai/rasa-addons#input-validation

**Comment by basque21** [comment]
Same problem here!

**Comment by akelad** [comment]
Thanks for raising this issue, @tmbo will get back to you about it soon.

**Comment by akelad** [comment]
the merge of PR https://github.com/RasaHQ/rasa_core/pull/1013 allows this
