### ISSUE TITLE
Slack connector not working

### ISSUE THREAD

**Issue by ctrado18** [RasaHQ/rasa_core#360]
hi,

this connector:
https://core.rasa.com/connectors.html#slack-setup

is not working because of some challenge paramter. What I have to do to set up properly the slack connector (also for using buttons)?

**Comment by tiwari85aman** [comment]
refer #270 you will find the solution

**Comment by ctrado18** [comment]
I works via core. run but not with python code! In the field for event subscription I get no verfied but the message that the challenge paramter is missing!

```

`from rasa_core.channels import HttpInputChannel
from rasa_core.channels.slack import SlackInput
from rasa_core.agent import Agent
from rasa_core.interpreter import RegexInterpreter

# load your trained agent
agent = Agent.load("dialogue", interpreter=RegexInterpreter())

input_channel = SlackInput(
   slack_token="YOUR_SLACK_TOKEN",  # this is the `bot_user_o_auth_access_token`
   slack_channel="YOUR_SLACK_CHANNEL"  # the name of your channel to which the bot posts
)

agent.handle_channel(HttpInputChannel(5004, "/app", input_channel))`
```

**Comment by akelad** [comment]
are you still having issues with this?

**Comment by chinnusujitha** [comment]
Hi,
I'm trying to connect the moodbot to slack and follow this tutorials:
[](https://core.rasa.com/tutorial_basics.html) 
[](https://core.rasa.com/connectors.html)

And i used ngrok to connect to the slack events:
https://XXX.ngrok.io/slack/events
and for interactive components the url is
https://XXX.ngrok.io/slack/actions
 But its throwing an error 
**Your URL didn't respond with the value of the challenge parameter.**

Can someone please me on solving this issue.

Thanks in advance.

**Comment by akelad** [comment]
Might be something to do with this? "The outgoing webhook integration is only available in public channels. If you would like to get data out of private groups and DMs in real-time, try a slash command." from https://api.slack.com/custom-integrations/outgoing-webhooks

I assume you're trying this in a private group/DM?
