### ISSUE TITLE
Slots getting filled with wrong values for unrelated intents

### ISSUE THREAD

**Issue by dheeraj-pb** [RasaHQ/rasa_core#363]
**Rasa Core version**:
0.8.5
**Python version**: 
Python 3.5.4 :: Anaconda 4.2.0 (64-bit)
**Operating system** (windows, osx, ...):
Windows 10 Enterprise 64-bit
**Issue**:
I have an entity defined among the training examples of one particular intent and a slot defined in Rasa-Core's files to fill that particular entity. However the entity and slot values are getting populated with wrong values like 'hey' from unrelated intents like 'greet'. (The entity which I have defined using the training examples is not even remotely related to words like 'hey' by any means. They are nouns of technical nature, to be specific.)
What I would like to know is how can I tie an entity (or even a slot, as either should serve my purpose) to a particular intent so that it is not filled by random values from other user inputs which belong to different intents?

Thanks in advance...

Edit : I have tried looking for the answer for this issue and a few other problems I faced in the documentation but often will have little luck. I have felt that the documentation section, especially the section discussing Slots and Actions could be more elaborate explaining the concepts and idea as to what they are, apart from very simple examples which are present, Although I was able to find quite many pages written on success stories using RASA stack, there is close to zero pages which one can use to get an idea on the library apart from the official documentation. 

**Content of domain file** (if used & relevant):
```yaml

```

**Comment by foxjr** [comment]
The entities and the slots are, by default, unrelated. You can define NLU objects that map a phrase to a certain intent and show example entities to be extracted, but that won't help you with your slot fills. When you say you have a slot defined in your Rasa files, do you mean in your domain? Once the slot is defined, slot-filling is shown through the stories. 
For example:
```
...
* inform[issue=power]
  - slot{"issue":"power"}
  - action_search_kb
  - slot{"article":"This is an example of text that was retrieved from a knowledge base (kb). It was placed into a slot by action_search_kb. The following utterance can refer to it by using the {article} placeholder in the template."}
  - utter_kb_info
  - utter_more_help
* decline
  - utter_goodbye
...
```
What's going on in that example is `power` was extracted as the entity `issue`, and then a slot by the same name was filled with the same value. The slot could have been called anything. Creating stories that follow the format I've given establishes the association between an entity extraction and a slot-fill, but there needs to be lots of stories.

**Comment by dheeraj-pb** [comment]
Thanks for your response. So that confirms that entity extraction and intent classification happens separately and this has to be taken care by me in the training examples or by custom logic using Action classes.
Could you also please look into the matter of having a more detailed documentation? Because for example, dispatecher.utter_button_message was one of the function which I wanted to use almost immediately after starting to work in a simple use case but I was not able to find any documentation.
I was able to continue after scanning through the source code for about 45 minutes but it would have been much helpful if there was more documentation from the devs. Thanks!

**Comment by akelad** [comment]
There's documentation here on how to add buttons to utterances in the template here https://core.rasa.com/domains.html#images-and-buttons
But yes, we'll keep that in mind.

I'll close this for now, let us know if you're having any more issues
