### ISSUE TITLE
how to handle this empty response scenario?

### ISSUE THREAD

**Issue by Selvaganapathi06** [RasaHQ/rasa_core#364]
i checked in restaurant bot have 1000 stories but if i enters a questions in the order which is in stories list it is responding with correct answer but if i change the order of conversation which is not in stories list it is not responding with exact answer and sometimes it is showing errors and the response is empty. how to handle this empty response scenario?

**Comment by foxjr** [comment]
Are you sure it's responding with an empty string? Could it just be listening? Can you post an example conversation and any errors? Also, how many epochs are you training for? 

I haven't looked over those stories, but it seems like the model could be overfit and not generalizing very well.

**Comment by Selvaganapathi06** [comment]
i have used restaurant bot example and below is my training information
  agent.train(
            training_data_file,
            max_history=4,
            epochs=400,
            batch_size=200,
            validation_split=0.2
    )

**Comment by akelad** [comment]
I'm not sure what you mean with "changing the order of conversation". Can you please post an example of a conversation that goes wrong? And also the errors you're getting.
