### ISSUE TITLE
Trying to understand Interactive Learning

### ISSUE THREAD

**Issue by luisdemarchi** [RasaHQ/rasa_core#368]
**Rasa Core version**: 0.8.5

**Python version**: 3.6

**Operating system**: osx

**Issue**:
I wonder if the contributors to this project are taking care of the new tag in stackoverflow (rasa-core)? I believe that there is an easier place for future research.

I put a question there:
https://stackoverflow.com/questions/49743585/chatbot-trying-to-understand-interactive-learning

**Comment by akelad** [comment]
Are you still having issues with this?

"How do I create multiple stories with interactive learning? Would have to make a way "happy", generate the file, start a new training and then join the files? I tried to fix multiple paths, in the file generated by the end it seems to have become a single story." > you have to export each time and then start a new online training process.

**Comment by luisdemarchi** [comment]
@akelad I gave up on Rasa. Because of library spaCy, which for Portuguese is not anything accurate even after putting 3.5 gb of vectors of my language. The competitor UDPipe is sensational but is not supported by Rasa and also can not be used commercially.
