### ISSUE TITLE
No Interpreter output about Intent/confidence/entities when using Agent

### ISSUE THREAD

**Issue by fakesecret** [RasaHQ/rasa_core#37]
**Rasa Core version** : 0.7.3

**Operating system** (windows, osx, ...): no matter

**Question solved**: In order to retrieve the NLU interpretation of the chatbot, the parse_data including intent/confidence/entities can be found this way:

```
sender_id = "user"
lst_out_msg = agent.handle_message(text_message=my_sent, 
            sender_id=sender_id)
tracker = agent.tracker_store.retrieve(sender_id=sender_id)
if tracker:
    print (tracker.current_state()) # or do other things
```

**Comment by rabberbock** [comment]
@fakesecret 
You can get the state from the tracker.
```
tracker = agent.tracker_store.get_or_create_tracker("sender_id") 
# get current tracker state to log
tracker.current_state()
```

**Comment by fakesecret** [comment]
@rabberbock Thanks for your advice. The tracker can provide interpreter's parse data (Intent/confidence/entities), if we set correctly "sender_id" for agent.handle_message method.

Do you have an idea that whether we can get core's action name and confidence?

**Comment by tmbo** [comment]
We can most certainly include the action confidence somewhere, that is already logged in another issue though. For the other part, you are basically looking for something like:
```
r = agent.interprete(message)
```
where `r` now contains the result of running the NLU that has been setup on the message?

**Comment by fakesecret** [comment]
@tmbo At my initial discussion with you a week a go, we decided to make this issue for improvement for reporting NLU's Intent/confidence/entities and Core's Action/confidence.

Now, the first part can be solved as below (thanks to @rabberbock ):
```
sender_id = "user"
lst_out_msg = agent.handle_message(text_message=my_sent, 
                              sender=sender_id) # keyword "sender" need to be changed
tracker = agent.tracker_store.retrieve(sender_id=sender_id)
if tracker:
    print (tracker.current_state()) # or do other things
```
The tracker.current_state() contains NLU's interpretation. It might be good to add this into docs and examples.

For the 2nd part, Action/confidence info can be put into tracker in the same manner in the future.

**Comment by fakesecret** [comment]
@tmbo The main question is solved. You can close this issue.
