### ISSUE TITLE
Can Rasa_core connect multiple Rasa_nlu 

### ISSUE THREAD

**Issue by Tenglu** [RasaHQ/rasa_core#379]
Rasa Core version: 0.8.5

Python version: Python 3.6

Operating system (windows, osx, ...): Windows 10

Hi,
I am wondering if a Rasa_core can connect multiple rasa_nlu? In my scenario, there are tens of intents. I think it may be better to classify intents to categories and each rasa_nlu for a category. And there is one center rasa_nlu that is to decide which domain it is, and then pass to the specific rasa_nlu. I just think it may can improve the accuracy. Is that possible to achieve? Or is one rasa_nlu can handle tens of intents? Thank you.

**Comment by akelad** [comment]
Yes that number of intents should be no problem with one NLU model. As long as you have enough training examples and the intents aren't too easily confused. You can use the evaluate script to test how well your model is doing https://nlu.rasa.com/evaluation.html

**Comment by amn41** [comment]
If you really want to do this, though, you can. You just have to subclass the `Interpreter` class, creating something like a `MetaRasaNLUInterpreter`

**Comment by Tenglu** [comment]
@akelad So Theoretically, rasa_nlu can handle even more than one handred intents as long as I have enough training examples and intents are not too easily confused, right?

**Comment by Tenglu** [comment]
@akelad @amn41 Can I ask if you we need to handle handreds of intents, can we use single rasa_nlu to train? Or is there a better solution? Thank you.

**Comment by akelad** [comment]
If there's hundreds of intents, then it'd probably be better to have multiple nlu models and use them according to the use case you're currently dealing with.

**Comment by tmbo** [comment]
I'll close this for now, please let us know if you have any further questions.
