### ISSUE TITLE
repeat last action 

### ISSUE THREAD

**Issue by lg05** [RasaHQ/rasa_core#380]
**Rasa Core version**: 0.8.5

**Python version**: 3.6

**Operating system** :linux

**Issue**:
when the user input information is out of flow ,the bot can’t understand the right user intent,i want to the bot repeat the last action is mean that let users input the right information again .
Is there any way to solve the problem? 
How can i write the flow in stories to solve the problem?
any reply is appreciated.

**Content of domain file** (if used & relevant):
```yaml

```

**Comment by akelad** [comment]
take a look at this https://github.com/RasaHQ/rasa_core/issues/137#issuecomment-367734878

**Comment by lg05** [comment]
thanks

**Comment by tmbo** [comment]
I'll close this for now, please let us know if you have any further questions.
