### ISSUE TITLE
How to get User message ?

### ISSUE THREAD

**Issue by dilipbobby** [RasaHQ/rasa_core#396]
**Issue**:
I want to get user message directly, when one of the intent is matched.I want to write a custom action class where I directly want to get users message ! Is it possible to get ? For getting Entities we are using tracker.get_slot() in same way do we have any other method to get user message directly In action class ?

**Comment by akelad** [comment]
`tracker.latest_message.text` will do that

**Comment by dilipbobby** [comment]
when i connected bot to the slack at back end it is generating user_id and bot is able reply each user without any confusion.Now , I want to do without slack,instead of slack i will connect to a website then does core will take care of  users sending messages to bot ? if yes then how can I get those user_id's.

**Comment by tmbo** [comment]
@dilipbobby you need to create the user id's on your end. core just uses them as ids for the conversation - so as long as you send the same id, it will be the same conversation. if you send different ids, core will assume these are different conversations. https://core.rasa.com/http.html#starting-a-conversation

**Comment by Brijeshlakkad** [comment]
Can i get messages or intent of previous conversation?

**Comment by Ghostvv** [comment]
@Brijeshlakkad all the events are stored in `tracker.events` that you can access from your custom action

**Comment by Brijeshlakkad** [comment]
sorry @Ghostvv , but how can i use them?

**Comment by Brijeshlakkad** [comment]
Can anybody help me? I want to get previous user utterances in custom action.

**Comment by ashukrishna100** [comment]
For version 0.11 and above Use this

`(tracker.latest_message)['text']`
This is for version 0.10 and lower `tracker.latest_message.text`

**Comment by FRTNX** [comment]
Greetings. Sorry for digressing but I'm sure the answer might benefit those on this thread too. How do I get the current user_id from actions.py?

**Comment by MetcalfeTom** [comment]
@FRTNX you can use `tracker.get("sender_id")`

**Comment by FRTNX** [comment]
Thank you for the quick response @MetcalfeTom

**Comment by MetcalfeTom** [comment]
No problem!  I should have mentioned that this is only for when using the serialized flavor of the tracker.  Otherwise `tracker.sender_id` will work.

In general the tracker is your best tool for looking up any and all information from a conversation.  It also has a bunch of other useful methods defined in `trackers.py`
