### ISSUE TITLE
Implement action masks from HCN paper (to enable constraint checking)

### ISSUE THREAD

**Issue by tmbo** [RasaHQ/rasa_core#397]
Would allow to e.g. check in an action if certain slots are set, masking the action from the predicted policy probabilities if it should not be executed.

E.g.

```
class MyAction(Action):
  def name(self):
    "my_action"
  
  def can_be_run(tracker):
    return tracker.slot("my_slot") is not None
```

**Comment by vedmathai** [comment]
I tried searching, but would you be able to provide a link to the HCN paper you are referring to here? Thanks!

**Comment by amn41** [comment]
https://arxiv.org/abs/1702.03274

**Comment by akelad** [comment]
the merging of the forms PR (#1013) will allow this -- an action will be able to say it can't run with an `ActionExecutionError`

**Comment by akelad** [comment]
The PR was merged
