### ISSUE TITLE
agent.handle_message() returns empty text after a few conversations

### ISSUE THREAD

**Issue by ewagner70** [RasaHQ/rasa_core#401]
**Rasa Core version**: 0.9.0a2
**Rasa NLU version**: 0.12.2
**Python version**: 3.6
**Tensorflow version**: tensorflow-gpu 1.7.0
**Operating system** (windows, osx, ...): Ubuntu 17.10
**Issue**: agent.handle_message() returns only empty dict/text after a few conversations. See example below:

George: hi
Bot: hey there None!
George: my name is eric
Bot: Good to know you, None
George: i am called eric
Bot: Good to know you, None
George: my parents call me eric
Bot: Good to know you, eric
George: bye
Bot: KEINE ANTWORT ## means dict/text is empty, i.e. None
George: that's correct
Bot: KEINE ANTWORT  ## means dict/text is empty, i.e. None
George: hi       
Bot: KEINE ANTWORT ## means dict/text is empty, i.e. None
George: my parents call me eric
Bot: KEINE ANTWORT ## means dict/text is empty, i.e. None
George: 

**Content of domain file** (if used & relevant):
see attached zip files 
```
Thx in advance for your help!
KR Eric
[test_rasa.zip](https://github.com/RasaHQ/rasa_core/files/1939666/test_rasa.zip)

**Comment by akelad** [comment]
hmm, is there any reason you can't just use the rasa_core run script? Could you try that and see if you're still having problems?

**Comment by ewagner70** [comment]
not necessary ...after restructuring the stories and NOT using the "slot" assignment, this None return vanished. I switched to "inform".

(1) However, can you explain what that "slot{"slotname":"slotvalue"} really does? because it is not necessary to assign the slot value (it's done automatically if entity and slot are named the same) !

**Comment by akelad** [comment]
yes so that `slot{"slotname":"slotvalue"}` thing is **only** necessary when you're setting slots with a custom action, and those slots are of a type different than `unfeaturized`

Gonna close this issue for now since your problem seems to be fixed, let us know if you have more questions

**Comment by saqibahmed515** [comment]
I'm having same problem. I don't have any slots in my stories. I'm using sample stories and domain from the documentation.
My NLU version is 0.12.3. Other than that, all versions are same.

**Comment by akelad** [comment]
@saqibahmed515 can you be more specific? what script are you running etc?

**Comment by saqibahmed515** [comment]
@akelad I trained rasa_core and rasa_nlu with the data given [here](http://core.rasa.com/tutorial_basics.html) using `rasa_core.train` and `rasa_nlu.train`. Now I'm using the trained data in following script to run my bot:

```
from rasa_core.interpreter import RasaNLUInterpreter
from rasa_core.agent import Agent
from flask import Flask, request
from flask_restful import Resource, Api
from json import dumps
from flask import jsonify

agent = Agent.load('test/dialogue', interpreter=RasaNLUInterpreter("test/nlu/default/model_20180511-103427"))


app = Flask(__name__)
api = Api(app)

class Response(Resource):
    def get(self):
        responses = agent.handle_message(request.args.get('q'))
        return jsonify(responses)


api.add_resource(Response, '/respond')


if __name__ == '__main__':
     app.run(port='5002', host='0.0.0.0')
```

This works fine at the start of the conversation but the bot starts to send an empty response after some time as explained in the original issue. 

## Environment
**Rasa Core**: 0.9.0a3
**Rasa NLU**: 0.12.3

**Comment by tmbo** [comment]
Mind trying that with the latest master? We merged a large change that influences the training of the models which might improve the performance for this issue. If there is no answer, this usually means the bot has no idea what to do and doesn't do anything.

**Comment by ewagner70** [comment]
yes, please let us know how to install version 0.9.0a5
pip install rasa_core==0.9.0a5 --user
Collecting rasa_core==0.9.0a5
  Could not find a version that satisfies the requirement rasa_core==0.9.0a5 (from versions: 0.7.0a5, 0.7.0a8, 0.7.0a9, 0.7.0a10, 0.7.0, 0.7.1, 0.7.2, 0.7.3, 0.7.4, 0.7.5, 0.7.6, 0.7.7, 0.7.9, 0.8.0, 0.8.1, 0.8.2, 0.8.3, 0.8.4, 0.8.5, 0.8.6, 0.9.0a1, 0.9.0a2, 0.9.0a3)
No matching distribution found for rasa_core==0.9.0a5

**Comment by saqibahmed515** [comment]
@ewagner70 You can clone the master branch and then run `setup.py`. It will install the latest code.

**Comment by ewagner70** [comment]
I know, tried that, but rasa_core installs in /root/ instead of ~ wither the sudo-H and —user parameter . Any ideas why?

**Comment by tmbo** [comment]
try running `pip install -U git+https://github.com/rasahq/rasa_core.git `

**Comment by saqibahmed515** [comment]
I tried to train with latest rasa_core master and same data and I got following exception:

```
2018-05-15 10:00:37 DEBUG    rasa_core.training.generator - Starting data generation round 0 ... (using 1 trackers)
Processed Story Blocks: 100% 4/4 [00:00<00:00, 1961.79it/s, # trackers=1]
2018-05-15 10:00:37 DEBUG    rasa_core.training.generator - Finished phase. (4 training samples found)
2018-05-15 10:00:37 DEBUG    rasa_core.training.generator - Starting data generation round 1 ... (using 4 trackers)
Processed Story Blocks: 100% 4/4 [00:00<00:00, 768.08it/s, # trackers=4]
2018-05-15 10:00:37 DEBUG    rasa_core.training.generator - Finished phase. (20 training samples found)
2018-05-15 10:00:37 DEBUG    rasa_core.training.generator - Starting data generation round 2 ... (using 16 trackers)
Processed Story Blocks: 100% 4/4 [00:00<00:00, 180.81it/s, # trackers=16]
2018-05-15 10:00:37 DEBUG    rasa_core.training.generator - Finished phase. (84 training samples found)
2018-05-15 10:00:37 DEBUG    rasa_core.training.generator - Found 84 training examples.
Traceback (most recent call last):
  File "/usr/local/lib/python3.6/runpy.py", line 193, in _run_module_as_main
    "__main__", mod_spec)
  File "/usr/local/lib/python3.6/runpy.py", line 85, in _run_code
    exec(code, run_globals)
  File "/app/projects/rasa_core/rasa_core/train.py", line 126, in <module>
    additional_arguments)
  File "/app/projects/rasa_core/rasa_core/train.py", line 100, in train_dialogue_model
    agent.train(training_data, **kwargs)
  File "/app/projects/rasa_core/rasa_core/agent.py", line 191, in train
    raise Exception("Passing `featurizer` and `max_history` "
Exception: Passing `featurizer` and `max_history` to `agent.train(...)` is not supported anymore. Pass appropriate featurizer directly to the policy instead. More info https://core.rasa.com/migrations.html#x-to-0-9-0
```

**Comment by tmbo** [comment]
the parameter `max_history` has moved to the policy level. Take a look at https://core.rasa.com/master/migrations.html#x-to-0-9-0

**Comment by ewagner70** [comment]
@tmbo: 
thx `pip install -U git+https://github.com/rasahq/rasa_core.git --user` worked (i had to use --user in addition)

@tmbo:
the max_history and featurizer issue wasn't necessary until 0.9.0a3, only from 0.9.0a5 onwards, plus to complement the limited documentation for all the poor folks out there in the world:

training the dialogue BEFORE 0.9.0a5:
```
agent = Agent(domain_file, policies=[MemoizationPolicy(), KerasPolicy(), fallback])
agent.train(training_data_file,
            max_history=5,
            epochs=500,
            batch_size=10,
            validation_split=0.2)
```

training the dialogue FROM 0.9.0a5 ONWARDS:
```
agent = Agent(domain_file, policies=[MemoizationPolicy(max_history=5), KerasPolicy(), fallback])
training_data=agent.load_data(training_data_file)
agent.train(training_data,
            epochs=500,
            batch_size=10,
            validation_split=0.2)
```

**Comment by saqibahmed515** [comment]
Also, what do I do with this command to make it work with 0.9.0a5:
`python -m rasa_core.train -d domain.yml -s stories.md -o test/dialogue --debug`
Currently, it is throwing the exception.

**Comment by tmbo** [comment]
That command looks good - we fixed a bug in the training script on master yesterday, so best to run 
`pip install -U git+https://github.com/rasahq/rasa_core.git --user` again

**Comment by PrasannaGaneshu** [comment]
Hi,
Im facing an similar issue..

Im currently using Klein as an API wrapper and able to run RASA Core in my terminal. This is an example of one of the API which is working.

Here is the code snippet :

@app.route(’/api/v1/<sender_id>/validate’, methods=[‘GET’, ‘POST’])

def validate(self, request, sender_id):
    request.setHeader('Content-Type', 'application/json')
    request.setHeader('Access-Control-Allow-Origin', '*')
    request_params = request_parameters(request)
    data=""
    i=""
    try:
        user_sent = str(sender_id).upper()
        info  = db.rasa_cust_info.find({"USERID":user_sent})
        for i in info:
            data = "Hey there, Im BOT"
        #return json.dumps({"wlcm_msg":str(data)})
        return json.dumps(str(data))
    except Exception as e:
        request.setResponseCode(500)
        logger.error("Caught an exception during parse: {}".format(e), exc_info=1)
        return json.dumps({"error": "{}".format(e)}) 
Im able to get a response from this API. However the API shown below is not working…

@app.route(’/api/v1/<sender_id>/respond’, methods=[‘GET’, ‘POST’])

def respond(self, request, sender_id):
    request.setHeader('Content-Type', 'application/json')
    request.setHeader('Access-Control-Allow-Origin', '*')
    request_params = request_parameters(request)
    print("=========Request PARam================: ",request_params)
    if 'query' in request_params:
        message = request_params.pop('query')
    elif 'q' in request_params:
        message = request_params.pop('q')
    else:
        request.setResponseCode(400)
        return json.dumps({"error": "Invalid parse parameter specified"})
    try:
        out = CollectingOutputChannel()
        print("***********", message, "====", out, "====", sender_id)
        response = self.agent.handle_message(message, output_channel=out, sender_id=sender_id)
        request.setResponseCode(200)
        print("TRY: " , response)
        return json.dumps(response)
    except Exception as e:
        request.setResponseCode(500)
        logger.error("Caught an exception during parse: {}".format(e), exc_info=1)
        return json.dumps({"error": "{}".format(e)}) 


Im not able to get the response for the 2nd API which worked perfectly fine with version 7 of RASA.After the upgrade of RASA from 7 to 12 it was not working. Im not able to understand why the code for 2nd API is not working.Requesting your help…

**Comment by arunmiet88** [comment]
ModuleNotFoundError: No module named 'rasa_core.policies.fallback'
where i used 
rasa==0.1.1
rasa-core==0.9.0a2
rasa-core-sdk==0.12.1
rasa-nlu==0.14.1

When i run my chatbot then i face this problem

**Comment by tmbo** [comment]
You need to update to a newer version of core AND use select the version of the software you are using in the documentation. (also, please don't crosspost on existing issues.)
