### ISSUE TITLE
slot not populated in greet (i.e. default population of slot)

### ISSUE THREAD

**Issue by ewagner70** [RasaHQ/rasa_core#402]
**Rasa Core version**: 0.9.0a2
**Rasa NLU version**: 0.12.2
**Python version**: 3.6
**Tensorflow version**: tensorflow-gpu 1.7.0
**Operating system** (windows, osx, ...): Ubuntu 17.10
**Issue**: See example below:

George: hi
Bot: hey there None! ## here should appear "human" instead of "None" (!)

**Content of domain file** (if used & relevant): see attached zip file
Thx in advance!
KR Eric
[test_rasa.zip](https://github.com/RasaHQ/rasa_core/files/1939685/test_rasa.zip)

**Comment by akelad** [comment]
hmm, as far as i can see you haven't specified a default value for the slot in your domain file

**Comment by ewagner70** [comment]
(1) forgive my limited knowledge, but "how do I specify a default value for the slot in my domain file?". I can't see any doc/description - maybe I'm too stupid.

(2) why doesn't the the following story paragraph put the slot name accordingly? the utter_greet appears correctly (!)
## greet path
* greet
  - slot{"username":"human"}
  - utter_greet

**Comment by ewagner70** [comment]
Thx alot!
