### ISSUE TITLE
Form Actions fill more than one slot per entity

### ISSUE THREAD

**Issue by hotzenklotz** [RasaHQ/rasa_core#407]
**Rasa Core version**:
Current Master with Form Fill Actions
(0.9.0a2)

**Python version**: 
2.7 

**Operating system** (windows, osx, ...):
OSX

**Issue**:
I noticed a shortcoming of the new form fill actions. For a sentence: “I want to travel to Berlin” it will extract the entity `spacy_GPE: Berlin`. Now with the auto slot filling of the PR it will fill both my `origin` and `destination` slot with Berlin instead of asking the next question in the form. 

Perhaps add a check where a single entity can only be assigned to single slot even if several qualify.
Linking the right slot might be tricky with the generic entity names for duckling and spacy. Perhaps using the first “empty” slot might be first baseline.

**Content of domain file** (if used & relevant):
```yaml
slots:
  destination:
    type: text
  origin:
    type: text
```

**Comment by tmbo** [comment]
I guess this is another reason we should think about introducing roles into the entity labeling of NLU.

**Comment by hotzenklotz** [comment]
I just noticed one more case where this is not working:

### Setup
```
slots:
  destination:
    type: text
  origin:
    type: text
```

from the FormAction:
```
def required_fields():
        return [
            EntityFormField("GPE", "destination"),
            EntityFormField("GPE", "origin"),
        ]
```

### Test Case 1
`I want to travel to Munich today` --> Only one slot should be filled with the `GPE` entity. Great, this works:
```
destination: Munich
origin: None
```

### Test Case 2
`I want to travel from Berlin to Munich today.`--> Only one slot is set even though two `GPE` entities were extracted. Expected state should have been:
```
destination: Munich
origin: Berlin
```

**Comment by amn41** [comment]
yeah this is just a limitation of the workaround we implemented to only extract one at a time. As @tmbo points out the proper solution is to use roles

**Comment by hotzenklotz** [comment]
I agree that roles are helpful. But they are only necessary to assign the correct semantic slot (e.g. destination vs. origin). Not assigning all available extracted entities is clearly a bug (and would be so even if you had roles).
