### ISSUE TITLE
Multiple Entities of the same type

### ISSUE THREAD

**Issue by rabberbock** [RasaHQ/rasa_core#41]
I did not see in the documentation anything about if some text has multiple entities of the same type how can rasa core pick up each one. So if a user says `I want apples and bananas`, how can we pick up both those entities as the fruit entity. What type of slot would be used here?

Thanks!

**Comment by tmbo** [comment]
To be honest, haven't thought about this yet. I think one idea would be to always store the first value, if the slot type is list - append them to that slot?

**Comment by Bellator95** [comment]
I found one solution which can help in this situation. As far as you know, rasa_core overwrites entities in slots after parsing if there is more than one entity of the same type in your string. 

    def slots_for_entities(self, entities):
        if self.store_entities_as_slots:
            return [SlotSet(entity['entity'], entity['value'])
                    for entity in entities
                    for s in self.slots
                    if entity['entity'] == s.name]

In this case, you can create your own ArraySlot and overwrite __setattr__ for "value" parameter as follow:

    from rasa_core.slots import DataSlot

    class ArraySlot(DataSlot):
        type_name = 'custom_slot'

        def __init__(self, name, initial_value=None, value_reset_delay=1):
            super(ArraySlot, self).__init__(name, initial_value, value_reset_delay)

        def __setattr__(self, name, value):
            if name == 'value':
                try:
                   self.__dict__['value'].append(value)
                except KeyError:
                    self.__dict__['value'] = []
            else:
                super().__setattr__(name, value)

        def as_feature(self):
            return [1]

        def reset(self):
            del self.value[:]

This is not the best solution, but it will help you to store the list of parameters from your query.
Also, you should add this slot to your domain.yml like follow:

    slots:
      params_holder:
        type: path.to.array_slot.ArraySlot

**Comment by tmbo** [comment]
I'll close this in favor of #171 to keep the discussion in one place.
