### ISSUE TITLE
How can I get buttons in my action class ?

### ISSUE THREAD

**Issue by dilipbobby** [RasaHQ/rasa_core#411]
**Issue**: I have a idea on creating buttons as given in this example in yml file

 utter_greet:
  - text: "Hey! How are you?"
    buttons:
    - title: "great"
      payload: "great"
    - title: "super sad"
      payload: "super sad

so I want to do same work in action class.I need to call buttons in that ? please let me know how can I do that

**Comment by akelad** [comment]
You want to send a button message from inside a custom action? You can do that with dispatcher.utter_button_message or dispatcher.utter_button_template
https://github.com/RasaHQ/rasa_core/blob/master/rasa_core/dispatcher.py#L106

**Comment by tmbo** [comment]
I'll close this for now, please let us know if you have any further questions.

**Comment by SachinNarkhede** [comment]
Can you please tell me how to generate responses on button
e.g . I have two button "submit" and "cancel" ,On Submit I want to generate response "Kindly confirm your payment" and On "cancel" response is "payment has been cancelled"

Also when user say's "Submit" two new button appear like "Confirm" and "Cancel"

**Comment by Junitinn** [comment]
I guess that's something you could configure since your story.md. Declaring "Submit" and "Cancel" as intends and write your stories based on whatever you want the bot say.
