### ISSUE TITLE
Multiple entities with similar or same values

### ISSUE THREAD

**Issue by piyushporwal6795** [RasaHQ/rasa_core#420]
Rasa Core version - 0.8.5

Python version - 3.5 

Operating system -  Windows 10

Issue - How rasa core can differentiate two slot values based on the user’s input? For example one slot is user and other slot is manager both have same or similar values like you can say it is in the format of FirstName.LastName?
How to use multiple slots with similar values?

And these slots defined in yaml file as type unfeaturized.

**Comment by auzair92** [comment]
I think this will depend on your stories. Let's say you have two action templates, `utter_ask_user` and `utter_ask_manager`. You could try training your model on storylines which specify that the input you get after `utter_ask_user` is **user**'s name, and the input you get after `utter_ask_manager` is **manager**'s name. Probable stories would go like:

```
## flow_1
* greet
 - utter_greet
 - utter_ask_user 
* inform{"user":"alex"}
 - utter_ask_manager
* inform{"manager": "john"}
 - utter_thanks

## flow_2
* greet
 - utter_greet
 - utter_ask_manager
* inform{"manager": "john"}
 - utter_ask_user
* inform{"user":"alex"}
 - utter_thanks
```

**Comment by piyushporwal6795** [comment]
It's done in that way only. Right now what is actually happening is that rasa core isn't able to differentiate my two entities User name and Manager name? 
I have provided 15-20 examples for respective entities in data.json file.

**Comment by auzair92** [comment]
When you say 'rasa core isn't able to differentiate my two entities', do you mean it is not picking them up at all or is it putting user's name in manager's, and vice versa? Could you provide a few example stories here where you are taking care of this scenario, and the associated intent/slot/entity values?

**Comment by piyushporwal6795** [comment]
Rasa core is picking them up but it is putting manager's name in user's name. Here is the story and associated intent, entity values:
     {
        "text": "Piyush.Porwal",
        "intent": "inform",
        "entities": [
          {
            "start": 0,
            "end": 13,
            "value": "Piyush.Porwal",
            "entity": "user_name"
          }
        ]
      },
      {
        "text": "Vinod.Porwal",
        "intent": "inform",
        "entities": [
          {
            "start": 0,
            "end": 12,
            "value": "Vinod.Porwal",
            "entity": "manager_name"
          }
        ]
      } 

## Generated Story -320341839263751463
* greet
    - utter_greet
    - request_user_name
* inform{"user_name": "piyush.porwal"}
    - slot{"user_name": "piyush.porwal"}
    - request_manager_name
* inform{"manager_name": "vinod.porwal"}
    - slot{"manager_name": "vinod.porwal"}
    - utter_done
How rasa core will differentiate these both entities having same format of FirstName.LastName ?

**Comment by akelad** [comment]
this is an NLU issue. As these entities are pretty much the same from an NLU perspective, i'd suggest just having them as one entity type, and storing them in different slots with a custom action dependent on which part of the conversation you're at.

**Comment by piyushporwal6795** [comment]
Ohh I get it. Thanks for the help :)

**Comment by akelad** [comment]
cool, will close the issue then, but let us know if you encounter any other problems

**Comment by piyushporwal6795** [comment]
Yes sure definitely.
