### ISSUE TITLE
Rasa core to Web

### ISSUE THREAD

**Issue by piyushporwal6795** [RasaHQ/rasa_core#425]
Rasa Core version - 0.8.5

Python version - 3.5

Operating system - Windows 10

Issue- How we are supposed to integrate rasa core to the web?

**Comment by akelad** [comment]
You'll have to build a connector for wherever you're trying to run your bot in. We have some prebuilt ones already: https://core.rasa.com/connectors.html

**Comment by tmbo** [comment]
I'll close this for now, please let us know if you have any further questions.
