### ISSUE TITLE
rasa_core whitle hitting http server

### ISSUE THREAD

**Issue by chhavvi** [RasaHQ/rasa_core#427]
when I run the http server as following command:

python -m rasa_core.server -d models/current/  -o output.log

I expect the message started with _ will been parsed successfully.

user@KELLGGNCPU0319:~/Documents/tsg/rasa_core/examples/restaurantbot$ curl -XPOST localhost:5005/conversations/default/parse -d '{"query":"hi"}'
error : 
No agent loaded. To continue processing, a model of a trained agent needs to be loaded.

**Comment by akelad** [comment]
are you still having this issue? It seems like you're trying to parse an nlu query, but haven't actually specified a model for that

**Comment by tmbo** [comment]
I'll close this for now, please let us know if you have any further questions.
