### ISSUE TITLE
duckling entities not generating

### ISSUE THREAD

**Issue by praveenrengarajan** [RasaHQ/rasa_core#430]
**Rasa Core version**: 0.8

**Python version**: 3.6

**Operating system** (windows, osx, ...): Windows 10 64

**Issue**:
@mouadino 
nlu_config.json
`{
"pipeline": [
"nlp_spacy",
"spacy_sklearn",
"tokenizer_spacy",
"intent_featurizer_spacy",
"intent_classifier_sklearn",
"ner_crf",
"ner_synonyms",
"ner_duckling"
],
"path" : "./models/nlu",
"data" : "./data/training_data.json",
"duckling_dimensions": ["time", "number", "amount-of-money", "distance" , "email" , "url", "phone-number", "duration"]
}`
Its creating ner_duckling.json file in model folder
`{
  "dimensions": [
    "time",
    "number",
    "amount-of-money",
    "distance",
    "email",
    "url",
    "phone-number",
    "duration"
  ]
}`   
but in training_data.json its not giving duckling entities
`{
        "intent": "info",
        "entities": [],
        "text": "the first Tuesday of October"
  }`

**Comment by praveenrengarajan** [comment]
@mouadino

**Comment by akelad** [comment]
training_data.json won't contain any entities from duckling. That's fine though, this is training data you've written yourself. Ner_duckling will predict entities when you've actually got the model loaded.

**Comment by praveenrengarajan** [comment]
It's working after I declared slot name as time and date

**Comment by mouadino** [comment]
@praveenrengarajan We did that using interactive learning, with that the slot get generated automatically you can check our examples from the gist here https://gist.github.com/mouadino/78ab561e9164b4857528745e6668c0f1
