### ISSUE TITLE
Best practice on dialog training

### ISSUE THREAD

**Issue by mouadino** [RasaHQ/rasa_core#432]
**Rasa Core version**: 0.8.5

**Python version**: 3.6

**Operating system** (windows, osx, ...): OSX

**Issue**:

We have been trying to write a conversation that involves booking vacations for users, the idea is to support three types of input that drive the discussion:

- User asks for a vacation while providing both start and end dates, e.g.
   * "I would like to take a vacation from tomorrow until Friday"
- User asks for a vacation by only providing a start date, e.g.
   * "I would like to take a vacation starting tomorrow"
- User asks for vacation without providing any date, e.g.
   * "I would like to book a vacation"

We tried to model the different scenarios with interactive learning, please check the stories in the gist, they should start with "Book leave", however, we noticed some strange behavior that we couldn't make sense of, and we tried digging in the code without any success, so it would be great if you can share with us any hints or shared best practices to help us train the conversation better.

But here are a list of things going wrong:

- Many responses at ones, which lead to the circuit breaker inside the policy to be triggered.
- Conversation stops where Rasa always chose `action_listen`.
- Most annoying one was the brittle behavior, where a really small change in one story breaks all the other conversations.

Here are things that we tried:

- Training data with a mix of stories that have a `greet` than `leave_annual_take ` intents and other without the `greet` part, we thought it will help, which kind of did but broke other conversation.
- Increasing max-history to 4 for the `MemoizationPolicy`, a bigger number lead to worst results.

Other than that we are not sure what else to try, so any hints will be great.

**Content of domain/stories/pipeline file**

Please check this Gist of all files like stories, domains, and pipeline and code of the actions:

https://gist.github.com/mouadino/78ab561e9164b4857528745e6668c0f1

**Comment by mouadino** [comment]
Update from our case, we tuned more our training variables and enable cross-validation for Keras to give us a better understanding in which direction we should tune, other variables that made it work better were the bigger batch size (now it's 30), increasing epoch also helped (now it's 100) and same of max training sample, but the bot still act strangely from often than we like, and the symptoms above still keep happening, story authoring wise we are still in the mode of try and error without a clear understanding on what should help or not, examples of questions that we still have:

- Is adding different scenarios with greet and no greet helps?
- How many of this scenarios should we have? b/c we are moving in the direction of a rule-based bot.
- Seems that slots that don't get used nor reset end-up influencing the conversation, how can we expire them? or reset them? should we put a restart_action at the start of each story? 

Any help is appreciated still, thanks

**Comment by amn41** [comment]
Thanks for the thoughtful post and the update! 
Once you get to larger use cases, the hyperparameters do matter more and I want to include some better scripts tooling for evaluating those. How did you pick your batch size and epochs? trial and error I guess? 
We also have a big PR open with a new policy architecture that is better at generalising, so that you don't need as many stories. 

For slots that go 'stale' - a good idea is to trigger an `AllSlotsReset` event if something happens that makes the prior history irrelevant, you can also add a reset delay https://github.com/RasaHQ/rasa_core/blob/master/rasa_core/slots.py#L16

**Comment by mouadino** [comment]
Yes, it was a trial and error process. 

The reset delay is pretty nice but it looks like it's not implemented yet https://github.com/RasaHQ/rasa_core/blob/master/rasa_core/slots.py#L37 or is it? but maybe we can leave with `AllSlotsReset` only.

**Comment by tmbo** [comment]
You are right there, the reset delay is not implemented yet.
