### ISSUE TITLE
Temporary field 

### ISSUE THREAD

**Issue by fdevillard** [RasaHQ/rasa_core#434]
**Rasa Core version**: 0.9.0a3

**Python version**: Python 3.5.2

**Operating system** (windows, osx, ...): Ubuntu 16.04

**Issue**: I try to handle a form-filling like dialogue where API calls are used in order to disambiguate the user's query. And typically, I would need to store intermediate results from the API and, typically, this information should be clean when a given slot change of value.

The idea being:

- The user search for a term (let say that this search terms are stored in a slot which is called `search_keywords`)
- The action find the most relevant search result, and stores it in a temporary slot
- User/actions can play with this temporary data
- Once the user change the `search_keywords` slot, the temporary slot is cleaned 
- Typically, if this temporary slot is featurized, action that will re-fill the temporary slot is triggered and the value is presented

**Proposition**:

Update the domain's schema to support:

```yaml
slots:
  search_keywords:
    type: unfeaturized
  temporary:
    type: text
    depends_on: 
      - search_keywords
```

Which causes that whenever the system generate a `slot{search_keywords: any}` it'll generate `slot{temporary: null}` as well.

Concerning the domain file, the opposite way might be easier to implement:

```yaml
slots:
  search_keywords:
    type: unfeaturized
    cascade_on: temporary
  temporary:
    type: text
```

Does it make sense? Is this feature worth it for you?

**Comment by fdevillard** [comment]
Yes, it is feasible. Actually, as my search is (or should be :no_mouth: ) deterministic, I can re-execute the query at each interaction which should not penalize the UX (and therefore avoiding to have a `temporary` slot). 

But lets try to do it with `SlotSet` events. And suppose that we want to query a weather database:

```
* ask_weather{"location "Berlin", "time": "now"}
  - slot{"location": "Berlin"}
  - slot{"time": "now"}
  - action_get_location
  - slot{"search_result": {
             "most_relevant": {
               "name": "Berlin",
               "id": "https://en.wikipedia.org/wiki/Berlin"
             },
             "ambiguity": ["Berlin (Seedorf)", "Berlin, Connecticut", ...]
          }
    } 
  - utter_ambiguity
  - action_get_weather
* inform{"time": "tomorrow"}
  - slot{"time": "tomorrow"}
  - action_get_weather
* inform{"location": "Lausanne"}
  - slot{"location": "Lausanne"}
  - action_get_location
  - slot{"search_result": {
             "most_relevant": {
               "name": "Lausanne",
               "id": "https://en.wikipedia.org/wiki/Lausanne"
             },
             "ambiguity": ["Lausanne Township, Carbon County, Pennsylvania", ...]
          }
    } 
  - utter_ambiguity
  - action_get_weather
```

Thus typically, what we want is:

- If the user `inform` about the location, we want to re-search for a location
- If the user `inform` about the time, we **don't** want to re-search for the location, as this might cause to suddenly search for another place (like _Berlin (Seedorf)_).

And, if I understand well how Rasa Core works, this will not work because:

- The user's intent are the same, and
- The slot featurisation will also be the same as both these two slots have a non-null value

Therefore the features are the same and the model should predict the same thing in both case, which is not what we want. Or, it could also overfit on "the first `inform`, I don't re-perform a `action_get_location`", but "I perform a `action_get_location` for the second `inform`".

True?

Just to link with what I meant by _deterministic_ is in the case where `action_get_location` will always have the same value if we don't change the value of `tracker.get_slot("location")`.

If this assumption holds, we can rewrite our stories as: 

```
* ask_weather{"location "Berlin", "time": "now"}
  - slot{"location": "Berlin"}
  - slot{"time": "now"}
  - action_get_location
  - slot{"search_result": {
             "most_relevant": {
               "name": "Berlin",
               "id": "https://en.wikipedia.org/wiki/Berlin"
             },
             "ambiguity": ["Berlin (Seedorf)", "Berlin, Connecticut", ...]
          }
    } 
  - utter_ambiguity
  - action_get_weather
* inform{"time": "tomorrow"}
  - slot{"location": "Berlin"}
  - slot{"time": "tomorrow"}
  - action_get_location
  - slot{"search_result": {
             "most_relevant": {
               "name": "Berlin",
               "id": "https://en.wikipedia.org/wiki/Berlin"
             },
             "ambiguity": ["Berlin (Seedorf)", "Berlin, Connecticut", ...]
          }
    } 
  - utter_ambiguity
  - action_get_weather
* inform{"location": "Lausanne"}
  - slot{"location": "Lausanne"}
  - action_get_location
  - slot{"search_result": {
             "most_relevant": {
               "name": "Lausanne",
               "id": "https://en.wikipedia.org/wiki/Lausanne"
             },
             "ambiguity": ["Lausanne Township, Carbon County, Pennsylvania", ...]
          }
    } 
  - utter_ambiguity
  - action_get_weather
```

And it should work fine.

Note: if there are several scenarios that use `inform` to update slots, then `search_result` should be featurized and be used only in this scenario. Otherwise the action that should be performed after several `inform` will be ambiguous (_when_ depends of the value of `max_history` used during the training phase).

Just to be sure that I'm clear with the proposition, lets phrase this problem as proposed. Thus, our domain would look like:

```yaml
slots:
  location:
    type: unfeaturized
    cascade_on: temporary
  time:
    type: unfeaturized
  search_result:
    type: text
```

and the story (based on the first example):

```
* ask_weather{"location "Berlin", "time": "now"}
  - slot{"location": "Berlin"}
  - slot{"search_result": null}     <--- added 
  - slot{"time": "now"}
  - action_get_location
  - slot{"search_result": {
             "most_relevant": {
               "name": "Berlin",
               "id": "https://en.wikipedia.org/wiki/Berlin"
             },
             "ambiguity": ["Berlin (Seedorf)", "Berlin, Connecticut", ...]
          }
    } 
  - utter_ambiguity
  - action_get_weather
* inform{"time": "tomorrow"}
  - slot{"time": "tomorrow"}
  - action_get_weather
* inform{"location": "Lausanne"}
  - slot{"location": "Lausanne"}
  - slot{"search_result": null}     <--- added 
  - action_get_location
  - slot{"search_result": {
             "most_relevant": {
               "name": "Lausanne",
               "id": "https://en.wikipedia.org/wiki/Lausanne"
             },
             "ambiguity": ["Lausanne Township, Carbon County, Pennsylvania", ...]
          }
    } 
  - utter_ambiguity
  - action_get_weather
```

**Comment by tmbo** [comment]
I don't think the featurization in your two cases (1. user provides time 2. user provides location) is the same, as the entities that are present in the user message influence the featurization as well, so you can very well run different actions after the same user intent even if the slots are the same, if the entities are different

**Comment by fdevillard** [comment]
@amn41 this might happen in different cases (for example if the underlying DB has a lot of changes)

@tmbo 

```
as the entities that are present in the user message influence the featurization as well
```

Perfect, I thought that only the slots were featurized. Therefore, my proposition will over-complexify without being useful 😄 

Thanks for your time and inputs :)
