### ISSUE TITLE
Core dump while training

### ISSUE THREAD

**Issue by cmckni3** [RasaHQ/rasa_core#436]
**Rasa Core version**:

0.8.3

**Python version**: 

2.7.12

**Operating system** (windows, osx, ...):

Ubuntu 14.04 Docker

**Issue**:

https://github.com/tensorflow/tensorflow/issues/17411

Downgrading Tensorflow and Rasa Core returned it to a working state.

**Comment by akelad** [comment]
looks like you fixed the issue - can i close this? Downgrading just tensorflow would've probably also worked right?

**Comment by cmckni3** [comment]
I tried downgrading to Tensorflow 1.5 and it core dumped as well. iirc Rasa Core 0.8.3 depended on Tensorfow 1.5 or 1.6.

**Comment by tmbo** [comment]
I'll close this for now, please let us know if you have any further questions.

**Comment by cmckni3** [comment]
Strange. It’s been awhile since I looked at it but 0.8.3 depended on TS 1.5-1.6 iirc

**Comment by tmbo** [comment]
Yes, but the latest master should work fine with tensorflow 1.7

**Comment by tmbo** [comment]
As stated in the tensorflow issue and on the stackoverflow page https://stackoverflow.com/a/49094955/1906073 - your hardware is not supported by the precompiled binaries. So either downgrade tensorflow, or compile tensorflow from source directly on your hardware.
