### ISSUE TITLE
Implementing Policy for Fallback (Custom Keras Policy)

### ISSUE THREAD

**Issue by praveenrengarajan** [RasaHQ/rasa_core#440]
**Rasa Core version**: 0.90a3 (Master)

**Python version**: 3.6

**Operating system** (windows, osx, ...): Win 10 x64

**Issue**:  I have added `probabilities_using_best_policy` function in Keras policy which is used in Restaraunt Example. 
2) added `fallback` action bot.py file.
3) in `domain.yml` mentioned `fallback` action
**Note** I have upgraded Rasa core from 0.8 to master and Rasa Nlu to latest version. For Master Core updated doc https://core.rasa.com/master/policies.html  
Couldn't understand document properly, can you (@akelad ) guide me, steps to include fallback action

Please check gist https://gist.github.com/praveenrengarajan/0d004ab6deb047e3fe6ce3893def07e5
**Content of domain file** (if used & relevant):
```yaml

```

**Comment by praveenrengarajan** [comment]
@ewagner70

**Comment by ewagner70** [comment]
Yes? What's your specific question/request to me?

**Comment by praveenrengarajan** [comment]
@ewagner70  How did you implemented Fallback policy? Please check my gist and guide me how to do it.

**Comment by tmbo** [comment]
In the domain you linked there, you've set the fallback action to be `"utter_default"`:
```python
fallback = FallbackPolicy(fallback_action_name="utter_default",
core_threshold=0.3,
nlu_threshold=0.3)
agent = Agent(domain_file, policies=[MemoizationPolicy(), KerasPolicy(), fallback])
```

it should rather be `"fallback"`, to tell the bot that you want to use your custom action.

**Comment by praveenrengarajan** [comment]
@tmbo facing issue https://github.com/RasaHQ/rasa_core/issues/424 but one thing I didn't understand, for ##intent: default means I have to mention some examples for non-related sentence in NLU? and have to define that intent name in domain.yml file?

**Comment by praveenrengarajan** [comment]
simply added `- utter_default` fallback function in domain.yml 
## default story
  - utter_default
but getting 10 times repeating the message.

**Comment by ewagner70** [comment]
yep ... in debug mode you can see that next_action prediction is wrong ... mostly indicating that you need (more) stories for training the next best action.

**Comment by amn41** [comment]
update: fallbackpolicy now automatically predicts `listen` after the default action, so this is no longer needed
