### ISSUE TITLE
Auto generated '.\stories.md' ?

### ISSUE THREAD

**Issue by MnHung** [RasaHQ/rasa_core#441]
**Rasa Core version**: 0.8.3
**Python version**:  2.7
**Operating system** :  ubuntu

**Issue**: 

I notice that a **stories.md** file is auto generated at root path of project, is that normal? Should I put it into .gitignore?

My project is based on the example/restaurantbot, after running a robot or doing a interactive-learning to robot, a stories.md is generated or updated. And I noticed that example/concertbot also generates a stories.md.

*the path is {project}/stories.md, not {project}/data/stories.md

**Comment by MnHung** [comment]
Thank you for reply @jLukeC 

Yes I know that the default output path in interactive learning is `./stories.md`
But I does not mean this situation.

Actually when I specify `data/stories.md` in interactive learning, the `./stories.md` is updated. 
And when I run the chatbot, (in restaurantbot example, I called `python bot.py run`), the `./stories.md` is also updated.

**Comment by AlvaroMonteagudo** [comment]
I just had the same issue, https://github.com/AbdurRub point me out it was already explained here: https://github.com/RasaHQ/rasa_core/issues/415

**Comment by akelad** [comment]
yeah i'll close this issue, we'll keep the discussion on the other thread
