### ISSUE TITLE
How to replace the SlotSet value with a new value?

### ISSUE THREAD

**Issue by NikhilBansal21** [RasaHQ/rasa_core#442]
**Rasa Core version**:0.9.0a3

**Python version**: 3.6.5

**Operating system** (windows, osx, ...):10 pro

**Issue**:  i want to replace the slot set value every time that particular intent  action setting the slot value is called. I know i have to reset the slot to null every time a new value is being extracted but how?

**Content of domain file** (if used & relevant):
```yaml

```

**Comment by akelad** [comment]
you don't have to reset the slot to null, you should just be able to do `SlotSet()` to overwrite the slot

**Comment by NikhilBansal21** [comment]
![rasa-incidentid issue](https://user-images.githubusercontent.com/16642277/39812303-bc1d75d8-53a9-11e8-9b8f-1968407fbbd4.PNG)
it does not reset always i know this does reset the slot but sometimes it does not resets the slot with new value

**Comment by akelad** [comment]
are you still having issues or can we close this?

**Comment by tmbo** [comment]
I'll close this for now, please let us know if you have any further questions.
