### ISSUE TITLE
TensorFlow Python2 Windows 10

### ISSUE THREAD

**Issue by keyloguer** [RasaHQ/rasa_core#446]
**Rasa Core version**:0.8.6

**Python version**: 2.7.14

**Operating system** (windows, osx, ...):windows 10

**Issue**: Rasa has support for python3? Next question, if rasa don't have support with pytho3, how to build tensorflow in python2 in Windows10?

**Comment by akelad** [comment]
Yes it has support for python 3. Could you give more details of your problem?

**Comment by keyloguer** [comment]
I have this code:
```
from __future__ import absolute_import
from __future__ import division
from __future__ import unicode_literals

import logging

from rasa_core.agent import Agent
from rasa_core.policies.keras_policy import KerasPolicy
from rasa_core.policies.memoization import MemoizationPolicy

if __name__ == '__main__':
	logging.basicConfig(level='INFO')
	
	training_data_file = "\\data\\stories.md"
	model_path = '\\models\\dialogue'
	
	agent = Agent('domain.yml', policies = [MemoizationPolicy(), KerasPolicy()])
	
	agent.train_online(
			training_data_file,
        	augmentation_factor=50,
        	max_history=2,
        	epochs=500,
        	batch_size=10,
        	validation_split=0.2)
			
	agent.persist(model_path)
```

The path is right but when i build with python2 i have this error referring tensorflow

> C:\Users\Youssef\Anaconda2\lib\site-packages\h5py\__init__.py:34: FutureWarning: Conversion of the second argument of issubdtype from `float` to
> `np.floating` is deprecated. In future, it will be treated as `np.float64 == np.dtype(float).type`.
>   from ._conv import register_converters as _register_converters
> Using TensorFlow backend.
> Traceback (most recent call last):
>   File "train_init.py", line 17, in <module>
>     agent = Agent('C:\\Users\\Youssef\\Documents\\megaImagemBot\\domain.yml', policies = [MemoizationPolicy(), KerasPolicy()])
>   File "C:\Users\Youssef\Documents\megaImagemBot\rasa_core\rasa_core\policies\keras_policy.py", line 28, in __init__
>     import keras
>   File "C:\Users\Youssef\Anaconda2\lib\site-packages\keras\__init__.py", line 3, in <module>
>     from . import utils
>   File "C:\Users\Youssef\Anaconda2\lib\site-packages\keras\utils\__init__.py", line 6, in <module>
>     from . import conv_utils
>   File "C:\Users\Youssef\Anaconda2\lib\site-packages\keras\utils\conv_utils.py", line 3, in <module>
>     from .. import backend as K
>   File "C:\Users\Youssef\Anaconda2\lib\site-packages\keras\backend\__init__.py", line 83, in <module>
>     from .tensorflow_backend import *
>   File "C:\Users\Youssef\Anaconda2\lib\site-packages\keras\backend\tensorflow_backend.py", line 1, in <module>
>     import tensorflow as tf
> ImportError: No module named tensorflow

and python3: 

> Traceback (most recent call last):
>   File "train_init.py", line 7, in <module>
>     from rasa_core.agent import Agent
>   File "C:\Users\Youssef\Documents\megaImagemBot\rasa_core\rasa_core\agent.py", line 17, in <module>
>     from rasa_core.policies import PolicyTrainer, Policy
>   File "C:\Users\Youssef\Documents\megaImagemBot\rasa_core\rasa_core\policies\__init__.py", line 6, in <module>
>     from rasa_core.policies.policy import Policy
>   File "C:\Users\Youssef\Documents\megaImagemBot\rasa_core\rasa_core\policies\policy.py", line 19, in <module>
>     from rasa_core.training.data import DialogueTrainingData
>   File "C:\Users\Youssef\Documents\megaImagemBot\rasa_core\rasa_core\training\__init__.py", line 11, in <module>
>     from rasa_core.training.dsl import StoryFileReader
>   File "C:\Users\Youssef\Documents\megaImagemBot\rasa_core\rasa_core\training\dsl.py", line 14, in <module>
>     from rasa_nlu import utils as nlu_utils
> ImportError: No module named 'rasa_nlu'

because this error above i want to ask you how to install rasa_nlu and rasa_core in python3.

**Comment by AlvaroMonteagudo** [comment]
https://core.rasa.com/installation.html

**Comment by akelad** [comment]
Yeah are you sure you've properly followed the installation instructions in the link above?

**Comment by tmbo** [comment]
I'll close this for now, please let us know if you have any further questions.
