### ISSUE TITLE
ValueError: on Action when trying to load Agent based post request

### ISSUE THREAD

**Issue by annadow75** [RasaHQ/rasa_core#450]
**Rasa Core version**: 0.9.0a2

**Python version**: 3.6.5

**Operating system** (windows, osx, ...): Windows 10 

**Issue**:

How to handle request from HttpInputChannel when you have two bot created in two different folder under the root directory. I have a weather bot to get the current weather and the restaurant bot in example . Both of these are in their respective folders with different config files , stories and data folder.

I tried to load the Agent based on the folder name in  post request and it says 
```
ValueError: Action 'actions.ActionWeather' doesn't correspond to a template / action. Remember to prefix actions that should utter a template with `utter_`. Error: No module named 'actions'
```

**Comment by annadow75** [comment]
Is there a way to load the agent first  to listen on a specific channel and then later at some point of time attach the dialog model  and interpreter?

**Comment by annadow75** [comment]
@akelad  Can you please give some advice on this. I got really stuck on this.

**Comment by annadow75** [comment]
The value error only happens when I have an action attached to the bot. if there are no action attached it never gives me the error and everything works just fine

**Comment by akelad** [comment]
you would have to specify the actions as bot1.actions.Action and bot2.actions.Action (whatever the directories of your bot1 and bot2 are), since you're running from the root directory, not the respective folders.

**Comment by annadow75** [comment]
@akelad Thanks for replying . I did following changes in the domain.yml file: 


```

actions:
 - utter_greet
 - utter_goodbye
 - utter_ask_time
 - bot1.callplace.Call
 - bot1.apptplace.Appointment
```
I got the same error. 

Then I tried to retrain the bot by getting into the bot1 folder and tried to run the command to train the bot. This time it returned me error as : 

```
ValueError: Action 'bot1.callplace.Call' doesn't correspond to a template / action. Remember to prefix actions that should utter a template with `utter_`. Error: No module named 'bot1'
``

**Comment by tmbo** [comment]
Can you show the directory tree? We need some more information about the project structure. As you can see at the end of the error message, `No module named 'bot1` - which means python is not able to find a module named `bot1`. This means it is not in the current search path, or it is not a package (e.g. doesn't include an `__init__.py`)

**Comment by BhuvanKumarRbk** [comment]
Sorted?? @annadow75 . I am getting the same error.

**Comment by akelad** [comment]
What does your directory structure look like? And your exact error? It's likely that the problem is just that you don't have an `__init__.py` in the directory
