### ISSUE TITLE
Multiple Entities Extract

### ISSUE THREAD

**Issue by hemanth1991** [RasaHQ/rasa_core#452]
Hi!! 
I have loaded intents in GUI of rasa ..Suppose I have a text saying "I want to play Badminton on Monday and Friday" and I highlight Monday and Friday to Days Entity. How should I extract days in a list format in tracker in actions.py? to process further?

Also, last entity is coming I think its getting overwritten.

Kindly help

**Comment by akelad** [comment]
You can get them using `get_latest_entity_values(entity_type)`

**Comment by tmbo** [comment]
I'll close this for now, please let us know if you have any further questions.
