### ISSUE TITLE
custom dispatchers 

### ISSUE THREAD

**Issue by amn41** [RasaHQ/rasa_core#455]
Allow retrieving bot utterances from somewhere else but the domain (e.g. a web api or a database)

**Comment by tmbo** [comment]
will be merged as part of the `sdk` merge

**Comment by LeoArruda** [comment]
@amn41 
I did an alternative solution to a similar problem. In my case, I'm trying to have an Action Answer to provide stored answers in a MongoDB database based on Intents. 

The structure of my collection is simple; this is an example:
`{["id": "text", 
     "intent": "text",
      "text": "text"]
  }`

This code is part of my actions.

`from pymongo import MongoClient`
`client = MongoClient('mongodb://localhost:27017')`
`db = client['local']`

`class ActionAnswer(Action):`
`    def name(self):`
`        return 'action_answer'`

    def run(self, dispatcher, tracker, domain):
        # define mongoDB collection
        knowledge = db.knowledgeBase
        #Identify the last message intent
        intent = tracker.latest_message.intent['name']
        #find in Knowledge base collection the intent answer
        # you have to treat errors like intent not found and others. I sugest a Try-Exception 
        answer = knowledge.find_one({'intent':str(intent)})

        response = """Initial intent is {}. The answer found is:{}""".format(intent, answer["text"])

        dispatcher.utter_message(response)
        return []`
