### ISSUE TITLE
how can I send custom message, buttons payload to client (api response) with pay load.

### ISSUE THREAD

**Issue by nileshgarg** [RasaHQ/rasa_core#459]
**Rasa Core version**: Master branch

**Python version**:  3.6 

**Operating system** (windows, osx, ...): windwos 10

**Issue**: i want to render, images etc on client chat window. response is from api

**Content of domain file** (if used & relevant):
```yaml

```

**Comment by tmbo** [comment]
You can directly specify buttons and images in the bots response templates, e.g. https://core.rasa.com/tutorial_basics.html#define-a-domain

**Comment by manojjjm** [comment]
i want to send a response to slack client with a button and a link to that button how can we do that . please help

**Comment by akelad** [comment]
There's information in our docs on how to do this: http://rasa.com/docs/core/domains/#utter-templates
Also please ask these kinds of question in our [forum](https://forum.rasa.com)
