### ISSUE TITLE
Request: Comprehensive End-2-End Examples and respective Documentation Training Material

### ISSUE THREAD

**Issue by ewagner70** [RasaHQ/rasa_core#464]
**Rasa Core version**: 0.9.0a3 (cannot install 0.9.0a5)

**Python version**: 3.6

**Operating system** (windows, osx, ...): ubuntu 18.04

**Issue**: Proposal for comprehensive end-to-end examples and their respective documentation/training materials
Current Examples cover only VERY basic rasa_core logic and documentation rarely reflects examples. I propose to provide 2-3 examples which cover all tricky elements end-to-end (and not only fragments/parts), f.ex.
- FormAction
- Buttons
- (Slack) Channel
- Custom Actions
- Fallback Policy
- 2-3 different "domains" in parallel
- etc.

**Content of domain file** (if used & relevant):
```yaml

```

**Comment by amn41** [comment]
👍 we are working on updating the documentation - a lot of stuff has been added / changed since those tutorials were first written so we're going to do an update

**Comment by ewagner70** [comment]
great ... looking forward - any timeline?

**Comment by tmbo** [comment]
lots of updates have been merged on that end, will close this one.
