### ISSUE TITLE
train_nlu restarts the whole python script

### ISSUE THREAD

**Issue by ewagner70** [RasaHQ/rasa_core#472]
**Rasa Core version**: 0.9.0a5

**Python version**: 3.6

**Operating system** (windows, osx, ...): ubuntu 18.04

**Issue**: train_nlu seems to completely start the whole python script new (realized that after upgrade to 0.9.0a5)

**Content of domain file** (if used & relevant):
```yaml
def train_nlu():
    from rasa_nlu.training_data import load_data
    from rasa_nlu import config
    from rasa_nlu.model import Trainer

    training_data = load_data('data/georgebot_nlu.md')
    trainer = Trainer(config.load("georgebot_nluconfig.yml"))
    trainer.train(training_data)
    model_directory = trainer.persist('models/nlu',
                                      fixed_model_name="current")

    return model_directory
```

**Comment by tmbo** [comment]
what do you mean with it starts the whole python script new?

**Comment by ewagner70** [comment]
I do not use your scripts (need more flexibility) and have my own “bot.py” so to say. And the whole bot.py starts again a second time (can see that on the various print’s that I do) shortly before the end/at the end of “train_nlu” ...

**Comment by tmbo** [comment]
Can you share that script? I am not sure why it would do that. Would be good to take a look at the log as well if you dont mind.

**Comment by ewagner70** [comment]
Sure ... be warned - I load a lot of packages/libraries ;-) which wasn't an issue until 0.9.0a3 (no double starts until then)
and the DEBUG Infos that I can see on the screen. The Line "['account_opening.txt', 'short_selling.txt']" indicates the start of the python script...
[gb.zip](https://github.com/RasaHQ/rasa_core/files/2010105/gb.zip)
[logfile.zip](https://github.com/RasaHQ/rasa_core/files/2010138/logfile.zip)

**Comment by ewagner70** [comment]
Interesting new insight after further testing:
It is NOT the train_nlu, but the train_dialogue and it is NOT restarting the .py script, it "merely" prints the previous print statements (only the first 2, still don't know why) again in the following code:

```
def train_dialogue(domain_file="georgebot_domain.yml",
                   model_path="models/dialogue",
                   training_data_file="data/georgebot_stories.md"):
    fallback = FallbackPolicy(fallback_action_name="utter_default",
                      core_threshold=0.25,
                      nlu_threshold=0.25)
    agent = Agent(domain_file, policies=[MemoizationPolicy(max_history=6), KerasPolicy(), fallback])
    training_data=agent.load_data(training_data_file)
    agent.train(
            training_data,
            epochs=700,
            batch_size=10,
            validation_split=0.2)

    agent.persist(model_path)
    return agent
```
and it is that line agent = Agent(domain_file, policies=[MemoizationPolicy(max_history=6), KerasPolicy(), fallback]) and subsequently in the agent.py __init__ the following line: 
`self.domain = self._create_domain(domain)`

**Comment by tmbo** [comment]
Mhm no, I really don't know why that would be the case. All of the code is using the `logging` system, so not really using any `print` statements. I am not sure how that could happen.

**Comment by ewagner70** [comment]
The print statements came from me ... I further tested and realised that the printed information is also shown, when I even commented the respective print statements (sic!). 
It seems that the outputs of (former) print statements are “stored“ somewhere and then shown when run again (at the same code snippet shown above).
Can it have something to do with the logging? Will continue to test it on a different machine/environment.

**Comment by ewagner70** [comment]
can reproduce that in a docker container (still ubuntu 18.04) ... am I'm the only one experiencing that?
