### ISSUE TITLE
How to set a slot programmatically? 

### ISSUE THREAD

**Issue by auzair92** [RasaHQ/rasa_core#473]
**Core**: 0.9.0a3 / **NLU**: 0.12.2
**Python version**: 3.6
**Operating system**: Ubuntu SMP

What's a simple way to set a slot's value within a Python-based action function? I do not want it to be dependent on any entity. Let's say that whenever the bot loads, I want to set the slot `bot_name` to a string of my choice. How should I go about doing that?

**Comment by amn41** [comment]
actions return a list of events which will be used to update the tracker, so your action should return:

```
class MyAction(Action):
    def run(...):
        ...
        return [SlotSet("bot_name": my_string)]
```

**Comment by Shehzad777** [comment]
How about multiple slots?
Will this work?
return [SlotSet("bot_name": my_string, "bot_nick_name": my_string_2)]

**Comment by amn41** [comment]
should be: 
`return [SlotSet("bot_name": my_string) , SlotSet("bot_nick_name": my_string_2)]`

**Comment by Shehzad777** [comment]
Thanks @amn41
