### ISSUE TITLE
How to get multiple entities value in multiple sloats

### ISSUE THREAD

**Issue by hardiksanchawat** [RasaHQ/rasa_core#475]
Rasa Core Version: 0.8.6

Python Version: 3.6

Windows 10

Issue: 
I'm passing one string in that two values are there 'ABC' and 'XYZ' that is belongs to different entities.
eg:
Entities                 Value
'Moon'                  'ABC'
'Sun'                     'XYZ'

Then How to get both entities value in different sloats?

I have used ```tracker.get_latest_entity_values("Moon")``` and ```tracker.get_sloats("Moon")```. Always I am getting 'Sun' entities value in the sloat. I need both entities value in different sloats.

Let me know if I'm doing something wrong.

**Comment by tmbo** [comment]
In which slot should the value of the `Moon` entity go and in which slot should the value for the `Sun` entity go?

**Comment by hardiksanchawat** [comment]
@tmbo Do you know which function I can use to get values from different entities?

**Comment by tmbo** [comment]
To get the value of an entity in the last user message you can use 
`tracker.get_latest_entity_values("Moon")`
and
`tracker.get_latest_entity_values("Sun")`
.
For slots you can use `tracker.get_slot("Sun")`.

**Comment by hardiksanchawat** [comment]
@tmbo Its weird, But, I have ```tried tracker.get_latest_entity_values("Moon")``` and ```tracker.get_latest_entity_values("Sun")``` but I'm getting only value for 'Sun' entity not for 'Moon'.
Also tried ```tracker.get_slot("Moon")``` and ```tracker.get_slot("Sun")``` but got only 'Sun' entity value not for 'Moon'.

My question is why it's taking only last entity value, not both?

**Comment by tmbo** [comment]
It probably did not detect an entity of type `Moon` in your sentence.

**Comment by hardiksanchawat** [comment]
I also think so, I'll give another name and will try. 
@tmbo Thanks for your suggestion. But I'm still thinking in a backend spacy_sklearn I'm using. Then, why it's not recognizing entity name.
