### ISSUE TITLE
FallbackPolicy loop issue - Can we artificially stop this?

### ISSUE THREAD

**Issue by naoko** [RasaHQ/rasa_core#477]
**Rasa Core version**: master (0.9.0.a5)

**Python version**: 3.6.1

**Operating system** (windows, osx, ...): both OS X and Linux

**Issue**: So I see this was discussed a few times that `FallbackPolicy` can be looped and eventually exit with `Circuit breaker tripped. Stopped predicting more actions for sender 'default'`. This is because this condition (https://github.com/RasaHQ/rasa_core/blob/master/rasa_core/policies/fallback.py#L80) managed to be True for all following predictions. 
To stop that, I've added secondary condition
` and tracker.latest_action_name != self.fallback_action_name` and it appears to be working.
I wasn't sure though if there is better way to solve this problem.

**Content of stories.md file** :
```
## fallback story user like to forward info to human
- action_fallback_ask_escalate_to_human
* affirm
    - utter_hand_off
    - action_hand_off_to_human

## fallback story user user don't want info to be forwarded yet
- action_fallback_ask_escalate_to_human
* deny
  - utter_bye
```

**Comment by tmbo** [comment]
This is a very good point. I think there are two ways to solve this:
- let the policy only predict the fallback action (the change as you suggested it) - this way the other policies need to learn what to do after the fallback (means there should be at least one story in the training data with the fallback in there)
- let the fallback policy predict listen after the fallback (similar change to yours: predict fallback when needed, and during the next prediction predict `action_listen` if previous action is `fallback`)

I think your solution is better, as it allows the user to train whatever he likes after the fallback (and even do different things in different situations). Can you please open a PR with that change?
