### ISSUE TITLE
Error while finding module specification for 'rasa_core.train' - ModuleNotFoundError: No module named 'rasa_core'

### ISSUE THREAD

**Issue by EthanDev** [RasaHQ/rasa_core#483]
**Rasa Core version**: 0.8.6

**Python version**: 3.6.3

**Operating system** (windows, osx, ...): Windows

**Issue**:

When executing the command below I get the response that rasa_core module is not found

Command
python -m rasa_core.train -s data/stories.md -d domain.yml -o models/dialogue --epochs 300

Response
C:\Users\etrichardson\AppData\Local\Programs\Python\Python36-32\python.exe: Error while finding module specification for 'rasa_core.train' (ModuleNotFoundError: No module named 'rasa_core')

**Content of domain file** (if used & relevant):
```yaml

```

**Comment by tmbo** [comment]
Did you install `rasa_core` in that environment? (e.g. try running `pip list` or `pip show rasa_core`)

**Comment by jainsourabh2** [comment]
I am also facing same error. When I try to install rasa_core , it ends with below messages:

.....................
Collecting tensorflow<1.9,>=1.7 (from rasa_core)
  Could not find a version that satisfies the requirement tensorflow<1.9,>=1.7 (from rasa_core) (from versions: )
No matching distribution found for tensorflow<1.9,>=1.7 (from rasa_core)

**Comment by akelad** [comment]
try installing tensorflow seperately? with `pip install tensorflow==1.8.0`

**Comment by MaulishShah** [comment]
i found an error while running the file train_init.py 
ModuleNotFoundError: No module named 'rasa_core'

**Comment by MaulishShah** [comment]
rasa-core : 0.13.2 
ubuntu: 18.04
 python version - 3.6.5 

i found an error while running the file train_init.py ModuleNotFoundError: No module named ### 'rasa_core'
--

**Comment by akelad** [comment]
Please create a new issue
