### ISSUE TITLE
rasa_core/ dls.py problem

### ISSUE THREAD

**Issue by LeohTadeu** [RasaHQ/rasa_core#488]
Hi, I had a problem in train-dialogue execution.
In dls.py module, there's a class attribute for the directory rasa_nlu.utils.
Code:
 @staticmethod
    def read_from_folder(resource_name, domain, interpreter=RegexInterpreter(),
                         template_variables=None):
        """Given a path reads all contained story files."""

        story_steps = []
        for f in nlu_utils.list_files(resource_name):
            steps = StoryFileReader.read_from_file(f, domain, interpreter,
                                                   template_variables)
            story_steps.extend(steps)
        return story_steps
Problem:
nlu_utils has no attribute list_files

I'll really appreciate If anyone can give me a light!!!

**Comment by tmbo** [comment]
What version of Rasa NLU / Core are you using (`pip show rasa_nlu`, `pip show rasa_core` in the **environment you are using**)?

**Comment by LeohTadeu** [comment]
I'm using the recommended version 0.8.6.
In the file bot.py fixed a couple weeks ago, the train-nlu is working, but the train-dialogue not!!!
I don't know why is not working, because there's not a error report when I execute the command at ubuntu's terminal.

**Comment by akelad** [comment]
What happens when you execute the command?

**Comment by DileepkumarT** [comment]
Rasa nlu: 0.13.1
Rasa Core: 0.10.4
OS:Windows
I'm also not able to train the dialogue model. Checked the yml file and there is no error. Below is the error. Someone suggest what to do

C:\Users\RAM\Desktop\New Bot\RASA_NLU_CORE>python -m rasa_core.train -d domain.yml -s stories.md -o models/dialogue
C:\Anaconda3\lib\site-packages\h5py\__init__.py:36: FutureWarning: Conversion of the second argument of issubdtype from `float` to `np.floating` is deprecated. In future, it will be treated as `np.float64 == np.dtype(float).type`.
  from ._conv import register_converters as _register_converters
Using TensorFlow backend.
C:\Anaconda3\lib\site-packages\pykwalify\core.py:99: UnsafeLoaderWarning:
The default 'Loader' for 'load(stream)' without further arguments can be unsafe.
Use 'load(stream, Loader=ruamel.yaml.Loader)' explicitly if that is OK.
Alternatively include the following in your code:

  import warnings
  warnings.simplefilter('ignore', ruamel.yaml.error.UnsafeLoaderWarning)

In most other cases you should consider using 'safe_load(stream)'
  data = yaml.load(stream)
Traceback (most recent call last):
  File "C:\Anaconda3\lib\runpy.py", line 193, in _run_module_as_main
    "__main__", mod_spec)
  File "C:\Anaconda3\lib\runpy.py", line 85, in _run_code
    exec(code, run_globals)
  File "C:\Users\RAM\Desktop\New Bot\RASA_NLU_CORE\rasa_core\train.py", line 155, in <module>
    additional_arguments)
  File "C:\Users\RAM\Desktop\New Bot\RASA_NLU_CORE\rasa_core\train.py", line 114, in train_dialogue_model
    training_data = agent.load_data(stories_file, **data_load_args)
  File "C:\Users\RAM\Desktop\New Bot\RASA_NLU_CORE\rasa_core\agent.py", line 232, in load_data
    debug_plots)
  File "C:\Users\RAM\Desktop\New Bot\RASA_NLU_CORE\rasa_core\training\__init__.py", line 49, in load_data
    graph = extract_story_graph(resource_name, domain)
  File "C:\Users\RAM\Desktop\New Bot\RASA_NLU_CORE\rasa_core\training\__init__.py", line 29, in extract_story_graph
    domain, interpreter)
  File "C:\Users\RAM\Desktop\New Bot\RASA_NLU_CORE\rasa_core\training\dsl.py", line 144, in read_from_folder
    for f in nlu_utils.list_files(resource_name):
AttributeError: module 'rasa_nlu.utils' has no attribute 'list_files'

**Comment by akelad** [comment]
Are you sure you have nlu 0.13.1 installed?

**Comment by DileepkumarT** [comment]
Yeah it is. I have been trying for days but when i change the directory and run again it is working fine now. don't know what happened

**Comment by akelad** [comment]
so it works fine now then? I guess maybe you had two different environments, maybe conflicting versions were installed in those

**Comment by DileepkumarT** [comment]
Yeah! I didn't notice it first. It's cool  now. Thanks for the quick response.

**Comment by akelad** [comment]
Cool, I'll close this issue then
