### ISSUE TITLE
ImportError: cannot import name 'MaxHistoryTrackerFeaturizer'

### ISSUE THREAD

**Issue by johnnogent** [RasaHQ/rasa_core#498]
**Rasa Core version**: 0.8.6

**Python version**: 3.6.5

**Operating system** (windows, osx, ...): windows

**Issue**: cannot import name 'MaxHistoryTrackerFeaturizer'
I am running example restaurantbot as it is in this 

**Content of domain file** (if used & relevant):
```yaml

```the domain file as it is under github. No changes at all.


Thanks

**Comment by tmbo** [comment]
`MaxHistoryTrackerFeaturizer ` is only present in the latest version on master not in the version you referenced (`0.8.6`). So you either need to view the documentation for the version you have installed, or install the version you are viewing the documentation for.

**Comment by tmbo** [comment]
This isn't enough detail to let us help you.

What version of Core are you using?
Please attach a link to the documentation you are using?
What is the exact error message?
Is there a stacktrace?

**Comment by revathy-umapathy** [comment]
root@cri-sd-iva-dev:~/rasa_core/examples/restaurantbot# make train-nlu
python bot.py train-nlu
Traceback (most recent call last):
  File "bot.py", line 16, in <module>
    from rasa_core.featurizers import (
ImportError: cannot import name MaxHistoryTrackerFeaturizer
Makefile:13: recipe for target 'train-nlu' failed
make: *** [train-nlu] Error 1

**Comment by tmbo** [comment]
Which versions of the software are you using?

**Comment by benjamingarrett** [comment]
I too am having the same problem, and I'm running version 0.8.6 of rasa_core. Any suggestions are greatly appreciated. Thanks!

**Comment by tmbo** [comment]
Please make sure to follow the correct documentation for the version you installed, so in your case that would be https://core.rasa.com/0.8.6/index.html

**Comment by benjamingarrett** [comment]
Thanks tmbo, for your response. How do I upgrade to the most recent version? Or better yet, if I have both versions installed, how do I choose which version to use? And if MaxHistoryTrackerFeaturizer isn't supposed to be there, then why was it included in my 0.8.6 version in the first place?

**Comment by benjamingarrett** [comment]
Actually the version I have is now 0.9.0a6 and I still get the same problem, even though I see the featurizer module which is not able to be imported. Is there something obvious that I'm missing?

**Comment by manigaru** [comment]
Where to locate the the bot.py (older version)? Thank you so much.

Please make sure to follow the correct documentation for the version you installed, so in your case that would be https://core.rasa.com/0.8.6/index.html. As you can see in the example there, bot.py does not contain MaxHistoryTrackerFeaturizer

**Comment by tmbo** [comment]
I'll close this for now, please let us know if you have any further questions.

**Comment by ranjan-sumit** [comment]
---------------------------------------------------------------------------
ImportError                               Traceback (most recent call last)
<ipython-input-3-3c1a3501d105> in <module>()
     10 from rasa_core.policies.memoization import MemoizationPolicy
     11 from rasa_core.interpreter import RasaNLUInterpreter
---> 12 from rasa_core.utils import EndpointConfig
     13 from rasa_core.run import serve_application

ImportError: cannot import name 'EndpointConfig'


How to fix this error?

**Comment by akelad** [comment]
Please create a new issue
