### ISSUE TITLE
Mutiple Entities Extract in Rasa

### ISSUE THREAD

**Issue by hemanth1991** [RasaHQ/rasa_core#504]
Hi,
How to extract multiple entities belonging to a different entity name in tracker -- actions.py, say I have
Example: I want to play Badminton on Monday.
Here Badminton belongs to Sports Entity and Monday belongs to Days Entity.

I know how to take entity name belonging to the same Entity using "tracker.get_latest_entity_values("entity name") but not sure on the above issue. Kindly help.

Thanks
Hemanth Naidu S

**Comment by tmbo** [comment]
Lets say you defined two entity types `sport` and `date` for your NLU model to extract `Badminton` and `Monday` (although for a date you should use a pretrained entity, e.g. ducklings date type).

Now you can get these values in your action by using:
```
sport = next(tracker.get_latest_entity_values("sport"), None)   # and
date = next(tracker.get_latest_entity_values("date"), None)
```
They will be set to `None` if there is no value in the utterance for these entities.
