### ISSUE TITLE
deepcopy messes with my complex slot

### ISSUE THREAD

**Issue by pchalasani** [RasaHQ/rasa_core#505]
**Rasa Core version**:
master from github:  0.9.0a6
**Python version**: 
3.6.5
**Operating system** (windows, osx, ...):
Mac OS 10.13.4
**Issue**:
Tracker deepcopy messes with my complex slot

In my domain I have a slot that contains a complex object and I set it up as `unfeaturized`. Every now and then, the tracker insists on doing a deepcopy of all its slots, and when tries to do a deepcopy of this object, it fails eventually because `__len__()` gives an error. To get around this, instead of storing the object itself in the slot, I use `pickle.dumps(obj)` to convert it to a string, and store that in the slot. Obviously it would be good to avoid the back-and-forth pickling, so I'm wondering if there is some way I can prevent the tracker from doing a deepcopy of certain slots.

**Comment by tmbo** [comment]
This is because sometimes we need to clone the tracker to do some operations without modifying the original copy. Do you know why a deepcopy doesn't work for your object?

**Comment by pchalasani** [comment]
The object is from another (open source) package, and during deepcopy, it eventually needs the `__len__()` of the object and it fails because `__len__()` is not defined. 

You say that the tracker "sometimes" needs to be cloned. Is that behavior necessary or somehow modifiable? If not, I think `cpickle.dumps/loads` is fine for my purposes.
