### ISSUE TITLE
how can 2 intents share 1 entity value ?

### ISSUE THREAD

**Issue by linanzhu** [RasaHQ/rasa_core#507]
**Rasa Core version**: 0.9.0a3
**Python version**: 2.7.12
**Operating system** (windows, osx, ...): Ubuntu 16.04

**Issue**:  
[STORY1]
Human : I want to listen to music      -->  **intent : ```listen_music```**
Robot : Which music do you want ?   --> **action : ```utter_ask_music```**
Human : I like ```Jazz```  -->   **intent : ```like```**
Robot : Ok, I will play ```Jazz```  -->  **action : ```action.play_music```**

[STORY2 -  intent : ```order_food```]
Human : I want to order food for lunch  --> **intent : ```order_food```**
Robot : Which food do you want ?  --> **action : ```utter_ask_food```**
Human : I like ```Pizza```  --> **intent : ```like```**
Robot : Ok, I will order ```Pizza```  --> **action : ```action.order_food```** 

Here 3 intents.  ```listen_music```,  ```order_food``` and ```like```

First Question : Should I make 2 different ```like``` intent ?    like  ```like_music```,  ```like_food``` ?

Second Question : If it is ok to use one intent for ```like```,  and if human say "I like Jazz" for ```order_food``` intent, ```action.order_food``` action function should check validity of this entity?
```Jazz``` is not food name. The ```action.order_food```  should return like "Jazz is not food, give me food name".   How can I do this?        Or do you have better idea?

**Comment by Ghostvv** [comment]
You can use one intent with different entities, but you'll need to create nlu data for it, for example:
```
[
  {
    "text": "I like Jazz",
    "intent": "like",
    "entities": [
      {
        "start": 7,
        "end": 11,
        "value": "Jazz",
        "entity": "music"
      }
    ]
  },
  {
    "text": "I like Mexican food",
    "intent": "like",
    "entities": [
      {
        "start": 7,
        "end": 14,
        "value": "Mexican",
        "entity": "food"
      }
    ]
  }
]
```
see nlu docs nlu.rasa.com for details

A story for the `rasa_core` could be:
```
## story like music
* listen_music
   - utter_ask_music
* like{"music": "Jazz"}
   - action_play_music

## story like food
* order_food
   - utter_ask_food
* like{"food": "Mexican"}
   - action_order_food
```

see core docs core.rasa.com for details

**Comment by linanzhu** [comment]
@Ghostvv  Thank you for your answer.  
In case of answer "I like Jazz" for asking which food,  but NLU will take Jazz as entity, right?
Then action will say "I will order Jazz".  But this is wrong.
This should be taken care in action function?  or How can we handle this ?

**Comment by auzair92** [comment]
@Ghostvv Is there any major difference between providing the NLU data in JSON format and the one example that you have given above? I would normally use Chatito to write my training file for the above intent like this:

```
{
  "rasa_nlu_data": {
    "regex_features": [],
    "entity_synonyms": [],
    "common_examples": [
      {
        "text": "I like Jazz",
        "intent": "like",
        "entities": [
          {"start": 7, "end": 11, "value": "Jazz", "entity": "music"}
        ]
      },
      {
        "text": "I like Mexican food",
        "intent": "like",
        "entities": [
          {"start": 7, "end": 14, "value": "Mexican", "entity": "food"}
        ]
      }
    ]
  }
}
```

Are there any performance or optimization advantages associated with any of the two techniques, or do the training examples like
```
## intent:like
- I like [Jazz](music)
- I like [Mexican](food) food
```

eventually get converted to JSON format any way?

**Comment by Ghostvv** [comment]
@auzair92 you can use JSON. Markdown is just more human readable format

**Comment by Ghostvv** [comment]
@linanzhu if after asking food, a user input `I like Jazz`, predicted next action will depend on other stories and underlying ML algorithm. How to handle it depends on your full use case. One of the possible solutions would be to create another training story, for example:
```
## story like food
* order_food
   - utter_ask_food
* like{"music": "Jazz"}
   - action_wrong_input
   - utter_ask_food
```
or something similar.

**Comment by linanzhu** [comment]
@Ghostvv  Thank you for your explaining.   And one more following question.

You wrote  ```* like{"music": "Jazz"}```.    I am using spaCy.  This NLU can extract "Jazz"  in "I like Jazz".
But this NLU gives us the information that Jazz is one of music too?   
Or do we have to make some kind of dictionary ( or database) in RASA NLU training_data.json ?

What I thought was happening like this ...
```
## story like food
* order_food
   - utter_ask_food
* like{"food": "Jazz"}
   - action_order_food
```

If we add "Jazz" as music entity,  ```* like{"music": "Jazz"}```   this will be correct.
But if we forget to add "Hiphop" as music entity for example,  and Human said "I like Hiphop" in order_food story,  then NLU may be confused and it may extract Hiphop as food. 

To avoid this is happening, do we just need to add as many training data as possible into json ?

**Comment by Ghostvv** [comment]
@linanzhu If you define your NLU data as I mentioned earlier, `rasa_nlu` will extract "Jazz" as an entity of type "music". If you do not have "Hiphop" as an entity of type "music" in your training data it will never be extracted, so the phrase "I like Hiphop" would probably be just intent "like".

From the point of view of `rasa_core` these two stories are identical:
```
## story like music
* listen_music
   - utter_ask_music
* like{"food": "Jazz"}
   - action_order_food

## story like food
* order_food
   - utter_ask_food
* like{"food": "Mexican"}
   - action_order_food
```
