### ISSUE TITLE
Slot values in stories expect only strings

### ISSUE THREAD

**Issue by foxjr** [RasaHQ/rasa_core#511]
**Rasa Core version**: 0.8.6

**Python version**:  3.6

**Operating system** (windows, osx, ...): Linux (Fedora)

**Issue**:  Slot values in stories seem only to expect strings. For instance, when I am setting slots to `None` in actions (which is how they initialize, no?) and `null` in stories, I am bombarded by warnings that I'm setting slots to value types that are never set during training, since it is expecting `"None"`. This seems to indicate that my `None` value in actions is being stringified. 

Should I start using `"None"` in my stories? Could sticking to `null` adversely affect my bot's flow expectations? I've also noticed this behavior with `False`.

**Comment by tmbo** [comment]
Can you add an example? But no as far as I understand that should not be the case, you should be able to set any type allowed in a json.

**Comment by foxjr** [comment]
A story snippet:
![image](https://user-images.githubusercontent.com/34687548/40364608-c40aec84-5da0-11e8-8118-fc025d0499b3.png)

The above story snipped shows the action being performed based on the intent, and the slots being filled to some values throughout. The part of particular interest is at the end, where many slots are set to `null`.

My action snippet:
![image](https://user-images.githubusercontent.com/34687548/40364845-4708a68a-5da1-11e8-8098-4519f9c7d53e.png)

The above action snippet is my approach for clearing slots that were not filled after the last entity extraction, since this is appropriate my my specific use. You can see there that the slots are being set to `None` if they were not extracted from the most recent user message.

My command-line errors:
![image](https://user-images.githubusercontent.com/34687548/40364487-72b7a8e0-5da0-11e8-867d-b774895b44be.png)

The above errors seem to indicate that my `None` values given in my custom action are being stringified. It does seem to be adversely affecting my story flow, since in my case `{"results": null}` should trigger an expanded search; however, since it is being turned to a string, the bot things that there are results and attempts to display them.

**Comment by tmbo** [comment]
Alright, so I took a look at the print statement, the `""` are added to the `None` there, it is actually set to None, I'll change that output. Can you please add the content of the `policy_metadata.json` file from a trained model here? That would help me find the issue.

**Comment by foxjr** [comment]
Just trained using stories with `"None"` instead of `null`, and that _definitely_ didn't work--which makes sense, because it's just checking whether there's a string or not. I'll switch it back in my stories and then train again. I'll add the policy metadata content after that.

**Comment by tmbo** [comment]
So far I think you can ignore the warning. I also think the warning should not be emitted with the latest master version anymore. I am very happy to help :)

**Comment by foxjr** [comment]
I'm fairly certain it was a lack of training. I'm going to go ahead and close this. Thanks!
