### ISSUE TITLE
Connecti on with telegram is not happening

### ISSUE THREAD

**Issue by swathy06** [RasaHQ/rasa_core#528]
**Rasa Core version**: 0.8.6

**Python version**: 3.6

**Operating system** (windows, osx, ...): 7

**Issue**:
Connection with telegram is not happening.
Is the ssl certificate compulsory for connection of telegram and rasa core?
is ngrok method not possible for temporary connection,between rasa core and telegram?If yes,how to connect using ngrok?

**Content of domain file** (if used & relevant):
```yaml

```

**Comment by swapkh91** [comment]
Yes ssl is needed for Telegram unlike Slack. Telegram integration is working fine using ngrok. Following the docs on telegram integration should work, just use ngrok's https url as `webhook_url`.

**Comment by swathy06** [comment]
I have tried using ngrok url,Get works fine but the post is not happening from telegram.Can you please detail me the steps?

**Comment by swapkh91** [comment]
i just used the code [here](https://core.rasa.com/connectors.html#id6). You dont need to take care of get/post. what is the error you are getting?

**Comment by swapkh91** [comment]
I didn't try with the yml file because I needed some changes while running server. Try with the code it should work.

Use `Forwarding                    https://<sometext>.ngrok.io -> localhost:5004` as `webhook_url` and there shouldn't be a problem.

Also `verify="<bot username>"` should be normal bot name without `@`.

**Comment by swathy06** [comment]
Presently when i am trying to run the python code,there is error in this line
agent = Agent.load('dialogue1', interpreter=RegexInterpreter())
Any reason?Should i train the model again?

**Comment by swapkh91** [comment]
What is the error?

This line requires path to the dialogue folder, like `./models/dialogue` and the interpreter you are using eg. RegexInterpreter or RasaNLUInterpreter. But you need to have a trained model before this.

**Comment by swathy06** [comment]
I gave the path,presently i have used as set_webhook as the webhook_url,for the connection.When i run the program,it shows,Tensorflow backend.
It remains like that for about an hour.No response

**Comment by swapkh91** [comment]
If it is like this then your server is running:

![sadd](https://user-images.githubusercontent.com/5755405/40643770-c609f5d6-633e-11e8-9c9f-1ea4ed60e95f.PNG)

It should accept messages from telegram.

**Comment by swathy06** [comment]
The https url from ngrok is getting no valid message,when i inspected the ngrok

**Comment by akelad** [comment]
what's the webhook url you're passing?

**Comment by swathy06** [comment]
In the ngrok,i typed ngrok http 5004.
After getting the https url,I gave the url as "**https://14f13bde.ngrok.io/app/webhook**" for python program.I have also tried the command line run program where i gave the url as "**https://14f13bde.ngrok.io/webhook**"
Both are giving me the same error

**Comment by akelad** [comment]
Oh I've figured out your problem, you're using version 0.8.6 - in that version the webhook doesn't get set automatically. You have to navigate to `/set_webhook` first and then it will work.

**Comment by swathy06** [comment]
I have upgraded  rasa core to 0.9.3. Now am getting this error after setting ngrok
**Failed to complete tunnel connection**
The connection to https://0acea6d1.ngrok.io was successfully tunneled to your ngrok client, but the client failed to establish a connection to the local address localhost:5002.

Make sure that a web service is running on localhost:5002 and that it is a valid address.

The error encountered was: dial tcp [::1]:5002: connectex: No connection could be made because the target machine actively refused it.

**Comment by akelad** [comment]
I guess set a different port? In any case this seems like an issue with ngrok rather than rasa core

**Comment by tmbo** [comment]
I'll close this for now, please let us know if you have any further questions.
