### ISSUE TITLE
Add contributors to rasa and link from docs

### ISSUE THREAD

**Issue by akelad** [RasaHQ/rasa_core#536]

**Comment by tmbo** [comment]
Given that there are a lot contributions that overlap between core and nlu, we are going to put them on the rasa webpage and link from the documentation

**Comment by tmbo** [comment]
@amn41 is this part of the docs refactoring?

**Comment by amn41** [comment]
yes we're adding community info to the new landing page

**Comment by tmbo** [comment]
ok, is this done and part of the PR or does the landing page need to be created?

**Comment by amn41** [comment]
there's a first version but in a separate repo (not the core PR)
