### ISSUE TITLE
Mistake in documentation or ambiguity. About slots influencing next action prediction

### ISSUE THREAD

**Issue by rafis** [RasaHQ/rasa_core#540]
**Rasa Core version**: 0.9.0

**Python version**: 3.6

**Operating system** (windows, osx, ...): Ubuntu 18.04

**Issue**: I was reading how slots works for predicting next action on https://core.rasa.com/master/patterns.html. And have found two contradicting sentences:
"but the value of a TextSlot has **no impact** on which actions Rasa Core predicts."
"The value of the slot **will influence** the story dialogue if you add the slot to the training stories"

**Content of domain file** (if used & relevant):
```yaml
* inform{"number": 3}
     - action_restaurant_form
     - slot{"people": 3}
```

So the question is will this value of 3 in `inform{"number": 3}"` influence next action prediction or I can put any value there like 5,8,10 and it will behave the same?

**Comment by amn41** [comment]
if you have a `TextSlot`, then values "3", "5", "8", etc are all identical, the only thing which affects the dialogue is whether the value is `None` or something other than `None`.

**Comment by Priprocks** [comment]
- The slot of type unfeaturized will have no impact whatsoever in the subsequent predictions.

- For slots of all other types it's the outcome of the slot that affects the prediction.
   For example,
   - for type bool, it's either true or false.
   - for type text, its either there is a value or none.

I guess you are getting the idea. :)

**Comment by tmbo** [comment]
I'll close this for now, please let us know if you have any further questions. The docs have been updated (or are in the process of getting updated) as well.
