### ISSUE TITLE
Generator prints warning that loop checkpoints are unreachable.

### ISSUE THREAD

**Issue by Ghostvv** [RasaHQ/rasa_core#547]
**Rasa Core version**: `master`

**Python version**: 

**Operating system** (windows, osx, ...):

**Issue**:
Probably original loop checkpoints should be deleted in `with_cycles_removed` method.

**Content of domain file** (if used & relevant):
```yaml

```

**Comment by tmbo** [comment]
I think this should be fixed in latest master right?
