### ISSUE TITLE
Is the work being done to handle channel messages/mentions in Telegram? 

### ISSUE THREAD

**Issue by swapkh91** [RasaHQ/rasa_core#548]
**Rasa Core version**: 0.8.6

**Python version**: 3.6

**Operating system** (windows, osx, ...): WIndows

**Issue**:
Current version doesn't handle messages sent from Telegram channels or through mentions. Is it under work?

If not then I have made changes in `telegram.py` to handle this and I'll create a PR.

**Content of domain file** (if used & relevant):
```yaml

```

**Comment by akelad** [comment]
What do you mean through telegram channels? There's a telegram connector? Or do you mean group chats?

**Comment by swapkh91** [comment]
There are channels and groups in telegram where you need to type @bot or /bot if you want to talk to the bot. The current `rasa_core/channels/telegram.py` does not handle this.

**Comment by akelad** [comment]
This is supported: https://github.com/RasaHQ/rasa_core/blob/master/rasa_core/channels/telegram.py#L128

**Comment by swapkh91** [comment]
Yeah that line is for user message, not for message from a user through a channel/group where the bot is mentioned as `/bot <message>`. In that case the request is different.

**Comment by akelad** [comment]
Have you tried using it in a channel/group? Because we've built a bot and use it in a group, which works completely fine.

**Comment by akelad** [comment]
An important thing to do is to set the group settings of the bot to listen on mention only, otherwise it will parse every single message in that group

**Comment by swapkh91** [comment]
If we send message to bot from a channel, the text is present inside `channel_post.text` key of the request json and not in `message`.

**Comment by akelad** [comment]
Ok that's interesting. Is it possible that this is a recent change? In any case, if you've already written the code, we'd be happy to accept a pull request.

**Comment by swapkh91** [comment]
I don't know about the change but this is only in case of a channel message. Also I didn't find any setting related to bot only listening to mentions for the channel. It is there for groups.

**Comment by akelad** [comment]
I'm still not understanding what the difference is between a group and channel... To me those are one and the same. In any case, the url you linked says that bots can have private mode enabled, which is what i'm talking about.

**Comment by amn41** [comment]
@swapkh91 can we close this?
