### ISSUE TITLE
agent_handle : gevent module issue not fixed in 0.9

### ISSUE THREAD

**Issue by praveenrengarajan** [RasaHQ/rasa_core#549]
**Rasa Core version**: 0.9

**Python version**:  3.6

**Operating system** (windows, osx, ...): Windows 10 x64

**Issue**:  

`from __future__ import absolute_import
from __future__ import division
from __future__ import print_function
from __future__ import unicode_literals

import logging

from rasa_core.channels import HttpInputChannel
from rasa_core import utils
from rasa_core.agent import Agent
from rasa_core.interpreter import RasaNLUInterpreter
from rasa_core.channels.channel import UserMessage
from rasa_core.channels.direct import CollectingOutputChannel
from rasa_core.channels.rest import HttpInputComponent
from flask import Blueprint, request, jsonify

logger = logging.getLogger(__name__)
class SimpleWebBot(HttpInputComponent):

    def blueprint(self, on_new_message):
        custom_webhook = Blueprint('custom_webhook', __name__)

        @custom_webhook.route("/status", methods=['GET'])
        def health():
            return jsonify({"status": "ok"})

        @custom_webhook.route("/", methods=['POST'])
        def receive():
            payload = request.json
            sender_id = payload.get("sender", None)
            text = payload.get("message", None)
            out = CollectingOutputChannel()
            on_new_message(UserMessage(text, out, sender_id))
            responses = [m["text"] for m in out.messages]
            return jsonify(responses)
    
        return custom_webhook

def run(serve_forever=True):
    #path to your NLU model
    interpreter = RasaNLUInterpreter("models/nlu/default/current")
    # path to your dialogues models
    agent = Agent.load("models/dialogue", interpreter=interpreter)
    #http api endpoint for responses
    input_channel = SimpleWebBot()
    if serve_forever:
        agent.handle_channel(HttpInputChannel(5004, "/chat", input_channel))
    return agent
if __name__ == '__main__':
    utils.configure_colored_logging(loglevel="INFO")
    run()`
when trying to run flask am getting following error. ** Even downgraded gevent from 1.3 to 1.2  ** but no use. @tmbo  as you guys mentioned https://github.com/RasaHQ/rasa_core/commit/93ff38333935354b1e4f01d74bbf6f7dce4242e0
if it fixed. why am still getting the error. 
![gevent error](https://user-images.githubusercontent.com/2884636/40643400-a7d5f566-633d-11e8-85e8-f314598333b2.PNG)

** please help to fix this, 2 days am looking for the solution for this issue**

**Content of domain file** (if used & relevant):
```yaml

```

**Comment by praveenrengarajan** [comment]
@tmbo  @akelad @tupac56

**Comment by tmbo** [comment]
You are most certainly not using version `0.9` because it uses `from gevent.pywsgi import WSGIServer` at that location.

**Comment by tmbo** [comment]
So please double check your version, but most likely you've installed an unsupported version of gevent  with an older rasa core version.

**Comment by praveenrengarajan** [comment]
@tmbo  
![gevent](https://user-images.githubusercontent.com/2884636/40648703-b40f8090-634c-11e8-91a3-2bc72652adfa.PNG)
![rasa-core](https://user-images.githubusercontent.com/2884636/40648705-b447ee12-634c-11e8-9c50-5bd82d84cc41.PNG)

**Comment by tmbo** [comment]
You are probably in a different env there. I took another look at the code that is tagged with 0.9.0 and this is the code at that location https://github.com/RasaHQ/rasa_core/blob/0.9.0/rasa_core/channels/rest.py#L57 and it contains the correct import (`pywsgi` instead of `wsgi`). So really make sure your code in your anaconda env is really running 0.9.0

**Comment by praveenrengarajan** [comment]
yep, my bad. Created new Conda environment working now. I have installed 0.9.0a3 global and 0.9 in old environment , but i dont why it didnt take environment package.  Any how thanks.

**Comment by tmbo** [comment]
:+1:
