### ISSUE TITLE
Create event stream output

### ISSUE THREAD

**Issue by tmbo** [RasaHQ/rasa_core#554]
Rasa Core should submit new events on trackers to an output (e.g. Kafka) as an event stream. This allows other systems to consume the data about conversations and do some analytics.

**Comment by nahidalam** [comment]
This seems like a great feature. @ricwo If you or anyone else has started working on it, would love to collaborate

**Comment by tmbo** [comment]
@ricwo has been working on a first implementation of this. I'd love to get your input on the PR if you like, @nahidalam.

**Comment by tmbo** [comment]
@ricwo I think we can close this now that the changes are merged into the sdk branch. Or is there something that still needs to be done here?
