### ISSUE TITLE
How to find the number of active connections to Rasa agent

### ISSUE THREAD

**Issue by nahidalam** [RasaHQ/rasa_core#555]
**Rasa Core version**: 0.9.0a6

**Python version**: 3.6

**Operating system** (windows, osx, ...): OSx

**Issue**:
I am creating connection with Rasa agent using different `sender_id`
Is there a way to know how many agent connections are active right now? I don’t see anything in the `agent` API.

**Content of domain file** (if used & relevant):
```yaml

```

**Comment by auzair92** [comment]
I believe you can do that by performing a GET call on `/conversations` endpoint.
[Relevant docs](https://core.rasa.com/master/http.html?highlight=conversation#get--conversations).

**Comment by tmbo** [comment]
I'll close this for now, please let us know if you have any further questions.
