### ISSUE TITLE
 Failed to load any agent model.

### ISSUE THREAD

**Issue by NikhilBansal21** [RasaHQ/rasa_core#560]
**Rasa Core version**: 0.9.0a3

**Python version**: 3.6.5

**Operating system** (windows, osx, ...):10

**Issue**:
Failed to load model metadata from 'E:\nikhil_projects\nodeProjects\ChatBot-latest\RASA\itsm-rasa-bot\nlu\default\current\metadata.json'. [Errno 2] No such file or directory: 'nlu\\default\\current\\metadata.json'  

I have metadata.json present in the mentioned directory.
The error occurs on running the command for rasa core server 
python -m rasa_core.server -d models\dialogue -u nlu\default\current -o out.log
i have checked and created a separated directory also still getting this error. This used to work fine with following command python -m rasa_core.server -d models\dialogue -u nlu\default\current -o out.log

**Content of domain file** (if used & relevant):
```yaml

```

**Comment by auzair92** [comment]
I think you might be missing the `models` directory for the `-u` switch. Could this be the command you're looking for:
`python -m rasa_core.server -d models\dialogue -u models\nlu\default\current -o out.log`

**Comment by Priprocks** [comment]
- Are you training the NLU and is the fixed_model_name set to 'current'?
- Check if the folder is generated there.
- As @auzair92 mentioned, you are missing the nlu model parameter in the argument.

**Comment by NikhilBansal21** [comment]
thanks i missed the small detail

**Comment by akelad** [comment]
Will close this for now, let us know if there's more issues.
