### ISSUE TITLE
HTTP server not creating new session for each user

### ISSUE THREAD

**Issue by nelashj** [RasaHQ/rasa_core#563]
**Rasa Core version**: 0.9.0

**Python version**: 2.7

**Operating system** (windows, osx, ...): RHEL

**Issue**: I have deployed rasa as http server. It works fine when one user try to acces it but when multiple user try to access, it does not create new session for each user. Session get shared between multiple users. 

SO want to understand how to main separate session for each user so that each user can access bot independently

**Comment by auzair92** [comment]
How are you calling the server for each user? In the GET/POST call, you can change the `sender_id` for each user to start a new conversation. Here's the call: `localhost:5005/conversations/sender_id/parse`.

For example, for two separate users, user_1 and user_2, the calls would be, respectively:
localhost:5005/conversations/default/parse

**Comment by Priprocks** [comment]
I guess you are making the requests using 'default'. It works for a single client, when there are more than 1, you need to make those calls using the client ids.

**Comment by nelashj** [comment]
thanks for replying.. it worked...
