### ISSUE TITLE
Cisco Spark connector

### ISSUE THREAD

**Issue by tmbo** [RasaHQ/rasa_core#565]
Connector to connect to the cisco spark chat client.

**Comment by nahidalam** [comment]
Where are we with this? I work at Cisco, maybe I can help? BTW - it is called Webex Teams now.

**Comment by nahidalam** [comment]
@tmbo from the codebase perspective, you mean creating a channel, right?

**Comment by akelad** [comment]
yes, if you'd be willing to make this contribution that'd be great. I'm not sure there's an API to connect to though?

**Comment by nahidalam** [comment]
@akelad not sure what you mean? There is Botkit for Cisco Webex Teams, so there must be an API.  Also messages from Webex Teams comes as webhooks FYI.

**Comment by nahidalam** [comment]
Hm, I looked around a bit. There is a python API (https://pypi.org/project/ciscosparkapi/) but that is not supported by Cisco. The way Botkit does it is through the supported NodeJS API. So I think it is doable but not sure if Cisco will support if there is any API issue

**Comment by akelad** [comment]
Is it not supported by Cisco? It seems to be: https://github.com/CiscoDevNet/webexteamssdk

**Comment by nahidalam** [comment]
Yes, already working. Wrote the portion for the bot. But I am a bit confused about the authentication related class methods like `def from_credentials(cls, credentials):` following other channels code.

**Comment by nahidalam** [comment]
While developing a Webex Teams bot, we get an access token called `CISCOSPARK_ACCESS_TOKEN` which is a setup in the environment (.bash_profile for Mac). As per https://github.com/CiscoDevNet/webexteamssdk this token is automatically picked up by this API (can't verify yet).  So my `from_credentials` method looks like below. 

```
def from_credentials(cls, credentials):
        if not credentials:
            cls.raise_missing_credentials_exception()

        return cls(credentials.get("CISCOSPARK_ACCESS_TOKEN"))
```

Am I in the right direction? Any other way I can do faster communication than this github issue?

**Comment by akelad** [comment]
i think people should write that token to a file with the credentials, so you can just do `credentials.get("access_token")`
Communication through here is best, to keep track of everything

**Comment by nahidalam** [comment]
Thanks @akelad 

I looked into `connectors.rst` and it says

"**Your blueprint should have at least the two routes ``health`` on ``/``
and ``receive`` on the http route ``/webhook``.**"

But as a sample, I don't see any `receive` in `slack.py` or `facebook.py` connectors. What am I misisng?

**Comment by nahidalam** [comment]
Also, following slack connector here (https://github.com/RasaHQ/rasa_core/blob/master/rasa_core/channels/slack.py), is there a reason that you are sub-classing the `SlackClient` class?

**Comment by nahidalam** [comment]
@akelad Finished coding and testing it now
I am testing it with below command

`python -m rasa_core.run -d models/dialogue -u models/nlu/current --port 5002 --credentials credentials.yml`

This is showing below error

`rasa_nlu.model.UnsupportedModelError: The model version is to old to be loaded by this Rasa NLU instance. Either retrain the model, or run withan older version. Model version: 0.12.3 Instance version: 0.13.7`

I have the core version from github master and nlu version `0.12.3`. And it looks like I need to train the nlu model with NLU version `0.13.7` before I can use this core version? Only changing the core version and retraining the dialogue model with the new core version is not enough? 

This command `python -m rasa_core.run -d models/dialogue -u models/nlu/current --port 5002 --credentials credentials.yml` is only dealing with rasa core so why the error message is about rasa nlu?
Am I missing something?

**Comment by akelad** [comment]
because you're loading an nlu model in that command :) you can just leave out the `-u` flag and test only with core. Otherwise you have to retrain your NLU model with version 0.13.7 (because it seems you have NLU 0.13.7 installed, but the nlu model you're loading was trained with 0.12.3)

**Comment by nahidalam** [comment]
Ok, so that is resolved along with the core issue. Now when I am testing, I am seeing error 

`KeyError: 'ciscowebexteams'`

But it is not pointing to any specific code line that I wrote. So assuming it is expecting  `ciscowebexteams` key somewhere else where I haven't specified it. The entire call stack is 

```
Traceback (most recent call last):
  File "/Users/nahalam/anaconda3/lib/python3.6/runpy.py", line 193, in _run_module_as_main
    "__main__", mod_spec)
  File "/Users/nahalam/anaconda3/lib/python3.6/runpy.py", line 85, in _run_code
    exec(code, run_globals)
  File "/Users/nahalam/Documents/code/rasa_core/rasa_core/run.py", line 260, in <module>
    cmdline_args.jwt_method)
  File "/Users/nahalam/Documents/code/rasa_core/rasa_core/run.py", line 195, in serve_application
    input_channels = create_http_input_channels(channel, credentials_file)
  File "/Users/nahalam/Documents/code/rasa_core/rasa_core/run.py", line 115, in create_http_input_channels
    for c, k in all_credentials.items()]
  File "/Users/nahalam/Documents/code/rasa_core/rasa_core/run.py", line 115, in <listcomp>
    for c, k in all_credentials.items()]
  File "/Users/nahalam/Documents/code/rasa_core/rasa_core/run.py", line 124, in _create_single_channel
    input_channel_class = utils.class_from_module_path(channel)
  File "/Users/nahalam/Documents/code/rasa_core/rasa_core/utils.py", line 90, in class_from_module_path
    return globals()[module_path]
KeyError: 'ciscowebexteams'

```

Any suggestion?

**Comment by tmbo** [comment]
the code assumes that the name you used in the `credentials.yml` is either a build in channel name or a module path. 

One solution is:
1. make sure the `name` method of your channel returns `ciscowebexteams`
2. add the channel class to `input_channel_classes` in `rasa_core/channels/__init__.py`

**Comment by nahidalam** [comment]
@tmbo thanks. 

I am running below command

`python -m rasa_core.run -d models/dialogue -u models/nlu/current --port 5002 --credentials credentials.yml`


Now I have the webexteams bot and sending message through a webhook. But I get below message in the terminal. 

```
2018-11-04 11:39:42 INFO     root  - Rasa Core server is up and running on http://localhost:5002
127.0.0.1 - - [2018-11-04 14:32:42] "POST /wenhook HTTP/1.1" 404 342 0.004444
```

Looks like the server is not running although the output is saying that the server is running. And someone had a typo of `wenhook` instead of `webhook`.  Please suggest.


My blueprint code looks like below:

```
def blueprint(self, on_new_message):
        ciscowebexteams_webhook = Blueprint('ciscowebexteams_webhook', __name__)

        @ciscowebexteams_webhook.route("/", methods=['GET'])
        def health():
            return jsonify({"status": "ok"})

        @ciscowebexteams_webhook.route("/webhook", methods=['GET', 'POST'])
        def webhook():
            """Processes incoming requests to the '/webhook' URI."""
            if request.method == 'GET':
                return ("HTML code removed for simplicity")
            elif request.method == 'POST':
                """Respond to inbound webhook JSON HTTP POST from Webex Teams."""

                # Get the POST data sent from Webex Teams
                json_data = request.json
                print("\n")
                print("WEBHOOK POST RECEIVED:")
                print(json_data)
                print("\n")

                # Create a Webhook object from the JSON data
                webhook_obj = Webhook(json_data)
                # Get the room details
                room = WebexTeamsAPI().rooms.get(webhook_obj.data.roomId)
                # Get the message details
                message = WebexTeamsAPI().messages.get(webhook_obj.data.id)
                # Get the sender's details
                person = WebexTeamsAPI().people.get(message.personId)

                print("NEW MESSAGE IN ROOM '{}'".format(room.title))
                print("FROM '{}'".format(person.displayName))
                print("MESSAGE '{}'\n".format(message.text))

                # This is a VERY IMPORTANT loop prevention control step.
                # If you respond to all messages...  You will respond to the messages
                # that the bot posts and thereby create a loop condition.
                me = WebexTeamsAPI().people.me()
                if message.personId == me.id:
                    # Message was sent by me (bot); do not respond.
                    return 'OK'

                else:
                    return self.process_message(
                            on_new_message,
                            text=message,
                            sender_id=message.personId)


            return make_response()

        return ciscowebexteams_webhook
```

**Comment by tmbo** [comment]
What is the webhook url you configured in webex?

**Comment by nahidalam** [comment]
So the server is running at `http://localhost:5002`
I used ngrok to create a URL `http://51b830e7.ngrok.io -> localhost:5002`

And the webhook is /webhook so the target URL at webex is `http://51b830e7.ngrok.io/webhook`

Does that make sense?

**Comment by tmbo** [comment]
alright I think that explains the issue: the webhook is actually at 
`http://localhost:5002/webhooks/ciscowebexteams/webhook` (where `ciscowebexteams` is the same string as returned by the `def name` function of your channel).

**Comment by nahidalam** [comment]
@tmbo thanks so the webhook is working. I see the message is coming with JSON output and logs but after that I get this error

```
2018-11-05 04:41:05 ERROR    rasa_core.channels.ciscowebexteams  - Exception when trying to handle message.'Message' object has no attribute 'startswith'
2018-11-05 04:41:05 ERROR    rasa_core.channels.ciscowebexteams  - 'Message' object has no attribute 'startswith'
Traceback (most recent call last):
  File "/Users/nahalam/Documents/code/rasa_core/rasa_core/channels/ciscowebexteams.py", line 117, in process_message
    on_new_message(user_msg)
  File "/Users/nahalam/Documents/code/rasa_core/rasa_core/agent.py", line 305, in handle_message
    return processor.handle_message(message)
  File "/Users/nahalam/Documents/code/rasa_core/rasa_core/processor.py", line 77, in handle_message
    tracker = self.log_message(message)
  File "/Users/nahalam/Documents/code/rasa_core/rasa_core/processor.py", line 123, in log_message
    self._handle_message_with_tracker(message, tracker)
  File "/Users/nahalam/Documents/code/rasa_core/rasa_core/processor.py", line 256, in _handle_message_with_tracker
    parse_data = self._parse_message(message)
  File "/Users/nahalam/Documents/code/rasa_core/rasa_core/processor.py", line 232, in _parse_message
    if (message.text.startswith(INTENT_MESSAGE_PREFIX) or
  File "/Users/nahalam/anaconda3/lib/python3.6/site-packages/webexteamssdk/models/immutable.py", line 104, in __getattr__
    "".format(self.__class__.__name__, item)
AttributeError: 'Message' object has no attribute 'startswith'
127.0.0.1 - - [2018-11-05 04:41:05] "POST /webhooks/ciscowebexteams/webhook HTTP/1.1" 200 115 2.372838
```

**Comment by tmbo** [comment]
Most likely the argument you pass to the `on_new_message` function is not a `UserMessage` object (it needs to be an instance of `from rasa_core.channels import UserMessage` ). Not sure, maybe you are passing in a webex specific message object? (not sure because you didn't add the code for `self.process_message`)

**Comment by nahidalam** [comment]
@tmbo looks like it is working. Just tested. Attached screenshot. 

![image](https://user-images.githubusercontent.com/2341472/48140403-90901e00-e25d-11e8-9e6c-647f127d6524.png)

**Comment by nahidalam** [comment]
@tmbo submitted the PR https://github.com/RasaHQ/rasa_core/pull/1292

**Comment by tmbo** [comment]
Thats awesome :+1: thanks a lot for the time you have put into this! We'll take a look at it :rocket:

**Comment by nahidalam** [comment]
@tmbo 
it is failing PEP test. Other than PEP, what other tests I should run?

**Comment by nahidalam** [comment]
We probably should close this issue as the connector is already merged

**Comment by akelad** [comment]
good point, thanks for noticing :D
