### ISSUE TITLE
Bot messages wrapped with "text:" string

### ISSUE THREAD

**Issue by Amsterdoom** [RasaHQ/rasa_core#566]
**Rasa Core version**:
0.9.0a2

**Python version**: 
Python 3.6

**Operating system** (windows, osx, ...):
Ubuntu 17.10

**Issue**:
Messages from the rasa bot are preceded by the string "text :" and between quotation mark (in personal UI and when running the bot directly in the terminal).
Example :  text:"How can I help you?" instead of How can I help you?

From my message_store file : 
"username": "bot", "message": {"type": "text", "text": "text:\"How can I help you?\""}, "uuid": "1c7d6a59-2a00-4102-85b1-f29b65a27893"}

Any ideas on how to resolve this issue?

**Comment by auzair92** [comment]
Can you show a few bot utterance examples from the domain file? It should be something like this:
```
utter_offer_help:
  - text: "How can I help you?"
```
From your message_store example above, it is clear that `"text:"How can I help you?"` is the string that is being used as `text` parameter in its entirety. You need to take care of that in your utter templates.

**Comment by Amsterdoom** [comment]
Indeed that was the source of the problem, something went wrong with my domain generation script, I feel bad for not realizing this. Thank you for your help!
