### ISSUE TITLE
Is it possible to create mathematical operations from rasa core,like calculator bot.

### ISSUE THREAD

**Issue by swathy06** [RasaHQ/rasa_core#579]
**Rasa Core version**:0.9.3

**Python version**: 3.6

**Operating system** (windows, osx, ...):7

**Issue**:Is it possible for  rasa core bot  to do mathematical operations The user have to input number,the bot would ask the action which it needs to perform?

**Content of domain file** (if used & relevant):
```yaml

```

**Comment by Walter-Ullon** [comment]
I don't see why it shouldn't be possible.

If you're training your bot to recognize and capture numbers as entities, and mathematical operations as intents, then the actual calculation logic would be handled by your `actions.py` file.

Similarly, you could also call an operation, say, SUM, and the bot would ask for a list of numbers to add. You would fill a slot with this and use logic in `actions.py` file to parse the list and add them, etc..

**Comment by swathy06** [comment]
In the actions.py,how to pass the the number to do calculation which are defined in slots?

**Comment by amn41** [comment]
you can get slots within an action by calling `tracker.get_slot()`

**Comment by tmbo** [comment]
I'll close this for now, please let us know if you have any further questions.
