### ISSUE TITLE
Setting context in Rasa

### ISSUE THREAD

**Issue by Priprocks** [RasaHQ/rasa_core#582]
**Issue**:
Is there a way to set a hierarchy of intent classification?
I mean to say is, if that some intent (child) can only be triggered if the previous intent was its parent intent.
In dialogflow, there's context that can be used to do the same but I cannot seem to find anything here.

**Comment by Walter-Ullon** [comment]
This is a really interesting question, do you have a concrete example of the behavior your expecting?
