### ISSUE TITLE
Repeating intent handling

### ISSUE THREAD

**Issue by RAJAT--PALIWAL** [RasaHQ/rasa_core#584]
**Rasa Core version**: **0.9.3**

**Python version**: **3.6.4**

**Operating system** (windows, osx, ...):**Windows 10**

**Issue**: If the same intent is repeated then trained stories fail to predict right response. 

**Content of domain file** (if used & relevant):
```
## Story 00
* payment
  - utter_payment_summary
* mail_invoice
  - utter_payment_invoice
* over_due
  - utter_payment_overdue
```

If over_due is called twice, story flow breaks and bot generates the response from other stories or gives response for payment.

Issue seems to be there because of max_history of past actions helping prediction of next action in CustomPolicy.

**Comment by auzair92** [comment]
I used [checkpoints](https://core.rasa.com/stories.html?highlight=checkpoint#format) when I faced a similar issue. In my case, I looped the input back to a previous point. I'm not sure how it would work in your case, but here's an example of how I did it:
```
## offer help
- utter_offer_help
> chk_offer_help

## handle unknown
> chk_offer_help
* unknown_services
- utter_cant_do_that
- utter_offer_help
> chk_offer_help
```
May be something similar could work for you as well.

**Comment by amn41** [comment]
@RAJAT--PALIWAL have you included this as a story ? e.g. 
```
## Story 01
* payment
  - utter_payment_summary
* mail_invoice
  - utter_payment_invoice
* over_due
  - utter_payment_overdue
* over_due
  - utter_payment_overdue
```

**Comment by RAJAT--PALIWAL** [comment]
@amn41 @auzair92 I'm going to try both of your approaches and let you know.

**Comment by RAJAT--PALIWAL** [comment]
@amn41 your solution works well but does not scale and starts making mistakes if In story intents have different actions.
```
## Story 01
* mail_invoice
  - utter_sorry
* mail_invoice
  - utter_sorry

## Story 02
* payment
  - utter_payment_summary
* mail_invoice
  - utter_payment_invoice
* mail_invoice
  - utter_payment_invoice

```

**Comment by reza-ebrahimi** [comment]
I have same problem, intents repeats with jumping over them and executing their actions continuously.
