### ISSUE TITLE
starting the bot with an uttering, not with action_listen

### ISSUE THREAD

**Issue by disimone** [RasaHQ/rasa_core#585]
**Rasa Core version**:
commit b0b76d8076b7165345477715b886f5771081c7f5

**Issue**:

Hi, I have a simple setup with just a few utterings, and a few stories (a handful of them) that always start with an uttering. Still the bot always starts with action_listen. How do I teach a bot that it has to be the first to utter?

Thanks for your help,

Andrea.

**Comment by Graziella-Husson** [comment]
If you will, I would like to complete the question. Is this possible to start with a custom action? (where we can handle messages, trigger a reminder or something...)?

**Comment by akelad** [comment]
By default no, you can't have the bot send the first message. But dependent on the platform you are deploying this on, you can set it it so that the user presses a button, and only then the conversation starts. so e.g. in facebook you can have a "Get started" button, which sends a predefined intent, and then the bot will reply to that

**Comment by miguelvr** [comment]
this can be "hacked" in multiple ways, sure... but it's clearly a feature that is very common in chatbots, so it doesn't make sense to me not to have it implemented in RASA

**Comment by akelad** [comment]
The thing is that on Facebook and most other platforms the user has to initiate the conversation. This is to avoid things like spambots etc.

**Comment by disimone** [comment]
I understand the use-cases that are being covered now. This does not seem like a good argument for not also covering different use cases :)

At lease, could I ask for some pointers on what would be the best place to implement our own hacks around this?

Thanks for your help,

Andrea.

**Comment by miguelvr** [comment]
@akelad that's still no reason to develop an option to turn such a feature on or off, making it possible to develop in any platform.

**Comment by akelad** [comment]
Sure but there's not really a general solution to this, given that each platform is different in terms of how do you know when to send the message, which user do you send it to etc. 
The easiest solution here would be to e.g. send the `/start` intent (or whatever your initial story starts with) to rasa_core as a message from a specific user
