### ISSUE TITLE
What is the best way to train the rasa bot?

### ISSUE THREAD

**Issue by NikhilBansal21** [RasaHQ/rasa_core#586]
**Rasa Core version**: 0.9.0a3

**Python version**: 3.6.5

**Operating system** (windows, osx, ...):10

**Issue**: I know you guys have given in docs the way to train a bot in rasa. But i am not able to understand it pretty well because of less content. I am using dialogflow agent data for my rasa core bot . It was working fine at first then i updated the bot with new intent's like i added some faq's in my bot. On adding that my welcome intent started misbehaving. The phrases of welcome intent like "Hi" catches an faq intent instead of welcome intent.  I don't want my bot to work in a specific flow. I just want it to act as an intent classifier and for entity extraction.
 I am sending you guys my stories.md snippet hope you can understand. I have just limiting it to welcome and faq intent only for now!

https://gist.github.com/NikhilBansal21/6be660f125b24e5fe5832331a6064543

**Content of domain file** (if used & relevant):
```yaml

```

**Comment by auzair92** [comment]
If you only want intent detection then I believe you don't need the Rasa Core part, only the Rasa NLU will be enough. I think you can use the [`/parse` endpoint](https://nlu.rasa.com/http.html#post-parse-no-emulation) to achieve this. I don't think you'll stories in this case.

**Comment by NikhilBansal21** [comment]
i know nlu can do the same thing which i actually wanted but i am using slots for storing values. I don't want my client to handle storing entity  part

**Comment by akelad** [comment]
if your intent is being misclassified, this is more of an nlu problem no? what classifier are you using?

**Comment by NikhilBansal21** [comment]
@akelad  i am using these pipeline configs for nlu 

"pipeline":  
  - name: "nlp_spacy"
  - name: "tokenizer_spacy"
  - name: "intent_featurizer_spacy"
  - name: "intent_classifier_sklearn"
  - name: "ner_crf"
  - name: "ner_synonyms",

**Comment by akelad** [comment]
I'm not sure how much training data etc you have, but it sounds like you probably have to little, if those intents are getting confused. Also are you using the medium spacy model?
