### ISSUE TITLE
How to use rasa core model in personal website.

### ISSUE THREAD

**Issue by SaiDilipReddyKiralam** [RasaHQ/rasa_core#590]
**Issue**:

I worked with rasa core and developed a working bot model and used slack connector as a front end interface.Now I don't want to use slack to interact with bot. i want to add model in my own website. I did not find any example of adding bot to a personal website.
In simple :  
`from rasa_slack_connector import SlackInput` instead of this I want use rasa_personal_connector to connect with my site.

**Comment by auzair92** [comment]
You can do this very easily using [Rasa HTTP server](https://core.rasa.com/http.html). 

Once your server is up and running according to the instructions given in the page linked above or [this example](https://github.com/RasaHQ/rasa_core/tree/master/examples/remotebot), you can call different endpoints from your front-end to interact with your bot. The `/respond` endpoint of the server will return you the utterances of your bot, or if you want to implement utterances on your front-end you can do that too using `/parse` endpoint.

You may develop the front-end by yourself or find a chatbot template written in JavaScript or Angular. You may follow [this tutorial](https://hackernoon.com/chatbot-with-angular-5-dialogflow-fdac97fef681), and replace the calls to Dialogflow service with a call to your Rasa HTTP server.

**Comment by phidodido** [comment]
I think it would be really beginner-friendly if there was a starter kit with a pre-built front-end that can be run locally.

For example Botkit has a template with a self-contained chat server, API and web-based messaging client.
https://github.com/howdyai/botkit-starter-web

**Comment by Rajskc** [comment]
Hi @auzair92 , I am trying to use rasa as HTTP server. The server is running but I am not able to get back reply from it. The errors are:

![image](https://user-images.githubusercontent.com/33925712/42361314-868db45c-810b-11e8-9ff0-20b3317c1610.png)

When I try with **| python -mjson.tool** code added:
![image](https://user-images.githubusercontent.com/33925712/42361426-0187fd48-810c-11e8-9cf0-a37079ba4409.png)

I have also tried with replacing localhost with ip address of my pc, but didn;t work. Can you help me with the command for the bot to respond? Thanks!

**Comment by Rajskc** [comment]
@SaiDilipReddyKiralam @phidodido  There is a chatroom available https://github.com/scalableminds/chatroom with which you can integrate your bot. If you wanto integrate it with your website....then you can create a chatroom using JS and add to website HTML code and integrate the bot to it. I hope this is clear and helpful to you.
