### ISSUE TITLE
Using FallbackPolicy with agent.load_data() leads to an error

### ISSUE THREAD

**Issue by rusiaaman** [RasaHQ/rasa_core#594]
**Rasa Core version**: 0.10.0a2

**Python version**: 3.6

**Operating system** (windows, osx, ...): Linux Ubuntu 16.04

**Issue**:
File agent.py line 200 in the method load_data() of class Agent:
```     
 if hasattr(policy.featurizer, 'max_history'):
    max_max_history = max(policy.featurizer.max_history,
                                       max_max_history)
```
FallbackPolicy has attribute max_history but it is set to None in fallback.py. This causes error in the max function.

Simple solution:
```
if hasattr(policy.featurizer, 'max_history') and policy.featurizer.max_history!=None:
                max_max_history = max(policy.featurizer.max_history,
                                      max_max_history)
```

**Comment by Ghostvv** [comment]
Could you please try this PR: #591, and check if FallbackPolicy works as expected?

**Comment by rusiaaman** [comment]
#591 fixes the problem in agent.py but one error pops up due to the following line in ensemble.py (line 101):
`if isinstance(p.featurizer, MaxHistoryTrackerFeaturizer):`

Since the FallbackPolicy is missing the featurizer.

**Comment by Ghostvv** [comment]
I added a fix for this problem

**Comment by Ghostvv** [comment]
the PR is merged

**Comment by souvikg10** [comment]
@Ghostvv I tried the #591 , but I still receive this error
```
File "core-api/core-train-online.py", line 62, in <module>
    run_training_online(input_channel=ConsoleInputChannel(), interpreter=interpreter)
  File "core-api/core-train-online.py", line 32, in run_training_online
    training_data = agent.load_data(training_data_file)
  File "/app/rasa_core/rasa_core/agent.py", line 202, in load_data
    max_max_history)
TypeError: '>' not supported between instances of 'int' and 'NoneType'
```

here is my train agent
```
fallback = FallbackPolicy(fallback_action_name="utter_fallback",
                          core_threshold=0.2,
                          nlu_threshold=0.2)
    agent = Agent(domain_file, policies=[
        AugmentedMemoizationPolicy(max_history=6),
        KerasPolicy(),fallback],interpreter=interpreter)
    training_data = agent.load_data(training_data_file)
    agent.train_online(training_data,
                       input_channel=input_channel,
                       model_path=model_path,
                       batch_size=20,
                       epochs=100,
                       validation_split=0.2,
                       max_number_of_trackers=100)
```
I am running the latest GitHub version with the merge and I still receive this error. I feel it is related to the issue above

**Comment by souvikg10** [comment]
though in the commit history of the master branch, I don't see the commits for #591 . Can you please check,,
thanks

**Comment by rusiaaman** [comment]
@souvikg10 The PR #591 is merged with the branch 0.9.x and not with the master branch. Not sure why. I also need it to get merged with the master branch.

**Comment by souvikg10** [comment]
Yeah I noticed. I will try it. Though officially can't use it unless it is in master 😟

**Comment by akelad** [comment]
sorry about that, we're merging that into master as well today

**Comment by Ghostvv** [comment]
merged it to mater
