### ISSUE TITLE
Deterministic action loop in Rasa

### ISSUE THREAD

**Issue by miguelvr** [RasaHQ/rasa_core#597]
**Rasa Core version**: 0.9.0a3
**Python version**: 3.6.4
**Operating system**: Linux Ubuntu 16.04LTS

**Issue**:
I want to achieve a deterministic action loop for a certain intent, until a certain condition is fulfilled.

It would looks something like this:
```
User: "Are you hiring?"
Bot: "Yes we are! Let us know your email and we'll reach you"
User: [Inserts something that's not an email]
Bot: "That's not a valid email, try again"
```

I would like to break out of the loop if the email is correct (I would check it via regex) or if the user inserts an invalid email twice.

Is it possible to do this in a single action? I would like to do so, but I'm not sure how to output text and keep listening to user input from within my custom action class. Otherwise, how would I be able to achieve this?

Best regards,
Miguel

**Comment by amn41** [comment]
You should check out [form actions](http://core.rasa.com/patterns.html#collecting-information-to-complete-a-request-slot-filling)

**Comment by miguelvr** [comment]
@amn41 but those are not deterministic at all

**Comment by tmbo** [comment]
you are right, they are not deterministic, they still need to be predicted. But the checking of filled slots & asking for them is deterministic so as long as the form filling action is predicted.

**Comment by miguelvr** [comment]
@tmbo yes, but I don't want to rely on statistical predictions when I don't need to. If you know what you want to achieve, deterministic is always better than stochastic.

Watson Conversation has this "irrelevant" intent when they enter in a deterministic flow.

I'm currently trying to figure some workaround to this, but RASA should really plan to support this, as doesn't make sense to trust machine learning to predict what you know it should be.

Best,
Miguel

**Comment by Ghostvv** [comment]
@miguelvr did you try `MemoizationPolicy`? It does not rely on ML, and predicts an action, if the story exactly the same as in training.
