### ISSUE TITLE
Fallback Policy threshold is not respected

### ISSUE THREAD

**Issue by souvikg10** [RasaHQ/rasa_core#598]
**Rasa Core version**: 0.9.3

**Python version**: 3.6

**Operating system** (windows, osx, ...):osX

**Issue**:
Fallback policy is not working
```
fallback = FallbackPolicy(fallback_action_name="utter_fallback",
                          core_threshold=0.2,
                          nlu_threshold=0.2)
    agent = Agent(domain_file, policies=[
        AugmentedMemoizationPolicy(max_history=max_history),
        KerasPolicy(),fallback])
    training_data = agent.load_data(training_data_file)

    
    agent.train(training_data,
                       batch_size=20,
                       epochs=200,
                       validation_split=0.2,
                       max_number_of_trackers=100)
```
However when called, I receive intents with confidence less than 20% predicts the next action as defined but not fallback.

Not sure why is that

**Comment by akelad** [comment]
have you added a story with the fallback action?

**Comment by souvikg10** [comment]
Yeah

**Comment by akelad** [comment]
try adding 

```
## fallback
  - utter_fallback
```

**Comment by souvikg10** [comment]
Ok, I will give it a shot 👍

**Comment by souvikg10** [comment]
Is it possible to create a pattern if fallback happens more than once, I change to another action?

**Comment by NikhilBansal21** [comment]
@akelad  do we have to create an intent for fallback and if yes how can we determine training phrases for a fallback????

**Comment by tmbo** [comment]
No you don't need to create an intent for the fallback. You can still do that, but using the FallbackPolicy is another approach: it looks at the confidence scores of the intent & action predictions and if they are to low runs a custom action.

**Comment by NikhilBansal21** [comment]
@tmbo as in dialogflow fallback has its own json response for an out of scope message. I want a json response to handle at my node server end. I am not using actions for replies i am parsing for intent matching and sending replies from my node app . By adding fallback policy i am not getting right response it is catching up wrong intent's

**Comment by Primtek** [comment]
@tmbo could you please share how to use FallbackPolicy?

**Comment by akelad** [comment]
@Primtek have you read the comments in this thread, they have quite a good explanation of how to use it. In addition to that, here is the exact code you have to add to your training script: https://core.rasa.com/patterns.html?highlight=fallback#fallback-default-actions
And make sure to add this story as well:
```
## fallback
  - utter_fallback
```

**Comment by asaiyed10** [comment]
Hey sorry to reopen this. Any help would be very appreciated!! 

How exactly do you train the model with the new fallback policy using the command line? 

I know rasa_core/train.py has a '--fallback_action_name', argument. Would I specify the python script afterwards  for example ; 

python -m rasa_core.train -d domain.yml -s stories.md -o models/dialogue --fallback_action_name fallback.py 

with fallback.py being : 

```
from rasa_core.policies.fallback import FallbackPolicy
from rasa_core.policies.keras_policy import KerasPolicy
from rasa_core.agent import Agent

fallback = FallbackPolicy(fallback_action_name="action_default_fallback",
                          core_threshold=0.3,
                          nlu_threshold=0.3)

agent = Agent("domain.yml", policies=[KerasPolicy(), fallback]) 
```

If not how exactly do I train my model with fallback.py being taken into account using the command line? 

Thanks!!

**Comment by akelad** [comment]
Since the original issue was solved, I'll close it. 
@asaiyed10 please post questions like this in our [forum](https://forum.rasa.com)
You don't need to specify the `--fallback_action_name`, there's a default one that comes with rasa core. There is however nlu_threshold and core_threshold args which you should define
