### ISSUE TITLE
How to remove sender_Id from InMemoryTrackerStore?

### ISSUE THREAD

**Issue by lisongshan** [RasaHQ/rasa_core#617]
**Rasa Core version**:
0.9.4
**Python version**: 
3.6
**Operating system** (windows, osx, ...):
Linux
**Issue**:
Once a sender_id is added to InMemoryTrackerStore, it seems there is no function to remove it.  What is the best way to clear garbage sender_ids? 

I am using rasa_core http server, there is no end point for garbage collecting unneeded sender_ids.

**Content of domain file** (if used & relevant):
```yaml

```

**Comment by LawnboyMax** [comment]
InMemoryTrackerStore is simply a dict. Use `tracker.store.pop(sender_id)` to remove entries from it. See how it's implemented [here](https://github.com/RasaHQ/rasa_core/blob/91c65288b71d0cee15f1d538b43e985df960a683/rasa_core/tracker_store.py#L66).

**Comment by tmbo** [comment]
Yes that is a very good point, not sure how we'd do automatic cleaning of it. But then again, it should really be only used for development so I guess thats fine.
