### ISSUE TITLE
Properly handle if a remote NLU server doesn't respond 

### ISSUE THREAD

**Issue by reza-ebrahimi** [RasaHQ/rasa_core#626]
What happens when we run `rasa_core` without understanding part `rasa_nlu`? I have tested it and see it works.

I was shutting down `rasa_nlu` HTTP server and delete previous generated models, then run `rasa_core`.

or pass `None` to interpreter.

```python
agent = Agent.load("models/dialogue", interpreter=None)
```

**Comment by reza-ebrahimi** [comment]
In this case:
```python
agent = Agent.load("models/dialogue", interpreter=None)
```

It will creates default interpreter:
https://github.com/RasaHQ/rasa_core/blob/master/rasa_core/interpreter.py#L27

```python
    @staticmethod
    def create(obj):
        if isinstance(obj, NaturalLanguageInterpreter):
            return obj
        if isinstance(obj, str):
            return RasaNLUInterpreter(model_directory=obj)
        else:
            return RegexInterpreter()  # default interpreter
```

**Comment by reza-ebrahimi** [comment]
What happens when `rasa_nlu` HTTP server is down and not respond to `rasa_core` requests? `

**Comment by reza-ebrahimi** [comment]
What happens when `rasa_nlu` HTTP server is down and not respond to `rasa_core` requests?

**Comment by tmbo** [comment]
Good question. So it will use
```
{"intent": {"name": "", "confidence": 0.0}, "entities": [], "text": ""}
```
as the result for the parsing of the incoming messages. Hence, things will continue normally, and core will use the ML policy to predict a next action. What this next action is kind of depends on the training data but is unclear (you can not really create a training example for this case).

What would you like it to do?

**Comment by reza-ebrahimi** [comment]
@tmbo I think if `confidence` level is `0.0`, it might does nothing (without injecting policies logic right there) and fall into a default message that tells doesn't understand input message or something else, if we are going to add policies in this case, I think the behavior is defined based on policy logic and could be same as before and fall into fallback policy and tells a default message.

**Comment by reza-ebrahimi** [comment]
@tmbo I think if `confidence` level is `0.0`, it might does nothing (without injecting policies logic right there) and fall into a default message that tells doesn't understand input message or something else, if we are going to add policies in this case, I think the behavior is defined based on policy logic and could be same as before and fall into `Fallback policy` and tells a default message.
