### ISSUE TITLE
[Load balancing] - How many concurrent users a Rasa bot can handle?

### ISSUE THREAD

**Issue by imsurinder90** [RasaHQ/rasa_core#634]
**Query**:
If I deploy Rasa Bot over the production. How many users can talk to the bot at the same time without getting delays in response?

**Comment by sipvoip** [comment]
Think that depends on the type of box or VM your running on.

**Comment by imsurinder90** [comment]
No, that's a different thing.
When 100 users each hitting 80 requests at a time to the bot and I open the bot with UI
then the response returned from the server took 3 minutes.
The CPU usage was just 5%

So, my question is:
Is there any way for reducing response time of bot when 1000's of users are accessing the bot at a time?

**Comment by amanvars** [comment]
So which server is best for deploying Rasa bot (both nlu + core) to make it live.

**Comment by imsurinder90** [comment]
Apache with mod_wsgi would work.
