### ISSUE TITLE
Validate () of FormField

### ISSUE THREAD

**Issue by piyushporwal6795** [RasaHQ/rasa_core#635]
Rasa Core version: 0.9.3

Python version: 3.5 

Operating system: Windows 10

Issue: How to use validate() of FormField ?

**Comment by tannn** [comment]
There is information for validation in the [documentation](https://core.rasa.com/0.9.2/patterns.html#validation-and-free-text-input).

**Comment by piyushporwal6795** [comment]
I am ain't getting it exactly. How we will use?

**Comment by tannn** [comment]
Below is an example implementation if you would like to validate that the user is entering a valid color. Any entry that doesn't match in the if statement would return None.

    from rasa_core.actions.forms import FormAction 

    class CustomFormActionColorValidation(FormAction):
        def validate(self, value):
            if value is not None:
                if value == "red":
                    return value
                elif value == "blue":
                    return value
                elif cluster == "green":
                    return value
                elif cluster == "yellow":
                    return value
                elif cluster == "purple":
                    return value
                elif cluster == "black":
                    return value
                elif cluster == "white":
                    return value
                elif cluster == "magenta":
                   return value
            return None

**Comment by piyushporwal6795** [comment]
Okay thanks, will try and get back to you if I face any issues further

**Comment by Egalite123** [comment]
Pardon for duplicating the same question. I think, this is a better place.
Will it be possible to keep the validate function outside the core unit (within forms.py) and make it part of custom code?
Though this is working, it could lead to a mess. Imagine I am developing multiple bots and have to write all validations in a single unit. Possibly, some unnecessary code could creep into the master!
Thanks for considering.

**Comment by tannn** [comment]
@Egalite123 Yes, in that case you can create the class in the directory you would like to use it, and import it when necessary. There is no requirement for adding files to the core code.
