### ISSUE TITLE
ValueError: X.shape[1] = 387 should be equal to 303, the number of features at training time

### ISSUE THREAD

**Issue by NikhilBansal21** [RasaHQ/rasa_core#636]
**Rasa Core version**:0.9.0a3

**Python version**: 3.6.5

**Operating system** (windows, osx, ...):10

**Issue**: On making the parse request to the http server i am getting this error. My code is hosted on the windows os server. Same bot is working fine on my local system.

**Content of domain file** (if used & relevant):
```yaml

```

**Comment by akelad** [comment]
You're most likely using a different spacy model on the local system/server. Try retraining your model on the server

**Comment by NikhilBansal21** [comment]
@akelad i know this problem gets resolved on training the data again.. But on training the data again my intent's are getting mismatched

**Comment by akelad** [comment]
I assume there's an issue with your training data, or nlu config then. Have you added new intents/entites?

**Comment by NikhilBansal21** [comment]
yes the same training data works well on local system but on training the data on server misbehaves sometimes, specially happens with intent catching an custom regex

**Comment by Ghostvv** [comment]
could it be that you switched to different spacy version?

**Comment by NikhilBansal21** [comment]
@Ghostvv  thanks your suggestion solved my problem :)
