### ISSUE TITLE
Get session data from users 

### ISSUE THREAD

**Issue by ctrado18** [RasaHQ/rasa_core#638]
When you use the facebook conncector or any other webchat with Rasa Core,
how are different users handled?  What if two users use the chatbot at same time. Does Rasa handles those two seperately? I think hast something to do with this sender_id?

**But how do I use Rasa core to extract for every user (distinguished by sender_id?) the messages, intents, etc?**

I want to use my Rasa chatbot via facebook and want to extract this data for testing.

Thank you!

**Comment by souvikg10** [comment]
if you take a look at the documentation,
GET /conversations
List the sender ids of all the running conversations.

this basically looks into the tracker for all the sender ids, then for each of them you can get tracker with

GET /conversations/(str: sender_id)/tracker
Retrieves the current tracker state for the conversation with sender_id. This includes the set slots as well as the latest message and all previous events.

depends on what you are using as a tracker( is it Redis? ) or InMemory? You can create a trigger for redis to pull data out of the tracker if there is an event and save it to your persistent storage. 

You can also add your own tracker store ( RabbitMQ or even Kafka- though one might argue) 

p.s sender id for Facebook is the messenger-id. I think It is linked to the user session in Facebook(not sure)

**Comment by ctrado18** [comment]
Thanks! I get a feeling. But I don't know how to use this (within python or  java script?). How do I use Redis? What exactly is it? There is nothing in the docs about that. Right now I have my bot in python on my local machine. Do I have to do something in python to use those Redis trackers?

Sorry for those naive questions...

But those endpoint calls for the tracker state are nice. That is what I want.

**Comment by souvikg10** [comment]
Redis is a Message Queque where the tracker is stored temporarily for the period of the conversation( you can even configure it). this allows the tracker to be persistent for a user. 
You have a library in python called redis, you can check how Rasa did it. 
You can write a script to extract data from the redis queue or use the API. 
If you are not too familiar with python, use the API. extract data on a a periodic basis. Redis also has API for other languages as well. Just connect to the Redis server  and look at the API, how to retrieve the objects.

**Comment by ctrado18** [comment]
Thanks! I am rather familiar with python. So, this way is ok. Can you show me where Rasa uses Redis?

**Comment by souvikg10** [comment]
A snippet from tracker_store.py
```
class RedisTrackerStore(TrackerStore):

    def keys(self):
        pass

    def __init__(self, domain, host='localhost',
                 port=6379, db=0, password=None):

        import redis
        self.red = redis.StrictRedis(host=host, port=port, db=db,
                                     password=password)
        super(RedisTrackerStore, self).__init__(domain)

    def save(self, tracker, timeout=None):
        serialised_tracker = self.serialise_tracker(tracker)
        self.red.set(tracker.sender_id, serialised_tracker, ex=timeout)

    def retrieve(self, sender_id):
        stored = self.red.get(sender_id)
        if stored is not None:
            return self.deserialise_tracker(sender_id, stored)
        else:
            return None
```

**Comment by krisand** [comment]
The way i understand this is RedisTrackerStore is available by default within RASA. However, we have to implement the Tracker Endpoint? Is that right? Can some one clarify for me please?

**Comment by souvikg10** [comment]
Well there is a tracker endpoint that can be called via Http as mentioned above if you are running rasa core as a server based on the implementation provided by Rasa already.

You have a choice on where you want to store your tracker, could a Redis or InMemory(by default). So when you load your Agent, you have to provide the tracker_store if it is not InMemory. So all you need to do when you load your agent in server.py , you have to provide the tracjer 

Rasa has implementation of Redis and InMemory. You can add your own tracker store as well(implemetation could be in the tracker_store.py( Could be Mongo, Couchbase) keep in mind Rasa is serializing the tracker object ( basically creating pickle file in python and storing it in redis)

There is already a tracker API over http that allows you to read the tracker object at any time and even update it with your custom information asynchronously of the ongoing chat for a user. Really powerful if you want to trigger reminders.

Hope this helps

**Comment by ctrado18** [comment]
@souvikg10 What is actually the sense of server.py when you you use an GUI interface like facebook or any other interface. I don'tnt see that any connector (slack, fb) uses the endpoints from the server.py for getting the parsed message?! I.e where does 
https://github.com/RasaHQ/rasa_core/blob/master/rasa_core/channels/facebook.py

requests the parsed message endpoint?

My custom GUI also doesn't use server.py. So, what do I need to do when I want to Redis Tracker store?

**Comment by souvikg10** [comment]
When you are using a connector pre defined, you are using run.py where you are loading the agent with a particular model, it is there you should pass the tracker_store 

I am not sure how you are using your custom GUI( did you use your own Flask server to run up?) Our GUI is not directly connected to Rasa UI as we have an intermediate gateway with Botkit which runs on node js, we use Rasa for model inference in this case.

**Comment by ctrado18** [comment]
I use:

https://github.com/scalableminds/chatroom/blob/master/rasa_utils/bot_server_channel.py

```
from bot_server_channel import BotServerInputChannel

# Creating the Interpreter and Agent
def load_agent(): ...

# Creating the server
def main_server():
    agent = load_agent()
    channel = BotServerInputChannel(agent)
    agent.handle_channel(channel)

main_server()
```

and it uses flask.

So, it uses InMemory in line 119?

` tracker = self.agent.tracker_store.get_or_create_tracker(cid)`

What I have to change for Redis?

**Comment by ctrado18** [comment]
@souvikg10 So, it seems they don't use the HTTP API for the NLU? I guess I would extract Intents and ENtities like running locally?

**Comment by souvikg10** [comment]
https://github.com/scalableminds/chatroom/blob/master/rasa_utils/bot.py

In this code, they are loading the agent with the models that are stored locally. 
agent = Agent.load(cmdline_args.core, cmdline_args.nlu) (line 59)

You can pass the tracker store there 
Agent.load(model_directory, interpreter,
                          tracker_store=tracker_store,
                         )

**Comment by souvikg10** [comment]
@ctrado18 indeed, it is upto your how you want to use the interpreter. We have separated it since it seems Rasa NLU can also be used without necessarily needing the core and vice versa ( case - When you want rasa NLU to extract entities from tweets let's say or you have a click bot that is simply based on core without needing the NLU)

**Comment by ctrado18** [comment]
So, I guess I just use like  `tracker.latest_message.parse_data["intent"]["name"]` in bot_server_channel.py  to extract the data?

**Comment by e8180kimo** [comment]
> https://github.com/scalableminds/chatroom/blob/master/rasa_utils/bot.py
> 
> In this code, they are loading the agent with the models that are stored locally.
> agent = Agent.load(cmdline_args.core, cmdline_args.nlu) (line 59)
> 
> You can pass the tracker store there
> Agent.load(model_directory, interpreter,
> tracker_store=tracker_store,
> )

Hi @souvikg10 , I encountered a similar issue. But chatroom updated their code. I cannot find the exactly line as you mentioned. I want to use InMemory tracker though. Thanks.
