### ISSUE TITLE
Why Rasa library is auto updating? Is there any way to stop auto updates?

### ISSUE THREAD

**Issue by DhruvMevada** [RasaHQ/rasa_core#639]
**Rasa Core version**:

**Python version**: 

**Operating system** (windows, osx, ...):

**Issue**: When rasa new versions 0.9.0a3 , 0a5, 0a6 releases, Rasa Library is updated automatically. I haven't apply any update command at that time, Then also when rasa new version releases, rasa_core is updated automatically.

Is there any way to stop auto updates?

**Content of domain file** (if used & relevant):
```yaml

```

**Comment by souvikg10** [comment]
How do you install the library? if you are using pip, you can stay on a version with 
```
pip install rasa_core==0.9.6

```
if that helps

**Comment by DhruvMevada** [comment]
@souvikg10 I have installed Rasa library using simple 
``` pip install rasa-core```

**Comment by souvikg10** [comment]
You can try to mention the version, to force it to stay on the version, otherwise it will pull the latest since you haven't tagged your library.

**Comment by DhruvMevada** [comment]
okay I will test it.

**Comment by tmbo** [comment]
`pip install rasa_core` will always install the latest version (won't install alpha releases if I remember correctly). as @souvikg10 suggested, if you need a specific version, specify it as part of the install command `pip install rasa_core==0.9.6`.
