### ISSUE TITLE
how the Policy works? what is use of different policies?

### ISSUE THREAD

**Issue by DhruvMevada** [RasaHQ/rasa_core#644]
**Rasa Core version**:

**Python version**: 

**Operating system** (windows, osx, ...):

**Issue**: 
Is any one knows about policy? how it detects & fire actions based on relevant intents?

There are around 5-6 different policies. when you use them? 

I saw the documentation on http://core.rasa.com/policies.html . But it's not much in details with all the policies. Only 1-2 policies are explored in that. Is there any proper documentations present regarding different policies, it's use and how it is working?

**Content of domain file** (if used & relevant):
```yaml

```

**Comment by tmbo** [comment]
We are currently improving the documentation, does this a better job at explaining it, or is there something you are missing? http://newdocs.rasa.com/core/policies.html#id1

**Comment by MinhMinnie** [comment]
@tmbo this link doesn’t work
