### ISSUE TITLE
Slot Type for Time

### ISSUE THREAD

**Issue by andreamtang** [RasaHQ/rasa_core#647]
**Rasa Core version**: 0.9.6

**Python version**: 3.6.5

**Operating system** (windows, osx, ...): OSX

**Issue**:

I want my chatbot to be able to store a user's target bedtime as a slot so that it can send the user a reminder an hour before this time. Is there an available/predefined slot class used for time? Or will I have to create my own?

**Comment by disimone** [comment]
For my understanding: what would be the advantage of a specific slot type wrt to, say, a text slot? You can always convert the text to time in your action. Actually, if you use duckling in your pipeline for advanced time parsing, I think the entities you get back are string objects.

**Comment by amn41** [comment]
It really depends on what you want to do with the information. For example, you could have a slot which behaves differently for weekdays vs weekends, or the future versus the past. In those cases you'd create your own subclass of the `CategoricalSlot` with custom logic to define the features

**Comment by andreamtang** [comment]
I was able to use ner_duckling in my pipeline and the bedtime slots are filled appropriately. However, my chatbot's reminders are presented in this way:
`Don't forget: bedtime tonight is 2018-06-27T00:30:00.000Z!`
Is there some way that I could format it so that the message is not in 24hr clock and simply:
`Don't forget: bedtime tonight is 12:30!`

**Comment by Ghostvv** [comment]
call `parser.parse("...")` on your `string` to convert it to `datetime` format then you can convert it to anything you like. For example:
```
from dateutil import parser
time = parser.parse("2018-06-27T00:30:00.000Z")
time = time.replace(hour=12)
print(time.strftime('%H:%M'))
```

**Comment by andreamtang** [comment]
Where in my code should I be converting the string? Should I do this in the FormAction so that the slot is filled with the correct format? (I'm not completely clear on what goes on under the hood with Rasa Core)

**Comment by Ghostvv** [comment]
I'd say, in your custom action, which creates the utterance, you posted above:
`Don't forget: bedtime tonight is 2018-06-27T00:30:00.000Z!`

**Comment by akelad** [comment]
@andreamtang do you have any more questions? can we close this issue?

**Comment by andreamtang** [comment]
I might have more in the future, but I'll close it for now
