### ISSUE TITLE
FormAction class submit() function

### ISSUE THREAD

**Issue by andreamtang** [RasaHQ/rasa_core#648]
**Rasa Core version**: 0.9.6

**Python version**: 3.6.5

**Operating system** (windows, osx, ...): osx

**Issue**:

I am trying to use the `FormAction` class to fill all my required slots and, after looking through the "Slot Filling and Common Patterns" tutorial on the rasa core website, I am confused as to how to alter the `submit()` function (my chatbot isn't required to make any API calls) as well as what this function even does. Any guidance is appreciated!

This is what my `bot.py` file looks like so far:

```
from rasa_core.actions import Action
from rasa_core.actions.forms import FormAction
from rasa_core.actions.forms import EntityFormField, BooleanFormField
from rasa_core.events import SlotSet

class ActionSetup(FormAction):

    RANDOMIZE = False

    @staticmethod
    def required_fields():
        return [
            EntityFormField("name", "name"),
            EntityFormField("time", "goal_bedtime"),
            EntityFormField("time", "avg_bedtime"),
            EntityFormField("timezone", "timezone")
        ]

    def name(self):
        return 'action_setup'

    def submit(self, dispatcher, tracker, domain):
        results = RestaurantAPI().search(
            tracker.get_slot("name"),
            tracker.get_slot("goal_bedtime"),
            tracker.get_slot("avg_bedtime"),
            tracker.get_slot("timezone"))
        return [SlotSet("search_results", results)]
```

**Content of domain file** (if used & relevant):
```yaml

```

**Comment by HCIS2020** [comment]
in submit function, you just return []  for doing nothing.

**Comment by andreamtang** [comment]
if i leave it as `return[]` will my slots be updated?

**Comment by akelad** [comment]
Yes, if they have the same names as your entities, then they'll be updated automatically as the conversation goes

**Comment by Primtek** [comment]
@andreamtang  could you please share your codes here? .. 
I m new with this and now I m in the progress to learn how to implement FormAction.. 
many thanks

**Comment by andreamtang** [comment]
For FormAction, in the `domain.yml` file, you need to add the following under `slots:`
  ```
requested_slot:
    type: unfeaturized
```

and add the following under `actions:`
`- actions.[NameOfYourAction]`

And here is an example of a story in the `stories.md` file:
```
## Generated Story 2629288407567792433
* greet
    - utter_greet_introduction
    - action_setup
    - slot{"requested_slot": "PERSON"}
* inform{"PERSON": "Nicolas"}
    - slot{"PERSON": "Nicolas"}
    - utter_ack_PERSON
    - action_setup
    - slot{"requested_slot": "goal_bedtime"}
* inform{"time": "2018-07-01T00:00:00.000Z"}
    - utter_ack_general
    - action_setup
    - slot{"goal_bedtime": "2018-07-01T00:00:00.000Z"}
    - slot{"requested_slot": "avg_bedtime"}
* inform{"time": "2018-07-01T04:00:00.000Z"}
    - utter_last_question
    - action_setup
    - slot{"avg_bedtime": "2018-07-01T04:00:00.000Z"}
    - slot{"requested_slot": "timezone"}
* inform{"timezone": "pacific daylight time"}
    - slot{"timezone": "pacific daylight time"}
    - utter_ack_first_weekly_goal
```

**Comment by tarunbhavnani** [comment]
@akelad all the examples on the net refer to the restaurantAPI which is stated in the restaurant example in the documentation.
It is not clear how to use the form action or the FreeTextFormField.
Is it working?
