### ISSUE TITLE
A/B testing

### ISSUE THREAD

**Issue by phidodido** [RasaHQ/rasa_core#652]
For example I want to compare the effectiveness between two onboarding flows. In flow A I ask the name and age for user registration. In flow B I just collect the name. Then I want to compare the conversion rate.

With a normal chatbot framework I just randomly give 50% of users flow A and 50% of the users flow B.

How can such A/B testing be implemented with Rasa?

**Comment by souvikg10** [comment]
You can version your models , upon training provide the target folder with a version and upon serve use the model in that version so you can run up two instances. I don't how else would you split the same in a model. Eventually rasa core is building a generalized model that you can't really split based on stories. instead train two different one and on run define which one to use. A bit similar to Rasa nlu

**Comment by phidodido** [comment]
I can see how that could be a solution but it just gets a bit unwieldy if I want to run multiple A/B tests at the same time.

A/B testing is critical if I want to build a bot in a data-driven way. This really stops me from using Rasa at the moment.
