### ISSUE TITLE
Button vise invoking custom action

### ISSUE THREAD

**Issue by DhruvMevada** [RasaHQ/rasa_core#659]
**Rasa Core version**:

**Python version**: 

**Operating system** (windows, osx, ...):

**Issue**:  We are defining Buttons with payload in templates in domain.yml file, I want to know how Can I invoke specific custom actions when any specific button clicked by user/ the value of button in custom actions.

**Content of domain file** (if used & relevant):
```yaml

```

**Comment by disimone** [comment]
Hi,

you can associate special intents/entities to the payload, then write stories around them. See #583

**Comment by DhruvMevada** [comment]
Ya that option is there, but for that I need to create intent for each button. Is there any option is available so that we can directly call the custom actions when button is pressed.
