### ISSUE TITLE
Port rasa core examples to SDK code

### ISSUE THREAD

**Issue by tmbo** [RasaHQ/rasa_core#660]
Make sure all examples that are part of rasa core work with the sdk code. 

Please also update the documentation of the examples to reflect any changes.

- [x] moodbot
- [x] restaurantbot
- [x] concertbot (needs actions endpoint)
- [x] remotebot
- [x] interactive learning examples

List of doc changes:
 - [ ] connectors (still a WIP)
 - [x] custom actions - this might be a good place to mention how to run the actions server
 - [x] interactive learning
 - [x] domains - custom actions section
 - [x] agent (outdated functions)
 - [ ] migration guide

**Comment by akelad** [comment]
TODO: get the train_online script working with the SDK (waiting on @tmbo to finish implementing that part)

**Comment by akelad** [comment]
List of doc changes to be made:

- [ ] connectors (may need to write a new function for that that only starts the input channel)
- [ ] custom actions - this might be a good place to mention how to run the actions server
- [ ] interactive learning - blocked, still needs to be implemented
- [ ] domains - custom actions section
- [ ] agent (outdated functions)

**Comment by amn41** [comment]
@akelad will this include a migration guide as well?

**Comment by akelad** [comment]
It does not yet, but I guess I can add that to the migrations docs file right?

**Comment by amn41** [comment]
yeah what we learned from last major release is that we need to make an active effort to make migration steps prominent and not just hide them in the changelog

**Comment by akelad** [comment]
cool, added to the list up there!
