### ISSUE TITLE
Non existent slot

### ISSUE THREAD

**Issue by andreamtang** [RasaHQ/rasa_core#666]
**Rasa Core version**: 0.9.6

**Python version**: 3.6.5

**Operating system** (windows, osx, ...): OSX

**Issue**:
I keep getting the following error when I try to train my dialogue model:
`ERROR   rasa_core.trackers  - Tried to set non existent slot 'search_results'. Make sure you added all your slots to your domain file.`
However, I don't have a slot called `search_results` anywhere in my training data.

**Content of domain file** (if used & relevant):
```yaml

```

**Comment by akelad** [comment]
Can you post the content of your stories/domain file please?

**Comment by andreamtang** [comment]
Sorry I figured it out, just forgot to close this

**Comment by nitinsaivishnu** [comment]
How did you solve this? @andreamtang

**Comment by ctrado18** [comment]
I have same issue. I have not anywhere the requested slot in my data or domain file and get in debug mode (right after typing in the message!):

`ERROR:rasa_core.trackers:Tried to set non existent slot 'XY'. Make sure you added all your slots to your domain file.`
