### ISSUE TITLE
How to make stories and domain file dynamic

### ISSUE THREAD

**Issue by Ujjwalsas9** [RasaHQ/rasa_core#667]
**Rasa Core version**: 0.9.0a3

**Python version**: 

**Operating system** (windows, osx, ...):

**Issue**:
My conversation is changing everyday. So, to accommodate it, I keep changing the stories and domain.yml file everyday. So is it possible to make it easier or dynamic. 
Thanks!

**Content of domain file** (if used & relevant):
```yaml

```

**Comment by shatacheruvu** [comment]
What do you exactly mean?
Do you mean:
1. You have new intents coming up?
2. You have new actions for the same intents?
