### ISSUE TITLE
Irrelevant Form Action executes based on the Intent even story action is different.

### ISSUE THREAD

**Issue by saivisal1** [RasaHQ/rasa_core#672]
**Rasa Core version**: 0.9.6

**Python version**: 3.7

**Operating system** (windows, osx, ...): OSX

**Issue**:

Hi,
I have 2 FormActions. Action1 had 1 required slot and Action2 has 1 required slot.

utter_ask_field1 is for Action1 and utter_ask_field2 is for Action2.

I want to take the complete text typed by the user to store in the slots. So i have 2 more actions ActionGet1 and ActionGet2 which will fill the slot with last message by the user.

In stories I have 

```

## Story 1
* intent1
    - action_myaction1
    - slot{"requested_slot": "utter_ask_field1"}
* intent1
    - action_get_field1
    - slot{"field1": "Value1"}
    - action_myaction1

## Story 2
* intent2
    - action_myaction2
    - slot{"requested_slot": "utter_ask_field2"}
* intent2
    - action_get_field2
    - slot{"field2": "Value2"}
    - action_myaction2

## Story 3
* intent1
    - action_myaction1
    - slot{"requested_slot": "utter_ask_field1"}
* intent2
    - action_get_field1
    - slot{"field1": "Value1"}
    - action_myaction1


```
In the last story 3 I have written that the text sent by the user may have intent2 but I need to ignore the intend and take the complete text by using the action action_get_field1.

**ISSUE:** If the intent given by the NLU if it is intent1 then it works fine. But if the intent for the user text is intent2 then next action will be 

> slot{"requested_slot": "utter_ask_field2"}  

I guess this is because the user text intent was intent2 and in FormAction the required field if field2. Thus  utter_ask_field2 was executed. But actual requirement was to execute action_get_field1. 

How can I implement this? Is this a bug?

**Comment by amn41** [comment]
What is the type of your required slot? you you using a `FreeTextFormField` ?

**Comment by saivisal1** [comment]
I used the `FreeTextFormField` in my custom action. In my online training Form field is requested but the response text is not populated in to the slot.

```
class ActionWeatherCheck(FormAction):
    def name(self):
        return 'action_weather'
	
    @staticmethod
    def required_fields():
        return [
            FreeTextFormField("city")
        ]	
    
    def submit(self, dispatcher, tracker, domain):
        try:
            city= tracker.get_slot('city')

```

My train online worked like this:

```
Bot loaded. Type a message and press enter: 
what is the weather?
/usr/local/lib/python3.6/site-packages/sklearn/preprocessing/label.py:151: DeprecationWarning: The truth value of an empty array is ambiguous. Returning False, but in future this will result in an error. Use `array.size > 0` to check that an array is not empty.
  if diff:
------
Chat history:

	bot did:	None

	bot did:	action_listen

	user said:	what is the weather?

		 whose intent is:	weather_check

we currently have slots: city: None, fuel: None, location: None, requested_slot: None, search_keyword: None

------
The bot wants to [action_weather] due to the intent. Is this correct?

	1.	Yes
	2.	No, intent is right but the action is wrong
	3.	The intent is wrong
	0.	Export current conversations as stories and quit
1
May I know which city you want's to know?
------
Chat history:

	bot did:	None

	bot did:	action_listen

	user did:	weather_check

	bot did:	action_weather

we currently have slots: city: None, fuel: None, location: None, requested_slot: city, search_keyword: None

------
The bot wants to [action_listen]. Is this correct?

	1.	Yes.
	2.	No, the action is wrong.
	0.	Export current conversations as stories and quit
1
Next user input:
Bangalore
/usr/local/lib/python3.6/site-packages/sklearn/preprocessing/label.py:151: DeprecationWarning: The truth value of an empty array is ambiguous. Returning False, but in future this will result in an error. Use `array.size > 0` to check that an array is not empty.
  if diff:
------
Chat history:

	bot did:	action_listen

	user did:	weather_check

	bot did:	action_weather

	bot did:	action_listen

	user said:	Bangalore

		 whose intent is:	deny

we currently have slots: city: None, fuel: None, location: None, requested_slot: city, search_keyword: None

------
The bot wants to [utter_default] due to the intent. Is this correct?

	1.	Yes
	2.	No, intent is right but the action is wrong
	3.	The intent is wrong
	0.	Export current conversations as stories and quit
```

Is there any error in my code?

**Comment by amn41** [comment]
from what I can see, the problem is that Rasa NLU is classifying 'Bangalore' as a `deny` intent, which is probably not what you have in your stories. I would recommend that you try and fix the NLU model, then this should work

**Comment by saivisal1** [comment]
@amn41 
I have my Story written as:

```
## Test Story
* weather_check
    - action_weather
```

and my NLU JSON data for deny intent is 

```
     {
        "text": "no",
        "intent": "deny",
        "entities": []
      },
      {
        "text": "i can't",
        "intent": "deny",
        "entities": []
      },
      {
        "text": "not correct",
        "intent": "deny",
        "entities": []
      },
      {
        "text": "reject",
        "intent": "deny",
        "entities": []
      },
      {
        "text": "not at all",
        "intent": "deny",
        "entities": []
      },
      {
        "text": "something else",
        "intent": "deny",
        "entities": []
      },
      {
        "text": "its is not that",
        "intent": "deny",
        "entities": []
      },
      {
        "text": "no i want a different city",
        "intent": "deny",
        "entities": []
      },
```

I also have a Fallback policy for 0.3

I guess if NLU gives a different intent also `FreeTextFormField` should store the latest message completely into the slot.

**Comment by saivisal1** [comment]
@amn41 Could you please help me in resolving this?

**Comment by amn41** [comment]
```
This should not happen right? When FreeTextFormField for a requested slot is fired then the next user input should be stored in to the slot irrespective of the intent.
```

This is not how it currently works. We may change this in the future but right now NLU still needs to predict the right intent (or core needs to see stories with different intents so that it knows to always call the `FormAction`)

**Comment by saivisal1** [comment]
@amn41 

Thanks for the reply. :) 

So what i did is I had 2 intents which was weather `weather_check` and `price_check` changed to intent `inform` .  Also i have added some city name in NLU to identify city names as intent `inform`.  As I have two different actions ie **ActionWeather** and **ActionPriceCheck** I need to change the flow based on the the user text ie weather or price.

So I created one more slot to identify the context and the intent is:

```
context:
        type: text
```

If the context is weather then **ActionWeather** should be executed and if context is price then **ActionPriceCheck** should be executed. 

Story:

```
## Generated Story 3148366572886787618
* inform{"context": "weather"}
    - slot{"context": "weather"}
    - action_weather
    - slot{"requested_slot": "city"}
* inform
    - action_weather
    - slot{"city": "bangalore"}
    - slot{"requested_slot": null}
    - export

## Generated Story 6736847337211843710
* inform{"context": "price"}
    - slot{"context": "price"}
    - price_api
    - slot{"requested_slot": "city"}
* inform
    - price_api
    - slot{"city": "bangalore"}
    - slot{"requested_slot": "fuel"}
* inform{"fuel": "petrol"}
    - slot{"fuel": "petrol"}
    - price_api
    - slot{"fuel": "petrol"}
    - slot{"requested_slot": null}
    - export

```
But issue is that Rasa Core wont check the slot value of my slot `context` and execute the action. Now what happens is that the actions  **ActionWeather**  and **ActionPriceCheck** executes randomly. 


O/p


> Using TensorFlow backend.
> Bot loaded. Type a message and press enter: 
> **what is the weather in bangalore**
> Can you specify whether you want to know the petrol price or diesel price?
> **petrol**
> Okay, The current petrol price in Bengaluru is INR 77.12
> **what is the weather in bangalore**
> The weather forecast in Bengaluru seems to be broken clouds as of now and the temperature shows 26°C. The humidity is around 65% and the wind speed is currently 6.7Kmph.
> **what is the diesel price**
> The weather forecast in Bengaluru seems to be broken clouds as of now and the temperature shows 26°C. The humidity is around 65% and the wind speed is currently 6.7Kmph.
> **what is the weather in chennai**
> The weather forecast in Chennai seems to be broken clouds as of now and the temperature shows 34°C. The humidity is around 49% and the wind speed is currently 6.2Kmph.
