### ISSUE TITLE
Action confidence check

### ISSUE THREAD

**Issue by arachny** [RasaHQ/rasa_core#677]
**Rasa Core version**: 0.9.6

**Python version**: 3.6.1

**Operating system** (windows, osx, ...): Ubuntu 18.04

**Issue**:

Is there a way to check the confidence of an action (i.e. within the python action class) and then using some logic decide how to respond, or even give options to "execute" a user defined action?

For example if the action's confidence is low then the system would trigger the default action (i.e. when confidence is below a threshold) and in that default action method's body I want to see what the top 3 actions are (based on their confidence) and then ask the user which one to execute.

Is that possible?

**Comment by amn41** [comment]
this is possible with a `FallbackPolicy`  http://core.rasa.com/patterns.html#fallback-default-actions

**Comment by arachny** [comment]
Probably I was not very clear... I have done that part and the fallback actions kicks in and I can capture that and send a message. But how would I check from the fallback action what were the confidence levels of the top 3 candidate actions?

**Comment by Ghostvv** [comment]
Is your issue related to https://github.com/RasaHQ/rasa_core/issues/656?

**Comment by arachny** [comment]
yes, I did read that, but was not sure how to actually implement what you suggest. I looked into the code for the given objects in the run method (dispatcher, tracker, domain) and could not find any methods or properties containing the actions and confidence levels

**Comment by Ghostvv** [comment]
I added the description of the methods you would need to customize. Is it helpful?

**Comment by arachny** [comment]
I can understand the functionality and how I would even override this if I was to customise it. But I still cannot see how to actually call this function (probabilities_using_best_policy) from within the action method. For example if I try something like:

`
class UtterDefault(Action):
    def name(self):
        return 'utter_default'

    def run(self, dispatcher, tracker, domain):
        utters = ["Sorry, I could not get that. Please rephrase."]
        dispatcher.utter_message(random.choice(utters))
        logger.info("*** Probs: " + str(SimplePolicyEnsemble.probabilities_using_best_policy(tracker, domain)))
        return []
`
it would not work obviously... as I get: "TypeError: unbound method probabilities_using_best_policy() must be called with SimplePolicyEnsemble instance as first argument (got DialogueStateTracker instance instead)"

**Comment by Ghostvv** [comment]
from within the action, I'm not sure, but you can add this logger directly to `probabilities_using_best_policy` method

**Comment by arachny** [comment]
Thanks Vladimir... very useful. It would have been so much more flexible if that was possible, but I can work around with your suggestion.

So to add this would it look something like that?
```
fallback = FallbackPolicy(fallback_action_name="utter_default", core_threshold=0.2, nlu_threshold=0.2)
ensemble = MyPolicyEnsemble([])
agent = Agent(domain_file, policies=[MemoizationPolicy(max_history=4), DirectoryPolicy(), fallback, ensemble])
```
Trying to figure out how to change the default policy.

**Comment by Ghostvv** [comment]
@arachny I think it should be:
```
fallback = FallbackPolicy(fallback_action_name="utter_default", core_threshold=0.2, nlu_threshold=0.2)
policies=[MemoizationPolicy(max_history=4), DirectoryPolicy(), fallback]
ensemble = MyPolicyEnsemble(policies)
agent = Agent(domain_file, policies=ensemble)
```

**Comment by arachny** [comment]
It looks like is working... although the logger does not print anything out yet. Will need to investigate a bit more.

**Comment by Ghostvv** [comment]
@arachny if you want, you can put here your custom ensemble and I'll try to see why logger doesn't work

**Comment by arachny** [comment]
Sorry for the slow reply... it worked in the end, I just had to retrain the model!
Thanks again for your help.

**Comment by Ghostvv** [comment]
@arachny cool! I'll close the issue, feel free to open it, if you need

**Comment by Nomiluks** [comment]
Hi, 

How can I use "MyPolicyEnsemble" ?
should we need import it like "from rasa_core.policies.ensemble import MyPolicyEnsemble" ?

**Comment by Ghostvv** [comment]
@Nomiluks `MyPolicyEnsemble` is a custom ensemble created by @arachny, and not a part of `rasa_core`

**Comment by saqibahmed515** [comment]
@Ghostvv My custom ensemble works fine with `MemoziationPolicy` but when I add `KerasPolicy`, it starts to throw an exception. I know I didn't train a keras model, but I don't know how to pass a trained model to `Agent` constructor because it only takes domain file. I'm missing some basic concept here. I'm initializing my ensemble like below:
```
    policies = [MemoizationPolicy(max_history=4), KerasPolicy()]
    ensemble = CustomEnsemble(policies)
    agent = Agent('domain.yml', policies=ensemble, interpreter=RasaNLUInterpreter("./data/nlu/default/model_20180713-210440"))
```

Without `KerasPolicy`, it doesn't throw any exceptions, but gives no response either (I'm using `handle_message` to test). With `KerasPolicy`, I get following exception:

```
[2018-07-16 13:02:43,882] ERROR in app: Exception on /respond [GET]
Traceback (most recent call last):
  File "/usr/local/lib/python3.6/site-packages/Flask-1.0.2-py3.6.egg/flask/app.py", line 1813, in full_dispatch_request
    rv = self.dispatch_request()
  File "/usr/local/lib/python3.6/site-packages/Flask-1.0.2-py3.6.egg/flask/app.py", line 1799, in dispatch_request
    return self.view_functions[rule.endpoint](**req.view_args)
  File "/usr/local/lib/python3.6/site-packages/flask_restful/__init__.py", line 480, in wrapper
    resp = resource(*args, **kwargs)
  File "/usr/local/lib/python3.6/site-packages/Flask-1.0.2-py3.6.egg/flask/views.py", line 88, in view
    return self.dispatch_request(*args, **kwargs)
  File "/usr/local/lib/python3.6/site-packages/flask_restful/__init__.py", line 595, in dispatch_request
    resp = meth(*args, **kwargs)
  File "/Users/saqib/chatbot/test/nlu_agent.py", line 50, in get
    responses = agent.handle_message(request.args.get('q'))
  File "/usr/local/lib/python3.6/site-packages/rasa_core-0.10.0a3-py3.6.egg/rasa_core/agent.py", line 117, in handle_message
    UserMessage(text_message, output_channel, sender_id))
  File "/usr/local/lib/python3.6/site-packages/rasa_core-0.10.0a3-py3.6.egg/rasa_core/processor.py", line 92, in handle_message
    self._predict_and_execute_next_action(message, tracker)
  File "/usr/local/lib/python3.6/site-packages/rasa_core-0.10.0a3-py3.6.egg/rasa_core/processor.py", line 266, in _predict_and_execute_next_action
    action = self._get_next_action(tracker)
  File "/usr/local/lib/python3.6/site-packages/rasa_core-0.10.0a3-py3.6.egg/rasa_core/processor.py", line 412, in _get_next_action
    idx = self.policy_ensemble.predict_next_action(tracker, self.domain)
  File "/Users/saqib/chatbot/test/nlu_agent.py", line 42, in predict_next_action
    probabilities = self.probabilities_using_best_policy(tracker, domain)
  File "/Users/saqib/chatbot/test/nlu_agent.py", line 28, in probabilities_using_best_policy
    probabilities = p.predict_action_probabilities(tracker, domain)
  File "/usr/local/lib/python3.6/site-packages/rasa_core-0.10.0a3-py3.6.egg/rasa_core/policies/keras_policy.py", line 195, in predict_action_probabilities
    X = self.featurizer.create_X([tracker], domain)
  File "/usr/local/lib/python3.6/site-packages/rasa_core-0.10.0a3-py3.6.egg/rasa_core/featurizers.py", line 424, in create_X
    X, _ = self._featurize_states(trackers_as_states)
  File "/usr/local/lib/python3.6/site-packages/rasa_core-0.10.0a3-py3.6.egg/rasa_core/featurizers.py", line 346, in _featurize_states
    for state in tracker_states]
  File "/usr/local/lib/python3.6/site-packages/rasa_core-0.10.0a3-py3.6.egg/rasa_core/featurizers.py", line 346, in <listcomp>
    for state in tracker_states]
  File "/usr/local/lib/python3.6/site-packages/rasa_core-0.10.0a3-py3.6.egg/rasa_core/featurizers.py", line 116, in encode
    raise Exception("BinarySingleStateFeaturizer "
Exception: BinarySingleStateFeaturizer was not prepared before encoding.
```

**Comment by lgrinberg** [comment]
I'm trying to follow the instruction above to use a custom ensemble and pass it to the agent using a
class Custom_Ensemble(PolicyEnsemble) and then passing it to the agent as indicated above:
       policies=[MemoizationPolicy(max_history=3), KerasPolicy(), fallback]
        ensemble=Custom_Ensemble(policies)
        agent = Agent(domain_file,
                      policies=ensemble,
                      interpreter=interpreter)

But then I get an error:
 File "C:\Users\lgrin\Anaconda3\lib\site-packages\rasa_core\agent.py", line 426, in _create_ensemble
    "policies, or a policy ensemble".format(passed_type))
ValueError: Invalid param `policies`. Passed object is of type 'Custom_Ensemble', but should be policy, an array of policies, or a policy ensemble

Looking at agent.py, I see this:
 def _create_ensemble(policies):
        # type: (Union[List[Policy], PolicyEnsemble, None]) -> PolicyEnsemble
        if policies is None:
            return SimplePolicyEnsemble([])
        if isinstance(policies, list):
            return SimplePolicyEnsemble(policies)
        elif isinstance(policies, PolicyEnsemble):
            return policies
        else:
            passed_type = type(policies).__name__
            raise ValueError(
                    "Invalid param `policies`. Passed object is "
                    "of type '{}', but should be policy, an array of "
                    "policies, or a policy ensemble".format(passed_type))

How will a custom ensemble pass this?  Shouldn't the validation include another step for  
   elif issubclass (policies, PolicyEnsemble):
     return policies

For the subclass to pass.  Should I add this option to the agent.py to make it work?

**Comment by Ghostvv** [comment]
It looks like your `Custom_Ensemble` is not a subclass of `PolicyEnsemble`.

this line checks if your passed ensemble is a subclass: https://github.com/RasaHQ/rasa_core/blob/ce0defcb520a5a6909ca2d8b2241c2e37d5a67d3/rasa_core/agent.py#L422
