### ISSUE TITLE
Is there a way to track number of conversations (not number of dialogues received) with Rasa Core ?.

### ISSUE THREAD

**Issue by geojolly12** [RasaHQ/rasa_core#681]
**Rasa Core version**: 0.9

**Python version**: 2.7

**Operating system** (windows, osx, ...): Ubunute

**Issue**:

**Content of domain file** (if used & relevant):
```yaml

```

**Comment by foxjr** [comment]
The tracker_store keeps track of the sender IDs, which can be returned by its `keys()` function. You could try `len(tracker_store.keys())` to get just the number of conversations, but that's really just returning the number of unique keys.

**Comment by geojolly12** [comment]
@foxjr  but this method will give the number of unique sender IDS which I already have. Each user may have multiple conversations with the agent at different times. i would like to get the number of unique conversations, not just number of unique senderIDs

**Comment by foxjr** [comment]
Yeah, true. It depends on your use case, but the simplest way may be to create a small custom action that occurs only at the start of every interaction that increments a counter (or counts by some other mechanism).

**Comment by geojolly12** [comment]
@foxjr  I am using something similar as you suggested right now, but I need a more solid method 🏭

**Comment by foxjr** [comment]
Maybe create your own tracker class that counts by some mechanism, both when initialized and when reset.
