### ISSUE TITLE
Https webhook for facebook.

### ISSUE THREAD

**Issue by saivisal1** [RasaHQ/rasa_core#683]
**Rasa Core version**: 0.9.6

**Python version**: 3.6.5

**Operating system** (windows, osx, ...): osx

**Issue**:  
Hi,

I have created a facebook webhook from my localhost which is port forwarded to a public ip address. I need to add the webhook to facebook application but the connection is not secure. I have generated ssl certificate using openssl. 

How can I make the webhooks for facebook a https secure connection?

```from rasa_core.channels import HttpInputChannel
from rasa_core.channels.facebook import FacebookInput
from rasa_core.agent import Agent
from rasa_core.interpreter import RegexInterpreter

# load your trained agent
agent = Agent.load("./models/dialogue", interpreter=RegexInterpreter())

input_channel = FacebookInput(
   fb_verify="rasa-bot",  # you need tell facebook this token, to confirm your URL
   fb_secret="33423a03caaeb3cc1403ea623a2566",  # your app secret
   fb_access_token="EAAcQmbfNZBz208eNDOCeahergiHYDW6L5CZCqNs4IilKXaqWesjeYqNeyjCqNR9UyZCLX5ZA5CdDeojawRn6ksfG5orK71baITdKVYaStWjGyygeuEjgRHHfrKtrS36ZCJuYIZCk3IBZAhjUOUt3rq4KFFv3ooRDNMDZBW9t8J08HBSAZDZD"   # token for the page you subscribed to
)

agent.handle_channel(HttpInputChannel(5004, "/app", input_channel))

**Comment by amn41** [comment]
the best way to do this on your machine is to use [ngrok](https://ngrok.com/) . 
If you are setting this up on a server, I'd recommend getting your certificates from letsencrypt and using nginx to proxy to your rasa server

**Comment by saivisal1** [comment]
@amn41 
I want to setup a server and I have .cer file and .key file from service provider for the domain. How can I add the certificates to WSGIServer. 

Or can you please tell me how can I setup proxy to rasa server using nginx?

**Comment by amn41** [comment]
here's an example nginx config:

NB you will need SSL certificates from a trusted authority, Facebook will not accept connections if your SSL cert is self-signed. Hence why I recommend lensencrypt. 

```
server {
  listen 443 ssl;
  server_name  myhost.example.com;

  index index.html index.htm;

  ssl_certificate        /path/to/fullchain.pem;
  ssl_certificate_key   /path/to/privkey.pem;

  ssl_protocols TLSv1 TLSv1.1 TLSv1.2;
  ssl_prefer_server_ciphers on;
  ssl_ciphers 'EECDH+AESGCM:EDH+AESGCM:AES256+EECDH:AES256+EDH';


  location / {
    proxy_pass http://localhost:5000/;  # <-- port where Rasa is running
    proxy_set_header  X-Real-IP  $remote_addr;
    proxy_buffering    off;
    proxy_set_header Host $http_host;
    proxy_set_header X-Forwarded-For $proxy_add_x_forwarded_for;
    proxy_set_header X-Forwarded-Proto http;
  }
}
```

**Comment by saivisal1** [comment]
In my chatbot I have both slack and facebook connectors. Both are running in 2 different port. Can I run both of them in same port?
