### ISSUE TITLE
newbie need an example to start 

### ISSUE THREAD

**Issue by Primtek** [RasaHQ/rasa_core#690]
**Rasa Core version**:
0.9.7
**Python version**: 
2.7.3
**Operating system** (windows, osx, ...):
centOS 7
**Issue**:
Hi All,
I am new with this, and I am in the progress learning RASA, I am looking for an example for interactive bot, like as follow:

bot: hi.. my name is bot, what is your name?
user: john
bot: your date of birth?
user: 21-12-1980  
bot: gender?
user: male
bot: country?
user: singapore
bot: thank you
bot: this is your data:
bot: name: john
bot: DOB: 21-12-1980
bot: Gender: male
bot: Country: Singapore
bot: is it correct? Y/N
user: Y
bot: Thank you, have a great day!

could anybody here, can point me where can I find such example?

thanks a lot in advance
Regards
Win

**Content of domain file** (if used & relevant):
```yaml

```

**Comment by saivisal1** [comment]
Hi @Primtek 

Use any of the example from  [https://github.com/RasaHQ/rasa_core/tree/master/examples ](url) 
and modify it.

You can also have a look on to this video 
[https://vimeo.com/254777331](url) and demo code is in git
[https://github.com/JustinaPetr/Weatherbot_Tutorial](url)

> Happy Learning

**Comment by akelad** [comment]
@Primtek does that solve your issue or do you need more help?
