### ISSUE TITLE
Bool slot only influences flow when set to True

### ISSUE THREAD

**Issue by foxjr** [RasaHQ/rasa_core#691]
**Rasa Core version**: 0.9.7

**Python version**: 3.6

**Operating system** (windows, osx, ...): Linux

**Issue**: I've noticed that a bool slot doesn't seem influence the flow unless set to `True`. The description of the bool slot is `Checks if slot is set and if True`, but might there be some benefit to considering `False` values, too? How it is now, a `False` value seems to influence flow the same as a `None` value.

**Comment by amn41** [comment]
can you please produce a minimal example of this? Do you have stories which describe what shuold happen if the slot is set to False?

**Comment by foxjr** [comment]
@Ghostvv - That's a good thought. I got it working by inverting the bools, and I created an issue to see if this was expected behavior.

**Comment by foxjr** [comment]
At first, my stories relied on the `False` flag to influence the flow. Here's a relevant snippet:
```
* search_location{"time": "time", "subject": "subject", "participle": "participle"}
    - slot{"time": "time"}
    - slot{"subject": "subject"}
    - slot{"participle": "participle"}
    - action_check_db
    - slot{"db_type": "db_type"}
    - slot{"has_db": true}
    - action_search_location
    - slot{"has_loc": false}
    - utter_nolocation
* inform{"location": "location"}
    - slot{"location": "location"}
    - action_search_location
    - slot{"has_valid_loc": false}
    - utter_invalidlocation
* inform{"location": "location"}
    - slot{"location": "location"}
    - action_search_location
    - slot{"has_valid_loc": false}
    - utter_invalidlocation
* inform{"location": "location"}
    - slot{"location": "location"}
    - action_search_location
    - slot{"lat": "lat"}
    - slot{"lng": "lng"}
    - slot{"results": "results"}
    - utter_askdisplay
```
My stories file included many examples, of varying length, following the model above. I found the bot would either `utter_invalidloc` or `utter_noloc` whenever there was a location issue, but it would often select the incorrect utterance for the specific issue; e.g., the bot would `utter_invalidloc` when the user didn't provide a location at all. It seemed to learn that whenever the `lat`, `lng`, and `results` slots were not filled by `action_search_location`, it should utter one of those two things, but it was unable to learn which one based on the flag being set. 

Next, I inverted the bools, like so:
```
* search_location{"time": "time", "subject": "subject", "participle": "participle"}
    - slot{"time": "time"}
    - slot{"subject": "subject"}
    - slot{"participle": "participle"}
    - action_check_db
    - slot{"db_type": "db_type"}
    - slot{"has_db": true}
    - action_search_location
    - slot{"has_no_loc": true}
    - utter_nolocation
* inform{"location": "location"}
    - slot{"location": "location"}
    - action_search_location
    - slot{"has_invalid_loc": true}
    - utter_invalidlocation
* inform{"location": "location"}
    - slot{"location": "location"}
    - action_search_location
    - slot{"has_invalid_loc": true}
    - utter_invalidlocation
* inform{"location": "location"}
    - slot{"location": "location"}
    - action_search_location
    - slot{"lat": "lat"}
    - slot{"lng": "lng"}
    - slot{"results": "results"}
    - utter_askdisplay
```
After making only this change and then re-training, the bot answered with the correct utterance every time; i.e., invalid locations were followed by `utter_invalidloc`, and `utter_noloc` followed when no location was given by the user.

**Comment by Ghostvv** [comment]
That make sense, because the `bool` slot's feature set to one only if it is `True`. `False` is equal to not set, the other case I think is covered by `category` slot.

**Comment by foxjr** [comment]
Yeah, I noted that in my initial post. I first wanted to confirm that this is the expected behavior; if so, I'd like to make the suggestion that `True` and `False` flags influence the flow equally, since that is probably what developers will be expecting. Inverting the flags (like in my case), doubling the flags, and changing bools to categories are all workarounds, but they do seem to be _workarounds_. I would argue that encoding bools in the same way categories are encoded is more intuitive than how it currently is done.

**Comment by amn41** [comment]
I totally agree! this should have 3 possible values, `[0,0], [1,0], [1,1]` for "not set", "False", and "True" - adding to backlog now. Thought this was how this already behaved
