### ISSUE TITLE
Attribute error which I cannot figure out where to solve

### ISSUE THREAD

**Issue by abhi2652254** [RasaHQ/rasa_core#693]
**Rasa Core version**:rasa-core 0.9.4       
**Python version**:  3

**Operating system** : ubuntu 16.04 
**Issue**:

Hello,

I am facing an issue retrieving results from a .csv file where I have stored the results of restaurant details (I did not use an API but webscrapped the data from yelp.com and put some data in the .csv file to test results for displaying french restaurants only). Can anyone please help me with finding out the solution to the issue I am mentioning below? Thanks in advance.

File "/home/abhi/.local/lib/python2.7/site-packages/rasa_core/processor.py", line 302, in _run_action
events = action.run(dispatcher, tracker, self.domain)
File "actions.py", line 37, in run
results = result.search(tracker.get_slot("cuisine"),
AttributeError: 'unicode' object has no attribute 'search'

Please help me identify the source of the error, The code I am providing below.

def run(self, dispatcher, tracker, domain):
        dispatcher.utter_message("looking for restaurants")
        rest_details_df = pd.read_csv('/home/abhi/Desktop/rest_details.csv')
        cuisine = tracker.get_slot('cuisine')
        result = rest_details_df['Cuisine'] = "{0}".format(cuisine)
        results = result.search(tracker.get_slot("cuisine"),
            tracker.get_slot("people"),
            tracker.get_slot("location"), 
            tracker.get_slot("price"), 
            tracker.get_slot("info"),
            tracker.get_slot("vegetarian"))
        return [SlotSet("matches", results)]

**Content of domain file** (if used & relevant):
```slots:
  cuisine:
    type: text
  people:
    type: text
  location:
    type: text
  price:
    type: text
  info:
    type: text
  matches:
    type: list

intents:
 - greet
 - affirm
 - deny
 - inform
 - thankyou
 - request_info

entities:
 - location
 - info
 - people
 - price
 - cuisine

templates:
  utter_greet:
    - "hey there!"
  utter_goodbye:
    - "Bye-bye"
    - "goodbye :("
    - "Welcome"
  utter_default:
    - "default message"
  utter_ack_dosearch: 
    - "ok let me see what I can find"
  utter_ack_findalternatives:
    - "ok let me see what else there is"
  utter_ack_makereservation:
    - "ok making a reservation"
  utter_ask_cuisine: 
    - "what kind of cuisine would you like?"
  utter_ask_helpmore:
    - "is there anything more that I can help with?"
  utter_ask_howcanhelp:
    - "how can I help you?"
  utter_ask_location:
    - "in which city?"
  utter_ask_moreupdates: 
    - "anything else you'd like to modify?"
  utter_ask_numpeople:
    - "for how many people?"
  utter_ask_price: 
    - text: "in which price range?"
      buttons:
      - title: "cheap"
        payload: "cheap"
      - title: "expensive"
        payload: "expensive"

  utter_on_it: 
    - "I'm on it"

actions:
  - utter_greet
  - utter_goodbye
  - utter_default
  - utter_ack_dosearch
  - utter_ack_findalternatives
  - utter_ack_makereservation
  - utter_ask_cuisine
  - utter_ask_helpmore
  - utter_ask_howcanhelp
  - utter_ask_location
  - utter_ask_moreupdates
  - utter_ask_numpeople
  - utter_ask_price
  - utter_on_it
  - actions.ActionSearchRestaurants
  - actions.ActionSuggest  

```

**Comment by foxjr** [comment]
What are you thinking the `result` variable is holding when you attempt to search?

```
cuisine = tracker.get_slot('cuisine')
result = rest_details_df['Cuisine'] = "{0}".format(cuisine)
```
In the above lines, you store whatever is in the `cuisine` slot in the `cuisine` variable, and then you store that same value in the `result` variable.

**Comment by abhi2652254** [comment]
Thanks for the response. I am not getting anything while looking for **result** variable since it cannot load **cuisine** variable. It is showing an attribute error (**str** object has no attribute **search**) while I am trying to get the restaurant details.

**Comment by akelad** [comment]
@abhi2652254 you're setting the result variable to `"{0}".format(cuisine)`
don't you want to set it to `rest_details_df['Cuisine']` ?

**Comment by foxjr** [comment]
Or do you want to set `result` to `rest_details_df[cuisine]`? Also, you probably want to incorporate some kind of check to ensure that `cuisine` is something other than `None`.

**Comment by abhi2652254** [comment]
Thanks for the responses and sorry for the delayed response from my side. Specifically speaking, if a user wants to look for a specific cuisine (e.g. french, chinese, italian, etc.), the bot can be able to display the result(s) (the restaurant details like name, price range, cuisines, address and contact details)on the screen. Currently, I can only display all the records which is not desirable from user standpoint. Can anyone please help me with the problem? Thanks in advance.

**Comment by akelad** [comment]
I'm not sure what you mean with "all the records" - could you show us a screenshot? 
Generally, you need to post process this information in your custom action so that you get the correct format for Rasa Core to display

**Comment by abhi2652254** [comment]
Thanks for the early response. I have written this code below where it is displaying results for specific condition provided by me (not the user). Now, what I exactly want is if the user wants to find some specific cuisine (e.g. italian) restaurant (if it is present in the .csv file), it should be displayed on the ubuntu bash. Here, I have a 30 records in a .csv file which is too less a data but if I want to experiment it from the user standpoint it is not working. The code contains a class which is being called by the class ActionSearchRestaurants(). Please find the code below and thanks in advance. Please do not hesitate to get back to me for more information on this.


class RestaurantAPI(object):
    def search(self, info):
        rest_details_df = pd.read_csv('/home/abhi/Desktop/rest_details.csv')
        rest_details_df1 = rest_details_df[rest_details_df['Cuisine'] == 'French']
        return rest_details_df1.to_json()

class ActionSearchRestaurants(Action):
    def name(self):
        return 'action_search_restaurants'
    
    def run(self, dispatcher, tracker, domain):
        dispatcher.utter_message("looking for restaurants")
        restaurant_api = RestaurantAPI()
        restaurants = restaurant_api.search(tracker.get_slot("cuisine"))
        return [SlotSet("matches", restaurants if restaurants is not None else [])]

**Comment by foxjr** [comment]
Let's step through this:
- `restaurants = restaurant_api.search(tracker.get_slot("cuisine"))`
You use your custom search to find restaurants. 
- `rest_details_df = pd.read_csv('/home/abhi/Desktop/rest_details.csv')`
You use what looks like pandas to load your file into memory.
- `rest_details_df1 = rest_details_df[rest_details_df['Cuisine'] == 'French']`
You set `rest_details_df1` either to `rest_details_df[True]` or  `rest_details_df[False]`, based on how `rest_details_df['Cuisine'] == 'French'` evaluates. 
- `return rest_details_df1.to_json()`
You attempt to convert that result to json, which I'm guessing either throws some kind of error (if you haven't received one already), or at least doesn't do what you're hoping. 
- `return [SlotSet("matches", restaurants if restaurants is not None else [])]`
You attempt to set the matches slot to what your custom code returned

Now, I don't know how your csv is set up, but I'm guessing that neither  `rest_details_df[True]` nor  `rest_details_df[False]` will return anything valuable. Don't you want to do something like `rest_details_df[a]`, where `a` is the type of cuisine for which the user would like to search? Because that's not what you're doing at the moment.

**Comment by abhi2652254** [comment]
Thank you for the early response and addressing them separately. Let me explain the dataframe "rest_details_df" first. rest_details_df is a dataframe having columns "Name: it contains the name, address and phone number of the restaurants", "Cuisine: it contains the type of cuisine (not many are there since there are only 30 rows) like French, Bistros, Brasseries" and "Price range: it is low, medium and high (in strings)". 

In the line " rest_details_df1 = rest_details_df[rest_details_df['Cuisine'] == 'French'] " it is giving me the desired results as needed and for the .to_json() I was getting an error previously before using the .to_json() function. 

Now my objective is this to achieve:
bot: what kind of cuisine would you like?
user: please find me a french eating place.
bot: I am on it.
bot: this is what I found

[List of French restaurants with menus, price range, address and phone number]

What I am getting now is a static response as per the code which is only French restaurants. 

Please help me with an idea to achieve the above objective.
Thanks in advance and please do not hesitate to get back to me for more information.

**Comment by foxjr** [comment]
So if I'm understanding correctly, entity extraction and slot filling seems to be your issue. You want to do `tracker.get_slot('cuisine')` instead of hard-coding "French," right? If that's the case, you may just need more NLU examples showing `cuisine` entity extraction.
