### ISSUE TITLE
integers as input for domain.yml file

### ISSUE THREAD

**Issue by Ujjwalsas9** [RasaHQ/rasa_core#697]
**Rasa Core version**:

**Python version**: 

**Operating system** (windows, osx, ...):

**Issue**:

How can we accept integer values from user.  For example: suppose I ask about the user's age and user says 29 years. So can I implement it in training data and stories.md and domain.yml file.

**Content of domain file** (if used & relevant):
```yaml

```

**Comment by akelad** [comment]
Yes, you can accept integer input from users, this would be part of NLU rather than core though. So they should still get mapped to an intent/entity. You can use ner_duckling to extract numbers easily.

**Comment by Ujjwalsas9** [comment]
thank you very much.

**Comment by akelad** [comment]
No problem, I'll close this issue then - of course let us know if there's any more issues/questions
