### ISSUE TITLE
Is there any way that we can keep track of the chat we had with RASA?

### ISSUE THREAD

**Issue by tushar1328** [RasaHQ/rasa_core#705]
This would be great help to rectify the errors made during testing and developing phase. Please introduce and develop the feature if not. If available please guide me for the same @wrathagom @akelad

**Comment by akelad** [comment]
Could you explain what you mean by "keep track"? If you run core in debug mode (passing the --debug flag), all the detailed logs of NLU/Core should be saved to a log file (rasa_core.log by default)

**Comment by akelad** [comment]
Reading your comments on the other issue - saving of NLU data to a database isn't something that is implemented in Core/NLU now. This is however part of our enterprise subscription: http://rasa.com/products/rasa-platform/

**Comment by tushar1328** [comment]
thanks @akelad that would be a great option to my answer, i would surly like to try the RASA Platform. I have applied for it but they haven't yet responded to my mail.

**Comment by akelad** [comment]
@tushar1328 has someone gotten back to you yet?

**Comment by akelad** [comment]
i'll close this issue for now anyways since the question is answered :) let us know if there's any more issues/questions
