### ISSUE TITLE
Form Action : action named utter_ask_{}

### ISSUE THREAD

**Issue by Graziella-Husson** [RasaHQ/rasa_core#709]
**Rasa Core version**: 9.7

**Python version**: 3.5

**Operating system** (windows, osx, ...): Linux

**Issue**:
Documentation says : "You need to define utterances for asking for each slot in your domain, e.g. utter_ask_{slot_name}"
I have a question about this. Is it possible to trigger a custom action named utter_ask_{slot_name} instead of a sentence in the domain file ?

**Comment by amn41** [comment]
You can do this, but then you will have to create your own subclass of `FormAction` to implement this logic
