### ISSUE TITLE
Custom Actions are Executed during Rasa Core Evaluation

### ISSUE THREAD

**Issue by georgwiese** [RasaHQ/rasa_core#720]
**Rasa Core version**: 0.9.7

**Python version**: 3.6

**Operating system** (windows, osx, ...): Docker (python:3.6-slim-jessie)

**Issue**:

When I run the Rasa Core evaluation, my custom action is run. I verified this by adding a `logging.error()` call to the action, which gets printed during evaluation.

In my case, this leads to misclassifications, because the action overwrites the slot values specified in the story file. But generally, custom actions could do anything, so they shouldn't be run during evaluation.

I run the evaluation as:
`python -m rasa_core.evaluate  --stories data/core --core models/current/dialogue --output evaluation/core_confusion_matrix.pdf --failed evaluation/failed_stories.txt`

Interestingly, `failed_stories.txt` says `All stories passed`, but the confusion matrix shows imperfect classifications.

**Comment by akelad** [comment]
Why should they not be run during evaluation? These custom actions will be run when a user uses the bot, so they should also be tested.

Would you be willing to share your bot here? My guess is there's something wrong with your stories if there's misclassifications

**Comment by georgwiese** [comment]
Because, for example, a custom action could access an external API which we
can't control during testing. It could even do permanent changes to a
database.

I can construct a minimal example later today.

**Comment by georgwiese** [comment]
Here you go.

My story file is this:
```md
## Ask Weather (weather is nice)
* ask_weather
- weather_action
- slot{"weather": "nice"}
- utter_weather_nice

## Ask Weather (weather is rainy)
* ask_weather
- weather_action
- slot{"weather": "rainy"}
- utter_weather_rainy
```

`weather_action` is implemented as a custom action:
```python
class WeatherAction(AbstractAction):
    def run(self, dispatcher, tracker, domain):

        logging.error("Weather action executed")

        # Suppose test is run on a nice day
        return [SlotSet("weather", "nice")]
```

I'm evaluating like this:
```bash
python -m rasa_core.evaluate  --stories data/core \
	--core models/current/dialogue --output evaluation/core_confusion_matrix.pdf \
	--failed evaluation/failed_stories.txt
```

The effect is:
- While running the test, I get the `"Weather action executed"` log twice.
- `failed_stories.txt` says `All stories passed`
- `core_confusion_matrix.pdf` reports that `utter_weather_rainy` is never predicted (see below). I'm assuming this is because running the action always sets the slot to `nice`.
 
![screen shot 2018-07-18 at 11 52 35](https://user-images.githubusercontent.com/1701960/42874353-30f30b1c-8a81-11e8-9883-f58f9fdf0277.png)

**Comment by akelad** [comment]
If this action isn't executed though - how would you expect any of the stories to pass? The slot wouldn't be filled at all

**Comment by georgwiese** [comment]
I would expect the slot to be set by the testing framework as specified in
the story file, just as during training.

In the example, it does seem to try to test the rainy weather case as well,
but the `slot{}` statement is overwritten by the action.

**Comment by akelad** [comment]
Ok I see your point now, it makes sense. We'll be working on this soon

**Comment by georgwiese** [comment]
Is there a status update on this?

**Comment by tmbo** [comment]
Sorry, but we haven't started working on this yet. It is on the list, but there are some more urgent issues we need to tackle first.
