### ISSUE TITLE
Can I access the WSGI app object used in an HttpInputChannel?

### ISSUE THREAD

**Issue by m90** [RasaHQ/rasa_core#722]
**Rasa Core version**: 0.9.7

**Python version**: 3.6

**Operating system** (windows, osx, ...): Ubuntu

**Issue**:

I am currently running a Flask app that manually wraps rasa_core. I was looking into if I could be using the `HttpInputChannel` provided with rasa_core.

To successfully migrate to that approach I would need to access the Flask `app` object though as I need to a. add Sentry error monitoring and b. AWS Elastic Beanstalk expects me to point it to a WSGI compatible server that it will run (I think using sth like `gunicorn` would require the same).

 This portion of the code: https://github.com/RasaHQ/rasa_core/blob/c1e50a299fed90297837c76e0b8f0fd0a1870511/rasa_core/channels/rest.py#L45-L59 looks as if `app` is closed over and never being made available in any way.

Am I missing something and there is a way to access the WSGI app? In case not, would you accept a PR that adds the option to delegate the WSGI `run`ning to the caller?

**Comment by advl03** [comment]
I've got the same question. My objective is to run a rasa bot for Facebook Messenger, and have found that using the provided flask app allows a limited number of users. How can I use a production-grade WSGI compatible server with the Facebook (or any other) channel?

**Comment by advl03** [comment]
Btw, @m90, I’m interested on taking a look at your “Flask app that manually wraps rasa_core”. Could you explain how do you do that?

**Comment by m90** [comment]
@advl03 We already have an existing "proxy" kind of service running that used to connect dialogflow with several messengers and a web frontend, so we just needed to add rasa_core as an alternative backend to using dialogflow. This means we do not need to / want to use the Messaging app (Telegram / FB Messenger) specific features of rasa but instead just have our proxy interact with rasa using HTTP.

What this boils down to is that we currently just create a rasa `agent` that is wrapped in a Flask handler that just handles auth and relays incoming and outgoing messages to this very agent.

As for production readiness / scalability having `gunicorn` in front of the Flask app worked just fine until now as rasa_core seems pretty lightweight by itself (we have the NLU part running on yet a different service though, so YMMV here I guess).

I still think somehow making the WSGI object available would be very valuable as it's kind of the default interface to everything anyone ever wanted to put in front of a service.

**Comment by advl03** [comment]
Thanks for the detailed explanation, @m90. It’s a solution similar to the one I have in my mind, except that my proxy would have two rasa bots behind for load balancing. But it’s the same concept: launching the proxy inside gunicorn for escalation purposes.
And I agree with you: it would be easier if I can launch rasa core directly through wsgi and have nginx as load balancer for a couple of gunicorns.

**Comment by akelad** [comment]
@ricwo have you had a chance to look at this yet?

**Comment by m90** [comment]
Is there any input on if this might happen or not? Seeing that 0.11 will basically contain all the customizations that we are currently adding ourselves right out of the box, it'd be a pretty big win for us.

In case you agree that it'd be a good idea to expose the WSGI app in some way or the other I'd be happy to add this myself in case we can agree on a mechanism.

**Comment by ricwo** [comment]
@m90 thanks for raising this issue. I agree that making the app available beyond the message handler would be a valuable addition. so yes, feel free to create a PR

**Comment by m90** [comment]
Looking at current master, it appears to me it's already possible to do this by using `rasa_core.server.create_app` which worked differently when I created this issue.

I'll try to use this and see if it helps me remove all the custom code, but right now I think there's no need to add any functionality. Which is great.

**Comment by m90** [comment]
Using the approach described above works just fine for me. I pass the Agent I need to `create_app` and then use `/conversations/<sender_id>/respond` to exchnage messages.

Does this work for you as well @advl03 ?

**Comment by akelad** [comment]
Nice, I'm glad it's resolved! We merged a huge change to Core recently, so it works more like an SDK now and should simplify a lot of things

**Comment by advl03** [comment]
@m90 @akelad  Thanks for moving this! 
As I was using the core as a library (building on top of rasa_core different agents, trackers and custom channels) and not as a server, I'm not sure about how to migrate all of this in order to take advantage of using rasa_core as a server and launching it with gunicorn or other WSGI server. 
Is it possible to just launch the server on top of all the customizations I've done? Could you please tell me what is the proper document I can start with?
Thanks in advance!

**Comment by akelad** [comment]
The migration guide in the docs should be a good starting point:  http://rasa.com/docs/core/migrations/
You should be able to use everything as you did previously, no problem. 
I'm gonna close this issue since it's original question has been answered, but if you encounter any issues please create a new issue, or if you need some advice please post in our [forum](https://forum.rasa.com)
