### ISSUE TITLE
Can we integrate rasa core into stack storm?

### ISSUE THREAD

**Issue by gprabhuv4me** [RasaHQ/rasa_core#725]
**Rasa Core version**:

**Python version**: 

**Operating system** (windows, osx, ...):

**Issue**:

**Content of domain file** (if used & relevant):
```yaml

```

**Comment by gprabhuv4me** [comment]
if yes, please provide the details.

**Comment by akelad** [comment]
I'm not familiar with stack storm, but if it has an API to connect to a chat then yes, you can build a custom input/output channel if you want to use it.
