### ISSUE TITLE
RASA: Story generation

### ISSUE THREAD

**Issue by balinda-1995** [RasaHQ/rasa_core#729]
**Rasa Core version**:0.9.6

**Python version**: 3.6

**Operating system** (windows, osx, ...): Windows 10

**Issue**:
I want to find a way to automatically convert any conversation into a story format to be able to train my bot. 
I have generated my stories using the online training session, or the machine teaching offered by RASA Core, but I found this technique impractical when I want to have a big training data.
I want to use any conversation and be able to automatically convert it into a story without having to do so manually. Any ideas?

**Content of domain file** (if used & relevant):
```yaml

```

**Comment by tushar1328** [comment]
This can be done by adding a end action.
For example:
if conversations end with bye statement, just create a action for bye and at the end of the conversation it will convert the entire conversation in the story and save the same into a file you named.

## action.py
```
from rasa_core.events import Restarted
from rasa_core.events import StoryExported

#---------------Your Entire Action Code here-----------------------

class ActionByeBye (Action):
	def name(self):
		return 'action_bye'
	def run (self, dispatcher, tracker, domain):
		return[StoryExported("data.md"),Restarted()]
```
You will need to change the previous stories where the ending is called. you need to add the 'action_bye' to the end of bye intent and retrain you model. after that is done each and every time a conversation is done the story would be generated and would be stored into 'data.md' file.

Below is an example of the stories I made.

## stories.md
```
## Generated Story 7896053435535017207
* greet
    - utter_greet

#------------ Add the story accord to your BOT--------------

* goodbye
    - utter_goodbye
    - action_bye
    - export
```
and don't forget to add the action to you weather_domain.yml (If you are following the @JustinaPetr Video tutorial).

**Comment by balinda-1995** [comment]
Thanks, it worked !

**Comment by arachny** [comment]
I see that you used `return[StoryExported("data.md"),Restarted()]` in `action.py` and `- export` in `stories.md` so I wanted to ask if `- export` is necessary since you already return this... or in contrast if you should have added `- action_restart` in the `stories.md` after the `- export action`? Or either solution would work?

**Comment by akelad** [comment]
@balinda-1995 do you need any more help or can we close this issue?

**Comment by balinda-1995** [comment]
yes i am done, thanks!
