### ISSUE TITLE
stories, curly braces, -slot

### ISSUE THREAD

**Issue by pwierzgala** [RasaHQ/rasa_core#733]
**Rasa Core version**: 0.9.7

**Python version**: 3.5.2

**Operating system** (windows, osx, ...): ubuntu 16.04

**Issue**:

While reading rasa core documentation I'm confused of how to use:
- Data in curly braces.
- "-slot{...}" actions.

**Data in curly braces**
There is an example of stories training data on [stories](https://core.rasa.com/stories.html) documentation page:

`* inform{"location": "rome", "price": "cheap"}  <!-- user utterance, in format intent{entities} -->`

What is the reason to provide value for entitiy e.g. "rome" for "location"? I understand that user may need to define a story which should be followed when the message is recognized as "inform" intention with "location" and "price" entities but in such case there's no need to specify exact value for entity.

**"-slot{...}" actions**

One of the documentation [pages](https://core.rasa.com/patterns.html) contains the following example:

```
* request_restaurant
     - action_restaurant_form
     - slot{"requested_slot": "people"}
* inform{"number": 3}
     - action_restaurant_form
     - slot{"people": 3}
     - slot{"requested_slot": "time"}
* inform{"time": "8pm"}
   - action_restaurant_form 
```

My question here is similar to the previous one: "why do we specify exact value for a slot and how does it influence the story?" My understanding of the example is as follows:

- User asks for a restaurant.
- Using -slot{"requested_slot": "people"} we tell the bot to ask about number of people.
- User provides the number of people.
- Using -slot{"people": 3} we define that the slot "people" is set to prevent FormAction from asking about it.
- Using -slot{"requested_slot": "time"} we tell the bot to ask about reservation time.
- ... and so on.

**Comment by akelad** [comment]
so the entities in the story are just to indicate the presence of the entities, the exact value is irrelevant.
As for slots, the values they are set to matter only if you're using a categorical or boolean slot (or potentially a custom one). There you can write different stories for each value. For other slot types it's just to indicate that the slot was set. You could for example also include a `- slot{"people":null}` event, if you cleared your slot in a custom action or something

**Comment by pwierzgala** [comment]
Great, it's clear for me now. I read other issues and found that similar question was already asked:
https://github.com/RasaHQ/rasa_core/issues/333#issuecomment-380179919

Please consider adding this information to the documentation. Maybe I missed something but my impression is that this topic is not covered good enough.

Please close this issue.

**Comment by akelad** [comment]
Good point, I'll take a note of it and we'll add it to the docs :)
