### ISSUE TITLE
Could not find a version that satisfies the requirement tensorflow==1.8.0

### ISSUE THREAD

**Issue by umair-saeed-confiz** [RasaHQ/rasa_core#738]
**0.10.0a3**:

**3.6.6**: 

**windows**:

**Issue**:
I have been tried both ways "using pip" and  "using github + setup.py". And on both ways I stuck at following error
 Could not find a version that satisfies the requirement tensorflow==1.8.0 (from -r requirements.txt (line 13)) (from versions: )
No matching distribution found for tensorflow==1.8.0 (from -r requirements.txt (line 13))

**Content of domain file** (if used & relevant):
```yaml

```

**Comment by HCIS2020** [comment]
tensorflow 1.8.0 now only compiled for  64 bit. you need change to python 64 bit to run.

**Comment by darkmanAmazigh** [comment]
the same problem with python 3.7.1
