### ISSUE TITLE
Custom Slot Type

### ISSUE THREAD

**Issue by andreamtang** [RasaHQ/rasa_core#739]
**Rasa Core version**:0.9.6

**Python version**: 3.6.5

**Operating system** (windows, osx, ...): OSX

**Issue**:
Is there an example for how to define a custom slot type? I want my slot to be able to hold a Python `datetime` object rather than a string. Or should I just used the `unfeaturized` data type and convert a string such as `"2018-07-01T00:45:00.000Z"` into a `datetime` object in my existing `ActionSetUp(FormAction)` class within the `submit()` function?
Also, I am not sure what the following line in the Rasa Core docs means: "User has to subclass this and define the as_feature method containing any custom logic."

**Content of domain file** (if used & relevant):
```yaml

```

**Comment by akelad** [comment]
Is there any reason why you can't store that as a string in your slot and then if you need to process it in a custom action convert it to a datetime object there?

**Comment by andreamtang** [comment]
I have a number of custom actions that access these slots so it'd just be more convenient if they are all in the correct format when I use the `tracker.get_slot()` function rather than converting them each time.
