### ISSUE TITLE
Link bot to API (SPOONACULAR)

### ISSUE THREAD

**Issue by balinda-1995** [RasaHQ/rasa_core#741]
**Rasa Core version**: 0.9.8

**Python version**: 3.6

**Operating system** (windows, osx, ...): Windows 10

**Issue**: I want to improve my weatherbot by adding a recipe-suggesting service. I want to use Spoonacular as my recipe API from which I am going to get my recipes based on the preferred cuisine of the user. How can I do that? what's the outcome of spoonacular when I call it and provide it with a specific cuisine? I looked for a week and found nothing !

**Content of domain file** (if used & relevant):
```yaml


```
[domain.txt](https://github.com/RasaHQ/rasa_core/files/2192379/domain.txt)

**Comment by auzair92** [comment]
You first have to subscribe to a Spoonacular pricing plan before you can consume their Food API. You can do that [here](https://rapidapi.com/spoonacular/api/Recipe%20-%20Food%20-%20Nutrition/pricing). Then you'll be able to send requests to their API and receive responses, as detailed here, by filling out required parameters of the request (the `cuisine` parameter is optional, and this is where your cuisine title will go). 

An alternative is [Edamam](https://developer.edamam.com/edamam-recipe-api), and they too have free and paid price plans.

**Comment by akelad** [comment]
@balinda-1995 do you have any more questions or can we close this issue?

**Comment by balinda-1995** [comment]
Oh i'm sorry for the delay! it did work for me, thanks

**Comment by akelad** [comment]
no worries!
