### ISSUE TITLE
some of the "utter" actions do not send the full message to the output

### ISSUE THREAD

**Issue by lgrinberg** [RasaHQ/rasa_core#742]
**Rasa Core version**:
 0.9.6

**Python version**: 
 3.6.5

**Operating system** (windows, osx, ...): 
 Windows 10

**Issue**:
In my dialogue, for certain utter actions, the complete message does not get sent to the output channel (console in this case).  Instead I get what seems to be a random letter.

Bot loaded. Type a message and press enter:
hello
Hello
what is the time in elmwoodpark
figuring out the city  
i                         ##here's where the utter_which_one_of_two should be output
elmwoodpark illinois  
figuring out the city
time is 5:30PM
Good bye  

full log with some custom debugging output attached

**Content of domain file** (if used & relevant):
entities:
 - city
 - state
 - region
 - county
 - country
 - zip_code
 - location1
 - location2
 

slots:
  error:
    type:  text
  location1:
    type:  text
  location2:
    type:  text  
  city:
    type:  text
  zip_code:
    type:  text
  number: 
    type:  categorical
    values: 
    - unique
    - dual
    - plural
    - error
  time:
    type: text
  option1:
    type: text
  option2:
    type: text
  ambiguitiy:
    type: categorical
    values: 
    - county
    - state
    - country
    
intents:
 - greet
 - ask_time
 - location
 - goodbye

templates:
  utter_error:
      "Error! {error}"
  utter_time:
    - "time is {time}"
  utter_greet:
    - "Hello"
  utter_goodbye:
    - "Good bye"
  utter_specify:
    - "What city please?"
  utter_need_more_info: 
    - "That's not specific enough.  Maybe you know the zip code, county or state?"
  utter_anything_else:
    - "Another city time?"
  utter_which_one_of_two:
      "Is it {option1} or {option2}"

actions:
 - utter_error
 - utter_greet
 - utter_goodbye
 - utter_specify
 - utter_time
 - utter_anything_else
 - utter_need_more_info
 - utter_which_one_of_two
 - action.action_get_time
 - action.action_disambiguate

**Comment by akelad** [comment]
Could you post your stories file too please? (and format both with ``` please so it's legible)

**Comment by lgrinberg** [comment]
[time-stories.md.txt](https://github.com/RasaHQ/rasa_core/files/2203135/time-stories.md.txt)

**Comment by lgrinberg** [comment]
Akela, I uploaded my story file.

Thank you so much

**Comment by lgrinberg** [comment]
Hi Akela, I uploaded my story file.

Thank you
Leo

**Comment by akelad** [comment]
Hmm, I can't see anything obviously wrong there. Could you post a zip of the whole project, including actions file and trained models? That way I can try and reproduce it

**Comment by lgrinberg** [comment]
[timebot.zip](https://github.com/RasaHQ/rasa_core/files/2211439/timebot.zip)

Here it is

**Comment by akelad** [comment]
You've forgotten to add a `-` to some of your utterance templates
```
  utter_default:
      "I'm sorry, I didn't understand that.  What city please?"
  utter_error:
      "Error! {error}"
  utter_time:
    - "time is {time}"
  utter_greet:
    - "Hello"
  utter_goodbye:
    - "Good bye"
  utter_specify:
    - "What city please?"
  utter_need_more_info: 
    - "That's not specific enough.  Maybe you know the zip code, county or state?"
  utter_anything_else:
    - "Another city time?"
  utter_which_one_of_two:
      "Is it {option1} or {option2}"
```
Notice the difference between e.g. `utter_anything_else` and `utter_which_one_of_two`

**Comment by akelad** [comment]
You can use `ner_duckling` to extract time from text

**Comment by lgrinberg** [comment]
Hi Akela, yes, sorry about that, that's a silly mistake.   I did fix it (see below) and reran the bot, but I get the same result.

utter_default:
    - "I'm sorry, I didn't understand that.  What city please?"
  utter_error:
    - "Error! {error}"
  utter_time:
    - "time is {time}"
  utter_greet:
    - "Hello"
  utter_goodbye:
    - "Good bye"
  utter_specify:
    - "What city please?"
  utter_need_more_info: 
    - "That's not specific enough.  Maybe you know the zip code, county or state?"
  utter_anything_else:
    - "Another city time?"
  utter_which_one_of_two:
    - "Is it {option1} or {option2}"

**Comment by akelad** [comment]
Did you retrain it too?

**Comment by lgrinberg** [comment]
Yes, that did the trick.  It works now.  Thank you so much Akela.
