### ISSUE TITLE
Parsing required slots prior to filling

### ISSUE THREAD

**Issue by andreamtang** [RasaHQ/rasa_core#743]
**Rasa Core version**: 0.9.6

**Python version**: 3.6.5

**Operating system** (windows, osx, ...): OSX

**Issue**:
I have a question concerning the FormAction class. I want to parse certain required slots before they are filled so that all the time slots are in the format `%I:%M` (i.e., `09:30`). Would the best way to implement this be within the submit() function since (I'm assuming) it is run everytime a required slot is filled?

**Content of domain file** (if used & relevant):
```yaml

```

**Comment by akelad** [comment]
The submit function only gets called once all the slots are filled. But you could make the required changes to the slot values in that function and just return `SlotSet` events from that function

**Comment by andreamtang** [comment]
So my function would look something like this?:

```
    def submit(self, dispatcher, tracker, domain): 
        avg_bedtime = tracker.get_slot("avg_bedtime")
        goal_bedtime = tracker.get_slot("goal_bedtime")

        avg_bedtime_object = parser.isoparse(avg_bedtime) 
        goal_bedtime_object = parser.isoparse(goal_bedtime)

        avg_bedtime_object.strftime('%I:%M')
        goal_bedtime_object.strftime('%I:%M')

        return [SlotSet("avg_bedtime", value=avg_bedtime_object),
                SlotSet("goal_bedtime", value=goal_bedtime_object)]
```

**Comment by akelad** [comment]
Yes it would!
