### ISSUE TITLE
train_online to support handle_messages

### ISSUE THREAD

**Issue by Aliyss** [RasaHQ/rasa_core#746]
**Rasa Core version**:
0.9.8

**Python version**: 
3.6

**Operating system** (windows, osx, ...):
Windows

**Request**:
Another Request. Sorry. Would it be possible to make the train_online handle_messages as well as handle_channels. I made my own implementation of it and it seems to be working ok, however it isn't clean code. Just wanted to ask, in case this were a feature others would like to use as well.

**Comment by akelad** [comment]
Could I ask what you need the change for? We're actually currently working on a big refactor of how online training etc works

**Comment by akelad** [comment]
So you're saying you want to be able to use online training via discord? In our big refactor this will be easier to do, so i'd say wait until that gets merged (should be this week)

**Comment by Aliyss** [comment]
@akelad Has this been added? I couldn't find anything in the docs.

**Comment by akelad** [comment]
The changes have been merged to master now, yes. This is what online training looks like now: https://github.com/RasaHQ/rasa_core/blob/master/rasa_core/training/online.py

And a migration guide on everything is here: http://rasa.com/docs/core/master/migrations/

**Comment by Aliyss** [comment]
Thanks a lot.

**Comment by akelad** [comment]
Cool, I'll close this issue for now, if any issues come up feel free to create a new one
