### ISSUE TITLE
multilingual chatbot

### ISSUE THREAD

**Issue by MinhMinnie** [RasaHQ/rasa_core#779]
**Rasa Core version**: 0.9.6

**Python version**: python 3

**Operating system** (windows, osx, ...): Ubuntu

**Issue**:
I want to build a multilingual chatbot. for EX, when a user starts a conversation in French, The bot will response in French. if user types something in English, the bot will start the conversation in English. How can I do this? (I will use google translate API to detect language and translate)  
My idea is:
1. Create multiple agents in some languages 
2. Choose a default language, but allow switching to the other languages
3. Use language detection.
but I do not know how to make it work . 
 

**Content of domain file** (if used & relevant):
```yaml

```

**Comment by MinhMinnie** [comment]
I want to detect the language which user uses and translate user input into French before tokenization, featurization, extraction...
Could you tell me from the code, where should I modify it?

**Comment by akelad** [comment]
I think the ideal case here would be to have seperate bots that get loaded dependent on whether the language detected was english or french. I don't think translating the user input into french is such a good idea, google translate often messes that up and so you might not get the meaning you want

**Comment by MinhMinnie** [comment]
@akelad in run_bot(), how can I get the latest message from user?. I tried: DialogueStateTracker.latest_message but It gives me the error: type object 'DialogueStateTracker' has no attribute 'latest_message'

**Comment by MinhMinnie** [comment]
I want to get the latest_message to detect the language user uses

**Comment by akelad** [comment]
It's best to do that in a custom action, where you can call `tracker.latest_message.text`

**Comment by MinhMinnie** [comment]
I can get it in a custom action but I want to do in bot.py file because from there, I will decide which model should be loaded

**Comment by akelad** [comment]
@souvikg10 I think you had some suggestions on how best to get this working?

**Comment by souvikg10** [comment]
@MinhMinnie I think the models are loaded on startup, Imo, once your model becomes very large it is not a good idea to load it on the fly based on input message. You should spin up two bots with pre-loaded models and then put an detector in the middle that diverts traffic to each bot based on language detection( we use cookies to do that) but there are other methods. but as I mentioned in Gitter I suppose - lang detect is not easy specially English and French ( they are very similar in written when it comes to one word replies and you won't be able to make out anything). 

Can you explain me a scenario where you might face this on a regular basis? I work in Belgium and we deal with 4 languages but never heard a scenario where people are switching languages during a conversation and for each language we manage separate channels today.

**Comment by AdelePh** [comment]
@souvikg10 Could you help me please? 
I start the conversation by "Get started" button in fb messenger.
The bot gives me 3 options, "Choose a language" is one of them
After choosing "Choose a language", I have 2 choices : English and Français (I have 2 models : English and French)
The bot is pre loaded with English model
If I click on button "Français", How to reload the bot with the French model?

![capture d ecran de 2018-08-28 18-37-17](https://user-images.githubusercontent.com/42778118/44734239-aeb50180-aae9-11e8-91a5-32a7f508a8f5.png)

**Comment by souvikg10** [comment]
i wrote the solution in the above comment, create two bots in each language and use the same tracker store

**Comment by AdelePh** [comment]
@souvikg10 but in my case, the English model is loaded before the user chooses "French model". that means the user wants to switch the language during the English conversation.

I have 2 bots in each language, use Redis server as a tracker-store

**Comment by souvikg10** [comment]
You need an intermediary layer between two rasa chatbots(FR/EN), some sort of dispatcher, 

Dispatcher could be a simple application in python that has a webhook for your channels or in node js(we are using botkit) this dispatcher is able to detect the user language( in case of Facebook, you can get user's profile language to start with. 

In the backend you have two rasa servers with two endpoints for /parse, using the same user id you call either one of them using the ID 

Channels --> Dispatcher(FR/NL) --> CoreFR OR Core NL --> TrackerStore(Redis)

**Comment by souvikg10** [comment]
I will write up an example multilingual chatbot this weekend to better describe this case using Rasa.

**Comment by AdelePh** [comment]
Thanks @souvikg10. Waiting for the example

**Comment by akelad** [comment]
awesome, looking forward to seeing this @souvikg10!
