### ISSUE TITLE
Debug entities and slot filling

### ISSUE THREAD

**Issue by Krogsager** [RasaHQ/rasa_core#780]
**Rasa Core version**: 0.10.1

**Python version**: 3.6.6

**Operating system** Ubuntu

**Issue**:
I find it hard to keep track of the behavior of a bot. Whether it needs more data, lacks some setup in stories.md/nlu.md/domain.yml or some issue with the pipeline setup.

For example
Intent: select_animal,
Entity: ent_animal,
Slot: ent_animal, type: categorical, values: - horse - dog - cat - bird

If I train rasa_nlu to identify an additional entity ent_animal (lets say snake), the slot ent_animal will not be filled.
My problem is that slot filling happens automatically and silently. I would really like some way to inspect this when I run interactive training, the rasa_nlu.server,  or --debug as part of rasa_core.run
A solution could be a warning when an entitiy matches a slot, but the datatype or category does not match.

**Comment by akelad** [comment]
You can inspect this with the `--debug` flag, you can see both when entities are picked up and also when slots are filled. This explanation here might help: http://rasa.com/docs/core/debugging/

**Comment by Krogsager** [comment]
Regarding the debugger, does it have some bugs?
Whatever I write, the log repeats my message as the intent:

> 2018-07-23 15:11:54 DEBUG    rasa_core.processor - Received user message '**hi robot, how are you?**' with intent '{**'name': 'hi robot, how are you?**', 'confidence': 1.0}' and entities '[]'

Intent and entity recognition works when I run `python -m rasa_nlu.server --path training`
but not when I run `python -m rasa_core.run -d models/current/dialogue -u models/current/nlu --debug`

**Comment by akelad** [comment]
The problem with the online training is that you need to load an NLU model as your interpreter, currently you're using the RegexInterpreter, which only works when passing direct intents, e.g. `/greet`
As for the problem with `rasa_core.run` - I'm looking into it, will take a look
