### ISSUE TITLE
Agent.handle_message update issue

### ISSUE THREAD

**Issue by fakesecret** [RasaHQ/rasa_core#781]
**Rasa Core version**: 0.10.1 (using pip3)

**Python version**: 3.5 (No matter)

**Operating system** (windows, osx, ...): No matter

**Issue**: for Agent.handle_message # type: (...) -> Optional[List[Text]] 
with example "agent.handle_message("hello") --> [u'how can I help you?']". 

With the latest update, this information is longer true. Now, the return type is a list(dict), for example, for "hello", it can return [{'recipient_id': 'default', 'text': 'Greetings.'}]

This is a back-compatibility breaker. The scripts using this method and Rasa_core documentation need to be corrected accordingly, such as https://core.rasa.com/api/agent.html and https://core.rasa.com/migrations.html

**Comment by akelad** [comment]
Hmm, as far as I can see this hasn't changed from 0.9 to 0.10: https://github.com/RasaHQ/rasa_core/blob/0.9.x/rasa_core/channels/direct.py#L4

**Comment by fakesecret** [comment]
It should be a problem from 0.8. It seems to me that it was first str, then a tuple, and now a dict. However, the docstring and documentation still remain unchanged. For example, I'm not sure one of the very first tutos (https://core.rasa.com/tutorial_supervised.html) is still correct:

>>> agent.handle_message("/greet")
[u'hey there!']

**Comment by akelad** [comment]
Yes that documentation should definitely be updated. We'd be happy to accept a PR for that :)
