### ISSUE TITLE
why rasa get the same responses  with different question?

### ISSUE THREAD

**Issue by springwings** [RasaHQ/rasa_core#784]
**Rasa Core version**:

**Python version**: 

**Operating system** (windows, osx, ...):

**Issue**:

**Content of domain file** (if used & relevant):
```yaml

```

**Comment by akelad** [comment]
could you elaborate on what you mean?

**Comment by springwings** [comment]
![qq 20180723175053](https://user-images.githubusercontent.com/7347530/43069962-00650370-8e5e-11e8-9c09-6a70a9fb0a5a.png)
different question all get the same responses "I'm on it"

**Comment by akelad** [comment]
It's likely you don't have enough training data for Core/NLU yet
