### ISSUE TITLE
Date Tracking

### ISSUE THREAD

**Issue by andreamtang** [RasaHQ/rasa_core#785]
**Rasa Core version**: 0.9.6

**Python version**: 3.6.5

**Operating system** (windows, osx, ...): OSX

**Issue**:
My chatbot is supposed to help the user set weekly goals so I want it to perform certain actions only once a week (ideally on Sundays) that creates the upcoming week's goals. Is there some way to track what day of the week it is and, if it is a Sunday, to trigger that action?

**Content of domain file** (if used & relevant):
```yaml

```

**Comment by akelad** [comment]
You could check this in a custom action, using datetime and then set e.g. a boolean slot to true/false dependent on what day it is. Then add a story where if it's set to true, trigger the specific action you want to trigger

**Comment by andreamtang** [comment]
How would I ensure that the boolean slot is checked/updated at the start of each new day?

**Comment by akelad** [comment]
You would probably only do this when the user interacts with your bot right? So when the user asks something like "what are my goals", you can have a custom action that sets the slot
