### ISSUE TITLE
Slot not filling - #771 - with EXAMPLE Data from rasa

### ISSUE THREAD

**Issue by mrRobot62** [RasaHQ/rasa_core#789]
**Rasa Core version**:
rasa-core                     0.10.1     
rasa-nlu                      0.12.3     

**Python version**: 
3.6.6

**Operating system** (windows, osx, ...):
MacOS, Darwin MacBook-Pro-4 17.7.0 Darwin Kernel Version 17.7.0: Thu Jun 21 22:53:14 PDT 2018; root:xnu-4570.71.2~1/RELEASE_X86_64 x86_64

**Issue**:
This issue is based on #771 , but know I installed the rasa_core.examples (restaurant-bot) and I have the same issue !
**The slots are not filled.**

The only thing, I included in > bot.py a def train_online function to use online training.

I did below tests several times - in every case, I saw no slot fillings
(and yes, I trained nlu and dialog)

What I saw during running :
```
RuntimeError: module compiled against API version 0xb but this version of numpy is 0xa
RuntimeError: module compiled against API version 0xb but this version of numpy is 0xa
```

Example training-online
```
Bot loaded. Type a message and press enter: 
**I want a mexican restaurant**
------
Chat history:
	bot did:	None
	bot did:	action_listen
	user said:	I want a mexican restaurant

		 whose intent is:	I want a mexican restaurant

**we currently have slots: info: None, cuisine: None, people: None, matches: None, price: None, location: None**

------
The bot wants to [utter_on_it] due to the intent. Is this correct?
	1.	Yes
	2.	No, intent is right but the action is wrong
	3.	The intent is wrong
	0.	Export current conversations as stories and quit
1
I'm on it
------
Chat history:

	bot did:	None
	bot did:	action_listen
	user did:	I want a mexican restaurant
	bot did:	utter_on_it

we currently have slots: info: None, cuisine: None, people: None, matches: None, price: None, location: None

------
The bot wants to [utter_ask_cuisine]. Is this correct?
	1.	Yes.
	2.	No, the action is wrong.
	0.	Export current conversations as stories and quit
1
what kind of cuisine would you like?
------
Chat history:
	bot did:	action_listen
	user did:	I want a mexican restaurant
	bot did:	utter_on_it
	bot did:	utter_ask_cuisine

we currently have slots: info: None, cuisine: None, people: None, matches: None, price: None, location: None

------
The bot wants to [action_listen]. Is this correct?

	1.	Yes.
	2.	No, the action is wrong.
	0.	Export current conversations as stories and quit
1
Next user input:
**mexican**
------
Chat history:

	bot did:	utter_on_it
	bot did:	utter_ask_cuisine
	bot did:	action_listen
	user said:	mexican

		 whose intent is:	mexican

**we currently have slots: info: None, cuisine: None, people: None, matches: None, price: None, location: None**

------
The bot wants to [utter_on_it] due to the intent. Is this correct?

	1.	Yes
	2.	No, intent is right but the action is wrong
	3.	The intent is wrong
	0.	Export current conversations as stories and quit
```
**Content of domain file** (if used & relevant):

```
I used ALL example files - no changes from my side.
```

It's absolutely obfuscated for me, I can't go forward. Because, it didn't work. I'm in an evaluating period for rasa (company driven).

BTW: In some circumstances, the example-bot asked me several times "what kind of cuisine would you like?" my answer: "Mexican" and system repeated and repeated every time the same.

Please help me.

Regards Bernd

**Comment by akelad** [comment]
It seems the NLU model isn't loaded properly, and so the intents aren't being parsed. Have you tried talking to the bot normally, without training online?

**Comment by mrRobot62** [comment]
python bot.py train-nlu
2018-07-23 10:18:58 INFO     rasa_nlu.training_data.loading  - Training data format of data/franken_data.json is rasa_nlu
2018-07-23 10:18:58 INFO     rasa_nlu.training_data.training_data  - Training data stats: 
	- intent examples: 1977 (6 distinct intents)
	- Found intents: 'deny', 'thankyou', 'request_info', 'affirm', 'greet', 'inform'
	- entity examples: 1030 (5 distinct entities)
	- found entities: 'info', 'cuisine', 'price', 'location', 'people'

> RuntimeError: module compiled against API version 0xb but this version of numpy is 0xa
> RuntimeError: module compiled against API version 0xb but this version of numpy is 0xa
2018-07-23 10:19:02 INFO     rasa_nlu.utils.spacy_utils  - Trying to load spacy model with name 'en'
2018-07-23 10:19:03 INFO     rasa_nlu.components  - Added 'nlp_spacy' to component cache. Key 'nlp_spacy-en'.
2018-07-23 10:19:04 INFO     rasa_nlu.model  - Starting to train component nlp_spacy
2018-07-23 10:19:17 INFO     rasa_nlu.model  - Finished training component.
2018-07-23 10:19:17 INFO     rasa_nlu.model  - Starting to train component tokenizer_spacy
2018-07-23 10:19:17 INFO     rasa_nlu.model  - Finished training component.
2018-07-23 10:19:17 INFO     rasa_nlu.model  - Starting to train component intent_featurizer_spacy
2018-07-23 10:19:17 INFO     rasa_nlu.model  - Finished training component.
2018-07-23 10:19:17 INFO     rasa_nlu.model  - Starting to train component intent_classifier_sklearn
Fitting 2 folds for each of 6 candidates, totalling 12 fits
[Parallel(n_jobs=1)]: Done  12 out of  12 | elapsed:    4.7s finished
2018-07-23 10:19:23 INFO     rasa_nlu.model  - Finished training component.
2018-07-23 10:19:23 INFO     rasa_nlu.model  - Starting to train component ner_crf
2018-07-23 10:19:26 INFO     rasa_nlu.model  - Finished training component.
2018-07-23 10:19:26 INFO     rasa_nlu.model  - Starting to train component ner_synonyms
2018-07-23 10:19:26 INFO     rasa_nlu.model  - Finished training component.
2018-07-23 10:19:26 INFO     rasa_nlu.model  - Successfully saved model into '/Users/bernhardklein/Public/local-workspace/machine_learning/rasa/rasa_core/examples/restaurantbot/models/nlu/default/current'


Is this "RuntimeError: module compiled against API version 0xb but this version of numpy is 0xa"
reason for my problems?
Should I reinstall numpy - or what should I do?

**Comment by mrRobot62** [comment]
************ with run ********************
$ >make run
python bot.py run
RuntimeError: module compiled against API version 0xb but this version of numpy is 0xa
RuntimeError: module compiled against API version 0xb but this version of numpy is 0xa
2018-07-23 10:23:47 INFO     rasa_nlu.components  - Added 'nlp_spacy' to component cache. Key 'nlp_spacy-en'.
Using TensorFlow backend.
2018-07-23 10:23:47.942733: I tensorflow/core/platform/cpu_feature_guard.cc:140] Your CPU supports instructions that this TensorFlow binary was not compiled to use: AVX2 FMA
/Users/bernhardklein/Library/Python/2.7/lib/python/site-packages/pykwalify/core.py:99: UnsafeLoaderWarning: 
The default 'Loader' for 'load(stream)' without further arguments can be unsafe.
Use 'load(stream, Loader=ruamel.yaml.Loader)' explicitly if that is OK.
Alternatively include the following in your code:

  import warnings
  warnings.simplefilter('ignore', ruamel.yaml.error.UnsafeLoaderWarning)

In most other cases you should consider using 'safe_load(stream)'
  data = yaml.load(stream)
Bot loaded. Type a message and press enter: 
hi
how can I help you?
looking for a mexican restaurant
I'm on it
where?
nyc
for how many people?
2
in which price range?
1: cheap (cheap)
2: expensive (expensive)
2
if you'd like to modify anything else, please tell me what
no it's ok
ok let me see what I can find
looking for restaurants
here's what I found:
papi's pizza place
is it ok for you? hint: I'm not going to find anything else :)

*********** with train_online ****************
If I do same on training_online, it didn't work.
`def train_online(domain_file="restaurant_domain.yml",
                   model_path="models/dialogue",
                   training_data_file="data/babi_stories.md"):
    agent = Agent(domain_file,
                  policies=[MemoizationPolicy(max_history=3),
                            RestaurantPolicy()])

    training_data = agent.load_data(training_data_file)
    agent.train_online(
            training_data,
            epochs=400,
            batch_size=100,
            validation_split=0.2
    )

    agent.persist(model_path)
    return agent
`

Is this wrong?

**Comment by akelad** [comment]
Looks like you're not loading any NLU model, you need to provide it like this: https://github.com/RasaHQ/rasa_core/blob/master/rasa_core/train.py#L118
Please upgrade to 0.10.2 though, because there was a bug with the loading of the NLU model previously

**Comment by akelad** [comment]
there's no warning because you can also do online training in regex mode if you're just trying to test the performance of Core rather than also NLU. That means directly passing intents with things like `/greet`. I do see that a warning might be useful though, I'll keep that in mind. 
I'm going to close this issue now since the original problem is solved, and we're also discussing this via email :D If you encounter any different issues please open a new one
