### ISSUE TITLE
Are sorted intents with confidence score in `intent ranking` used for dialogue management (rasa_core)?

### ISSUE THREAD

**Issue by nicolaskodak** [RasaHQ/rasa_core#790]
**Rasa Core version**:
0.10.0
**Python version**: 
2.7.12
**Operating system** (windows, osx, ...):
Linux Ubuntu 16.04.1 LTS

**Issue**:
Hi, this is more of a question than an issue. When I looked at the nlu output, it has `intent_ranking` such as 
```...
intent_ranking":[
    {
        "confidence":0.7,
        "name":"intent1"
    },
    {
        "confidence":0.2,
        "name":"intent2"
    }
]
...
```

Afaik, rasa_core takes a featurized input composed of intents, entities, slots and previous system actions, but there doesn't seem any room for sorted intents. I wonder **if such information of intent ranking is used by dialogue manager when predicting system action?** If so, could you possibly point me to any reference/document for it? If not, I wonder **if there's any latest thinking about using sorted intents in rasa_core so it's statistically possible to correct mistakes (top-1 nlu ouput has wrong intents, wrong entities, etc.)**?

Thanks in advance. Both rasa_core and rasa_nlu are decent projects and they make dialogue system more accessible.

**Content of domain file** (if used & relevant):
```yaml

```

**Comment by akelad** [comment]
It's currently not used when predicting the next system action, no. Could you explain how you would use it to correct mistakes?

**Comment by rusiaaman** [comment]
This is one of the limitations of rasa_core. Since during training time it only sees the perfect values (of intents and entities), the trained policy wouldn't work well in real scenario of unsure intents. That's why the code forces the best intent's confidence = 1.0. The issue stems from the fact that the NLU is completely absent from Dialogue training. The trainer would have to be completely rewritten to take into account probabilistic intents and entities.

**Comment by nicolaskodak** [comment]
Agree with rusiaaman based on my understanding of rasa_core. Thanks for all the replies. I believe we can close this issue.

**Comment by akelad** [comment]
with "unsure intents" - we do have a fallback policy that handles this kind of problem, not sure if you've seen it: http://rasa.com/docs/core/fallbacks/
In other words that does pay attention to the confidence of NLU

If I understand correctly, what you're suggesting is more of an end-to-end approach no?

**Comment by nicolaskodak** [comment]
@akelad  yes what I suggested is more of an end-to-end approach for dialogue manager to predict the next action using top-n nlu outputs (intents, entities).
