### ISSUE TITLE
Rasa integration with Skype : connector does not exist

### ISSUE THREAD

**Issue by arcontechnologies** [RasaHQ/rasa_core#794]
**Rasa Core version**:
0.9.8
**Python version**: 
3.6
**Operating system** (windows, osx, ...):
Windows 10
**Issue**:
As far as I can see, there is no channel connector for Skype where it is by far one of the most used in big companies. Why you didn't build a connector for Skype ? is it so difficult ? is there any showstopper ?
Because of this lack of connector, I'm obliged to replace rasa_core with microsoft bot framework.
are you expecting to provide something or there is no chance ?

**Comment by tupac56** [comment]
I worked on a connector for Microsoft Teams using Bot Framework ([see this PR](https://github.com/RasaHQ/rasa_core/pull/576)). And Skype Entreprise also work with Bot Framework.

**Comment by arcontechnologies** [comment]
Seems there is a solution. I just went through Azure and I could create a channel with endpoint. 
![image](https://user-images.githubusercontent.com/17960609/43141297-dd56d6c6-8f55-11e8-9933-bb3c840296f1.png)

So if I'm able to connect Microsoft webchat to my Rasa Bot then the integration is done via Azure with Skype as here below

![image](https://user-images.githubusercontent.com/17960609/43141509-59fbb642-8f56-11e8-90f9-98a4b5866691.png)

My question (I'm not a web guy) : what kind of http endpoint connector should I have to achieve this ?

**Comment by tupac56** [comment]
In the Bot Framework [webpage](https://dev.botframework.com/), try to configure your messaging endpoint with this endpoint: ngrok_url/api/messages, which is the one used in Teams connector.

**Comment by tupac56** [comment]
Hi there! 
The name "teams" has been changed, make sure you import the module by doing `from rasa_core.channels.botframework import BotFrameworkInput`
Cheers

**Comment by arcontechnologies** [comment]
Got it. Thanks

**Comment by akelad** [comment]
Nice, thanks @tupac56 !
