### ISSUE TITLE
Multiple Intent sharing a single entity?

### ISSUE THREAD

**Issue by ParthPatel25** [RasaHQ/rasa_core#796]
**Rasa Core version**: 0.8.2

**Python version**:  3.6

**Operating system** (windows, osx, ...): Windows

**Issue**: I want to share the same entity for two different intents. Whenever I fill a slot for a particular entity,  it will pick the wrong intent. How do I go about it in order for Rasa to stay consistent with the intent?
For example, I have an e-commerce bot that handles two intents. 1. Purchase an item and 2. Return an item. These intents share the same entity, which is "item". Whenever I give the value in the item it's not picking the right intent and because of that, it makes wrong actions.

## Story - Purchase an item
* Purchace{"service": "purchase"}
    - slot{"service": "purchase"}
    - utter_ask_item
* Purchace{"item": "PS4"}
    - slot{"item": "PS4"}
    - action_purchase_item

## Story - Return an item
* Return{"service": "return"}
    - slot{"service": "return"}
    - utter_ask_item
* Return{"item": "PS4"}
    - slot{"item": "PS4"}
    - action_return_item

Example:
user ===> I want to purchase something
bot ===> okay, what item do you want?
user ===>PS4
bot ===> Thank you for returning the item.

**Content of domain file** (if used & relevant):
```YAML

```

**Comment by auzair92** [comment]
Personally, I'd modify that story to avoid re-using the same intent (you are re-using intents `Purchase` and `Return` for different user inputs). How about introducing a new intent for obtaining the item form user `GetItem` like this:

```
* Return{"service": "return"}
  - slot{"service": "return"}
  - utter_ask_item
* GetItem{"item": "PS4"}
  - slot{"item": "PS4"}
  - action_return_item
```
... and something similar for `Purchase`.

As a side-note, you should also consider cases where user provides both `service` and `item` in the same sentence. Like, `I want to return PS4`.

**Comment by auzair92** [comment]
You could consider adding more stories and more training examples to improve intent recognition. Also, can you double-check the body of the actions `action_purchase_item` and `action_return_item`?

**Comment by akelad** [comment]
You should introduce a third intent that's called something like `provide_item` for the case where you enter items like the PS4, that should avoid NLU conflict between the two intents. 
Another thing you can change is that for the case of the return and purchase intent, you don't need an entity for the service, since you're already distinguishing based on intent. 
So then you would have stories like this:
```
## purchase an item
* purchase
  - utter_ask_item
* enter_item{"item":"PS4"}
  - slot{"item":"PS4"}
  - action_purchase_item

## return an item
## purchase an item
* return
  - utter_ask_item
* enter_item{"item":"PS4"}
  - slot{"item":"PS4"}
  - action_return_item
```

**Comment by ParthPatel25** [comment]
If you have a separate intent just to fill the parameter slot(s), how would we structure our training phrases in our md file? For example, I imagine that a user would say something like "I want to return my PS4". If that training phrase goes into the `provide_item` intent then obviously rasa nlu will automatically assume that the intent is `provide_item`.  Wouldn't we want rasa to assume the `return` intent? 
Also, in my project, I have one action for both intents. This action would be called `action_transfer_item` which is essentially conjoining the `action_purchase_item` and `action_return_item`. Would it be better to have two separate actions for each intent like what is listed in the example `action_purchase_item` and `action_return_item`? I just wanted to point out in the case for a more accurate response, my action file `actionTransferItem` contains a series of if-else statements that account for both `return` and `purchase` intents.

**Comment by akelad** [comment]
You can still have this third intent, you would structure it something like this:
```
# intent:return
I want to return my [PS4](item)

# intent: return
I want to purchase a [PS4](item)

# intent: provide_item
[PS4](item)
```

So this intent would only be for providing information when it's ambiguous as to whether it's a return or purchase. So it could also be like "It's a PS4" or similar.

As for your actions question, no it's completely fine to have actions separately as you do now

**Comment by Chaithra-SA** [comment]
hey @akelad can we create secondary intents using rasa platform...That means, we will be having one main intent, which may have many other secondary intents..is it possible to do that?

**Comment by amn41** [comment]
@Chaithra-SA can you please provide an example of what you mean?

**Comment by reza-ebrahimi** [comment]
@amn41 @akelad 

Same question, I have three intents:
```markdown
- ask_restaurant
- ask_hospital
- ask_school
```
So we want to use same `city` entity in intents above, Which should be
```markdown{"city":"Tehran"}
- ask_restaurant{"city":"Tehran"}
- ask_hospital{"city":"Tehran"}
- ask_school{"city":"Tehran"}
```
We have listed around 50 cities and want to declare them for once not per intent.

**Comment by akelad** [comment]
So I'm afraid you do have to provide examples for each intent for now. But, this PR should help extract those cities, if you have a specified list: https://github.com/RasaHQ/rasa_nlu/pull/1312
