### ISSUE TITLE
Bug in SimplePolicyEnsemble probability normalization

### ISSUE THREAD

**Issue by benjamin-work** [RasaHQ/rasa_core#800]
**Rasa Core version**:
master

**Python version**: 
3.6

**Operating system** (windows, osx, ...):
Ubuntu

**Issue**:

I believe there is a bug in this line: https://github.com/RasaHQ/rasa_core/blob/e5a5404916ebaae1b425b3d6f20a191c5727caa8/rasa_core/policies/ensemble.py#L223

The intent is to have the probabilities sum to 1 but this is not what `np.linalg.norm` does by default. A better solution would be:

`result = result / np.sum(result)`

This is especially problematic for lines like this:

https://github.com/RasaHQ/rasa_core/blob/master/rasa_core/policies/fallback.py#L105

since dividing by L2-norm can lead to probabilities > 1.

Furthermore, in the [line above](/blob/e5a5404916ebaae1b425b3d6f20a191c5727caa8/rasa_core/policies/ensemble.py#L222), comparing floats with `==` is not advisable, better use `np.isclose`.

**Comment by Ghostvv** [comment]
Thanks for creating this issue, @tmbo will get back to you about it soon.

**Comment by tmbo** [comment]
@benjamin-work These are very valid points :+1: - I also don't think there is a need for the `norm`. I think @akelad you added that line, is there a reason we can't use `sum`?

It would be great if you could create a PR for this :rocket:

**Comment by benjamin-work** [comment]
One reason I can think of for not using `sum` is when `nan`s can be present in the vector. Then `np.nansum` and or an explicit check for `nan` could be uesful.

**Comment by tmbo** [comment]
Yes, so we should handle at least `None` as a value

**Comment by akelad** [comment]
no i'm not sure why i used that. @benjamin-work are you creating a PR for this?

**Comment by benjamin-work** [comment]
@akelad I'm currently short on time, so it's unlikely I could start this week.

**Comment by akelad** [comment]
@benjamin-work i'm just gonna take care of it in a PR i'm working on at the moment 🙂
