### ISSUE TITLE
set topic

### ISSUE THREAD

**Issue by yuxuan2015** [RasaHQ/rasa_core#804]
how to set the topic for the dialogue
![screenshot from 2018-07-27 10-02-27](https://user-images.githubusercontent.com/15645056/43297633-0edcbf40-9185-11e8-99b6-7c6b87a645ee.png)

**Comment by amn41** [comment]
This was an experimental feature which has since been removed. If you would like to keep track of a topic, one idea would be to set it as a slot.

**Comment by yuxuan2015** [comment]
if the user suddenly inserts another sentence in the normal process, if it is not controlled, it will continue according to the normal process, and there will be a situation in which the answer is not asked, so it is necessary to control the state of the conversation. How to solve it?
