### ISSUE TITLE
Control the tracks of dialogue

### ISSUE THREAD

**Issue by yuxuan2015** [RasaHQ/rasa_core#810]
If the user suddenly inserts another sentence in the normal process, if it is not controlled, it will continue according to the normal process, and there will be a situation in which the answer is not asked, so it is necessary to control the state of the conversation. How to solve it?

**Comment by matheusmatos** [comment]
Hello @yuxuan2015,

Can you provide more details about your issue? The Rasa Core will try to maintain the user in a story whenever possible; but if the user types something different, it will access an unknown path.

Whatever, you can still get the state of the conversation at any time using `tracker.current_state()` inside a custom action. Also, you can control the state sending events for the Dialogue State Tracker. You can get more details about that here: http://core.rasa.com/api/tracker.html

If nothing of that helps you, please let me know.

**Comment by yuxuan2015** [comment]
if normal process is as follow
YOU：hi
BOT：hi,what can I do for you?
YOU：What's the weather today?
BOT：fine

user suddenly inserts "who?",it will appear as below
YOU：hi
BOT：hi,what can I do for you?
YOU：who?
BOT：fine
@matheusmatos

**Comment by akelad** [comment]
You need to define some stories/intent training data to handle these kinds of cases
