### ISSUE TITLE
Comment out in stories only works for single line

### ISSUE THREAD

**Issue by Krogsager** [RasaHQ/rasa_core#812]
**Rasa Core version**: 0.10.2

**Python version**: 3.6.6

**Operating system**: Linux

**Issue**:
Comments in stories.md only work for single lines. If I comment out multiple lines I get warnings during core.train and the the training will fail.
> WARNING  rasa_core.domain - Failed to use action '->' in history. Please make sure all actions are listed in the domains action list. If you recently removed an action, don't worry about this warning. It should stop appearing after a while.

Comment that works:
``` ##story_1                     <!-- name of the story - just for debugging --> ```

Comment that does not work
```
<!--##story_greet
* int_greet
   - act_inquire_user_name
* int_my_name{"ent_user_name": "Anders"}
   - act_utter_greet

USING INT_GREET FOR ##force_likert -->
```

**Comment by matheusmatos** [comment]
Hello @Krogsager.

In fact, the stories file don't support comments. When you create a new story preceding the line with two hashes, everything after that is just for debugging. The following examples has the same effect:

```
## MyStory <!-- comment -->
## MyStory // comment
##story_greet and a comment
```

You can still create a story without any text after the two hashes:

```
##
* int_greet
   - act_inquire_user_name
* int_my_name{"ent_user_name": "Anders"}
   - act_utter_greet
```

This is why you are not receiving any warnings with your first example.
I hope it helps!

**Comment by Krogsager** [comment]
Thanks for the info. I think comments would be a good feature while developing stories, for testing and debugging variations. Consider that a feature request ;-) 
So for now I will probably write my own pre-processor.

**Comment by matheusmatos** [comment]
I think it would be a great feature too. I'm developing now a pre-processor to allow writing stories in a programmatic way. Something like that:

```
story = StoriesBuilder()

if story.is_intent('greeting'):
    story.do_action('actions.GreetingAction')
    story.utter('utter_greeting_default')

    ## Happy Path
    if story.is_intent('confirm'):
        story.utter('utter_confirm')
        story.end()

    ## Sad Path
    if story.is_intent('deny'):
        story.utter('utter_deny')
        story.end()

    story.end() # end the global story
```

I don't know yet if it will be a better way to write stories :grimacing:

**Comment by Krogsager** [comment]
Interesting! I hope you'll post an update when it is tested.
I've also written a tool that compares all intents, actions, entities etc. across nlu/domain/story files and checks for missing or misspelled names. It is pretty effective but also a hard mistress.
I'm thinking of sharing it somewhere on github so other rasa developers can use it. I just don't know where.

**Comment by tmbo** [comment]
@Krogsager just saw this, that sounds like something really cool :+1: - would be great if you can share it or even create a PR

**Comment by Krogsager** [comment]
@tmbo 
I hope to have a bit of time before the end of October for documenting and sharing the script.

**Comment by tmbo** [comment]
that sounds great - looking forward to it :rocket:

**Comment by Krogsager** [comment]
@tmbo 
Completely beta.
https://github.com/Krogsager/rasa_inspection/blob/master/inspector.py
