### ISSUE TITLE
 Documentation Form Action import

### ISSUE THREAD

**Issue by NicoHood** [RasaHQ/rasa_core#819]
Some information is missing in the docs:
https://core.rasa.com/patterns.html?highlight=formaction

There is an example `class ActionSearchRestaurants(FormAction):` which seems to be the only FormAction example in the whole documentation. The problem I've got is that the imported modules are missing. And `from rasa_core.actions import FormAction` is not working: `ImportError: cannot import name 'FormAction'`

**Comment by NicoHood** [comment]
The missing piece seems to be
```python
from rasa_core.actions.forms import (
    BooleanFormField,
    EntityFormField,
    FormAction,
    FreeTextFormField
)
```

Please add this to the docs ;)

**Comment by akelad** [comment]
Thanks, we'll take a note of this and add it :)

**Comment by vinaynagpal9** [comment]
sorry but this is not working

Traceback (most recent call last):
  File "actions.py", line 8, in <module>
    from rasa_core.actions.forms import (
ModuleNotFoundError: No module named 'rasa_core.actions.forms'

**Comment by akelad** [comment]
I assume you've recently migrated to 0.11, please refer to our migration guide and the forms docs: https://rasa.com/docs/core/migrations/

**Comment by FRTNX** [comment]
@akelad what has become of ````from rasa_core.actions.forms import EntityFormField``` The migrations page in the link above makes no mention of them

**Comment by FRTNX** [comment]
Nevermind. Found it after running a grep search. 
```from rasa_core.actions.forms import (
    BooleanFormField,
    EntityFormField,
    FormAction,
    FreeTextFormField
)``` 
is now
```from rasa_core_sdk.forms import (
    BooleanFormField,
    EntityFormField,
    FormAction,
    FreeTextFormField
)```
