### ISSUE TITLE
Question about setting slots values from tracker

### ISSUE THREAD

**Issue by mephistopheies** [RasaHQ/rasa_core#833]
In the current dev version, whenever core receives an SlotSet event, a function 
```
def apply_to(self, tracker):
        tracker._set_slot(self.key, self.value)
```
is called, if we look at tracker
```
def _set_slot(self, key, value):
        # type: (Text, Any) -> None
        """Set the value of a slot if that slot exists."""

        if key in self.slots:
            self.slots[key].value = value
```
we see that the value is just assigned to a slot's `value`.

Now let's assume that I want to have kind of TimeSlot, which has Time data structure as value instead of string. I expect that I can inherit Slot class, add there a logic to convert string (extracted by NLU) to certain data type, and assign it to `value` of a slot. Is there any RASA way how to do it?

Imho, `Slot` should have a function like `set_value(string value)` which returns True if values is set up, or false. And tracker should call `self.slots[name].set_value(value)`. And base slot class `Slot` can contain trivial implementation:

```
def set_value(self, value):
    self.value = value
    return True
```

**Comment by akelad** [comment]
Thanks for raising this issue, @Ghostvv will get back to you about it soon.

**Comment by Ghostvv** [comment]
Sorry, for long response. Because the slots should be serializable, we use extracted `string` as `value`. I would suggest to use custom slots and set time in different attribute, and then use this attribute in your custom action.

**Comment by mephistopheies** [comment]
@Ghostvv right now there are only a few types of slot in the package, what do you think about adding an abstract class kind of `RasaDataType` which has two functions `serialize(self) -> string` and `deserialize(string) -> RasaDataType`, then to implement these functions for existing types (string, float, category) and then call them whenever you are serializing slots?

for me as a user of rasa, I may be wrong and such vision diverges with your strategy, it looks more convenient if I add new data type `class TimeType(RasaDataType)` and `class TimeSlot(Slot)` and put all logic inside `TimeSlot` rather then add one more layer which at some point does conversion from string to required data types

let me give an example, I'm implementing booking room scenario, I have among other parameters two slots `booking_time` and `booking_duration`; whenever user says something like `I want to book a room tomorrow at 3` there is to duration and bot asks duration, then it see that we have all the required data to make a booking and try to convert string to the required data types and eventually fails; then I need to rollback discussion somehow

if I would be able to implement `string -> time` logic inside time slot, then if a bot can't parse data, it doesn't fill the slot with not parsed value and I expect the bot to refine time

if you agree with this, you can point me where you do serialization of slots and I will write all of this

or close it and I will have to add some костыли into my code -)

**Comment by Ghostvv** [comment]
костыли - отлично

**Comment by tmbo** [comment]
I am not sure if this is a good idea: We are working on a larger refactoring of rasa core, that will split the machine learning parts and the custom actions into two independent parts communicating over http. In this version, the slots are set on the action server, after that they are serialised and sent to core. the custom slot implemented lives on the core server, as the main idea of custom lots is featurization. 

so even if you would implement your custom slot in core, your action server would still need to serialise / deserialise your slot, but won't have your custom slot. do you know what i mean`?

**Comment by mephistopheies** [comment]
Thanks for the response, looking forward for a _larger refactoring of rasa core_ -)
