### ISSUE TITLE
Where to write the script for slot filling? 

### ISSUE THREAD

**Issue by gagan2103** [RasaHQ/rasa_core#835]
**Rasa Core version**: 0.10

**Python version**: 3.6

**Operating system** (windows, osx, ...): LINUX

**Issue**: can not able to fill the slots using script. where to write the script that will fill the slots properly.

**Comment by akelad** [comment]
Could you provide some more details on what's not working?

**Comment by pragya-96** [comment]
can anybody help me with the code of slot filling

**Comment by akelad** [comment]
I still need some more details on the exact issues you're having to be able to help 🙂 please provide some examples of your code and what's not working
