### ISSUE TITLE
Core HTTP Server - why not implement full responses?

### ISSUE THREAD

**Issue by MartinGentleman** [RasaHQ/rasa_core#843]
**Rasa Core version**:
0.9.3
**Python version**: 
3.6.6
**Operating system** (windows, osx, ...):
OSX
**Issue**:
For HTTP Server https://core.rasa.com/http.html the page states: The general idea is to run the actions within your code (arbitrary language), instead of python.

Why though is there no support for full HTTP API that would not just respond with next_action but actually executed the action and provided the result? I mean I can build a solution on top of Rasa Core and be implementing the response system and actions separately. It just seems strange that the ability is within Rasa Core but it is not exposed to the server.
Is there architecture within Rasa Core making that difficult? Are you planning to add the feature? Or am I welcome to submit a pull request adding the feature?

**Comment by auzair92** [comment]
If you're talking about custom Python actions whose result is forwarded via HTTP API, then this functionality is definitely available right now. The [`parse`](https://core.rasa.com/http.html#post--conversations-(str-sender_id)-parse) endpoint simply parses user input and responds with next action, but you can use a combination of [`continue`](https://core.rasa.com/http.html#post--conversations-(str-sender_id)-continue) and [`respond`](https://core.rasa.com/http.html#post--conversations-(str-sender_id)-respond) endpoints to execute custom actions written in Python as well. These actions shall be executed on the server side.

**Comment by akelad** [comment]
@MartinGentleman does that answer your question or do you need more clarification?

**Comment by amn41** [comment]
there is a `/respond` endpoint which does what you want

**Comment by MartinGentleman** [comment]
Yes I made it work, thank you. I had to find out that I cant use `action_factory: remote`, because the server would be just returning [] for `/respond`. Once I tried it without it, I can see basic utterances as well as action results.
