### ISSUE TITLE
Cannot debug custom actions without restarting interpreter

### ISSUE THREAD

**Issue by imohitmayank** [RasaHQ/rasa_core#849]
Rasa core version:   0.10.2
Python version: 3.6
OS: Windows 10

Issue: After training the dialog and reloading the agent, handle_message shows old issue(which is fixed now)

**Dialog training code:**
```
def train_dialog(dialog_training_data_file, domain_file, path_to_model = 'models/dialogue'):
    logging.basicConfig(level='INFO')
    featurizer = MaxHistoryTrackerFeaturizer(BinarySingleStateFeaturizer(),
                                         max_history=1)
    agent = Agent(domain_file,
              policies=[MemoizationPolicy(max_history=1)
#                         KerasPolicy(featurizer)
                       ])
    training_data = agent.load_data(dialog_training_data_file)
    agent.train(
        training_data,
        augmentation_factor=50,
        epochs=200,
        batch_size=10,
        validation_split=0.2)
#     agent.visualize("domain.yml", output_file="graph.png", max_history=5)
    agent.persist(path_to_model)
```

**Loading and running agent:**
```
rasaNLU = RasaNLUInterpreter("models/nlu/default/chat")
agent = Agent.load("models/dialogue", interpreter= rasaNLU)
agent.handle_message('what is the time?')
```

Here, initially I am getting error because of syntax error on custom action python script, which is called on the used message's intent. Now after fixing the syntax and repeating the above steps to re-load the dialog, NLU and utter message, I am getting the same error message as before on same line, which is now fixed. 

Any Ideas?

**Comment by akelad** [comment]
Can you post the error message and also your custom action code please?

**Comment by imohitmayank** [comment]
The custom action file goes like this,  (before correction)
**bot.py**:
```
from rasa_core.actions import Action
from rasa_core.events import SlotSet
class searchJob(Action):
	def name(self):
		return 'action_search'

	def run(self, dispatcher, tracker, domain):
                value = [1,2,3,4]
		ans = "length is" +  str(length(value))
		dispatcher.utter_message(ans)	
		return []
```
The error message was, `NameError: name 'length' is not defined @ line 9`

Modified the syntax `length `to `len`.

Now on re-training the dialog, loading the agent and passing message gives same error, points to same line i.e. `NameError: name 'length' is not defined @ line 9`; but I have already replace that with `len`

Whereas restarting the interpreter and performing training, agent loading and message passing works.

**Comment by akelad** [comment]
Yes this is expected behaviour, the custom action fix will only work once you've reloaded the bot. You don't need to retrain though
