### ISSUE TITLE
REST API - How to set intents

### ISSUE THREAD

**Issue by jonDel** [RasaHQ/rasa_core#856]
**Rasa Core version**:
rasa-core           0.9.8

**Python version**: 
Python 3.6.6 :: Anaconda, Inc.

**Operating system** (windows, osx, ...):
Fedora Linux

**Issue**:

In interactive training mode, when using buttons, it's easy to set a slot and force an intent to be fired, using the RegexInterpreter, like this:
```
/intent_name{"entity_name":"entity_value"}
```
How can I do the same when using the REST api and own NLU trained model as the interpreter?

**Comment by amn41** [comment]
@jonDel it should work just the same - if rasa core sees a message starting with `/`, it'll pass it to the regexinterpeter, otherwise it'll go to the interpreter you've loaded. See here https://github.com/RasaHQ/rasa_core/blob/master/rasa_core/interpreter.py#L20

**Comment by jonDel** [comment]
Thanks! That worked fine.
