### ISSUE TITLE
Cannot run the bot

### ISSUE THREAD

**Issue by samrudh** [RasaHQ/rasa_core#858]
**Rasa Core version**: 0.10 1

**Python version**: 3.6

**Operating system** (windows, osx, ...): osx

**Issue**:
When I ran bot after training the bot, it says bot loaded type message.
However if I type anything (eg. Hi, Hello) it goes in infinite hand state.

All files like domain.md, nlu.md are copied from quickstart [here](http://rasa.com/docs/core/quickstart/)

**Content of domain file** (if used & relevant):
```yaml

```

**Comment by akelad** [comment]
Can you post some more details? What command did you run to start it, did you train both the nlu + core models?

**Comment by samrudh** [comment]
Added stories using:
1. python -m rasa_core.train -d domain.yml -s stories.md -o models/dialogue
Then Trained bot using 
2. python -m rasa_nlu.train -c nlu_config.yml --data nlu.md -o models --fixed_model_name nlu --project current --verbose
Running bot using
3. python -m rasa_core.run -d models/dialogue -u models/current/nlu

**Comment by akelad** [comment]
Ok can you run it in debug mode like here: http://rasa.com/docs/core/debugging/, and see what the logs say? You can post them here if you can't find the issue
