### ISSUE TITLE
Can not connect chatbot to fb

### ISSUE THREAD

**Issue by MinhMinnie** [RasaHQ/rasa_core#860]
**Rasa Core version**: 0.10.4

**Python version**: python3

**Operating system** (windows, osx, ...): Ubuntu

**Issue**: 
I can not connect my chatbot to fb messenger platform. I am using this command : python3 -m rasa_core.run -d models/dialogue -u projects/default/model_20180810-113049 --port 5002 --connector facebook --credentials fb_credentials.yml 

My fb_credentials.yml file: 
verify: “minh-bot” 
secret: $MY_SECRET
page-access-token: $MY_PAGE_ACCESS_TOKEN

I am using ngrok for local testing. when I set up webhook, ngrok gave me : GET /webhook 200 OK . but when I send messages from fb messenger, chat bot doesn’t reply

**Content of domain file** (if used & relevant):
```yaml

```

**Comment by akelad** [comment]
Thanks for creating this issue, @Ghostvv will get back to you about it soon.

Also I have removed your secret and page-access-token from your original issue -- you don't really want this to be publically available, as anyone can access your fb page now.

**Comment by Ghostvv** [comment]
Hi, could you please add more details did you specify your `webhook` in developers.facebook.com?Does your bot receive a message? What are the logs?

**Comment by MinhMinnie** [comment]
@Ghostvv  Yes, I have specified webhook. The bot can receive messages but it's not able to response. I captured screen where I take App secret and verify Callback URL.

![capture d ecran de 2018-08-13 15-25-34](https://user-images.githubusercontent.com/39526598/44031888-ae4a592e-9f05-11e8-910a-e8f89be4e91b.png)

![capture d ecran de 2018-08-13 15-29-37](https://user-images.githubusercontent.com/39526598/44031740-3d62022a-9f05-11e8-9478-d6085dd32678.png)

**Comment by Ghostvv** [comment]
Could you please paste the logs from the bot?

**Comment by MinhMinnie** [comment]
here is my rasa_core log:
/usr/lib/python3.6/importlib/_bootstrap.py:219: RuntimeWarning: numpy.dtype size changed, may indicate binary incompatibility. Expected 96, got 88
  return f(*args, **kwds)

/usr/lib/python3.6/importlib/_bootstrap.py:219: RuntimeWarning: numpy.dtype size changed, may indicate binary incompatibility. Expected 96, got 88
  return f(*args, **kwds)

/usr/lib/python3.6/importlib/_bootstrap.py:219: RuntimeWarning: numpy.dtype size changed, may indicate binary incompatibility. Expected 96, got 88
  return f(*args, **kwds)

/usr/lib/python3.6/importlib/_bootstrap.py:219: RuntimeWarning: numpy.ufunc size changed, may indicate binary incompatibility. Expected 192, got 176
  return f(*args, **kwds)

/home/minh/.local/lib/python3.6/site-packages/pykwalify/core.py:99: UnsafeLoaderWarning: 
The default 'Loader' for 'load(stream)' without further arguments can be unsafe.
Use 'load(stream, Loader=ruamel.yaml.Loader)' explicitly if that is OK.
Alternatively include the following in your code:

  import warnings
  warnings.simplefilter('ignore', ruamel.yaml.error.UnsafeLoaderWarning)

In most other cases you should consider using 'safe_load(stream)'
  data = yaml.load(stream)

**Comment by Ghostvv** [comment]
could you call `rasa_core.run` script with `--verbose` flag

**Comment by MinhMinnie** [comment]
here is the result : 
![capture d ecran de 2018-08-13 19-12-02](https://user-images.githubusercontent.com/39526598/44043762-f01c68a6-9f23-11e8-89ac-31d9ac185d8c.png)

**Comment by Ghostvv** [comment]
but you started command line script. could you run the script, you run for facebook, but wit `--verbose` flag?

**Comment by MinhMinnie** [comment]
sorry I uploaded the wrong one. 
![capture d ecran de 2018-08-14 10-44-20](https://user-images.githubusercontent.com/39526598/44078209-3bf08226-9fa6-11e8-9839-3ec57cbee9db.png)

**Comment by Ghostvv** [comment]
could you input message in fb and check what is logged

**Comment by MinhMinnie** [comment]
Here is what exactly I have done many times so far
Step1:
in fb_credentials.yml file:
verify: "minh-bot"
secret: I take the app secret here
![capture d ecran de 2018-08-14 11-33-21](https://user-images.githubusercontent.com/39526598/44080655-fbd656d2-9fac-11e8-8cec-7f5b25b36ffd.png)
page-access-token: in here
![capture d ecran de 2018-08-14 11-37-18](https://user-images.githubusercontent.com/39526598/44080843-88825e3c-9fad-11e8-8245-6fa060f44ead.png)
Step2 : I run this script:
python3 -m rasa_core.run -d models/dialogue -u projects/default/model_20180813-121815 --port 5002 --connector facebook --credentials fb_credentials.yml

and run ./ngrok http 5002 for local testing

Step 3 : Edit user subcription (verify token : minh-bot)
![capture d ecran de 2018-08-13 15-29-37](https://user-images.githubusercontent.com/39526598/44080973-dc16d334-9fad-11e8-87b3-f51a68dc337e.png)
Verify and save
Step4 : in put message in fb

**Comment by Ghostvv** [comment]
could you in step2: ```python3 -m rasa_core.run -d models/dialogue -u projects/default/model_20180813-121815 --port 5002 --connector facebook --credentials fb_credentials.yml --verbose```

Step5: check logs

**Comment by MinhMinnie** [comment]
yes, the result of 
Step2 :
![capture d ecran de 2018-08-14 11-52-26](https://user-images.githubusercontent.com/39526598/44081682-99d16e1a-9faf-11e8-8579-0712e648c793.png)
Step5:
![capture d ecran de 2018-08-14 11-51-49](https://user-images.githubusercontent.com/39526598/44081725-b2d170a4-9faf-11e8-88dc-12243082fe76.png)
![capture d ecran de 2018-08-14 11-51-11](https://user-images.githubusercontent.com/39526598/44081728-b5c1022a-9faf-11e8-83aa-3f22c1b1c058.png)

**Comment by akelad** [comment]
@MinhMinnie when you press "Verify and Save" does it save or does it show you an error message? Also, is the webhook also set under your Messenger settings like this?
<img width="961" alt="screen shot 2018-08-14 at 11 38 56" src="https://user-images.githubusercontent.com/32450038/44084317-ae070686-9fb6-11e8-9483-55dce4c810db.png">

Next, can you post your ngrok logs if that doesn't work

**Comment by MinhMinnie** [comment]
![capture d ecran de 2018-08-14 12-46-32](https://user-images.githubusercontent.com/39526598/44084602-6d723d1a-9fb7-11e8-9b4c-01f4c8b0f82b.png)
After I press "verify and save", it is properly saved 

here is ngrok logs
![capture d ecran de 2018-08-14 12-47-58](https://user-images.githubusercontent.com/39526598/44084649-8d1240f2-9fb7-11e8-84d1-589ce1f7c10e.png)

**Comment by akelad** [comment]
> Also, is the webhook also set under your Messenger settings like this?
<img width="961" alt="screen shot 2018-08-14 at 11 38 56" src="https://user-images.githubusercontent.com/32450038/44084317-ae070686-9fb6-11e8-9483-55dce4c810db.png">

**Comment by MinhMinnie** [comment]
yeah, exactly the same like this

**Comment by akelad** [comment]
@MinhMinnie any luck with this? (sorry I was on vacation)

**Comment by MinhMinnie** [comment]
@akelad  I think the problem was because I didn't update the information in Basic/settings page. After I updated, It works till now. you can close the post
