### ISSUE TITLE
Stories Stuck during execution

### ISSUE THREAD

**Issue by SemabAli** [RasaHQ/rasa_core#862]
**Rasa Core version**:
rasa-core (0.10.2)

**Python version**: 
2.7

**Operating system** (windows, osx, ...):
windows

**Issue**:
rasa_core stucks between stories i check separatly with rsa nlu intent identification is correct seems there is problem with rasa core story handling mechanism

*** this two action mostly stuck***********

class ActionOpenLastEncounters(Action):
     def name(self):
        return 'action_open_last_encounters'

    def run(self, dispatcher, tracker, domain):
        intent=tracker.latest_message.intent
        if tracker.get_slot('PERSON') is not None:
            name=tracker.get_slot('PERSON')
            myjson={"intent": intent["name"],"data": {'present': {'patientNameFilter': name}, 'missing': []}}
            dispatcher.utter_message(str(myjson))
            #dispatcher.utter_message("opening last encounter of "+name)
        else:
            myjson={"intent": intent["name"],"data": {'present': {}, 'missing': ['patientNameFilter']}}
            dispatcher.utter_message(str(myjson))
            #dispatcher.utter_message("Please specify Patient Name")
        return []

class ActionOpenEncounters(Action):
    def name(self):
        return 'action_open_encounters'

    def run(self, dispatcher, tracker, domain):
        intent=tracker.latest_message.intent
        if (tracker.get_slot('PERSON') is not None) and (tracker.get_slot('DATE') is not None):                
            date=tracker.get_slot('DATE')
            name=tracker.get_slot('PERSON')
            myjson={"intent": intent["name"],"data": {'present': {'patientNameFilter': name,'dateNameFilter': date}, 'missing': []}}
            dispatcher.utter_message(str(myjson))
            return_slots = []
            for slot in tracker.slots:
                if slot != "PERSON":
                    return_slots.append(SlotSet(slot, None))
            return return_slots
        elif (tracker.get_slot('DATE') is not None):
            date=tracker.get_slot('DATE')
            myjson={"intent": intent["name"],"data": {'present': {'dateNameFilter': date}, 'missing': ['patientNameFilter']}}
            dispatcher.utter_message(str(myjson))
            return_slots = []
            for slot in tracker.slots:
                if slot != "PERSON":
                    return_slots.append(SlotSet(slot, None))
            return return_slots
            #dispatcher.utter_message("Opening Encounter of "+date)
        elif (tracker.get_slot('PERSON') is not None): 
            name=tracker.get_slot('PERSON')
            myjson={"intent": intent["name"],"data": {'present': {'patientNameFilter': name}, 'missing': ['dateNameFilter']}}
            dispatcher.utter_message(str(myjson))
            #dispatcher.utter_message("Opening Encounter of "+name+" for "+date)
        else:
            myjson={"intent": intent["name"],"data": {'present': {}, 'missing': ['patientNameFilter','dateNameFilter']}}
            dispatcher.utter_message(str(myjson))
            #dispatcher.utter_message("Please specify Encounter details")
        
        return []

**Comment by SemabAli** [comment]
@tmbo 


![image](https://user-images.githubusercontent.com/30036324/44013843-9334f5aa-9ee1-11e8-9a34-2f5438d2ced2.png)

**Comment by SemabAli** [comment]
import argparse
import logging
from rasa_core.policies.keras_policy import KerasPolicy

from policy import AllisonPolicy
from rasa_core import utils
from rasa_core.actions import Action
from rasa_core.agent import Agent
from rasa_core.channels.console import ConsoleInputChannel
from rasa_core.events import SlotSet
from rasa_core.featurizers import (MaxHistoryTrackerFeaturizer,BinarySingleStateFeaturizer)
from rasa_core.interpreter import RasaNLUInterpreter
from rasa_core.policies.memoization import MemoizationPolicy,AugmentedMemoizationPolicy
from rasa_core.policies.fallback import FallbackPolicy
logger = logging.getLogger(__name__)
fallback = FallbackPolicy(fallback_action_name="utter_default",core_threshold=0.2,nlu_threshold=0.2)

def train_dialogue(domain_file="allison_domain.yml",model_path="models/dialogue/sibtain/",training_data_file="data/independent.md"):
    agent = Agent(domain_file,policies=[AugmentedMemoizationPolicy(max_history=1),AllisonPolicy(),fallback])
    training_data = agent.load_data(training_data_file)
    agent.train(training_data,epochs=8,batch_size=5,validation_split=0.2) 
    agent.persist(model_path)
    return agent


def train_nlu():
    from rasa_nlu.training_data import load_data
    from rasa_nlu import config
    from rasa_nlu.model import Trainer

    training_data = load_data('data/merged_data.json')
    trainer = Trainer(config.load("entity_config.yml"))
    trainer.train(training_data,verbose=1)
    model_directory = trainer.persist('models/nlu/sibtain/',fixed_model_name="current")

    return model_directory

**Comment by akelad** [comment]
what do you mean by stuck? can you post your stories file and also run Core in debug mode? that should help tell you what's going on: http://rasa.com/docs/core/debugging/

**Comment by SemabAli** [comment]
Stuck means no response from rasa agent . Same story sometimes execute and sometimes stucks.I uploaded the screen shot. and here  is my stories file.


##1
* OpenSummary
    - slot{"PERSON": "Donald Trump"}
    - action_open_summary

##2
* LastImmunized
    - slot{"PERSON": "Donald Trump"}
    - action_last_immunized
    
##3
* OpenAddressBook
    - slot{"PERSON": "Donald Trump"}
    - action_open_address_book
    
##4
* OpenPatientList
    - slot{"PERSON": "Kumail Raza"}
    - action_open_patient_list

##5
* OpenPatientMessages
    - slot{"PERSON": "Kumail Raza"}
    - action_open_patient_messages 

##6
* OpenLastEncounters
    - slot{"PERSON": "Donald Trump"}
    - action_open_last_encounters

##7
* OpenHistory
    - slot{"PERSON": "Donald Trump"}
    - action_open_history

##8
* OpenProfile
    - slot{"PERSON": "Donald Trump"}
    - action_open_profile

##9
* OpenLastMedication
     - slot{"PERSON": "Donald Trump"}
     - action_open_last_medication

##10
* OpenDailyAppointment
     - action_open_daily_appointment

##11
* OpenAppointmentSetting
    - action_open_appointment_setting

**Comment by SemabAli** [comment]
This is  when agent does not give any response.

![image](https://user-images.githubusercontent.com/30036324/44025559-ea80d4a0-9f09-11e8-9c11-78e9d13a35bd.png)

**Comment by SemabAli** [comment]
This output is when model gives normal output 

![image](https://user-images.githubusercontent.com/30036324/44025837-a5a0bbe2-9f0a-11e8-9155-f3490e73b06b.png)

**Comment by akelad** [comment]
How are these slots getting set? the way you've written your stories makes it seem like the intent sets the slots, which doesn't seem possible as no entities are recognised. This is what's causing the predictions to be wrong

**Comment by SemabAli** [comment]
@akelad how is it possible intent sets slots. whats the right way can you correct one story? but slots are filled normally I checked. unable to understand your point.

**Comment by akelad** [comment]
It's not possible that intents set the slots, that's what I'm saying. I assume an entity gets picked up from a user utterance? This isn't captured in your stories anywhere, see: http://rasa.com/docs/core/stories/

**Comment by SemabAli** [comment]
now i changed my stories to this slots are filled but stucking problem is still there

##1
* OpenSummary
    - action_open_summary

##2
* LastImmunized
    - action_last_immunized
    
##3
* OpenAddressBook
    - action_open_address_book
    
##4
* OpenPatientList
    - action_open_patient_list

##5
* OpenPatientMessages
    - action_open_patient_messages

##6
* OpenLastEncounters
    - action_open_last_encounters

##7
* OpenHistory
    - action_open_history

##8
* OpenProfile
    - action_open_profile

##9
* OpenLastMedication
     - action_open_last_medication

##10
* OpenDailyAppointment
     - action_open_daily_appointment

##11
* OpenAppointmentSetting
    - action_open_appointment_setting

##12
* OpenReports
    - action_open_reports

##13
* AddEncounter
    - action_add_encounter

**Comment by akelad** [comment]
Have you looked at the link I sent you for the story format? If e.g. a PERSON entity is expected to be picked up from a user message, your story would have to look like this:
```
* OpenEncounters{"PERSON": "Kumail Raza"}
  - action_open_encounters
```

In any case since this is more of a question asking for advice, please post this in our [forum](https://forum.rasa.com)
