### ISSUE TITLE
Change default behaviour for utter_restart if it is not defined

### ISSUE THREAD

**Issue by tmbo** [RasaHQ/rasa_core#865]
Currently, if the bot is restarted and the bot doesn't have an utterance template for `utter_restarted` - the bot will utter something to the user like "Undefined utter template <utter_restarted>."

Instead, the bot should just not send any message to the user.

**Comment by victoriazm18** [comment]
So how can I avoid this message: "Undefined utter template <utter_restart>." In my stories I haven't used utter_restart, I have used action_restart. But the message appers and Im not sure if the dialogue was restarted or it wasn't.

**Comment by akelad** [comment]
it was restarted -- you can define the template `utter_restart` in your domain file and that message will be sent instead

**Comment by victoriazm18** [comment]
Thanks so much @akelad . Now it works as I need to.

**Comment by kothiyayogesh** [comment]
@akelad @tmbo Is there any way to silently end the conversation? i.e without keeping utter_restart template message in domain.yml and just keeping action_restart at the end of each story.

Alternatively, Can I achieve the same by keeping augmentation_factor=0?

PS: This will be useful when a particular flow is ended for e.g successfully fetching details or when user say goodbye.

**Comment by akelad** [comment]
This should be possible with 0.11 if you don't define an `utter_restart` template

**Comment by kothiyayogesh** [comment]
@akelad Is there any option to do in 0.13.x? 

Can you also tell me difference and similarity between utter_restart/action_restart and augmentation_factor? I couldn't understand clear difference.

**Comment by akelad** [comment]
0.13.x is the NLU version. The latest Core version is 0.11
`utter_restart` is the template, whereas action_restart is the action that actually restarts the conversation, and calls the `utter_restart` template. 
`augmentation_factor` doesn't relate to this, it's something used during training to augment your training data
