### ISSUE TITLE
Interactive learning as http server

### ISSUE THREAD

**Issue by jonDel** [RasaHQ/rasa_core#867]
**Rasa Core version**:
rasa-core           0.9.8

**Python version**: 
Python 3.6.6 :: Anaconda, Inc.

**Operating system** (windows, osx, ...):
Fedora Linux

**Issue**:

Is there a way to run the interactive learning as a http server? Or, at, least, call its components programmatically, instead of using the usual CLI?
Reasoning: I want to build a simple frontend boostrap interface, very similar to the one I'll use to effectivelly chat with the bot (https://github.com/jonDel/simple_chat_interface), but with the purpose of training it. Then, the boring part of training the bot could be delegated to non-technicians, who are of course not familiar with CLI or terminal interfaces.

**Comment by amn41** [comment]
@jonDel this will be possible in Rasa Core 0.11 which is coming out soon

**Comment by jonDel** [comment]
Thanks @amn41 !

**Comment by akelad** [comment]
It is run as an http server now, please take a look at this issue: #343
