### ISSUE TITLE
Prevent entites from automatically being picked up

### ISSUE THREAD

**Issue by derdanielb** [RasaHQ/rasa_core#871]
I am not sure if this a topic for rasa_core or rasa_nlu.
I stick with core since i am using _ActionForms_.

I am filling a few slots with an ActionForm. I also added a regex_feature to pick up a 'target' entity (e.g. pattern: A12345, B56789 ...).
During the _ActionForm_ i am using a _FreeTextFormField_ to collect the information from a topic submitted by the user, which can be anything. The 'target' entity/slot is requested before the topic slot.
Sometimes the topic can contain a target reference, which then is recognized as an entity. Unfortunately the 'target' entity picked up in the topic text overrides the 'target' entity, which was intentionally specified before.

Is there a way to prevent the entity recognition for a single user input?

**Comment by akelad** [comment]
Thanks for raising this issue, @JoeyFaulkner will get back to you about it soon.

**Comment by derdanielb** [comment]
Also, being able to prevent other intents from being triggered while filling slots in an _ActionForm_ would be great.

Like, if someone submits a topic (free text -> _FreeTextFormField_), which is only 'hi' triggers the greet intent in between.

**Comment by akelad** [comment]
Ok your second question will be solved with the new forms here: https://github.com/RasaHQ/rasa_core/pull/878

As for your first question, could this maybe be an NLU issue as well? if entities are getting picked up where they shouldn't. Could you provide some examples please?

**Comment by derdanielb** [comment]
Okay, a conversation goes like this: (target and topic are part of the ActionForm)

Bot (asking about meta data): What is the target?
User: save it to A12345
_entity 'target' (A12345) gets extracted correctly_
Bot: Now name the topic.
User: "Appointment regarding U84838"

_In this step a new entity 'target' (U84838) is recognized by the ner_crf and the old entity is replaced._

`Received user message 'Appointment regarding U84838' with intent '{'name': 'greet', 'confidence': 0.5265942391183036}' and entities '[{'start': 22, 'end': 28, 'value': 'u84838', 'entity': 'target', 'confidence': 0.9989859584038462, 'extractor': 'ner_crf'}]'`

Is this caused by the regex_feature? Since in the intent no entity was ever specified. Regardless of the intent that is recognized for the input of the _FreeTextFormField_ ('greet' intent in this example) .

**Comment by akelad** [comment]
No this isn't because of the regex feature, it's because those two words are very similar. Entities aren't strict to one particular intent, but can be picked up in any intent. In your case I would suggest defining an entity called e.g. `id` and then storing that in the target/topic slot with a custom action, dependent on the context

**Comment by akelad** [comment]
Also I'm going to close this issue, as this is more of a methodology question, which should be posted in our [forum](https://forum.rasa.com). If you have any more questions, please post them there
