### ISSUE TITLE
User Message 

### ISSUE THREAD

**Issue by abirhajji** [RasaHQ/rasa_core#874]
**Rasa Core version**:
0.10.0
**Python version**: 
Python 3.6.6 :: Anaconda
**Operating system** (windows, osx, ...):
Windows 8
**Issue**:
Hey everyone!I want to save all the user message in order to use it to train rasa nlu model again .I is there any solution for this problem ?

**Content of domain file** (if used & relevant):
```yaml

```

**Comment by akelad** [comment]
Thanks for creating this issue, @tmbo will get back to you about it soon.

**Comment by tmbo** [comment]
I am not sure how you run your model, but if you are using the `rasa_nlu.server` script, there is an argument called `--response_log` that will dump your incoming queries and the predictions of the model to a file. Does that solve your issue?

**Comment by akelad** [comment]
@abirhajji do you need any more help or can we close this issue?

**Comment by abirhajji** [comment]
I solve it thank you
