### ISSUE TITLE
Extracting entity scores along with the intent scores (this is already achieved)

### ISSUE THREAD

**Issue by abhi2652254** [RasaHQ/rasa_core#889]
Rasa Core version:rasa-core 0.9.4
Python version: 3.6.5

Operating system : ubuntu 16.04

**Issue**:
I am trying to extract the entity and the entity scores along with the intent and intent scores (which is already achieved). I am providing the code below along with the error I am facing. Please help me by identifying the error in the logic or format of the code. Thanks in advance. 

The code below is "actions.py" and the intent score is retrieved along with its display. I have used the two variables (entity_label and confidence) below from "ner_crf" pipeline component since it might help me to retrieve the entity and the entity scores but I am unable to retrieve them. 

key1 = tracker.latest_message.entities(entity_label)
l_confidence_1 = tracker.latest_message.entities(confidence)

from __future__ import absolute_import
from __future__ import division
from __future__ import print_function
from __future__ import unicode_literals

import argparse
import logging
import warnings

from rasa_core import utils
from rasa_core.actions import Action
from rasa_core.agent import Agent
from rasa_core.trackers import DialogueStateTracker

with warnings.catch_warnings():
    warnings.filterwarnings("ignore", category= DeprecationWarning)
    

logger = logging.getLogger(__name__)

class ActionTest(Action):
    def name(self):
        return 'action_test'

    def run(self, dispatcher, tracker, domain):
        key = tracker.latest_message.intent["name"]
        l_confidence = tracker.latest_message.intent["confidence"]
        key1 = tracker.latest_message.entities(entity_label)
        l_confidence_1 = tracker.latest_message.entities(confidence)
        logger.info(key)
        logger.info(l_confidence)
        logger.info(key1)
        logger.info(l_confidence_1)
        if tracker:
            print(tracker.current_state()) # or do other things
       return []

It should give me the result as follows:
intent
intent score
entity
entity score

but is giving me instead as:
ERROR    rasa_core.processor  - name 'ent' is not defined
Traceback (most recent call last):
  File "/usr/local/lib/python3.6/dist-packages/rasa_core/processor.py", line 311, in _run_action
    events = action.run(dispatcher, tracker, self.domain)
  File "/home/Desktop/actions.py", line 30, in run
    key1 = tracker.latest_message.entities[ent.label_]
NameError: name 'ent' is not defined

In addition, if I provide 
key1 = tracker.latest_message.entities["name"]
l_confidence_1 = tracker.latest_message.entities["confidence"]

it is showing the error "cannot accept strings".

**Comment by Ghostvv** [comment]
It looks like the code you provided above with `key1 = tracker.latest_message.entities(entity_label)` doesn't correspond to the code you run: `key1 = tracker.latest_message.entities[ent.label]`

**Comment by abhi2652254** [comment]
Oh, I am sorry. My bad, the error was: 

2018-08-21 17:08:05 ERROR    rasa_core.processor  - Encountered an exception while running action 'action_test'. Bot will continue, but the actions events are lost. Make sure to fix the exception in your custom code.
2018-08-21 17:08:05 ERROR    rasa_core.processor  - name 'entity_label' is not defined
Traceback (most recent call last):
  File "/usr/local/lib/python3.6/dist-packages/rasa_core/processor.py", line 311, in _run_action
    events = action.run(dispatcher, tracker, self.domain)
  File "/home/abhi/Desktop/actions.py", line 30, in run
    key1 = tracker.latest_message.entities(entity_label)
NameError: name 'entity_label' is not defined

**Comment by Ghostvv** [comment]
It looks like, it doesn't know `entity_label`

**Comment by abhi2652254** [comment]
Yes, right but now I am trying to integrate the code of entity score extraction from the spacy website which I am providing below but still it is showing some errors. I am providing the code below along with the error I am getting now. I think I don't get the logic right in the def run() function for entity score extraction. Please help me with feedback, thanks in advance.

class ActionTest(Action):
    #"""We use this function to measure the accuracy of answers before responding"""
    def name(self):
        return 'action_test'

    def run(self, dispatcher, tracker, domain):
        key = tracker.latest_message.intent["name"]
        l_confidence = tracker.latest_message.intent["confidence"]
        doc = nlp(tracker.latest_message.text)
        
        
        docs = list(nlp.pipe(list(tracker.latest_message.text), disable=['ner']))
        (beams, somethingelse) = nlp.entity.beam_parse(docs, beam_width=16, beam_density=0.0001)

        for docs, beam in zip(doc, beams):
            entity_scores = defaultdict(float)
            for score, ents in nlp.entity.moves.get_beam_parses(beam):
                print (score, ents)
                for start, end, label in ents:
                    entity_scores[(start, end, label)] += score

        #key1 = tracker.latest_message.entities[ent.text]
        l_confidence_1 = tracker.latest_message.entity_scores
        logger.info(key)
        logger.info(l_confidence)
        #logger.info(key1)
        logger.info(l_confidence_1)
        if tracker:
            print(tracker.current_state()) # or do other things
        return []

rasa_core.processor  - Encountered an exception while running action 'action_test'. Bot will continue, but the actions events are lost. Make sure to fix the exception in your custom code.
2018-08-22 09:59:04 ERROR    rasa_core.processor  - 'UserUttered' object has no attribute 'entity_scores'
Traceback (most recent call last):
  File "/usr/local/lib/python3.6/dist-packages/rasa_core/processor.py", line 311, in _run_action
    events = action.run(dispatcher, tracker, self.domain)
  File "/home/abhi/Desktop/actions.py", line 48, in run
    l_confidence_1 = tracker.latest_message.entity_scores
AttributeError: 'UserUttered' object has no attribute 'entity_scores'

**Comment by abhi2652254** [comment]
Yes I tried tracker.latest_message.entities but it is showing something like this
I type 'hi' in the console and the following appears:

actions- greet
actions- 0.9439 (intent score)
actions- []

but the entity score appears as defined (not the entity itself). Thanks in advance.

**Comment by Ghostvv** [comment]
empty list means no entities were extracted, which I guess makes sense if you type `hi`, because it doesn't have any entities

**Comment by abhi2652254** [comment]
thanks for the response, yes but even if I provide some relevant sentence as per the bot requirement, it gives empty list.

**Comment by Ghostvv** [comment]
then your flu didn't extract the entities

**Comment by abhi2652254** [comment]
I don't get the part (variable) of ner_crf component which is helping to extract the entity in my code, thanks in advance.

**Comment by Ghostvv** [comment]
sorry, I don't understand what you mean. But I think that this question is better suited for our [rasa community forum](https://forum.rasa.com)

**Comment by abhi2652254** [comment]
Ok thank you very much. I will close the issue for now.

**Comment by azizullah2017** [comment]
> ent.label

AttributeError: 'dict' object has no attribute 'entities'

**Comment by azizullah2017** [comment]
@Ghostvv 
> It looks like the code you provided above with `key1 = tracker.latest_message.entities(entity_label)` doesn't correspond to the code you run: `key1 = tracker.latest_message.entities[ent.label]`. In the latest name `ent` was not defined

AttributeError: 'dict' object has no attribute 'entities'

**Comment by Ghostvv** [comment]
@azizullah2017 that was before `0.11` `sdk` update. Please try `tracker.latest_message["entities"]`

**Comment by azizullah2017** [comment]
@Ghostvv  I used that too, but I WANT the value of entity only.
can you help we with that ?

**Comment by Ghostvv** [comment]
there is several ways to do that `es = tracker.latest_message["entities"]` gives you a list `es` of dicts `e`, where `e['entity']` holds entity name and `e['value']` - its value. 
or you could use:
```
value = next(tracker.get_latest_entity_values(self.entity_name), None)
```
Please ask on forum this kind of questions
