### ISSUE TITLE
Rasa Core 0.11 estimated release date

### ISSUE THREAD

**Issue by jonDel** [RasaHQ/rasa_core#891]
**Rasa Core version**:
rasa-core           0.9.8

**Python version**: 
Python 3.6.6 :: Anaconda, Inc.

**Operating system** (windows, osx, ...):
Fedora Linux

**Issue**:

Any news on Rasa Core 0.11 release? I’m waiting this version, mostly for the feature of running the interactive learning as a http server, as seen in this issue, https://github.com/RasaHQ/rasa_core/issues/867.

Thanks in advance

**Comment by Ghostvv** [comment]
Thanks for raising this issue, @tmbo will get back to you about it soon.

**Comment by Bing-Xia** [comment]
looking forward to that awesome release

**Comment by reza-ebrahimi** [comment]
The versioning 0.11.0 is for minor releases, The changes are huge and most of the rasa_core are refactored, I think it should be a major versioning release.

**Comment by amn41** [comment]
@reza-ebrahimi we use [semantic versioning](https://semver.org/#spec-item-4) which means that for major version <0, 0.11.0 is a major version change

**Comment by akelad** [comment]
As it's been released, I'll close this :)

**Comment by Bing-Xia** [comment]
Hi @akelad , after searching around about the document of v0.11.x, I didn't found the introduction for the feature of running the interactive learning as a http server, does this feature was involved in v0.11.x ? Thank you in advance.

**Comment by akelad** [comment]
it's just run via http now, you can check out the code here: https://github.com/RasaHQ/rasa_core/blob/master/rasa_core/training/online.py
