### ISSUE TITLE
Not able to install rasa_core on window machine  with python 2.7

### ISSUE THREAD

**Issue by GurdeepSS** [RasaHQ/rasa_core#895]
**Rasa Core version**: pip install rasa_core --no-cache-dir

**Python version**: Python 2.7.14

**Operating system** (windows, osx, ...):windows

**Issue**:
>pip install rasa_core --no-cache-dir
Collecting rasa_core
  Downloading https://files.pythonhosted.org/packages/20/94/8375eef614b7720f0df0a43be488773fcb66242c15a6f55c776a21fdf3d7/rasa_core-0.10.4-py2.py3-none-any.whl (133kB)
    100% |UUUUUUUUUUUUUUUUUUUUUUUUUUUUUUUU| 143kB 1.3MB/s
Collecting ConfigArgParse~=0.13.0 (from rasa_core)
  Downloading https://files.pythonhosted.org/packages/77/61/ae928ce6ab85d4479ea198488cf5ffa371bd4ece2030c0ee85ff668deac5/ConfigArgParse-0.13.0.tar.gz
Collecting future~=0.16 (from rasa_core)
  Downloading https://files.pythonhosted.org/packages/00/2b/8d082ddfed935f3608cc61140df6dcbf0edea1bc3ab52fb6c29ae3e81e85/future-0.16.0.tar.gz (824kB)
    100% |UUUUUUUUUUUUUUUUUUUUUUUUUUUUUUUU| 829kB 5.4MB/s
Collecting twilio~=6.0 (from rasa_core)
  Downloading https://files.pythonhosted.org/packages/b1/3d/67d7a930afe81950fc97326ccaeff0ee4974dae6a96e7664ce9ddecba4ee/twilio-6.16.3-py2.py3-none-any.whl (872kB)
    100% |UUUUUUUUUUUUUUUUUUUUUUUUUUUUUUUU| 880kB 4.3MB/s
Collecting jsonpickle~=0.9.0 (from rasa_core)
  Downloading https://files.pythonhosted.org/packages/32/d5/2f47f03d3f64c31b0d7070b488274631d7567c36e81a9f744e6638bb0f0d/jsonpickle-0.9.6.tar.gz (67kB)
    100% |UUUUUUUUUUUUUUUUUUUUUUUUUUUUUUUU| 71kB 3.0MB/s
Collecting tensorflow<1.9,>=1.7 (from rasa_core)
  Could not find a version that satisfies the requirement tensorflow<1.9,>=1.7 (from rasa_core) (from versions: )
No matching distribution found for tensorflow<1.9,>=1.7 (from rasa_core)

**Content of domain file** (if used & relevant):
```yaml

```

**Comment by akelad** [comment]
> error: Microsoft Visual C++ 14.0 is required. Get it with "Microsoft Visual C++ Build Tools": https://visualstudio.microsoft.com/downloads/

That's what you want to be looking at, please install the microsoft visual C++ build tools

**Comment by GurdeepSS** [comment]
I Have tried with Python 2.7   .. below error .. looking for your help here.

pip install rasa_core --no-cache-dir
Collecting rasa_core
Downloading https://files.pythonhosted.org/packages/20/94/8375eef614b7720f0df0a43be488773fcb66242c15a6f55c776a21fdf3d7/rasa_core-0.10.4-py2.py3-none-any.whl (133kB)
100% |UUUUUUUUUUUUUUUUUUUUUUUUUUUUUUUU| 143kB 1.3MB/s
Collecting ConfigArgParse~=0.13.0 (from rasa_core)
Downloading https://files.pythonhosted.org/packages/77/61/ae928ce6ab85d4479ea198488cf5ffa371bd4ece2030c0ee85ff668deac5/ConfigArgParse-0.13.0.tar.gz
Collecting future~=0.16 (from rasa_core)
Downloading https://files.pythonhosted.org/packages/00/2b/8d082ddfed935f3608cc61140df6dcbf0edea1bc3ab52fb6c29ae3e81e85/future-0.16.0.tar.gz (824kB)
100% |UUUUUUUUUUUUUUUUUUUUUUUUUUUUUUUU| 829kB 5.4MB/s
Collecting twilio~=6.0 (from rasa_core)
Downloading https://files.pythonhosted.org/packages/b1/3d/67d7a930afe81950fc97326ccaeff0ee4974dae6a96e7664ce9ddecba4ee/twilio-6.16.3-py2.py3-none-any.whl (872kB)
100% |UUUUUUUUUUUUUUUUUUUUUUUUUUUUUUUU| 880kB 4.3MB/s
Collecting jsonpickle~=0.9.0 (from rasa_core)
Downloading https://files.pythonhosted.org/packages/32/d5/2f47f03d3f64c31b0d7070b488274631d7567c36e81a9f744e6638bb0f0d/jsonpickle-0.9.6.tar.gz (67kB)
100% |UUUUUUUUUUUUUUUUUUUUUUUUUUUUUUUU| 71kB 3.0MB/s
Collecting tensorflow<1.9,>=1.7 (from rasa_core)
Could not find a version that satisfies the requirement tensorflow<1.9,>=1.7 (from rasa_core) (from versions: )
No matching distribution found for tensorflow<1.9,>=1.7 (from rasa_core)

**Comment by akelad** [comment]
What python 2.7 error? Try running `pip install tensorflow==1.8.0` and then try installing core again

**Comment by GurdeepSS** [comment]
got the below error ...
Collecting tensorflow==1.8.0
  Could not find a version that satisfies the requirement tensorflow==1.8.0 (from versions: )
No matching distribution found for tensorflow==1.8.0

![image](https://user-images.githubusercontent.com/9370884/44692369-80ff8800-aa17-11e8-9482-506ef987d9f5.png)

**Comment by Krogsager** [comment]
> Tensorflow for Windows is only supported with Python 3.5 and Python 3.6 (since 1.2).
https://stackoverflow.com/a/45328447/2443487

**Comment by GurdeepSS** [comment]
Thanks Krogsager  and  akelad .. 
i have already tried with python 3.5 . here is error..  i don't want to installed Microsoft Visual C++ 14.0. its 6-7 GBs.

====so  pyhton 2.7 not working  and pyhton 3.5 stucked for Microsoft Visual C++ 14.0.
=================
error: Microsoft Visual C++ 14.0 is required. Get it with "Microsoft Visual C++ Build Tools": https://visualstudio.microsoft.com/downloads/

----------------------------------------
Command "c:\users\gurdesin\appdata\local\programs\python\python36\python.exe -u -c "import setuptools, tokenize;file='C:\Users\gurdesin\AppData\Local\Temp\pip-install-wc3o_3ci\Twisted\setup.py';f=getattr(tokenize, 'open', open)(file);code=f.read().replace('\r\n', '\n');f.close();exec(compile(code, file, 'exec'))" install --record C:\Users\gurdesin\AppData\Local\Temp\pip-record-_y6jl1j8\install-record.txt --single-version-externally-managed --compile" failed with error code 1 in C:\Users\gurdesin\AppData\Local\Temp\pip-install-wc3o_3ci\Twisted\

**Comment by Krogsager** [comment]
Personally I switched to develop on UNIX. So if you can get your hands on a mac or dual-boot in Linux then I would recommend that.
Side note: It is a lot of trouble to use [Linux on Windows](https://docs.microsoft.com/en-us/windows/wsl/install-win10) because if you edit any files with a Windows program then you risk breaking the file.

**Comment by akelad** [comment]
There's no other solution on Windows than to install those build tools. As @Krogsager said linux makes life easier 😄
