### ISSUE TITLE
slot-filling

### ISSUE THREAD

**Issue by yuxuan2015** [RasaHQ/rasa_core#900]
Can use the intent as the value of the slot?How?

**Comment by reza-ebrahimi** [comment]
No, The intent value is all the text classified by ML, you should select your text as entity then fill them into slot.

**Comment by amn41** [comment]
thanks @yuxuan2015 - as this is more of a usage issue, please post in the [forum](https://forum.rasa.com) . If you are using Rasa Core 0.10, you can look at the `BooleanFormField` as an example, though in 0.11.x (master) this will be done with a `FollowUpAction`, see https://github.com/RasaHQ/rasa_core_sdk/blob/forms/examples/formbot/myactions.py#L66

**Comment by akelad** [comment]
Since this has been moved over to the forum, I'll close this issue
