### ISSUE TITLE
Database required or not

### ISSUE THREAD

**Issue by amanvars** [RasaHQ/rasa_core#911]
is there any problem to have all the intents, entities and slots on domain.yaml file for large dataset.
Will it create performance lag in getting a response since text/MD file is not recommended for large dataset.

**Comment by akelad** [comment]
No this should be fine. You can handle your template replies externally though: https://rasa.com/docs/core/responses/
I'm going to close this issue because it's more of a question than a Rasa Core issue, please post these kinds of things in our [forum](https://forum.rasa.com)
