### ISSUE TITLE
Training slow for 10.4

### ISSUE THREAD

**Issue by ctrado18** [RasaHQ/rasa_core#916]
hey,

are there some params changed for  training. During each epoch the one counter is increased (I don't know what this param is), see:

```
4561/4561 [==============================] - 4s 871us/step - loss: 2.0603 - acc: 0.3271
Epoch 2/300
4561/4561 [==============================] - 2s 495us/step - loss: 1.3117 - acc: 0.6060
Epoch 3/300
4561/4561 [==============================] - 2s 453us/step - loss: 0.7052 - acc: 0.8373

````

What is this numer `4561`. This number was before update just about 200. How can I change it?

**Comment by ctrado18** [comment]
I mean this number `4561/4561` before this was justg about 200 and I changed nothing. I have no 4561 actions? Can you explain this more. How can I decrease it. This trakes much longer than before.

**Comment by akelad** [comment]
they're a number of unique story paths found pretty much. If you want it to be faster, try using `--augmentation 0`

**Comment by ctrado18** [comment]
@akelad Hmm, I already set it to 0! That is the strange thing?! It is same story file like before update and augmenation is 0.

**Comment by akelad** [comment]
What version were you using before? With 0.10.x we did a big refactor of core which improved story generation, that's probably why. 2s per epoch doesn't seem like an unreasonably long training time regardless

**Comment by ctrado18** [comment]
Yes, before 0.9.0 and now 10.4. Yes I saw the changelog. And this is now significantly slow. So, training seems now in general more slowly because of those changes as I used same data.  Does this arises from  changes under the hood which you cannot influence?

**Comment by ctrado18** [comment]
The strange thing is now that when using online learning for version 10.4 it is fast as before though using same data! Also same amount of unique actions were found!
For online training:
```
2018-09-05 13:00:38 INFO     rasa_core.featurizers  - Creating states and action examples from collected trackers (by MaxHistoryTrackerFeaturizer)...
Processed trackers: 100%|██████████████████████████████████████████| 1899/1899 [00:27<00:00, 69.35it/s, # actions=2270]
2018-09-05 13:01:06 INFO     rasa_core.featurizers  - Created 2270 action examples.
Processed actions: 2270it [00:00, 2884.61it/s, # examples=2236]
2018-09-05 13:01:07 INFO     rasa_core.policies.memoization  - Memorized 2236 unique action examples.
2018-09-05 13:01:07 INFO     rasa_core.featurizers  - Creating states and action examples from collected trackers (by MaxHistoryTrackerFeaturizer)...
Processed trackers: 100%|██████████████████████████████████████████| 1899/1899 [00:26<00:00, 71.11it/s, # actions=4823]
2018-09-05 13:01:33 INFO     rasa_core.featurizers  - Created 4823 action examples.
_________________________________________________________________
Layer (type)                 Output Shape              Param #
=================================================================
masking_1 (Masking)          (None, 5, 163)            0
_________________________________________________________________
lstm_1 (LSTM)                (None, 32)                25088
_________________________________________________________________
dense_1 (Dense)              (None, 31)                1023
_________________________________________________________________
activation_1 (Activation)    (None, 31)                0
=================================================================
Total params: 26,111
Trainable params: 26,111
Non-trainable params: 0
_________________________________________________________________
2018-09-05 13:01:35 INFO     rasa_core.policies.keras_policy  - Fitting model with 300 total samples and a validation split of 0.0
Epoch 1/200
2018-09-05 13:01:37.486686: I T:\src\github\tensorflow\tensorflow\core\platform\cpu_feature_guard.cc:140] Your CPU supports instructions that this TensorFlow binary was not compiled to use: AVX2
300/300 [==============================] - 2s 7ms/step - loss: 3.4014 - acc: 0.0833
Epoch 2/200
300/300 [==============================] - 0s 290us/step - loss: 3.2457 - acc: 0.3167
Epoch 3/200
300/300 [==============================] - 0s 277us/step - loss: 3.0960 - acc: 0.3300

```

**Comment by Ghostvv** [comment]
If you look carefully at your logs, you can see that for `online training` only `300 total samples` are used, while for `normal training` - `5822 total samples`, which explains the difference in time.

As to under the hood changes - yes we changed the way trackers are created from training stories and the way they are featurized. These changes can lead to increase of training time because we got rid of random subsampling of stories.

Since this is a discussion question, I'll close this issue. Please post this kind of questions on our forum: https://forum.rasa.com.
