### ISSUE TITLE
Tensorflow Version 1.10.0

### ISSUE THREAD

**Issue by meandor** [RasaHQ/rasa_core#931]
**Rasa Core version**: 0.11.1

**Python version**: 3.6.0

**Operating system** (windows, osx, ...): osx

**Issue**: Use Tensorflow version 1.10.0

So the requirements.txt for rasa_core 0.11.1 says it needs tensorflow==1.10.0. The setup.py says on line 42 says it needs tensorflow>=1.8,<1.10. This keeps me from installing and using tensorflow 1.10.0. Is this done deliberately?

**Comment by meandor** [comment]
I have create a PR to address this: #932

**Comment by Ghostvv** [comment]
You are right, thank you for rising the issue and creating PR, I approved it, we're going to merge it when the build is finished

**Comment by Ghostvv** [comment]
The PR is merged
