### ISSUE TITLE
HTTP API End points not working in version 0.11.3

### ISSUE THREAD

**Issue by kumarkrish85** [RasaHQ/rasa_core#949]
**Rasa Core version**: 0.11.3

**Python version**: 3.6.2

**Operating system** (windows, osx, ...): windows 10

**Issue**:

I have tried to run the example mentioned in QuickStart, I have successfully trained the NLU data and core. Started the server with the below command

`python -m rasa_core.run -d models/dialogue -u models/current/nlu --cors "*" --debug`

and tried to test the bot response using postman. when i am trying to hit this POST URL 

`http://localhost:5005/conversations/default/respond`

it always gives an error message. 

**Not Found

The requested URL was not found on the server. If you entered the URL manually please check your spelling and try again**.  and in command prompt

127.0.0.1 - - [2018-09-06 17:08:15] "POST /webhooks/rest/webhook?stream=true&token= HTTP/1.1" 200 217 0.235879
127.0.0.1 - - [2018-09-06 17:09:37] "POST /version HTTP/1.1" 404 374 0.000000

It gives the same response for all the end points. 

Am i missing any libraries to load? 

**Content of domain file** (if used & relevant):
```yaml

```

**Comment by akelad** [comment]
Thanks for raising this issue, @amn41  will get back to you about it soon.

**Comment by kumarkrish85** [comment]
Hi @akelad it worked fine. After adding --enable_api configuration in it.

`python -m rasa_core.run --enable_api -d models/dialogue -u models/current/nlu --cors "*" --debug --> to start the rasa_core server`

**Comment by nuronics** [comment]
am facing same problem @kumarkrish85 @akelad  am trying to do the same example place finder app 
when am trying to search restaurants in actions am getting key error could you help out with this issue

thanks in advance

**Comment by PrasannaGaneshu** [comment]
Hi @akelad ,
Im facing similar issue while running the bot...

Bot is not giving response even though the custom action server is up and running....

![untitled1](https://user-images.githubusercontent.com/38690247/51313997-e9a5da80-1a74-11e9-9322-765cc456edd7.png)

**Comment by akelad** [comment]
Please create a new issue
