### ISSUE TITLE
/conversations/[sender_id]/predict endpoint always returns action_listen with highest score

### ISSUE THREAD

**Issue by efanurag** [RasaHQ/rasa_core#965]
**Rasa Core version**: 0.13.2

**Python version**: 3.6

**Operating system** (windows, osx, ...): osx

**Issue**: /conversations/[sender_id]/predict endpoint after running rasa core server always returns action_listen with highest score as next action. Although the complete setup returns the correct output using /conversations/[sender_id]/respond endpoint.

Since /predict endpoint documentation is missing from Rasa core HTTP API docs, not sure how to use this endpoint.

**Comment by akelad** [comment]
Please provide your Rasa Core version, the one you've posted is the NLU version. I'd guess you're not using the latest version, so maybe 0.10.4? If that's the case, then look at the appropriate documentation here please: https://rasa.com/docs/core/0.10.4/

**Comment by efanurag** [comment]
Sorry, my bad.  I am using the below versions.

Rasa Core version: 0.11.3
Rasa NLU: 0.13.2
