### ISSUE TITLE
How I can save chat conversation on MongoDB

### ISSUE THREAD

**Issue by neerajb1** [RasaHQ/rasa_core#967]
**Rasa Core version**:0.10.4

**Python version**: 3.5

**Operating system** (windows, osx, ...):windows

**Issue**:

Save chatbot conversation in mongodb

**Content of domain file** (if used & relevant):
```yaml

```

**Comment by neerajb1** [comment]
Hi any document to save conversation on mongodb?

**Comment by akelad** [comment]
There's a Mongo tracker store: https://github.com/RasaHQ/rasa_core/blob/master/rasa_core/tracker_store.py#L144
Also, this is more of a question for the [forum](https://forum.rasa.com), so if you have any further questions please post them there

**Comment by neerajb1** [comment]
Hi ake,

Thank you for response. I am able to save tracker on mongo. I am getting only senderid and tracker id. Could please help me to retrieve data from these id
