### ISSUE TITLE
Exception during finetune request

### ISSUE THREAD

**Issue by tdzienniak** [RasaHQ/rasa_core#971]
**Rasa Core version**:
0.11.3
**Python version**: 
3.6
**Operating system** (windows, osx, ...):
Ubuntu 18.04
**Issue**:
When sending events for model finetune I get this error:

```
2018-09-11 08:54:19 ERROR    rasa_core.server  - Caught an exception during prediction.
Traceback (most recent call last):
  File "/home/tymoteusz/bot/venv/lib/python3.6/site-packages/rasa_core/server.py", line 387, in continue_training
    batch_size=batch_size)
  File "/home/tymoteusz/bot/venv/lib/python3.6/site-packages/rasa_core/agent.py", line 425, in continue_training
    **kwargs)
  File "/home/tymoteusz/bot/venv/lib/python3.6/site-packages/rasa_core/policies/ensemble.py", line 192, in continue_training
    self.training_trackers.extend(trackers)
AttributeError: 'NoneType' object has no attribute 'extend'
```

It seems like this variable is set here https://github.com/RasaHQ/rasa_core/blob/master/rasa_core/policies/ensemble.py#L64, but this line is never executed in my setup (runing server with `rasa_core.run`).

**Content of domain file** (if used & relevant):
```yaml

```

**Comment by akelad** [comment]
Thanks for raising this issue, @Ghostvv will get back to you about it soon.

**Comment by Ghostvv** [comment]
Could you please give an exact command that you use, so I could reproduce the error

**Comment by tdzienniak** [comment]
@Ghostvv, sure:
```
python -m rasa_core.run --enable_api -d models/default/dialogue -p 3010 --endpoints endpoints.yml --cors '*' -c 'rest'
```

**Comment by Ghostvv** [comment]
but this command doesn't call `continue_training`

**Comment by tdzienniak** [comment]
Yes, this command starts a server and I'm making POST request to `/finetune` endpoint with array of events.

**Comment by Ghostvv** [comment]
I see, so the problem is that in this case `continue_training` is called without `train`, so ensemble doesn't have original training trackers. @tmbo could you please look into it?

**Comment by Bing-Xia** [comment]
Same issue when call `/finetune` with events array,  so what the solution is ?

**Comment by tdzienniak** [comment]
> Same issue when call `/finetune` with events array, so what the solution is ?

Don't call `/finetune`. :) That is what I did. It is not essential to make interactive learning useful. In the next Rasa release will be an option to disable finetune during interactive learning.

**Comment by tmbo** [comment]
As said, there is no clear path forward yet on how to fix this. As @Ghostvv said, the model needs some information from the training that is not persisted. So it can not be finetuned without that information.

One next step should be though to fix the exception and reject the finetuning request if the model is not ready for finetuning.

The only way to get around this exception right now is to start the server with a model that has just been trained, as it is done during the online learning cli
