### ISSUE TITLE
How to enable embedding policy?

### ISSUE THREAD

**Issue by DhruvMevada** [RasaHQ/rasa_core#975]
**Rasa Core version**: 0.13.2

**Issue**: 
I have explored **embedding policy** in Rasa Core library from the documentation. But I didn't find any details  for **enabling the embedding policy in the docs.**
Can any one help me how to enable the embedding policy?

**Content of domain file** (if used & relevant):
```yaml

```

**Comment by Ghostvv** [comment]
what do you mean by enable? you have to pass appropriate `policies` list, e.g. `policies = [EmbeddingPolicy()]` to your Agent

**Comment by akelad** [comment]
Yes so as @Ghostvv says you can't enable this via the train script, but you can load an agent like this here: https://rasa.com/docs/core/policies/#id1 and specify your embedding policy as stated later on that page

**Comment by DhruvMevada** [comment]
thanks @akelad 
can you explain more for the embedding policy working?
https://rasa.com/docs/core/policies/#embedding-policy here its written that : it takes previous user inputs as a user memory and Embedding of previous system actions as a system memory.
**1.Then from where did the it taking the previous user inputs?
2. How the Embedding policy works better then Keras policy?
3. How can I differentiate the Embedding and Keras policy output?**

**Comment by akelad** [comment]
We'll be publishing a paper soon that explains all the details of this new policy. The main benefit of the embedding policy is that it learns to generalise on conversations better. I'll close this issue for now as this is more of a discussion topic. If you have more questions please post them on the [forum](https://forum.rasa.com)
