### ISSUE TITLE
User input triggers "action_listen" action and bot doesn't respond to user

### ISSUE THREAD

**Issue by aravindkarnam** [RasaHQ/rasa_core#99]
I am doing interactive training using agent.train_online() method and when I run the bot, it doesn't give any output to some of the user inputs, because bot predicted "action_listen" action . I think it is completely illogical if user input triggers "action_listen" from bot for any user input, as it would appear as though the bot is offline. It is OK for bot to "action_listen" after it performs a few utter_actions, but not to the user input. Is there an option to remove "action_listen" as a possible prediction for user input ? or am I misunderstanding the framework here ?

**Comment by tmbo** [comment]
There are use cases where this might be intended. E.g. the bot classified the first message as probably having a subsequent message or if the users status is still "typing" things like that.

To avoid that prediction the bot needs to be trained and told what to do in that situation (e.g. by adding more story training data).

**Comment by aravindkarnam** [comment]
In the use cases that you mentioned, bot still needs to prompt the user if the user doesn't send the subsequent message or "typing" status changes back to idle. It may make sense for the bot to wait for user input for a certain period of time(a delay), but "action_listen" should be followed by an action(probably second most probable action) after some delay.  Bot not responding to a user input indefinitely is equivalent to service failure and makes it a hard pitch for implementing rasa's dialogue management  reliably.

**Comment by vkrgowtham** [comment]
Hey @tmbo , for this use case is it possible to do something like rolling back the tracker  to previous state if we have mutilple action_listen's(lets say for two simaltaneous action_listen) , so that bot performs as intended.

**Comment by tmbo** [comment]
In a custom action you can use the `UserUtteranceReverted` event or the `ActionReverted` event to undo either the last action or everything until the previous user utterance.

**Comment by varshini-prasanna** [comment]
@tmbo
   templates:
  utter_greet:
    - "hey  {name}!great to see you"    # variable will be filled by slot with the same name or by custom code
i tried executing this part. But always this was the reply i got

Bot loaded. Type a message and press enter :
hello
DEBUG:rasa_core.tracker_store:Creating a new tracker for id 'default'.
DEBUG:rasa_core.processor:Received user message 'hello' with intent '{'name': 'greet', 'confidence': 0.50340026777146607}' and entities  '[]'
DEBUG:rasa_core.processor:Logged UserUtterance - tracker now has 2 events
DEBUG:rasa_core.processor:Current slot values:
        name: None
DEBUG:rasa_core.policies.memoization:Current tracker state [
        None
        None
        [('intent_greet', 1), ('prev_action_listen', 1)]]
DEBUG:rasa_core.policies.ensemble:Predicted next action #2 with prob 0.64.
hey None!great to see you
so , how do i fill the value for the slot?And,how do i do it using custom code?
I tried the tutorial thing but didn't work properly. please help me resolve this.

**Comment by tmbo** [comment]
I'll close this due to inactivity, let me know if there is still an issue.
